#!/usr/bin/env python3
"""Expand flashcard JSON files to 200 words each."""
import json, os

CONTENT_DIR = "/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content"

# Extra words for each category that needs expansion
# Format: (english, georgian, pronunciation, example_en, example_ka, level)
EXPANSIONS = {
    "street-urban": [
        ("alley", "შესახვევი", "/ˈæli/", "The alley was dark.", "შესახვევი ბნელი იყო.", "A2"),
        ("sidewalk", "ტროტუარი", "/ˈsaɪdwɔːk/", "Walk on the sidewalk.", "ტროტუარზე იარე.", "A2"),
        ("crosswalk", "საფეხმავლო გადასასვლელი", "/ˈkrɒswɔːk/", "Use the crosswalk.", "საფეხმავლო გადასასვლელი გამოიყენე.", "A2"),
        ("curb", "მოპირკეთება", "/kɜːrb/", "Step off the curb.", "ჩამოდი ბორდიურიდან.", "B1"),
        ("gutter", "არხი", "/ˈɡʌtər/", "Rain flows in the gutter.", "წვიმა არხში მიედინება.", "B1"),
        ("lamppost", "ფანარი", "/ˈlæmppoʊst/", "The lamppost lit the street.", "ფანარმა ქუჩა გაანათა.", "A2"),
        ("hydrant", "ჰიდრანტი", "/ˈhaɪdrənt/", "Don't park near the hydrant.", "ჰიდრანტთან არ დააყენო მანქანა.", "B1"),
        ("manhole", "კანალიზაციის ხვრელი", "/ˈmænhoʊl/", "The manhole cover was open.", "კანალიზაციის ხვრელი ღია იყო.", "B2"),
        ("billboard", "რეკლამა", "/ˈbɪlbɔːrd/", "A big billboard stood there.", "დიდი რეკლამა იდგა იქ.", "B1"),
        ("graffiti", "გრაფიტი", "/ɡrəˈfiːti/", "Graffiti covered the wall.", "გრაფიტიმ კედელი დაფარა.", "B1"),
        ("mural", "მურალი", "/ˈmjʊrəl/", "The mural was beautiful.", "მურალი ლამაზი იყო.", "B1"),
        ("bench", "სკამი", "/bentʃ/", "Sit on the bench.", "სკამზე დაჯექი.", "A1"),
        ("fountain", "შადრევანი", "/ˈfaʊntən/", "Kids play near the fountain.", "ბავშვები შადრევანთან თამაშობენ.", "A2"),
        ("mailbox", "საფოსტო ყუთი", "/ˈmeɪlbɑːks/", "Put the letter in the mailbox.", "წერილი საფოსტო ყუთში ჩააგდე.", "A2"),
        ("dumpster", "ნაგვის ყუთი", "/ˈdʌmpstər/", "The dumpster was full.", "ნაგვის ყუთი სავსე იყო.", "B1"),
        ("awning", "ტენტი", "/ˈɔːnɪŋ/", "Stand under the awning.", "ტენტის ქვეშ დადექი.", "B2"),
        ("scaffolding", "ხარაჩო", "/ˈskæfəldɪŋ/", "Workers climbed the scaffolding.", "მუშები ხარაჩოზე ავიდნენ.", "B2"),
        ("pothole", "ორმო", "/ˈpɒthoʊl/", "Watch out for potholes.", "ორმოებს უფრთხილდი.", "B1"),
        ("pedestrian", "ფეხმავალი", "/pəˈdestriən/", "The pedestrian crossed safely.", "ფეხმავალი უსაფრთხოდ გადავიდა.", "B1"),
        ("intersection", "გზაჯვარედინი", "/ˌɪntərˈsekʃən/", "Stop at the intersection.", "გზაჯვარედინზე გაჩერდი.", "B1"),
        ("overpass", "ხიდი", "/ˈoʊvərpæs/", "Drive under the overpass.", "ხიდის ქვეშ გაიარე.", "B1"),
        ("underpass", "გვირაბი", "/ˈʌndərpæs/", "The underpass was flooded.", "გვირაბი დატბორილი იყო.", "B2"),
        ("pavement", "ასფალტი", "/ˈpeɪvmənt/", "The pavement was wet.", "ასფალტი სველი იყო.", "A2"),
        ("streetlight", "ქუჩის ნათურა", "/ˈstriːtlaɪt/", "The streetlight turned on.", "ქუჩის ნათურა აინთო.", "A2"),
        ("vendor", "გამყიდველი", "/ˈvendər/", "The vendor sold fruit.", "გამყიდველი ხილს ყიდდა.", "B1"),
        ("busker", "ქუჩის მუსიკოსი", "/ˈbʌskər/", "The busker played guitar.", "ქუჩის მუსიკოსი გიტარაზე უკრავდა.", "B2"),
        ("vagrant", "მაწანწალა", "/ˈveɪɡrənt/", "A vagrant slept on the bench.", "მაწანწალა სკამზე ეძინა.", "C1"),
        ("jaywalking", "უწესრიგო გადასვლა", "/ˈdʒeɪwɔːkɪŋ/", "Jaywalking is dangerous.", "უწესრიგო გადასვლა საშიშია.", "B2"),
        ("boulevard", "ბულვარი", "/ˈbuːləvɑːrd/", "Walk down the boulevard.", "ბულვარზე გაიარე.", "B1"),
        ("avenue", "გამზირი", "/ˈævənjuː/", "They live on Fifth Avenue.", "ისინი მეხუთე გამზირზე ცხოვრობენ.", "A2"),
        ("downtown", "ცენტრი", "/ˈdaʊntaʊn/", "Let's go downtown.", "წავიდეთ ცენტრში.", "A2"),
        ("suburb", "გარეუბანი", "/ˈsʌbɜːrb/", "They moved to the suburb.", "ისინი გარეუბანში გადავიდნენ.", "B1"),
        ("skyscraper", "ცათამბჯენი", "/ˈskaɪskreɪpər/", "The skyscraper was tall.", "ცათამბჯენი მაღალი იყო.", "B1"),
        ("warehouse", "საწყობი", "/ˈwerhaʊs/", "Goods are stored in the warehouse.", "საქონელი საწყობში ინახება.", "B1"),
        ("penthouse", "პენტჰაუსი", "/ˈpenthaʊs/", "The penthouse has a great view.", "პენტჰაუსიდან კარგი ხედია.", "B2"),
        ("loft", "სხვენი", "/lɒft/", "They converted the loft.", "მათ სხვენი გადააკეთეს.", "B1"),
        ("rooftop", "სახურავი", "/ˈruːftɒp/", "Party on the rooftop.", "წვეულება სახურავზე.", "A2"),
        ("balcony", "აივანი", "/ˈbælkəni/", "She stood on the balcony.", "ის აივანზე იდგა.", "A2"),
        ("staircase", "კიბე", "/ˈsterkeɪs/", "Climb the staircase.", "კიბეზე ავიდი.", "A2"),
        ("elevator", "ლიფტი", "/ˈelɪveɪtər/", "Take the elevator.", "ლიფტით ავიდი.", "A2"),
        ("escalator", "ესკალატორი", "/ˈeskəleɪtər/", "Ride the escalator.", "ესკალატორით ავიდი.", "A2"),
        ("parking", "პარკინგი", "/ˈpɑːrkɪŋ/", "Find a parking spot.", "პარკინგის ადგილი იპოვე.", "A1"),
        ("garage", "გარაჟი", "/ɡəˈrɑːʒ/", "Park in the garage.", "გარაჟში დააყენე.", "A2"),
        ("barrier", "ბარიერი", "/ˈbæriər/", "Don't cross the barrier.", "ბარიერს არ გადაცდე.", "B1"),
        ("railing", "მოაჯირი", "/ˈreɪlɪŋ/", "Hold the railing.", "მოაჯირს მოეჭიდე.", "B1"),
        ("canopy", "საფარი", "/ˈkænəpi/", "Stand under the canopy.", "საფარის ქვეშ დადექი.", "B2"),
        ("kiosk", "კიოსკი", "/ˈkiːɒsk/", "Buy a newspaper at the kiosk.", "კიოსკთან გაზეთი იყიდე.", "B1"),
        ("stall", "სტენდი", "/stɔːl/", "The market stall sold fish.", "ბაზრის სტენდზე თევზს ყიდდნენ.", "B1"),
        ("arcade", "პასაჟი", "/ɑːrˈkeɪd/", "Walk through the arcade.", "პასაჟში გაიარე.", "B1"),
        ("plaza", "მოედანი", "/ˈplɑːzə/", "Meet me at the plaza.", "მოედანზე შემხვდი.", "B1"),
        ("courtyard", "ეზო", "/ˈkɔːrtjɑːrd/", "The courtyard was quiet.", "ეზო წყნარი იყო.", "B1"),
        ("terrace", "ტერასა", "/ˈterəs/", "Eat on the terrace.", "ტერასაზე ჭამე.", "B1"),
        ("patio", "ვერანდა", "/ˈpætioʊ/", "Relax on the patio.", "ვერანდაზე დაისვენე.", "B1"),
        ("dome", "გუმბათი", "/doʊm/", "The dome shone in the sun.", "გუმბათი მზეზე ბრწყინავდა.", "B1"),
        ("tower", "კოშკი", "/ˈtaʊər/", "The tower was ancient.", "კოშკი უძველესი იყო.", "A2"),
        ("monument", "ძეგლი", "/ˈmɒnjumənt/", "Visit the monument.", "ძეგლი ნახე.", "A2"),
        ("statue", "ქანდაკება", "/ˈstætʃuː/", "The statue was impressive.", "ქანდაკება შთამბეჭდავი იყო.", "A2"),
        ("pillar", "სვეტი", "/ˈpɪlər/", "The pillar supported the roof.", "სვეტი სახურავს აჭერდა.", "B1"),
        ("arch", "თაღი", "/ɑːrtʃ/", "Walk through the arch.", "თაღში გაიარე.", "B1"),
        ("chimney", "საკვამური", "/ˈtʃɪmni/", "Smoke rose from the chimney.", "კვამლი საკვამურიდან ამოდიოდა.", "A2"),
        ("antenna", "ანტენა", "/ænˈtenə/", "The antenna was on the roof.", "ანტენა სახურავზე იყო.", "B1"),
        ("drain", "კანალიზაცია", "/dreɪn/", "Water went down the drain.", "წყალი კანალიზაციაში ჩავიდა.", "B1"),
        ("sewer", "საკანალიზაციო", "/ˈsuːər/", "The sewer was blocked.", "საკანალიზაციო მილი დაიხშო.", "B2"),
        ("driveway", "შესასვლელი", "/ˈdraɪvweɪ/", "Park in the driveway.", "შესასვლელში დააყენე.", "A2"),
        ("fence", "ღობე", "/fens/", "Jump over the fence.", "ღობეს გადაახტი.", "A2"),
        ("hedge", "ბუჩქოვანი ღობე", "/hedʒ/", "Trim the hedge.", "ბუჩქოვანი ღობე შეჭერი.", "B1"),
        ("traffic", "ტრაფიკი", "/ˈtræfɪk/", "Traffic was heavy.", "ტრაფიკი მძიმე იყო.", "A2"),
        ("congestion", "საცობი", "/kənˈdʒestʃən/", "Avoid the congestion.", "საცობს მოერიდე.", "B2"),
        ("detour", "შემოვლითი გზა", "/ˈdiːtʊr/", "Take the detour.", "შემოვლითი გზით წადი.", "B1"),
        ("roadblock", "საგზაო ბარიერი", "/ˈroʊdblɑːk/", "Police set up a roadblock.", "პოლიციამ საგზაო ბარიერი დადგა.", "B2"),
        ("siren", "სირენა", "/ˈsaɪrən/", "I heard a siren.", "სირენა გავიგონე.", "B1"),
        ("horn", "სიგნალი", "/hɔːrn/", "Don't honk the horn.", "სიგნალს ნუ აყენებ.", "A2"),
        ("exhaust", "გამონაბოლქვი", "/ɪɡˈzɔːst/", "Exhaust pollutes the air.", "გამონაბოლქვი ჰაერს აბინძურებს.", "B2"),
        ("smog", "სმოგი", "/smɒɡ/", "Smog covered the city.", "სმოგმა ქალაქი დაფარა.", "B1"),
        ("litter", "ნაგავი", "/ˈlɪtər/", "Don't litter.", "ნაგავს ნუ ყრი.", "A2"),
        ("recycle", "გადამუშავება", "/riːˈsaɪkəl/", "Please recycle.", "გთხოვ გადაამუშავე.", "A2"),
        ("stroller", "ეტლი", "/ˈstroʊlər/", "Push the stroller.", "ეტლი აწიე.", "B1"),
        ("wheelchair", "ინვალიდის ეტლი", "/ˈwiːltʃer/", "The wheelchair ramp is there.", "ინვალიდის ეტლის პანდუსი იქაა.", "B1"),
        ("trolley", "ტროლეიბუსი", "/ˈtrɒli/", "Take the trolley.", "ტროლეიბუსით წადი.", "B1"),
        ("subway", "მეტრო", "/ˈsʌbweɪ/", "The subway is fast.", "მეტრო სწრაფია.", "A2"),
        ("tunnel", "გვირაბი", "/ˈtʌnəl/", "Drive through the tunnel.", "გვირაბში გაიარე.", "A2"),
        ("bridge", "ხიდი", "/brɪdʒ/", "Cross the bridge.", "ხიდზე გადაიარე.", "A1"),
        ("pier", "მისადგომი", "/pɪr/", "Walk along the pier.", "მისადგომზე გაიარე.", "B1"),
        ("harbor", "ნავსადგური", "/ˈhɑːrbər/", "Boats rest in the harbor.", "ნავები ნავსადგურში დგანან.", "B1"),
        ("dock", "ნავმისადგომი", "/dɒk/", "The ship reached the dock.", "გემი ნავმისადგომს მიადგა.", "B1"),
        ("canal", "არხი", "/kəˈnæl/", "The canal runs through town.", "არხი ქალაქში გადის.", "B1"),
        ("bank", "ნაპირი", "/bæŋk/", "Sit on the river bank.", "მდინარის ნაპირზე დაჯექი.", "A2"),
        ("slope", "ფერდობი", "/sloʊp/", "Walk up the slope.", "ფერდობზე ავიდი.", "B1"),
        ("trail", "ბილიკი", "/treɪl/", "Follow the trail.", "ბილიკს გაჰყევი.", "A2"),
        ("pathway", "ბილიკი", "/ˈpæθweɪ/", "The pathway was narrow.", "ბილიკი ვიწრო იყო.", "A2"),
        ("lane", "ზოლი", "/leɪn/", "Stay in your lane.", "შენს ზოლში იყავი.", "A2"),
        ("highway", "მაგისტრალი", "/ˈhaɪweɪ/", "Drive on the highway.", "მაგისტრალზე იარე.", "A2"),
        ("freeway", "ავტობანი", "/ˈfriːweɪ/", "The freeway was busy.", "ავტობანი დატვირთული იყო.", "B1"),
        ("roundabout", "წრე", "/ˈraʊndəbaʊt/", "Turn at the roundabout.", "წრეზე მოუხვიე.", "B1"),
        ("junction", "კვანძი", "/ˈdʒʌŋkʃən/", "Wait at the junction.", "კვანძთან დაელოდე.", "B1"),
        ("ramp", "პანდუსი", "/ræmp/", "Use the ramp.", "პანდუსი გამოიყენე.", "B1"),
        ("median", "გამყოფი ზოლი", "/ˈmiːdiən/", "Don't cross the median.", "გამყოფ ზოლს არ გადაცდე.", "B2"),
        ("bump", "ბორცვი", "/bʌmp/", "Slow down at the bump.", "ბორცვთან ნელა იარე.", "A2"),
        ("pole", "ბოძი", "/poʊl/", "The pole fell down.", "ბოძი დაეცა.", "A2"),
        ("wire", "მავთული", "/waɪər/", "Don't touch the wire.", "მავთულს ნუ ეხები.", "A2"),
        ("cable", "კაბელი", "/ˈkeɪbəl/", "The cable was underground.", "კაბელი მიწისქვეშ იყო.", "B1"),
        ("antenna", "ანტენა", "/ænˈtenə/", "Fix the antenna.", "ანტენა შეაკეთე.", "B1"),
        ("satellite", "თანამგზავრი", "/ˈsætəlaɪt/", "The satellite dish was big.", "თანამგზავრული ანტენა დიდი იყო.", "B1"),
        ("neon", "ნეონი", "/ˈniːɒn/", "Neon signs glow at night.", "ნეონის ნიშნები ღამით ანათებენ.", "B1"),
        ("marquee", "მარკიზა", "/mɑːrˈkiː/", "Read the marquee.", "მარკიზა წაიკითხე.", "C1"),
        ("vendor", "მოვაჭრე", "/ˈvendər/", "The street vendor sold hotdogs.", "ქუჩის მოვაჭრე ჰოთდოგებს ყიდდა.", "B1"),
        ("hustle", "აურზაური", "/ˈhʌsəl/", "City hustle never stops.", "ქალაქის აურზაური არასდროს ჩერდება.", "B2"),
        ("bustle", "ხმაური", "/ˈbʌsəl/", "The bustle of the market.", "ბაზრის ხმაური.", "B2"),
        ("commute", "მგზავრობა", "/kəˈmjuːt/", "My commute takes an hour.", "ჩემი მგზავრობა ერთ საათს გრძელდება.", "B1"),
        ("rush", "აჩქარება", "/rʌʃ/", "Don't rush.", "ნუ ჩქარობ.", "A2"),
        ("crowd", "ხალხი", "/kraʊd/", "The crowd was huge.", "ხალხი უზარმაზარი იყო.", "A2"),
        ("mob", "ბრბო", "/mɒb/", "The mob was angry.", "ბრბო გაბრაზებული იყო.", "B2"),
        ("parade", "პარადი", "/pəˈreɪd/", "Watch the parade.", "პარადი ნახე.", "A2"),
        ("rally", "მიტინგი", "/ˈræli/", "They held a rally.", "მათ მიტინგი გამართეს.", "B1"),
        ("protest", "პროტესტი", "/ˈproʊtest/", "The protest was peaceful.", "პროტესტი მშვიდობიანი იყო.", "B1"),
        ("curfew", "კომენდანტის საათი", "/ˈkɜːrfjuː/", "Curfew starts at midnight.", "კომენდანტის საათი შუაღამეს იწყება.", "B2"),
        ("surveillance", "მეთვალყურეობა", "/sərˈveɪləns/", "Cameras for surveillance.", "კამერები მეთვალყურეობისთვის.", "B2"),
        ("vandalism", "ვანდალიზმი", "/ˈvændəlɪzəm/", "Vandalism is a crime.", "ვანდალიზმი დანაშაულია.", "B2"),
        ("loitering", "უმიზნო ხეტიალი", "/ˈlɔɪtərɪŋ/", "No loitering allowed.", "უმიზნო ხეტიალი აკრძალულია.", "C1"),
        ("trespassing", "უნებართვო შესვლა", "/ˈtrespæsɪŋ/", "No trespassing.", "უნებართვო შესვლა აკრძალულია.", "B2"),
        ("poverty", "სიღარიბე", "/ˈpɒvərti/", "Poverty is a big issue.", "სიღარიბე დიდი პრობლემაა.", "B1"),
        ("homeless", "უსახლკარო", "/ˈhoʊmləs/", "Help the homeless.", "უსახლკაროებს დაეხმარე.", "A2"),
        ("shelter", "თავშესაფარი", "/ˈʃeltər/", "Find shelter.", "თავშესაფარი იპოვე.", "A2"),
        ("charity", "საქველმოქმედო", "/ˈtʃærəti/", "Donate to charity.", "საქველმოქმედო ორგანიზაციას შესწირე.", "B1"),
        ("volunteer", "მოხალისე", "/ˌvɒlənˈtɪr/", "Be a volunteer.", "მოხალისე იყავი.", "B1"),
        ("neighborhood", "უბანი", "/ˈneɪbərhʊd/", "I love my neighborhood.", "ჩემი უბანი მიყვარს.", "A2"),
        ("resident", "მცხოვრები", "/ˈrezɪdənt/", "She is a resident.", "ის მცხოვრებია.", "B1"),
        ("tenant", "მოიჯარე", "/ˈtenənt/", "The tenant pays rent.", "მოიჯარე ქირას იხდის.", "B1"),
        ("landlord", "მეპატრონე", "/ˈlændlɔːrd/", "Call the landlord.", "მეპატრონეს დაურეკე.", "B1"),
        ("lease", "იჯარა", "/liːs/", "Sign the lease.", "იჯარის ხელშეკრულება ხელი მოაწერე.", "B1"),
        ("rent", "ქირა", "/rent/", "Pay the rent.", "ქირა გადაიხადე.", "A2"),
        ("mortgage", "იპოთეკა", "/ˈmɔːrɡɪdʒ/", "Get a mortgage.", "იპოთეკა აიღე.", "B2"),
        ("eviction", "გამოსახლება", "/ɪˈvɪkʃən/", "Face eviction.", "გამოსახლების საფრთხე.", "C1"),
        ("renovation", "რემონტი", "/ˌrenəˈveɪʃən/", "The renovation took months.", "რემონტი თვეები გაგრძელდა.", "B1"),
        ("demolition", "დემონტაჟი", "/ˌdeməˈlɪʃən/", "The demolition was loud.", "დემონტაჟი ხმამაღალი იყო.", "B2"),
        ("construction", "მშენებლობა", "/kənˈstrʌkʃən/", "Construction is in progress.", "მშენებლობა მიმდინარეობს.", "A2"),
        ("crane", "ამწე", "/kreɪn/", "The crane lifted steel.", "ამწემ ფოლადი აიღო.", "B1"),
        ("scaffold", "ხარაჩო", "/ˈskæfəld/", "Workers on the scaffold.", "მუშები ხარაჩოზე.", "B2"),
        ("cement", "ცემენტი", "/sɪˈment/", "Mix the cement.", "ცემენტი აურიე.", "B1"),
        ("brick", "აგური", "/brɪk/", "Build with brick.", "აგურით ააშენე.", "A2"),
        ("concrete", "ბეტონი", "/ˈkɒŋkriːt/", "Pour the concrete.", "ბეტონი ჩაასხი.", "B1"),
        ("asphalt", "ასფალტი", "/ˈæsfɔːlt/", "Fresh asphalt on the road.", "ახალი ასფალტი გზაზე.", "B1"),
        ("gravel", "ხრეში", "/ˈɡrævəl/", "Walk on gravel.", "ხრეშზე იარე.", "B1"),
        ("cobblestone", "ქვაფენილი", "/ˈkɒbəlstoʊn/", "Old cobblestone streets.", "ძველი ქვაფენილის ქუჩები.", "B2"),
        ("tile", "ფილა", "/taɪl/", "Lay the tile.", "ფილა დააგე.", "A2"),
        ("awning", "ფარდული", "/ˈɔːnɪŋ/", "The store awning was torn.", "მაღაზიის ფარდული გახეული იყო.", "B2"),
        ("storefront", "ვიტრინა", "/ˈstɔːrfrʌnt/", "The storefront was decorated.", "ვიტრინა მორთული იყო.", "B1"),
        ("shutter", "ჟალუზი", "/ˈʃʌtər/", "Close the shutter.", "ჟალუზი დახურე.", "B1"),
        ("doorstep", "ზღურბლი", "/ˈdɔːrstep/", "Wait on the doorstep.", "ზღურბლთან დაელოდე.", "A2"),
        ("threshold", "ბარიერი", "/ˈθreʃhoʊld/", "Cross the threshold.", "ზღურბლი გადაკვეთე.", "B2"),
        ("lobby", "ლობი", "/ˈlɒbi/", "Wait in the lobby.", "ლობიში დაელოდე.", "B1"),
        ("hallway", "დერეფანი", "/ˈhɔːlweɪ/", "Walk down the hallway.", "დერეფანში გაიარე.", "A2"),
        ("corridor", "კორიდორი", "/ˈkɒrɪdɔːr/", "The corridor was long.", "კორიდორი გრძელი იყო.", "B1"),
        ("attic", "სხვენი", "/ˈætɪk/", "Check the attic.", "სხვენი შეამოწმე.", "B1"),
        ("basement", "სარდაფი", "/ˈbeɪsmənt/", "Go to the basement.", "სარდაფში ჩადი.", "A2"),
        ("cellar", "მარანი", "/ˈselər/", "Wine in the cellar.", "ღვინო მარანში.", "B1"),
        ("rooftop", "სახურავი", "/ˈruːftɒp/", "View from the rooftop.", "ხედი სახურავიდან.", "A2"),
        ("ledge", "კარნიზი", "/ledʒ/", "Don't stand on the ledge.", "კარნიზზე არ დადგე.", "B2"),
        ("gutter", "ღარი", "/ˈɡʌtər/", "Clean the gutter.", "ღარი გაწმინდე.", "B1"),
        ("drainpipe", "საწვიმარი მილი", "/ˈdreɪnpaɪp/", "The drainpipe was broken.", "საწვიმარი მილი გატეხილი იყო.", "B2"),
        ("sprinkler", "სასხურებელი", "/ˈsprɪŋklər/", "Turn on the sprinkler.", "სასხურებელი ჩართე.", "B1"),
        ("meter", "მრიცხველი", "/ˈmiːtər/", "Check the meter.", "მრიცხველი შეამოწმე.", "A2"),
        ("generator", "გენერატორი", "/ˈdʒenəreɪtər/", "The generator provides power.", "გენერატორი ენერგიას აწვდის.", "B1"),
        ("transformer", "ტრანსფორმატორი", "/trænsˈfɔːrmər/", "The transformer exploded.", "ტრანსფორმატორი აფეთქდა.", "B2"),
        ("outlet", "როზეტი", "/ˈaʊtlet/", "Plug into the outlet.", "როზეტში ჩართე.", "A2"),
        ("socket", "სოკეტი", "/ˈsɒkɪt/", "The socket was loose.", "სოკეტი მოშვებული იყო.", "B1"),
        ("fuse", "დამცავი", "/fjuːz/", "The fuse blew.", "დამცავი გადაიწვა.", "B2"),
        ("breaker", "ავტომატი", "/ˈbreɪkər/", "Flip the breaker.", "ავტომატი გადართე.", "B2"),
        ("wiring", "გაყვანილობა", "/ˈwaɪərɪŋ/", "Fix the wiring.", "გაყვანილობა შეაკეთე.", "B2"),
        ("plumbing", "სანტექნიკა", "/ˈplʌmɪŋ/", "Call for plumbing.", "სანტექნიკა გამოიძახე.", "B1"),
        ("sewage", "კანალიზაცია", "/ˈsuːɪdʒ/", "Sewage problem.", "კანალიზაციის პრობლემა.", "B2"),
        ("recycling", "გადამუშავება", "/riːˈsaɪklɪŋ/", "Put it in recycling.", "გადამუშავებაში ჩააგდე.", "A2"),
        ("compost", "კომპოსტი", "/ˈkɒmpɒst/", "Make compost.", "კომპოსტი გააკეთე.", "B2"),
        ("landfill", "ნაგავსაყრელი", "/ˈlændfɪl/", "Waste goes to the landfill.", "ნარჩენები ნაგავსაყრელზე მიდის.", "B2"),
        ("pollution", "დაბინძურება", "/pəˈluːʃən/", "Reduce pollution.", "დაბინძურება შეამცირე.", "A2"),
        ("emission", "გამოფრქვევა", "/ɪˈmɪʃən/", "Reduce carbon emissions.", "ნახშირბადის გამოფრქვევა შეამცირე.", "B2"),
        ("sustainability", "მდგრადობა", "/səˌsteɪnəˈbɪləti/", "Focus on sustainability.", "მდგრადობაზე ფოკუსირება.", "B2"),
        ("urban", "ურბანული", "/ˈɜːrbən/", "Urban life is fast.", "ურბანული ცხოვრება სწრაფია.", "B1"),
        ("rural", "სოფლის", "/ˈrʊrəl/", "Rural areas are quiet.", "სოფლის რაიონები წყნარია.", "B1"),
        ("metropolitan", "მეტროპოლიტენური", "/ˌmetrəˈpɒlɪtən/", "A metropolitan area.", "მეტროპოლიტენური არეალი.", "B2"),
        ("municipal", "მუნიციპალური", "/mjuːˈnɪsɪpəl/", "Municipal government.", "მუნიციპალური მთავრობა.", "B2"),
        ("zoning", "ზონირება", "/ˈzoʊnɪŋ/", "Check the zoning laws.", "ზონირების კანონები შეამოწმე.", "C1"),
        ("infrastructure", "ინფრასტრუქტურა", "/ˈɪnfrəstrʌktʃər/", "Improve infrastructure.", "ინფრასტრუქტურა გააუმჯობესე.", "B2"),
        ("gentrification", "გენტრიფიკაცია", "/ˌdʒentrɪfɪˈkeɪʃən/", "Gentrification changes neighborhoods.", "გენტრიფიკაცია უბნებს ცვლის.", "C1"),
        ("displacement", "გადაადგილება", "/dɪsˈpleɪsmənt/", "Displacement of residents.", "მცხოვრებლების გადაადგილება.", "C1"),
        ("commuter", "მგზავრი", "/kəˈmjuːtər/", "Commuters fill the subway.", "მგზავრები მეტროს ავსებენ.", "B1"),
    ],
    "freelancing-remote": [
        ("deadline", "ვადა", "/ˈdedlaɪn/", "Meet the deadline.", "ვადა დაიცავი.", "A2"),
        ("invoice", "ინვოისი", "/ˈɪnvɔɪs/", "Send an invoice.", "ინვოისი გაგზავნე.", "B1"),
        ("contract", "კონტრაქტი", "/ˈkɒntrækt/", "Sign the contract.", "კონტრაქტს ხელი მოაწერე.", "A2"),
        ("portfolio", "პორტფოლიო", "/pɔːrtˈfoʊlioʊ/", "Build your portfolio.", "პორტფოლიო ააწყვე.", "B1"),
        ("client", "კლიენტი", "/ˈklaɪənt/", "Meet the client.", "კლიენტს შეხვდი.", "A2"),
        ("proposal", "წინადადება", "/prəˈpoʊzəl/", "Write a proposal.", "წინადადება დაწერე.", "B1"),
        ("milestone", "ეტაპი", "/ˈmaɪlstoʊn/", "Reach a milestone.", "ეტაპს მიაღწიე.", "B1"),
        ("feedback", "უკუკავშირი", "/ˈfiːdbæk/", "Give feedback.", "უკუკავშირი მომეცი.", "A2"),
        ("revision", "შესწორება", "/rɪˈvɪʒən/", "Make a revision.", "შესწორება გააკეთე.", "B1"),
        ("scope", "მოცულობა", "/skoʊp/", "Define the scope.", "მოცულობა განსაზღვრე.", "B1"),
        ("negotiate", "მოლაპარაკება", "/nɪˈɡoʊʃieɪt/", "Negotiate the rate.", "ფასზე მოილაპარაკე.", "B1"),
        ("retainer", "აბონემენტი", "/rɪˈteɪnər/", "Work on a retainer.", "აბონემენტით მუშაობა.", "B2"),
        ("outsource", "აუთსორსინგი", "/ˈaʊtsɔːrs/", "Outsource the work.", "სამუშაო აუთსორსინგზე გადაიტანე.", "B2"),
        ("deliverable", "მოსაწოდებელი", "/dɪˈlɪvərəbəl/", "Submit the deliverable.", "მოსაწოდებელი წარადგინე.", "B2"),
        ("remote", "დისტანციური", "/rɪˈmoʊt/", "Work remote.", "დისტანციურად იმუშავე.", "A2"),
        ("flexible", "მოქნილი", "/ˈfleksəbəl/", "Flexible schedule.", "მოქნილი გრაფიკი.", "A2"),
        ("productivity", "პროდუქტიულობა", "/ˌprɒdʌkˈtɪvəti/", "Increase productivity.", "პროდუქტიულობა გაზარდე.", "B1"),
        ("workspace", "სამუშაო ადგილი", "/ˈwɜːrkspeɪs/", "Set up a workspace.", "სამუშაო ადგილი მოაწყვე.", "A2"),
        ("coworking", "კოვორკინგი", "/koʊˈwɜːrkɪŋ/", "Try a coworking space.", "კოვორკინგის სივრცე სცადე.", "B1"),
        ("freelancer", "ფრილანსერი", "/ˈfriːlænsər/", "She is a freelancer.", "ის ფრილანსერია.", "A2"),
        ("gig", "შეკვეთა", "/ɡɪɡ/", "Get a new gig.", "ახალი შეკვეთა მიიღე.", "B1"),
        ("platform", "პლატფორმა", "/ˈplætfɔːrm/", "Use a freelance platform.", "ფრილანსის პლატფორმა გამოიყენე.", "A2"),
        ("bid", "შეთავაზება", "/bɪd/", "Place a bid.", "შეთავაზება გააკეთე.", "B1"),
        ("hourly", "საათობრივი", "/ˈaʊərli/", "Charge hourly.", "საათობრივად ჩამოთვალე.", "A2"),
        ("rate", "ტარიფი", "/reɪt/", "Set your rate.", "ტარიფი დააწესე.", "A2"),
        ("deposit", "წინასწარი", "/dɪˈpɒzɪt/", "Pay a deposit.", "წინასწარი გადაიხადე.", "B1"),
        ("payment", "გადახდა", "/ˈpeɪmənt/", "Receive payment.", "გადახდა მიიღე.", "A2"),
        ("escrow", "ესქრო", "/ˈeskroʊ/", "Money is in escrow.", "ფული ესქროშია.", "C1"),
        ("testimonial", "რეკომენდაცია", "/ˌtestɪˈmoʊniəl/", "Get a testimonial.", "რეკომენდაცია მიიღე.", "B2"),
        ("review", "მიმოხილვა", "/rɪˈvjuː/", "Leave a review.", "მიმოხილვა დატოვე.", "A2"),
        ("rating", "რეიტინგი", "/ˈreɪtɪŋ/", "Improve your rating.", "რეიტინგი გააუმჯობესე.", "A2"),
        ("niche", "ნიშა", "/niːʃ/", "Find your niche.", "შენი ნიშა იპოვე.", "B1"),
        ("brand", "ბრენდი", "/brænd/", "Build your brand.", "ბრენდი ააწყვე.", "A2"),
        ("marketing", "მარკეტინგი", "/ˈmɑːrkɪtɪŋ/", "Learn marketing.", "მარკეტინგი ისწავლე.", "A2"),
        ("networking", "ნეთვორქინგი", "/ˈnetwɜːrkɪŋ/", "Networking is important.", "ნეთვორქინგი მნიშვნელოვანია.", "B1"),
        ("pitch", "პრეზენტაცია", "/pɪtʃ/", "Pitch your idea.", "იდეა წარადგინე.", "B1"),
        ("burnout", "გადაწვა", "/ˈbɜːrnaʊt/", "Avoid burnout.", "გადაწვას მოერიდე.", "B1"),
        ("balance", "ბალანსი", "/ˈbæləns/", "Find work-life balance.", "სამუშაო-ცხოვრების ბალანსი იპოვე.", "A2"),
        ("automation", "ავტომატიზაცია", "/ˌɔːtəˈmeɪʃən/", "Use automation tools.", "ავტომატიზაციის ინსტრუმენტები გამოიყენე.", "B1"),
        ("template", "შაბლონი", "/ˈtemplɪt/", "Use a template.", "შაბლონი გამოიყენე.", "A2"),
        ("onboarding", "ადაპტაცია", "/ˈɒnbɔːrdɪŋ/", "Client onboarding.", "კლიენტის ადაპტაცია.", "B2"),
        ("timezone", "დროის სარტყელი", "/ˈtaɪmzoʊn/", "Check the timezone.", "დროის სარტყელი შეამოწმე.", "A2"),
        ("asynchronous", "ასინქრონული", "/eɪˈsɪŋkrənəs/", "Work asynchronously.", "ასინქრონულად იმუშავე.", "B2"),
        ("collaborate", "თანამშრომლობა", "/kəˈlæbəreɪt/", "Collaborate online.", "ონლაინ ითანამშრომლე.", "B1"),
        ("communication", "კომუნიკაცია", "/kəˌmjuːnɪˈkeɪʃən/", "Clear communication matters.", "მკაფიო კომუნიკაცია მნიშვნელოვანია.", "A2"),
        ("prioritize", "პრიორიტეტი", "/praɪˈɒrɪtaɪz/", "Prioritize tasks.", "ამოცანები პრიორიტეტით დაალაგე.", "B1"),
        ("delegate", "დელეგირება", "/ˈdelɪɡeɪt/", "Delegate work.", "სამუშაო დაუნაწილე.", "B1"),
        ("subcontract", "ქვეკონტრაქტი", "/ˌsʌbˈkɒntrækt/", "Subcontract the design.", "დიზაინი ქვეკონტრაქტით.", "B2"),
        ("upskill", "კვალიფიკაცია", "/ˈʌpskɪl/", "Upskill constantly.", "მუდმივად აიმაღლე კვალიფიკაცია.", "B2"),
        ("certificate", "სერტიფიკატი", "/sərˈtɪfɪkət/", "Get a certificate.", "სერტიფიკატი მიიღე.", "A2"),
        ("portfolio", "პორტფოლიო", "/pɔːrtˈfoʊlioʊ/", "Update your portfolio.", "პორტფოლიო განაახლე.", "B1"),
        ("specialization", "სპეციალიზაცია", "/ˌspeʃəlaɪˈzeɪʃən/", "Choose a specialization.", "სპეციალიზაცია აირჩიე.", "B2"),
        ("expertise", "გამოცდილება", "/ˌekspɜːrˈtiːz/", "Share your expertise.", "გამოცდილება გაუზიარე.", "B1"),
        ("consultant", "კონსულტანტი", "/kənˈsʌltənt/", "Hire a consultant.", "კონსულტანტი დაიქირავე.", "B1"),
        ("contractor", "კონტრაქტორი", "/kənˈtræktər/", "Work as a contractor.", "კონტრაქტორად იმუშავე.", "B1"),
        ("agency", "სააგენტო", "/ˈeɪdʒənsi/", "Start an agency.", "სააგენტო დააარსე.", "B1"),
        ("scalable", "მასშტაბირებადი", "/ˈskeɪləbəl/", "Build a scalable business.", "მასშტაბირებადი ბიზნესი ააწყვე.", "B2"),
        ("passive", "პასიური", "/ˈpæsɪv/", "Earn passive income.", "პასიური შემოსავალი მიიღე.", "B1"),
        ("recurring", "განმეორებადი", "/rɪˈkɜːrɪŋ/", "Recurring revenue.", "განმეორებადი შემოსავალი.", "B2"),
        ("subscription", "გამოწერა", "/səbˈskrɪpʃən/", "Offer a subscription.", "გამოწერა შესთავაზე.", "B1"),
        ("retainer", "თვიური", "/rɪˈteɪnər/", "Monthly retainer.", "თვიური კონტრაქტი.", "B2"),
        ("profit", "მოგება", "/ˈprɒfɪt/", "Make a profit.", "მოგება მიიღე.", "A2"),
        ("expense", "ხარჯი", "/ɪkˈspens/", "Track expenses.", "ხარჯები აღრიცხე.", "A2"),
        ("tax", "გადასახადი", "/tæks/", "Pay your taxes.", "გადასახადები გადაიხადე.", "A2"),
        ("deduction", "გამოქვითვა", "/dɪˈdʌkʃən/", "Claim a deduction.", "გამოქვითვა მოითხოვე.", "B2"),
        ("accounting", "ბუღალტერია", "/əˈkaʊntɪŋ/", "Do the accounting.", "ბუღალტერია აწარმოე.", "B1"),
        ("spreadsheet", "ცხრილი", "/ˈspredʃiːt/", "Use a spreadsheet.", "ცხრილი გამოიყენე.", "A2"),
        ("software", "პროგრამა", "/ˈsɒftweər/", "Install software.", "პროგრამა დააყენე.", "A2"),
        ("tool", "ინსტრუმენტი", "/tuːl/", "Use the right tool.", "სწორი ინსტრუმენტი გამოიყენე.", "A1"),
        ("project", "პროექტი", "/ˈprɒdʒekt/", "Start a project.", "პროექტი დაიწყე.", "A2"),
        ("task", "ამოცანა", "/tæsk/", "Complete the task.", "ამოცანა შეასრულე.", "A2"),
        ("workflow", "სამუშაო პროცესი", "/ˈwɜːrkfloʊ/", "Improve your workflow.", "სამუშაო პროცესი გააუმჯობესე.", "B1"),
        ("efficiency", "ეფექტურობა", "/ɪˈfɪʃənsi/", "Increase efficiency.", "ეფექტურობა გაზარდე.", "B1"),
        ("focus", "ფოკუსი", "/ˈfoʊkəs/", "Stay focused.", "ფოკუსირებული იყავი.", "A2"),
        ("distraction", "ყურადღების გაფანტვა", "/dɪˈstrækʃən/", "Avoid distractions.", "ყურადღების გაფანტვას მოერიდე.", "B1"),
        ("procrastination", "გადავადება", "/proʊˌkræstɪˈneɪʃən/", "Stop procrastination.", "გადავადება შეწყვიტე.", "B2"),
        ("motivation", "მოტივაცია", "/ˌmoʊtɪˈveɪʃən/", "Find motivation.", "მოტივაცია იპოვე.", "A2"),
        ("discipline", "დისციპლინა", "/ˈdɪsəplɪn/", "Have discipline.", "დისციპლინა გქონდეს.", "B1"),
        ("routine", "რუტინა", "/ruːˈtiːn/", "Build a routine.", "რუტინა ჩამოაყალიბე.", "A2"),
        ("boundary", "საზღვარი", "/ˈbaʊndəri/", "Set boundaries.", "საზღვრები დაადგინე.", "B1"),
        ("availability", "ხელმისაწვდომობა", "/əˌveɪləˈbɪləti/", "Check availability.", "ხელმისაწვდომობა შეამოწმე.", "B1"),
        ("calendar", "კალენდარი", "/ˈkælɪndər/", "Check your calendar.", "კალენდარი შეამოწმე.", "A1"),
        ("meeting", "შეხვედრა", "/ˈmiːtɪŋ/", "Schedule a meeting.", "შეხვედრა დანიშნე.", "A2"),
        ("agenda", "დღის წესრიგი", "/əˈdʒendə/", "Set the agenda.", "დღის წესრიგი დაადგინე.", "B1"),
        ("conference", "კონფერენცია", "/ˈkɒnfərəns/", "Join the conference.", "კონფერენციას შეუერთდი.", "B1"),
        ("webinar", "ვებინარი", "/ˈwebɪnɑːr/", "Host a webinar.", "ვებინარი ჩაატარე.", "B1"),
        ("presentation", "პრეზენტაცია", "/ˌprezənˈteɪʃən/", "Give a presentation.", "პრეზენტაცია წარადგინე.", "A2"),
        ("slide", "სლაიდი", "/slaɪd/", "Create a slide.", "სლაიდი შექმენი.", "A2"),
        ("draft", "მონახაზი", "/dræft/", "Write a draft.", "მონახაზი დაწერე.", "A2"),
        ("proofread", "კორექტურა", "/ˈpruːfriːd/", "Proofread your work.", "კორექტურა გაუკეთე.", "B1"),
        ("edit", "რედაქტირება", "/ˈedɪt/", "Edit the document.", "დოკუმენტი დაარედაქტირე.", "A2"),
        ("format", "ფორმატი", "/ˈfɔːrmæt/", "Format the text.", "ტექსტი დააფორმატე.", "A2"),
        ("upload", "ატვირთვა", "/ˌʌpˈloʊd/", "Upload the file.", "ფაილი ატვირთე.", "A2"),
        ("download", "ჩამოტვირთვა", "/ˈdaʊnloʊd/", "Download the file.", "ფაილი ჩამოტვირთე.", "A2"),
        ("backup", "სარეზერვო", "/ˈbækʌp/", "Make a backup.", "სარეზერვო ასლი გააკეთე.", "A2"),
        ("cloud", "ღრუბელი", "/klaʊd/", "Save to the cloud.", "ღრუბელში შეინახე.", "A2"),
        ("storage", "საცავი", "/ˈstɔːrɪdʒ/", "Buy more storage.", "მეტი საცავი იყიდე.", "A2"),
        ("bandwidth", "გამტარობა", "/ˈbændwɪdθ/", "Check your bandwidth.", "გამტარობა შეამოწმე.", "B1"),
        ("encryption", "დაშიფვრა", "/ɪnˈkrɪpʃən/", "Use encryption.", "დაშიფვრა გამოიყენე.", "B2"),
        ("privacy", "კონფიდენციალურობა", "/ˈprɪvəsi/", "Protect privacy.", "კონფიდენციალურობა დაიცავი.", "B1"),
        ("password", "პაროლი", "/ˈpæswɜːrd/", "Change your password.", "პაროლი შეცვალე.", "A1"),
        ("authentication", "ავთენტიფიკაცია", "/ɔːˌθentɪˈkeɪʃən/", "Enable authentication.", "ავთენტიფიკაცია ჩართე.", "B2"),
        ("verification", "ვერიფიკაცია", "/ˌverɪfɪˈkeɪʃən/", "Complete verification.", "ვერიფიკაცია გაიარე.", "B1"),
        ("signature", "ხელმოწერა", "/ˈsɪɡnətʃər/", "Add your signature.", "ხელმოწერა დაამატე.", "A2"),
        ("agreement", "შეთანხმება", "/əˈɡriːmənt/", "Sign the agreement.", "შეთანხმებას ხელი მოაწერე.", "A2"),
        ("terms", "პირობები", "/tɜːrmz/", "Read the terms.", "პირობები წაიკითხე.", "A2"),
        ("copyright", "საავტორო", "/ˈkɒpiraɪt/", "Respect copyright.", "საავტორო უფლებები დაიცავი.", "B1"),
        ("license", "ლიცენზია", "/ˈlaɪsəns/", "Buy a license.", "ლიცენზია იყიდე.", "A2"),
        ("intellectual", "ინტელექტუალური", "/ˌɪntəˈlektʃuəl/", "Protect intellectual property.", "ინტელექტუალური საკუთრება დაიცავი.", "B2"),
        ("trademark", "სავაჭრო ნიშანი", "/ˈtreɪdmɑːrk/", "Register a trademark.", "სავაჭრო ნიშანი დაარეგისტრირე.", "B2"),
        ("patent", "პატენტი", "/ˈpætənt/", "File a patent.", "პატენტი შეიტანე.", "B2"),
        ("mentor", "მენტორი", "/ˈmentɔːr/", "Find a mentor.", "მენტორი იპოვე.", "B1"),
        ("coaching", "ქოუჩინგი", "/ˈkoʊtʃɪŋ/", "Try coaching.", "ქოუჩინგი სცადე.", "B1"),
        ("community", "საზოგადოება", "/kəˈmjuːnəti/", "Join a community.", "საზოგადოებას შეუერთდი.", "A2"),
        ("forum", "ფორუმი", "/ˈfɔːrəm/", "Post on the forum.", "ფორუმზე დაწერე.", "B1"),
        ("blog", "ბლოგი", "/blɒɡ/", "Start a blog.", "ბლოგი დაიწყე.", "A2"),
        ("podcast", "პოდკასტი", "/ˈpɒdkæst/", "Listen to a podcast.", "პოდკასტი მოუსმინე.", "A2"),
        ("newsletter", "სიახლეები", "/ˈnjuːzletər/", "Subscribe to the newsletter.", "სიახლეების გამოწერა.", "B1"),
        ("audience", "აუდიტორია", "/ˈɔːdiəns/", "Grow your audience.", "აუდიტორია გაზარდე.", "B1"),
        ("content", "კონტენტი", "/ˈkɒntent/", "Create content.", "კონტენტი შექმენი.", "A2"),
        ("strategy", "სტრატეგია", "/ˈstrætədʒi/", "Plan a strategy.", "სტრატეგია დაგეგმე.", "B1"),
        ("analytics", "ანალიტიკა", "/ˌænəˈlɪtɪks/", "Check analytics.", "ანალიტიკა შეამოწმე.", "B1"),
        ("conversion", "კონვერსია", "/kənˈvɜːrʒən/", "Improve conversion.", "კონვერსია გააუმჯობესე.", "B2"),
        ("funnel", "ფანელი", "/ˈfʌnəl/", "Build a sales funnel.", "გაყიდვების ფანელი ააწყვე.", "B2"),
        ("lead", "ლიდი", "/liːd/", "Generate leads.", "ლიდები მოიზიდე.", "B1"),
        ("prospect", "პოტენციური", "/ˈprɒspekt/", "Contact the prospect.", "პოტენციურ კლიენტს დაუკავშირდი.", "B1"),
        ("referral", "რეფერალი", "/rɪˈfɜːrəl/", "Ask for a referral.", "რეფერალი სთხოვე.", "B1"),
        ("commission", "საკომისიო", "/kəˈmɪʃən/", "Earn a commission.", "საკომისიო მიიღე.", "B1"),
        ("affiliate", "პარტნიორი", "/əˈfɪlieɪt/", "Join an affiliate program.", "პარტნიორულ პროგრამას შეუერთდი.", "B2"),
        ("resell", "გადაყიდვა", "/riːˈsel/", "Resell services.", "მომსახურების გადაყიდვა.", "B1"),
        ("upsell", "დამატებითი გაყიდვა", "/ˈʌpsel/", "Try to upsell.", "დამატებითი გაყიდვა სცადე.", "B2"),
        ("retention", "შენარჩუნება", "/rɪˈtenʃən/", "Improve client retention.", "კლიენტის შენარჩუნება გააუმჯობესე.", "B2"),
        ("satisfaction", "კმაყოფილება", "/ˌsætɪsˈfækʃən/", "Client satisfaction matters.", "კლიენტის კმაყოფილება მნიშვნელოვანია.", "B1"),
        ("reputation", "რეპუტაცია", "/ˌrepjuˈteɪʃən/", "Build your reputation.", "რეპუტაცია ააწყვე.", "B1"),
        ("credibility", "სანდოობა", "/ˌkredɪˈbɪləti/", "Build credibility.", "სანდოობა გაიმყარე.", "B2"),
        ("professional", "პროფესიონალი", "/prəˈfeʃənəl/", "Be professional.", "პროფესიონალი იყავი.", "A2"),
        ("competent", "კომპეტენტური", "/ˈkɒmpɪtənt/", "Be competent.", "კომპეტენტური იყავი.", "B1"),
        ("reliable", "საიმედო", "/rɪˈlaɪəbəl/", "Be reliable.", "საიმედო იყავი.", "A2"),
        ("responsive", "მობილური", "/rɪˈspɒnsɪv/", "Be responsive.", "მობილური იყავი.", "B1"),
        ("proactive", "პროაქტიული", "/proʊˈæktɪv/", "Be proactive.", "პროაქტიული იყავი.", "B1"),
        ("adaptable", "ადაპტირებადი", "/əˈdæptəbəl/", "Be adaptable.", "ადაპტირებადი იყავი.", "B1"),
        ("resourceful", "მარაგიანი", "/rɪˈsɔːrsfl/", "Be resourceful.", "რესურსებს კარგად გამოიყენე.", "B2"),
        ("innovative", "ინოვაციური", "/ˈɪnəveɪtɪv/", "Be innovative.", "ინოვაციური იყავი.", "B1"),
        ("competitive", "კონკურენტული", "/kəmˈpetɪtɪv/", "Stay competitive.", "კონკურენტული იყავი.", "B1"),
        ("sustainable", "მდგრადი", "/səˈsteɪnəbəl/", "Build something sustainable.", "მდგრადი რამე ააწყვე.", "B1"),
        ("profitable", "მომგებიანი", "/ˈprɒfɪtəbəl/", "Make it profitable.", "მომგებიანი გახადე.", "B1"),
        ("diversify", "დივერსიფიკაცია", "/daɪˈvɜːrsɪfaɪ/", "Diversify income.", "შემოსავალი დაადივერსიფიცირე.", "B2"),
        ("stability", "სტაბილურობა", "/stəˈbɪləti/", "Find stability.", "სტაბილურობა იპოვე.", "B1"),
        ("growth", "ზრდა", "/ɡroʊθ/", "Focus on growth.", "ზრდაზე ფოკუსირდი.", "A2"),
        ("scale", "მასშტაბი", "/skeɪl/", "Scale your business.", "ბიზნესი გაზარდე.", "B1"),
        ("invest", "ინვესტირება", "/ɪnˈvest/", "Invest in yourself.", "საკუთარ თავში ინვესტიცია გააკეთე.", "A2"),
        ("savings", "დანაზოგი", "/ˈseɪvɪŋz/", "Build savings.", "დანაზოგი დააგროვე.", "A2"),
        ("emergency", "საგანგებო", "/ɪˈmɜːrdʒənsi/", "Emergency fund.", "საგანგებო ფონდი.", "A2"),
        ("insurance", "დაზღვევა", "/ɪnˈʃʊrəns/", "Buy insurance.", "დაზღვევა იყიდე.", "A2"),
        ("retirement", "პენსია", "/rɪˈtaɪərmənt/", "Plan for retirement.", "პენსიისთვის დაგეგმე.", "B1"),
        ("independence", "დამოუკიდებლობა", "/ˌɪndɪˈpendəns/", "Financial independence.", "ფინანსური დამოუკიდებლობა.", "B1"),
        ("freedom", "თავისუფლება", "/ˈfriːdəm/", "Work gives freedom.", "სამუშაო თავისუფლებას გაძლევს.", "A2"),
        ("lifestyle", "ცხოვრების წესი", "/ˈlaɪfstaɪl/", "Design your lifestyle.", "ცხოვრების წესი დააპროექტე.", "A2"),
        ("wellbeing", "კეთილდღეობა", "/ˌwelˈbiːɪŋ/", "Focus on wellbeing.", "კეთილდღეობაზე ფოკუსირდი.", "B1"),
        ("mindset", "აზროვნება", "/ˈmaɪndset/", "Growth mindset.", "ზრდის აზროვნება.", "B1"),
        ("resilience", "გამძლეობა", "/rɪˈzɪliəns/", "Build resilience.", "გამძლეობა გაიმყარე.", "B2"),
        ("perseverance", "დაჟინებულობა", "/ˌpɜːrsɪˈvɪrəns/", "Show perseverance.", "დაჟინებულობა გამოიჩინე.", "B2"),
        ("determination", "მიზანდასახულობა", "/dɪˌtɜːrmɪˈneɪʃən/", "Show determination.", "მიზანდასახულობა გამოიჩინე.", "B1"),
        ("ambition", "ამბიცია", "/æmˈbɪʃən/", "Have ambition.", "ამბიცია გქონდეს.", "B1"),
        ("vision", "ხედვა", "/ˈvɪʒən/", "Share your vision.", "ხედვა გაუზიარე.", "A2"),
        ("goal", "მიზანი", "/ɡoʊl/", "Set a goal.", "მიზანი დაისახე.", "A1"),
        ("milestone", "ეტაპი", "/ˈmaɪlstoʊn/", "Celebrate milestones.", "ეტაპები აღნიშნე.", "B1"),
        ("achievement", "მიღწევა", "/əˈtʃiːvmənt/", "Celebrate achievements.", "მიღწევები აღნიშნე.", "B1"),
        ("success", "წარმატება", "/səkˈses/", "Define success.", "წარმატება განსაზღვრე.", "A2"),
        ("failure", "წარუმატებლობა", "/ˈfeɪljər/", "Learn from failure.", "წარუმატებლობიდან ისწავლე.", "A2"),
        ("iteration", "იტერაცია", "/ˌɪtəˈreɪʃən/", "Improve with each iteration.", "ყოველ იტერაციაზე გააუმჯობესე.", "B2"),
        ("prototype", "პროტოტიპი", "/ˈproʊtətaɪp/", "Build a prototype.", "პროტოტიპი ააწყვე.", "B2"),
        ("launch", "გაშვება", "/lɔːntʃ/", "Launch the product.", "პროდუქტი გაუშვი.", "A2"),
        ("pivot", "შეცვლა", "/ˈpɪvət/", "Pivot your strategy.", "სტრატეგია შეცვალე.", "B2"),
        ("adapt", "ადაპტირება", "/əˈdæpt/", "Adapt to changes.", "ცვლილებებს მოერგე.", "B1"),
        ("evolve", "განვითარება", "/ɪˈvɒlv/", "Evolve your skills.", "უნარები განავითარე.", "B1"),
        ("optimize", "ოპტიმიზაცია", "/ˈɒptɪmaɪz/", "Optimize your process.", "პროცესი ოპტიმიზირე.", "B1"),
        ("streamline", "გამარტივება", "/ˈstriːmlaɪn/", "Streamline your workflow.", "სამუშაო პროცესი გაამარტივე.", "B2"),
        ("automate", "ავტომატიზირება", "/ˈɔːtəmeɪt/", "Automate repetitive tasks.", "განმეორებადი ამოცანები ავტომატიზირე.", "B1"),
        ("integrate", "ინტეგრირება", "/ˈɪntɪɡreɪt/", "Integrate your tools.", "ინსტრუმენტები ინტეგრირე.", "B1"),
        ("synchronize", "სინქრონიზაცია", "/ˈsɪŋkrənaɪz/", "Synchronize your data.", "მონაცემები სინქრონიზე.", "B2"),
    ],
}

def expand_file(filename, new_words):
    filepath = os.path.join(CONTENT_DIR, filename)
    with open(filepath) as f:
        data = json.load(f)
    
    existing = {w["english"].lower() for w in data}
    category = filename.replace(".json", "")
    
    added = 0
    for eng, geo, pron, ex_en, ex_ka, level in new_words:
        if eng.lower() not in existing and len(data) < 200:
            data.append({
                "english": eng,
                "georgian": geo,
                "pronunciation": pron,
                "example_en": ex_en,
                "example_ka": ex_ka,
                "category": category,
                "level": level
            })
            existing.add(eng.lower())
            added += 1
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"{filename}: {len(data)} words (added {added})")

for filename, words in EXPANSIONS.items():
    expand_file(filename + ".json", words)
