#!/usr/bin/env python3
import json

INPUT = "/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/airport-flying.json"

with open(INPUT, "r") as f:
    existing = json.load(f)

existing_words = {e["english"].lower() for e in existing}

# New entries to add (word, georgian, pronunciation, example_en, example_ka)
new_entries = [
    ("Aisle", "გასასვლელი", "/aɪl/", "I prefer an aisle seat.", "გასასვლელთან ადგილი მირჩევნია."),
    ("Window", "ფანჯარა", "/ˈwɪndoʊ/", "Can I have a window seat?", "ფანჯარასთან ადგილი შეიძლება?"),
    ("Overhead", "თავზე", "/ˌoʊvərˈhed/", "Put your bag in the overhead bin.", "ჩანთა თავზე განყოფილებაში დადეთ."),
    ("Crew", "ეკიპაჟი", "/kruː/", "The crew was very friendly.", "ეკიპაჟი ძალიან მეგობრული იყო."),
    ("Stewardess", "სტიუარდესა", "/ˈstjuːərdəs/", "The stewardess served drinks.", "სტიუარდესამ სასმელები მოგვიტანა."),
    ("Copilot", "მეორე პილოტი", "/ˈkoʊpaɪlət/", "The copilot assisted with landing.", "მეორე პილოტმა დაფრენაში დაეხმარა."),
    ("Helicopter", "ვერტმფრენი", "/ˈhelɪkɒptər/", "A helicopter landed on the roof.", "ვერტმფრენი სახურავზე დაეშვა."),
    ("Jet", "რეაქტიული თვითმფრინავი", "/dʒet/", "The private jet was luxurious.", "კერძო რეაქტიული თვითმფრინავი ფუფუნებით იყო."),
    ("Engine", "ძრავა", "/ˈendʒɪn/", "The engine is very powerful.", "ძრავა ძალიან ძლიერია."),
    ("Wing", "ფრთა", "/wɪŋ/", "I could see the wing from my seat.", "ჩემი ადგილიდან ფრთა ჩანდა."),
    ("Tail", "კუდი", "/teɪl/", "The airline logo is on the tail.", "ავიაკომპანიის ლოგო კუდზეა."),
    ("Tray", "მაგიდა", "/treɪ/", "Please fold up your tray table.", "გთხოვთ, მაგიდა აკეცოთ."),
    ("Blanket", "საბანი", "/ˈblæŋkɪt/", "May I have a blanket please?", "შეიძლება საბანი მომცეთ?"),
    ("Headphones", "ყურსასმენი", "/ˈhedfəʊnz/", "Headphones are provided on board.", "ყურსასმენი ბორტზე გაიცემა."),
    ("Announcement", "განცხადება", "/əˈnaʊnsmənt/", "Listen to the announcement.", "განცხადებას მოუსმინეთ."),
    ("Baggage", "ბარგი", "/ˈbæɡɪdʒ/", "Baggage claim is downstairs.", "ბარგის მიღება ქვედა სართულზეა."),
    ("Carousel", "კარუსელი", "/ˌkærəˈsel/", "Wait at the baggage carousel.", "ბარგის კარუსელთან დაელოდეთ."),
    ("Belt", "ლენტი", "/belt/", "Your bag is on belt number four.", "თქვენი ჩანთა მეოთხე ლენტაზეა."),
    ("Tag", "ბირკა", "/tæɡ/", "Attach a tag to your luggage.", "ბარგზე ბირკა მიამაგრეთ."),
    ("Scale", "სასწორი", "/skeɪl/", "Put your bag on the scale.", "ჩანთა სასწორზე დადეთ."),
    ("Weight", "წონა", "/weɪt/", "The weight limit is 23 kilograms.", "წონის ლიმიტი 23 კილოგრამია."),
    ("Overweight", "ზედმეტი წონა", "/ˌoʊvərˈweɪt/", "Your bag is overweight.", "თქვენი ჩანთა ზედმეტი წონისაა."),
    ("Counter", "მრიცხველი", "/ˈkaʊntər/", "Go to the check-in counter.", "რეგისტრაციის დახლთან მიდით."),
    ("Lounge", "დარბაზი", "/laʊndʒ/", "We relaxed in the airport lounge.", "აეროპორტის დარბაზში დავისვენეთ."),
    ("Queue", "რიგი", "/kjuː/", "The queue at security was long.", "უსაფრთხოების რიგი გრძელი იყო."),
    ("Scanner", "სკანერი", "/ˈskænər/", "Put your items through the scanner.", "ნივთები სკანერში გაატარეთ."),
    ("X-ray", "რენტგენი", "/ˈeksreɪ/", "Your bag will go through the X-ray.", "თქვენი ჩანთა რენტგენს გაივლის."),
    ("Metal", "ლითონი", "/ˈmetəl/", "Remove all metal objects.", "ყველა ლითონის ნივთი მოიხსენით."),
    ("Detector", "დეტექტორი", "/dɪˈtektər/", "Walk through the metal detector.", "ლითონის დეტექტორში გაიარეთ."),
    ("Prohibited", "აკრძალული", "/prəˈhɪbɪtɪd/", "Liquids over 100ml are prohibited.", "100 მლ-ზე მეტი სითხე აკრძალულია."),
    ("Liquid", "სითხე", "/ˈlɪkwɪd/", "Pack liquids in a clear bag.", "სითხეები გამჭვირვალე ჩანთაში ჩადეთ."),
    ("Boarding pass", "ჩასხდომის ბარათი", "/ˈbɔːrdɪŋ pɑːs/", "Show your boarding pass at the gate.", "გეითზე ჩასხდომის ბარათი აჩვენეთ."),
    ("Destination", "დანიშნულების ადგილი", "/ˌdestɪˈneɪʃən/", "What is your final destination?", "რა არის თქვენი საბოლოო დანიშნულების ადგილი?"),
    ("Direct", "პირდაპირი", "/dəˈrekt/", "Is this a direct flight?", "ეს პირდაპირი ფრენაა?"),
    ("Domestic", "შიდა", "/dəˈmestɪk/", "Domestic flights are cheaper.", "შიდა ფრენები უფრო იაფია."),
    ("International", "საერთაშორისო", "/ˌɪntərˈnæʃənəl/", "The international terminal is larger.", "საერთაშორისო ტერმინალი უფრო დიდია."),
    ("Connecting", "დამაკავშირებელი", "/kəˈnektɪŋ/", "I have a connecting flight.", "დამაკავშირებელი ფრენა მაქვს."),
    ("Transfer", "ტრანსფერი", "/ˈtrænsfɜːr/", "Follow signs for transfer passengers.", "ტრანსფერის მგზავრებისთვის ნიშნებს მიჰყევით."),
    ("Round-trip", "ორმხრივი", "/raʊnd trɪp/", "A round-trip ticket costs less.", "ორმხრივი ბილეთი ნაკლები ღირს."),
    ("Refund", "თანხის დაბრუნება", "/ˈriːfʌnd/", "Can I get a refund for my ticket?", "ბილეთის თანხის დაბრუნება შეიძლება?"),
    ("Reservation", "დაჯავშნა", "/ˌrezərˈveɪʃən/", "I have a reservation for today.", "დღეისთვის დაჯავშნა მაქვს."),
    ("Itinerary", "მარშრუტი", "/aɪˈtɪnəreri/", "Print your travel itinerary.", "მოგზაურობის მარშრუტი ამობეჭდეთ."),
    ("Stopover", "გაჩერება", "/ˈstɒpoʊvər/", "We had a stopover in Dubai.", "დუბაიში გაჩერება გვქონდა."),
    ("Nonstop", "უგაჩერებო", "/ˌnɒnˈstɒp/", "This is a nonstop flight.", "ეს უგაჩერებო ფრენაა."),
    ("Charter", "ჩარტერი", "/ˈtʃɑːrtər/", "We flew on a charter flight.", "ჩარტერული ფრენით ვიფრინეთ."),
    ("Economy", "ეკონომ", "/ɪˈkɒnəmi/", "I always fly economy class.", "ყოველთვის ეკონომ კლასით დავფრინავ."),
    ("Business", "ბიზნეს", "/ˈbɪznəs/", "Business class has more legroom.", "ბიზნეს კლასში მეტი ფეხის ადგილია."),
    ("First class", "პირველი კლასი", "/fɜːrst klɑːs/", "First class tickets are expensive.", "პირველი კლასის ბილეთები ძვირია."),
    ("Upgrade", "გაუმჯობესება", "/ˈʌpɡreɪd/", "I got an upgrade to business class.", "ბიზნეს კლასში გადაყვანა მომცეს."),
    ("Recline", "გადაწევა", "/rɪˈklaɪn/", "May I recline my seat?", "შეიძლება სავარძელი გადავწიო?"),
    ("Armrest", "სახელური", "/ˈɑːrmrest/", "Please share the armrest.", "გთხოვთ, სახელური გაიყოთ."),
    ("Oxygen", "ჟანგბადი", "/ˈɒksɪdʒən/", "Oxygen masks will drop automatically.", "ჟანგბადის ნიღბები ავტომატურად ჩამოვარდება."),
    ("Mask", "ნიღაბი", "/mɑːsk/", "Put on your oxygen mask first.", "ჯერ თქვენი ჟანგბადის ნიღაბი დაიფარეთ."),
    ("Emergency", "საგანგებო", "/ɪˈmɜːrdʒənsi/", "Find the nearest emergency exit.", "უახლოესი საგანგებო გასასვლელი იპოვეთ."),
    ("Exit", "გასასვლელი", "/ˈeksɪt/", "The exit is at the rear of the plane.", "გასასვლელი თვითმფრინავის უკანაა."),
    ("Vest", "ჟილეტი", "/vest/", "A life vest is under your seat.", "სამაშველო ჟილეტი სავარძლის ქვეშაა."),
    ("Inflate", "გაბერვა", "/ɪnˈfleɪt/", "Pull the tab to inflate the vest.", "ჟილეტის გასაბერად ზოლი მოიწიეთ."),
    ("Evacuate", "ევაკუაცია", "/ɪˈvækjueɪt/", "Passengers must evacuate quickly.", "მგზავრებმა სწრაფად უნდა მოახდინონ ევაკუაცია."),
    ("Crash", "კატასტროფა", "/kræʃ/", "The plane made a crash landing.", "თვითმფრინავმა ავარიული დაშვება განახორციელა."),
    ("Radar", "რადარი", "/ˈreɪdɑːr/", "The radar detected a storm.", "რადარმა ქარიშხალი აღმოაჩინა."),
    ("Control tower", "მართვის კოშკი", "/kənˈtroʊl taʊər/", "The control tower gave clearance.", "მართვის კოშკმა ნებართვა გასცა."),
    ("Taxiing", "რულირება", "/ˈtæksiɪŋ/", "The plane is taxiing to the gate.", "თვითმფრინავი გეითისკენ რულირებს."),
    ("Throttle", "საჭე", "/ˈθrɒtəl/", "The pilot pushed the throttle forward.", "პილოტმა საჭე წინ მიწია."),
    ("Autopilot", "ავტოპილოტი", "/ˈɔːtoʊpaɪlət/", "The autopilot was engaged.", "ავტოპილოტი ჩართული იყო."),
    ("Navigation", "ნავიგაცია", "/ˌnævɪˈɡeɪʃən/", "Navigation systems are very advanced.", "ნავიგაციის სისტემები ძალიან განვითარებულია."),
    ("Compass", "კომპასი", "/ˈkʌmpəs/", "Pilots still carry a compass.", "პილოტები კომპასს კვლავ ატარებენ."),
    ("Airspace", "საჰაერო სივრცე", "/ˈeərspeɪs/", "We entered foreign airspace.", "უცხო ქვეყნის საჰაერო სივრცეში შევედით."),
    ("Route", "მარშრუტი", "/ruːt/", "The flight route goes over the ocean.", "ფრენის მარშრუტი ოკეანეზე გადის."),
    ("Weather", "ამინდი", "/ˈweðər/", "Bad weather delayed the flight.", "ცუდმა ამინდმა ფრენა დააგვიანა."),
    ("Fog", "ნისლი", "/fɒɡ/", "Thick fog closed the airport.", "სქელმა ნისლმა აეროპორტი დახურა."),
    ("Storm", "ქარიშხალი", "/stɔːrm/", "The storm caused many cancellations.", "ქარიშხალმა ბევრი გაუქმება გამოიწვია."),
    ("Lightning", "ელვა", "/ˈlaɪtnɪŋ/", "Lightning struck near the runway.", "ასაფრენი ზოლის მახლობლად ელვა დაეცა."),
    ("Wind", "ქარი", "/wɪnd/", "Strong winds affected the landing.", "ძლიერმა ქარმა დაფრენაზე იმოქმედა."),
    ("Cloud", "ღრუბელი", "/klaʊd/", "We flew above the clouds.", "ღრუბლებს ზემოთ ვფრინავდით."),
    ("Horizon", "ჰორიზონტი", "/həˈraɪzən/", "The sun set on the horizon.", "მზე ჰორიზონტზე ჩაესვენა."),
    ("Skies", "ცა", "/skaɪz/", "The skies were clear for flying.", "ცა ფრენისთვის ნათელი იყო."),
    ("Airfare", "ავიაბილეთის ფასი", "/ˈeərfer/", "Airfare has increased this year.", "ავიაბილეთის ფასი წელს გაიზარდა."),
    ("Airline", "ავიაკომპანია", "/ˈeərlaɪn/", "Which airline are you flying with?", "რომელი ავიაკომპანიით დაფრინავთ?"),
    ("Passenger", "მგზავრი", "/ˈpæsɪndʒər/", "All passengers must board now.", "ყველა მგზავრმა ახლა უნდა ჩაჯდეს."),
    ("Crew member", "ეკიპაჟის წევრი", "/kruː ˈmembər/", "Ask a crew member for help.", "დახმარებისთვის ეკიპაჟის წევრს მიმართეთ."),
    ("Steward", "სტიუარდი", "/ˈstjuːərd/", "The steward served dinner.", "სტიუარდმა სადილი მოგვიტანა."),
    ("Captain", "კაპიტანი", "/ˈkæptɪn/", "The captain welcomed us aboard.", "კაპიტანმა ბორტზე მოგვესალმა."),
    ("Cockpit door", "კაბინის კარი", "/ˈkɒkpɪt dɔːr/", "The cockpit door is reinforced.", "კაბინის კარი გამაგრებულია."),
    ("Fuel", "საწვავი", "/fjuːəl/", "The plane needs to refuel.", "თვითმფრინავს საწვავის შევსება სჭირდება."),
    ("Tank", "ავზი", "/tæŋk/", "The fuel tank is full.", "საწვავის ავზი სავსეა."),
    ("Cargo", "ტვირთი", "/ˈkɑːrɡoʊ/", "Cargo is loaded in the belly.", "ტვირთი მუცელში იტვირთება."),
    ("Freight", "სატვირთო", "/freɪt/", "The freight plane carried goods.", "სატვირთო თვითმფრინავმა საქონელი გადაიტანა."),
    ("Cockpit window", "კაბინის ფანჯარა", "/ˈkɒkpɪt ˈwɪndoʊ/", "The cockpit window cracked.", "კაბინის ფანჯარა დაიბზარა."),
    ("Nose", "ცხვირი", "/noʊz/", "The nose of the plane is aerodynamic.", "თვითმფრინავის ცხვირი აეროდინამიკურია."),
    ("Gear", "შასი", "/ɡɪr/", "The landing gear is down.", "სადესანტო შასი დაშვებულია."),
    ("Flap", "ფარფალი", "/flæp/", "The flaps extended for landing.", "ფარფლები დაფრენისთვის გაიშალა."),
    ("Thrust", "ბიძგი", "/θrʌst/", "Maximum thrust for takeoff.", "მაქსიმალური ბიძგი აფრენისთვის."),
    ("Speed", "სიჩქარე", "/spiːd/", "The plane reached cruising speed.", "თვითმფრინავმა კრეისერულ სიჩქარეს მიაღწია."),
    ("Knot", "კვანძი", "/nɒt/", "The wind speed is fifty knots.", "ქარის სიჩქარე ორმოცდაათი კვანძია."),
    ("Mach", "მახი", "/mɑːk/", "Concorde flew at Mach two.", "კონკორდი მახ ორით ფრინავდა."),
    ("Pressurize", "ჰერმეტიზაცია", "/ˈpreʃəraɪz/", "The cabin is pressurized.", "სალონი ჰერმეტიზებულია."),
    ("Depressurize", "დეჰერმეტიზაცია", "/diːˈpreʃəraɪz/", "The cabin depressurized suddenly.", "სალონი მოულოდნელად დეჰერმეტიზებული."),
    ("Oxygen tank", "ჟანგბადის ბალონი", "/ˈɒksɪdʒən tæŋk/", "The oxygen tank is in the overhead.", "ჟანგბადის ბალონი თავზე განყოფილებაშია."),
    ("Parachute", "პარაშუტი", "/ˈpærəʃuːt/", "Skydivers use parachutes.", "პარაშუტისტები პარაშუტს იყენებენ."),
    ("Skydive", "თავისუფალი ვარდნა", "/ˈskaɪdaɪv/", "I want to skydive someday.", "ოდესმე თავისუფალი ვარდნა მინდა."),
    ("Glider", "პლანერი", "/ˈɡlaɪdər/", "A glider has no engine.", "პლანერს ძრავა არ აქვს."),
    ("Biplane", "ბიპლანი", "/ˈbaɪpleɪn/", "The biplane did aerial tricks.", "ბიპლანმა საჰაერო ტრიუკები გააკეთა."),
    ("Handbag", "ხელჩანთა", "/ˈhændbæɡ/", "Keep your handbag with you.", "ხელჩანთა თან იქონიეთ."),
    ("Backpack", "ზურგჩანთა", "/ˈbækpæk/", "My backpack fits under the seat.", "ჩემი ზურგჩანთა სავარძლის ქვეშ ეტევა."),
    ("Trolley", "ურიკა", "/ˈtrɒli/", "I need a luggage trolley.", "ბარგის ურიკა მჭირდება."),
    ("Conveyor", "კონვეიერი", "/kənˈveɪər/", "Bags arrive on the conveyor.", "ჩანთები კონვეიერზე მოდის."),
    ("Claim", "მიღება", "/kleɪm/", "Claim your luggage at belt two.", "ბარგი მეორე ლენტაზე მიიღეთ."),
    ("Lost", "დაკარგული", "/lɒst/", "My luggage is lost.", "ჩემი ბარგი დაიკარგა."),
    ("Found", "ნაპოვნი", "/faʊnd/", "Your bag has been found.", "თქვენი ჩანთა იპოვეს."),
    ("Declare", "დეკლარირება", "/dɪˈkler/", "Do you have anything to declare?", "რამე გაქვთ სადეკლარაციო?"),
    ("Inspection", "შემოწმება", "/ɪnˈspekʃən/", "Random inspections are normal.", "შემთხვევითი შემოწმება ჩვეულებრივია."),
    ("Quarantine", "კარანტინი", "/ˈkwɒrəntiːn/", "Some items require quarantine.", "ზოგიერთ ნივთს კარანტინი სჭირდება."),
    ("Vaccination", "ვაქცინაცია", "/ˌvæksɪˈneɪʃən/", "Show your vaccination certificate.", "ვაქცინაციის მოწმობა აჩვენეთ."),
    ("Certificate", "მოწმობა", "/sərˈtɪfɪkət/", "Keep your certificate handy.", "მოწმობა ხელთ იქონიეთ."),
    ("Currency", "ვალუტა", "/ˈkʌrənsi/", "Exchange currency at the airport.", "ვალუტა აეროპორტში გადაცვალეთ."),
    ("Exchange", "გაცვლა", "/ɪksˈtʃeɪndʒ/", "The exchange rate is good today.", "გაცვლის კურსი დღეს კარგია."),
    ("Taxi", "ტაქსი", "/ˈtæksi/", "Take a taxi from the airport.", "აეროპორტიდან ტაქსით წადით."),
    ("Shuttle", "შატლი", "/ˈʃʌtəl/", "The hotel shuttle is free.", "სასტუმროს შატლი უფასოა."),
    ("Rental", "გაქირავება", "/ˈrentəl/", "I booked a rental car.", "მანქანის გაქირავება დავჯავშნე."),
    ("Parking", "პარკინგი", "/ˈpɑːrkɪŋ/", "Airport parking is expensive.", "აეროპორტის პარკინგი ძვირია."),
    ("Snack", "საჭმელი", "/snæk/", "Would you like a snack?", "საჭმელი გინდათ?"),
    ("Meal", "კვება", "/miːl/", "A meal is included on long flights.", "გრძელ ფრენებზე კვება შედის."),
    ("Beverage", "სასმელი", "/ˈbevərɪdʒ/", "Choose your beverage.", "სასმელი აირჩიეთ."),
    ("Turboprop", "ტურბოვინტური", "/ˈtɜːrboʊprɒp/", "We flew on a turboprop plane.", "ტურბოვინტურით ვიფრინეთ."),
    ("Biometric", "ბიომეტრიული", "/ˌbaɪoʊˈmetrɪk/", "Biometric passports are common now.", "ბიომეტრიული პასპორტები ახლა გავრცელებულია."),
    ("Fingerprint", "თითის ანაბეჭდი", "/ˈfɪŋɡərprɪnt/", "Scan your fingerprint at the gate.", "გეითზე თითის ანაბეჭდი დაასკანერეთ."),
    ("Retina", "ბადურა", "/ˈretɪnə/", "Retina scans are used for security.", "ბადურის სკანირება უსაფრთხოებისთვის გამოიყენება."),
    ("Lavatory", "ტუალეტი", "/ˈlævətɔːri/", "The lavatory is occupied.", "ტუალეტი დაკავებულია."),
    ("Galley", "სამზარეულო", "/ˈɡæli/", "Meals are prepared in the galley.", "კვება სამზარეულოში მზადდება."),
    ("Cabin crew", "სალონის ეკიპაჟი", "/ˈkæbɪn kruː/", "Cabin crew, prepare for landing.", "სალონის ეკიპაჟო, დაფრენისთვის მოემზადეთ."),
    ("Taxiway", "სარულირებო ბილიკი", "/ˈtæksiweɪ/", "The plane moved along the taxiway.", "თვითმფრინავი სარულირებო ბილიკზე გადაადგილდა."),
    ("Apron", "პერონი", "/ˈeɪprən/", "Planes are parked on the apron.", "თვითმფრინავები პერონზე დგას."),
    ("Beacon", "მაშუქი", "/ˈbiːkən/", "The airport beacon guides pilots at night.", "აეროპორტის მაშუქი ღამით პილოტებს უძღვის."),
    ("Clearance", "ნებართვა", "/ˈklɪrəns/", "The pilot received clearance to land.", "პილოტმა დაშვების ნებართვა მიიღო."),
    ("Mayday", "მეიდეი", "/ˈmeɪdeɪ/", "The pilot called mayday.", "პილოტმა მეიდეი გამოაცხადა."),
    ("Crosswind", "გვერდითი ქარი", "/ˈkrɒswɪnd/", "Crosswinds made landing difficult.", "გვერდითმა ქარმა დაფრენა გაართულა."),
    ("Headwind", "საპირისპირო ქარი", "/ˈhedwɪnd/", "Headwinds slowed the flight.", "საპირისპირო ქარმა ფრენა შეანელა."),
    ("Tailwind", "ზურგის ქარი", "/ˈteɪlwɪnd/", "A tailwind helped us arrive early.", "ზურგის ქარმა ადრე მოსვლაში დაგვეხმარა."),
    ("Deice", "ყინულის მოცილება", "/diːˈaɪs/", "They need to deice the wings.", "ფრთებიდან ყინულის მოცილება სჭირდებათ."),
    ("Handrail", "მოაჯირი", "/ˈhændreɪl/", "Hold the handrail on the stairs.", "კიბეზე მოაჯირს მოეჭიდეთ."),
    ("Jetway", "ტელესკოპური ხიდი", "/ˈdʒetweɪ/", "Walk through the jetway to board.", "ჩასხდომისთვის ტელესკოპურ ხიდში გაიარეთ."),
    ("Stairway", "კიბე", "/ˈsterweɪ/", "Use the stairway to board the plane.", "თვითმფრინავში ჩასასხდომად კიბე გამოიყენეთ."),
    ("Runway lights", "ზოლის განათება", "/ˈrʌnweɪ laɪts/", "Runway lights guide the pilot.", "ზოლის განათება პილოტს უძღვის."),
    ("Windshield", "ქარსაცავი მინა", "/ˈwɪndʃiːld/", "The windshield was covered in ice.", "ქარსაცავი მინა ყინულით იყო დაფარული."),
    ("Intercom", "ინტერკომი", "/ˈɪntərkɒm/", "The captain spoke on the intercom.", "კაპიტანმა ინტერკომით ილაპარაკა."),
    ("Turbine", "ტურბინა", "/ˈtɜːrbaɪn/", "The turbine generates thrust.", "ტურბინა ბიძგს ქმნის."),
    ("Aileron", "ელერონი", "/ˈeɪlərɒn/", "Ailerons control the roll.", "ელერონები გადახრას აკონტროლებს."),
    ("Rudder", "საჭე", "/ˈrʌdər/", "The rudder controls direction.", "საჭე მიმართულებას აკონტროლებს."),
    ("Elevator", "რულის სიმაღლე", "/ˈelɪveɪtər/", "The elevator controls pitch.", "სიმაღლის რული ტანგაჟს აკონტროლებს."),
    ("Black box", "შავი ყუთი", "/blæk bɒks/", "The black box records flight data.", "შავი ყუთი ფრენის მონაცემებს ჩაწერს."),
    ("Descent", "დაშვება", "/dɪˈsent/", "We began our descent.", "დაშვება დავიწყეთ."),
    ("Ascent", "აღმასვლა", "/əˈsent/", "The ascent was smooth.", "აღმასვლა მშვიდი იყო."),
    ("Cruising", "კრეისერული", "/ˈkruːzɪŋ/", "We reached cruising altitude.", "კრეისერულ სიმაღლეს მივაღწიეთ."),
    ("Approach", "მიახლოება", "/əˈproʊtʃ/", "The plane is on final approach.", "თვითმფრინავი საბოლოო მიახლოებაზეა."),
    ("Touchdown", "მიწაზე შეხება", "/ˈtʌtʃdaʊn/", "Touchdown was perfectly smooth.", "მიწაზე შეხება სრულყოფილად მშვიდი იყო."),
    ("Taxistand", "ტაქსის გაჩერება", "/ˈtæksi stænd/", "The taxistand is outside arrivals.", "ტაქსის გაჩერება ჩამოფრენის გარეთაა."),
    ("Hangar door", "ანგარის კარი", "/ˈhæŋər dɔːr/", "The hangar door opened slowly.", "ანგარის კარი ნელა გაიღო."),
    ("Maintenance", "ტექნიკური მომსახურება", "/ˈmeɪntənəns/", "The plane is under maintenance.", "თვითმფრინავი ტექნიკურ მომსახურებაზეა."),
    ("Inspection report", "შემოწმების ანგარიში", "/ɪnˈspekʃən rɪˈpɔːrt/", "The inspection report was clean.", "შემოწმების ანგარიში სუფთა იყო."),
    ("Preflight", "წინასაფრენო", "/ˈpriːflaɪt/", "Complete the preflight checklist.", "წინასაფრენო ჩამონათვალი შეავსეთ."),
    ("Checklist", "ჩამონათვალი", "/ˈtʃeklɪst/", "The pilot reviewed the checklist.", "პილოტმა ჩამონათვალი გადახედა."),
    ("Standby", "მოლოდინი", "/ˈstændbaɪ/", "We are on standby for the next flight.", "შემდეგი ფრენისთვის მოლოდინში ვართ."),
    ("Overbooking", "ზედმეტად დაჯავშნა", "/ˌoʊvərˈbʊkɪŋ/", "Overbooking caused delays.", "ზედმეტად დაჯავშნამ დაგვიანება გამოიწვია."),
    ("Bumped", "გადმოტვირთული", "/bʌmpt/", "I was bumped from my flight.", "ფრენიდან გადმომტვირთეს."),
    ("Compensation", "კომპენსაცია", "/ˌkɒmpənˈseɪʃən/", "They offered compensation for the delay.", "დაგვიანებისთვის კომპენსაცია შემოგვთავაზეს."),
    ("Voucher", "ვაუჩერი", "/ˈvaʊtʃər/", "I received a travel voucher.", "სამოგზაურო ვაუჩერი მივიღე."),
    ("Locker", "საკეტი", "/ˈlɒkər/", "Store valuables in a locker.", "ძვირფასი ნივთები საკეტიან ყუთში შეინახეთ."),
    ("Announcement board", "საინფორმაციო ტაბლო", "/əˈnaʊnsmənt bɔːrd/", "Check the announcement board.", "საინფორმაციო ტაბლო შეამოწმეთ."),
    ("Flyover", "გადაფრენა", "/ˈflaɪoʊvər/", "We saw a military flyover.", "სამხედრო გადაფრენა ვნახეთ."),
    ("Airstrip", "საფრენი ზოლი", "/ˈeərstrɪp/", "The small airstrip was in a field.", "პატარა საფრენი ზოლი მინდორში იყო."),
]

# Build final list
final = list(existing)
existing_lower = {e["english"].lower() for e in final}

for eng, geo, pron, ex_en, ex_ka in new_entries:
    if eng.lower() not in existing_lower:
        final.append({
            "english": eng,
            "georgian": geo,
            "pronunciation": pron,
            "example_en": ex_en,
            "example_ka": ex_ka,
            "category": "airport-flying"
        })
        existing_lower.add(eng.lower())
    if len(final) >= 200:
        break

print(f"Total entries: {len(final)}")
assert len(final) == 200, f"Expected 200, got {len(final)}"

with open(INPUT, "w", encoding="utf-8") as f:
    json.dump(final, f, ensure_ascii=False, indent=2)

print("Done! Written 200 entries.")
