#!/usr/bin/env python3
"""
Expand a category JSON to 200 words by generating new related single words.
Usage: python3 expand_category.py filename.json
"""
import json, sys, os

# Comprehensive word lists by category theme
WORD_BANKS = {
    "academic": ["thesis", "dissertation", "bibliography", "citation", "abstract", "methodology", "hypothesis", "analysis", "synthesis", "evaluation", "criterion", "paradigm", "phenomenon", "variable", "correlation", "implication", "framework", "perspective", "concept", "theory", "evidence", "argument", "conclusion", "assumption", "interpretation", "critique", "discourse", "empirical", "qualitative", "quantitative", "validity", "reliability", "objective", "subjective", "coherent", "comprehensive", "cumulative", "definitive", "explicit", "implicit", "inherent", "integral", "legitimate", "marginal", "negligible", "notwithstanding", "paramount", "predominant", "preliminary", "prevalent", "prior", "profound", "prospective", "rational", "relevant", "respective", "rigid", "robust", "salient", "simultaneous", "subsequent", "sufficient", "supplementary", "sustainable", "tangible", "tentative", "terminal", "trivial", "ultimate", "underlying", "unprecedented", "viable", "virtual", "ambiguous", "analogous", "arbitrary", "compatible", "contradictory", "controversial", "conventional", "crucial", "decisive", "deliberate", "detrimental", "diverse", "dominant", "dynamic", "elaborate", "equivalent", "excessive", "exclusive", "feasible", "fundamental", "genuine", "gradual", "hierarchical", "identical", "ideological", "inadequate", "indigenous", "inevitable", "inferior", "innovative", "instructive", "intensive", "intrinsic", "isolated", "literal", "logical", "minimal", "mutual", "nominal", "normative", "orthodox", "passive", "persistent", "plausible", "potential", "precise", "progressive", "prohibitive", "radical", "random", "redundant", "regulatory", "reluctant", "residual", "restrictive", "revolutionary", "selective", "sequential", "significant", "skeptical", "speculative", "static", "strategic", "structural", "subtle", "superficial", "symbolic", "systematic", "tactical", "temporary", "theoretical", "traditional", "transitional", "transparent", "trivial", "unambiguous", "unconventional", "unilateral", "unprecedented", "utilitarian", "versatile", "voluntary"],
    "animal": ["eagle", "hawk", "sparrow", "pigeon", "parrot", "owl", "penguin", "flamingo", "swan", "duck", "goose", "crane", "heron", "pelican", "seagull", "crow", "raven", "magpie", "robin", "finch", "canary", "peacock", "turkey", "chicken", "rooster", "hen", "chick", "quail", "dove", "falcon", "vulture", "ostrich", "stork", "woodpecker", "hummingbird", "kingfisher", "toucan", "cockatoo", "macaw", "budgie", "wolf", "fox", "bear", "deer", "moose", "elk", "bison", "buffalo", "zebra", "giraffe", "elephant", "rhinoceros", "hippopotamus", "gorilla", "chimpanzee", "orangutan", "baboon", "lemur", "sloth", "koala", "kangaroo", "wallaby", "platypus", "wombat", "possum", "raccoon", "badger", "otter", "beaver", "squirrel", "chipmunk", "hedgehog", "porcupine", "armadillo", "mole", "bat", "whale", "dolphin", "shark", "octopus", "squid", "jellyfish", "starfish", "seahorse", "coral", "crab", "lobster", "shrimp", "oyster", "clam", "mussel", "snail", "slug", "worm", "caterpillar", "butterfly", "moth", "beetle", "ant", "bee", "wasp", "dragonfly", "grasshopper", "cricket", "mosquito", "fly", "spider", "scorpion", "centipede", "lizard", "gecko", "iguana", "chameleon", "crocodile", "alligator", "turtle", "tortoise", "snake", "python", "cobra", "viper", "frog", "toad", "salamander", "newt", "panther", "leopard", "cheetah", "jaguar", "cougar", "lynx", "hyena", "jackal", "coyote", "mongoose", "ferret", "weasel", "mink", "skunk", "panda", "antelope", "gazelle", "wildebeest", "camel", "llama", "alpaca", "yak", "donkey", "mule", "pony", "stallion", "mare", "foal", "colt", "lamb", "ram", "ewe", "goat", "pig", "boar", "hamster", "gerbil", "guinea", "rabbit", "hare", "mouse", "rat", "chinchilla", "parrot", "mackerel", "salmon", "trout", "tuna", "cod", "sardine", "herring", "swordfish", "catfish", "goldfish", "piranha", "stingray", "eel", "clownfish", "barracuda", "marlin"],
    "food": ["apple", "banana", "orange", "grape", "strawberry", "blueberry", "raspberry", "blackberry", "cherry", "peach", "plum", "pear", "mango", "pineapple", "watermelon", "melon", "kiwi", "lemon", "lime", "grapefruit", "coconut", "avocado", "tomato", "potato", "carrot", "onion", "garlic", "pepper", "broccoli", "cauliflower", "cabbage", "lettuce", "spinach", "kale", "celery", "cucumber", "zucchini", "eggplant", "pumpkin", "squash", "corn", "peas", "beans", "lentils", "chickpeas", "rice", "wheat", "oats", "barley", "quinoa", "pasta", "noodles", "bread", "toast", "bagel", "croissant", "muffin", "pancake", "waffle", "cereal", "porridge", "soup", "stew", "broth", "salad", "sandwich", "burger", "pizza", "taco", "burrito", "sushi", "ramen", "curry", "steak", "chicken", "pork", "beef", "lamb", "turkey", "bacon", "sausage", "ham", "fish", "shrimp", "lobster", "crab", "oyster", "salmon", "tuna", "cod", "cheese", "butter", "cream", "yogurt", "milk", "egg", "honey", "sugar", "salt", "pepper", "cinnamon", "vanilla", "chocolate", "caramel", "syrup", "jam", "jelly", "sauce", "ketchup", "mustard", "mayonnaise", "vinegar", "oil", "flour", "dough", "batter", "frosting", "icing", "pie", "cake", "cookie", "brownie", "donut", "pastry", "pudding", "custard", "mousse", "sorbet", "gelato", "smoothie", "milkshake", "juice", "lemonade", "tea", "coffee", "espresso", "cappuccino", "latte", "mocha", "cocoa", "water", "soda", "wine", "beer", "cocktail", "whiskey", "vodka", "rum", "gin", "champagne", "cider", "nuts", "almonds", "walnuts", "cashews", "peanuts", "pistachios", "pecans", "hazelnuts", "popcorn", "chips", "crackers", "pretzel", "granola", "raisin", "fig", "date", "apricot", "cranberry", "pomegranate", "papaya", "guava", "lychee", "passion", "dragonfruit", "persimmon", "artichoke", "asparagus", "beet", "turnip", "radish", "parsley", "basil", "oregano", "thyme", "rosemary", "mint", "dill", "cilantro", "ginger", "turmeric", "cumin", "paprika", "chili", "nutmeg", "clove", "fennel", "saffron"],
    "sport": ["soccer", "football", "basketball", "baseball", "tennis", "volleyball", "golf", "hockey", "cricket", "rugby", "boxing", "wrestling", "judo", "karate", "taekwondo", "fencing", "archery", "shooting", "cycling", "swimming", "diving", "surfing", "sailing", "rowing", "kayaking", "canoeing", "skiing", "snowboarding", "skating", "curling", "bobsled", "luge", "biathlon", "triathlon", "marathon", "sprint", "relay", "hurdles", "javelin", "discus", "hammer", "shotput", "pole", "gymnast", "acrobat", "trampoline", "weightlifting", "powerlifting", "bodybuilding", "crossfit", "yoga", "pilates", "aerobics", "stretching", "warmup", "cooldown", "jogging", "running", "walking", "hiking", "climbing", "bouldering", "rappelling", "paragliding", "skydiving", "bungee", "rafting", "snorkeling", "scuba", "fishing", "hunting", "camping", "backpacking", "trekking", "mountaineering", "orienteering", "parkour", "skateboarding", "rollerblading", "BMX", "motocross", "racing", "drifting", "rally", "karting", "polo", "equestrian", "dressage", "showjumping", "rodeo", "lacrosse", "handball", "badminton", "squash", "racquetball", "pickleball", "croquet", "bowling", "darts", "billiards", "snooker", "chess", "checkers", "coach", "referee", "umpire", "trophy", "medal", "championship", "tournament", "league", "season", "playoff", "final", "semifinal", "quarterfinal", "qualifier", "elimination", "score", "goal", "point", "assist", "rebound", "tackle", "foul", "penalty", "overtime", "halftime", "timeout", "substitution", "bench", "roster", "draft", "transfer", "contract", "salary", "sponsor", "endorsement", "stadium", "arena", "court", "field", "pitch", "rink", "track", "pool", "gym", "dojo", "ring", "mat", "net", "hoop", "basket", "racket", "bat", "glove", "helmet", "uniform", "jersey", "shorts", "cleats", "sneakers", "whistle", "stopwatch", "scoreboard", "standings", "record", "streak", "upset", "underdog", "favorite", "rival", "opponent", "teammate", "captain", "rookie", "veteran", "champion", "contender", "athlete", "player", "starter", "reserve", "goalkeeper", "defender", "midfielder", "forward", "striker", "pitcher", "catcher", "batter", "quarterback", "linebacker", "receiver"],
    "technology": ["computer", "laptop", "tablet", "smartphone", "monitor", "keyboard", "mouse", "trackpad", "webcam", "microphone", "speaker", "headphones", "earbuds", "charger", "cable", "adapter", "router", "modem", "server", "database", "cloud", "storage", "backup", "firewall", "antivirus", "malware", "virus", "hacker", "encryption", "authentication", "password", "username", "login", "logout", "browser", "website", "webpage", "domain", "hosting", "bandwidth", "download", "upload", "streaming", "buffering", "pixel", "resolution", "display", "touchscreen", "processor", "chip", "memory", "RAM", "SSD", "motherboard", "graphics", "GPU", "CPU", "battery", "wireless", "bluetooth", "wifi", "hotspot", "network", "ethernet", "protocol", "IP", "URL", "HTTP", "API", "SDK", "IDE", "code", "script", "program", "software", "hardware", "firmware", "update", "patch", "bug", "debug", "compile", "deploy", "algorithm", "function", "variable", "array", "loop", "condition", "class", "object", "method", "interface", "module", "library", "framework", "repository", "branch", "merge", "commit", "push", "pull", "clone", "fork", "version", "release", "beta", "alpha", "prototype", "iteration", "agile", "scrum", "sprint", "backlog", "roadmap", "milestone", "feature", "component", "frontend", "backend", "fullstack", "responsive", "mobile", "desktop", "native", "hybrid", "emulator", "simulator", "virtual", "container", "docker", "kubernetes", "microservice", "serverless", "lambda", "node", "react", "angular", "vue", "python", "java", "javascript", "typescript", "ruby", "swift", "kotlin", "rust", "golang", "PHP", "SQL", "HTML", "CSS", "JSON", "XML", "markdown", "regex", "terminal", "command", "shell", "bash", "sudo", "root", "admin", "permission", "directory", "file", "folder", "path", "extension", "format", "compress", "extract", "archive", "install", "uninstall", "configure", "optimize", "cache", "cookie", "session", "token", "certificate", "SSL", "DNS", "proxy", "VPN", "tunnel", "gateway", "port", "socket", "packet", "latency", "throughput", "scalability", "redundancy", "failover", "load", "cluster", "instance", "snapshot", "migration", "automation", "pipeline", "integration", "deployment", "monitoring", "logging", "analytics", "dashboard", "metric", "alert", "notification", "webhook", "endpoint"],
    "music": ["melody", "harmony", "rhythm", "tempo", "beat", "note", "chord", "scale", "octave", "pitch", "tone", "tune", "key", "minor", "major", "sharp", "flat", "natural", "treble", "bass", "clef", "staff", "measure", "bar", "rest", "whole", "half", "quarter", "eighth", "sixteenth", "dotted", "triplet", "syncopation", "accent", "dynamics", "forte", "piano", "crescendo", "decrescendo", "staccato", "legato", "vibrato", "tremolo", "arpeggio", "glissando", "trill", "riff", "lick", "hook", "bridge", "chorus", "verse", "refrain", "intro", "outro", "interlude", "coda", "prelude", "overture", "sonata", "symphony", "concerto", "opera", "ballet", "suite", "fugue", "canon", "etude", "nocturne", "waltz", "march", "hymn", "anthem", "ballad", "lullaby", "serenade", "guitar", "piano", "violin", "viola", "cello", "bass", "harp", "flute", "clarinet", "oboe", "bassoon", "trumpet", "trombone", "tuba", "horn", "saxophone", "accordion", "harmonica", "banjo", "ukulele", "mandolin", "sitar", "tabla", "drums", "cymbal", "snare", "tambourine", "xylophone", "marimba", "glockenspiel", "timpani", "bongo", "conga", "djembe", "cajon", "triangle", "cowbell", "gong", "bell", "chime", "organ", "synthesizer", "sampler", "sequencer", "mixer", "amplifier", "equalizer", "reverb", "delay", "distortion", "compression", "filter", "oscillator", "waveform", "frequency", "amplitude", "decibel", "hertz", "stereo", "mono", "channel", "track", "recording", "mixing", "mastering", "production", "arrangement", "composition", "improvisation", "solo", "duet", "trio", "quartet", "quintet", "ensemble", "orchestra", "band", "choir", "conductor", "composer", "musician", "vocalist", "singer", "rapper", "drummer", "guitarist", "pianist", "bassist", "soloist", "performer", "artist", "genre", "pop", "rock", "jazz", "blues", "classical", "country", "folk", "reggae", "hip-hop", "rap", "electronic", "techno", "house", "trance", "dubstep", "ambient", "indie", "alternative", "punk", "metal", "grunge", "soul", "funk", "disco", "gospel", "latin", "salsa", "bossa", "flamenco", "opera"],
    "work": ["office", "desk", "chair", "meeting", "conference", "presentation", "report", "deadline", "project", "task", "assignment", "schedule", "calendar", "agenda", "memo", "email", "inbox", "attachment", "document", "spreadsheet", "slide", "chart", "graph", "budget", "forecast", "profit", "loss", "revenue", "expense", "salary", "wage", "bonus", "commission", "promotion", "demotion", "raise", "review", "evaluation", "feedback", "performance", "productivity", "efficiency", "teamwork", "collaboration", "delegation", "leadership", "management", "supervisor", "director", "executive", "CEO", "manager", "assistant", "intern", "trainee", "employee", "employer", "colleague", "coworker", "subordinate", "superior", "department", "division", "branch", "headquarters", "subsidiary", "startup", "corporation", "enterprise", "company", "firm", "agency", "consultant", "contractor", "freelancer", "vendor", "supplier", "client", "customer", "partner", "stakeholder", "shareholder", "investor", "board", "committee", "council", "strategy", "policy", "procedure", "guideline", "regulation", "compliance", "audit", "inspection", "certification", "accreditation", "license", "permit", "contract", "agreement", "proposal", "bid", "tender", "invoice", "receipt", "payment", "transaction", "account", "balance", "credit", "debit", "tax", "deduction", "exemption", "reimbursement", "pension", "retirement", "resignation", "termination", "layoff", "hiring", "recruitment", "candidate", "applicant", "resume", "portfolio", "interview", "orientation", "training", "workshop", "seminar", "webinar", "conference", "networking", "mentor", "mentee", "career", "profession", "occupation", "vocation", "trade", "skill", "expertise", "qualification", "credential", "diploma", "degree", "certificate", "apprenticeship", "internship", "fellowship", "scholarship", "grant", "fund", "subsidy", "sponsorship", "donation", "charity", "nonprofit", "volunteer", "initiative", "campaign", "advocacy", "lobby", "negotiate", "mediate", "arbitrate", "compromise", "consensus", "resolution", "conflict", "dispute", "grievance", "complaint", "appeal", "hearing", "verdict", "ruling", "judgment", "sanction", "penalty", "fine", "warning", "reprimand", "suspension", "dismissal", "severance", "compensation", "benefit", "insurance", "coverage", "premium", "claim", "liability"],
    "emotion": ["happy", "sad", "angry", "scared", "anxious", "nervous", "excited", "thrilled", "ecstatic", "joyful", "cheerful", "delighted", "pleased", "satisfied", "content", "grateful", "thankful", "appreciative", "hopeful", "optimistic", "confident", "proud", "relieved", "calm", "peaceful", "relaxed", "serene", "comfortable", "safe", "secure", "loved", "cherished", "adored", "respected", "valued", "inspired", "motivated", "determined", "ambitious", "passionate", "enthusiastic", "eager", "curious", "fascinated", "intrigued", "amazed", "astonished", "surprised", "shocked", "stunned", "overwhelmed", "confused", "puzzled", "perplexed", "bewildered", "uncertain", "doubtful", "skeptical", "suspicious", "worried", "concerned", "troubled", "distressed", "upset", "disappointed", "frustrated", "irritated", "annoyed", "furious", "enraged", "livid", "bitter", "resentful", "jealous", "envious", "insecure", "inadequate", "inferior", "worthless", "helpless", "hopeless", "desperate", "miserable", "depressed", "gloomy", "melancholy", "nostalgic", "lonely", "isolated", "abandoned", "rejected", "betrayed", "hurt", "wounded", "heartbroken", "devastated", "grief", "mourning", "sorrow", "regret", "remorse", "guilt", "shame", "embarrassed", "humiliated", "awkward", "uncomfortable", "tense", "stressed", "pressured", "burdened", "exhausted", "drained", "fatigued", "weary", "bored", "apathetic", "indifferent", "numb", "detached", "withdrawn", "reserved", "shy", "timid", "hesitant", "reluctant", "resistant", "defiant", "stubborn", "obstinate", "arrogant", "conceited", "vain", "selfish", "greedy", "possessive", "controlling", "manipulative", "deceitful", "dishonest", "suspicious", "paranoid", "hostile", "aggressive", "violent", "cruel", "ruthless", "merciless", "compassionate", "empathetic", "sympathetic", "tender", "gentle", "kind", "generous", "selfless", "humble", "modest", "sincere", "genuine", "authentic", "honest", "trustworthy", "loyal", "faithful", "devoted", "committed", "dedicated", "responsible", "mature", "wise", "patient", "tolerant", "forgiving", "understanding", "supportive", "encouraging", "nurturing", "protective", "courageous", "brave", "fearless", "bold", "daring", "adventurous", "spontaneous", "playful", "carefree", "lighthearted", "humorous", "witty", "charming", "charismatic", "magnetic", "attractive", "appealing"],
    "health": ["doctor", "nurse", "surgeon", "dentist", "therapist", "psychiatrist", "psychologist", "pharmacist", "paramedic", "midwife", "pediatrician", "cardiologist", "neurologist", "oncologist", "dermatologist", "ophthalmologist", "orthopedist", "radiologist", "anesthesiologist", "pathologist", "hospital", "clinic", "pharmacy", "laboratory", "emergency", "ambulance", "surgery", "operation", "procedure", "treatment", "therapy", "rehabilitation", "recovery", "diagnosis", "prognosis", "symptom", "condition", "disease", "illness", "infection", "inflammation", "allergy", "asthma", "diabetes", "hypertension", "arthritis", "cancer", "tumor", "stroke", "seizure", "fracture", "sprain", "bruise", "wound", "scar", "rash", "fever", "cough", "sneeze", "headache", "migraine", "backache", "stomachache", "nausea", "vomiting", "diarrhea", "constipation", "fatigue", "insomnia", "dizziness", "numbness", "swelling", "bleeding", "pain", "ache", "cramp", "spasm", "itch", "blister", "burn", "cut", "scratch", "sting", "bite", "medicine", "medication", "drug", "pill", "tablet", "capsule", "syrup", "injection", "vaccine", "antibiotic", "painkiller", "antiseptic", "bandage", "gauze", "splint", "cast", "crutch", "wheelchair", "stretcher", "stethoscope", "thermometer", "syringe", "scalpel", "microscope", "X-ray", "ultrasound", "MRI", "CT", "scan", "blood", "pressure", "pulse", "heartbeat", "breathing", "oxygen", "immune", "antibody", "vitamin", "mineral", "protein", "calcium", "iron", "zinc", "fiber", "calorie", "cholesterol", "glucose", "insulin", "hormone", "enzyme", "cell", "tissue", "organ", "bone", "muscle", "nerve", "vein", "artery", "capillary", "lymph", "plasma", "platelet", "hemoglobin", "metabolism", "digestion", "circulation", "respiration", "nutrition", "hydration", "exercise", "fitness", "wellness", "prevention", "screening", "checkup", "examination", "consultation", "referral", "prescription", "dosage", "overdose", "addiction", "withdrawal", "tolerance", "immunity", "susceptibility", "contagious", "chronic", "acute", "terminal", "benign", "malignant", "hereditary", "genetic", "congenital", "prenatal", "postnatal", "geriatric", "pediatric", "surgical", "clinical", "pharmaceutical", "therapeutic", "diagnostic", "preventive", "palliative", "holistic"],
    "travel": ["passport", "visa", "ticket", "boarding", "luggage", "suitcase", "backpack", "destination", "departure", "arrival", "terminal", "gate", "runway", "takeoff", "landing", "turbulence", "altitude", "cabin", "cockpit", "pilot", "flight", "airline", "airport", "customs", "immigration", "declaration", "duty", "quarantine", "vaccination", "itinerary", "reservation", "booking", "confirmation", "cancellation", "delay", "layover", "transit", "transfer", "connection", "domestic", "international", "nonstop", "direct", "charter", "economy", "business", "first", "upgrade", "seat", "aisle", "window", "overhead", "belt", "tray", "blanket", "pillow", "entertainment", "announcement", "captain", "attendant", "crew", "hotel", "hostel", "motel", "resort", "lodge", "inn", "guesthouse", "apartment", "villa", "cottage", "bungalow", "suite", "lobby", "reception", "concierge", "bellboy", "housekeeping", "checkout", "vacancy", "amenity", "accommodation", "tourist", "traveler", "passenger", "commuter", "explorer", "adventurer", "backpacker", "nomad", "guide", "excursion", "tour", "cruise", "safari", "expedition", "pilgrimage", "voyage", "journey", "trip", "getaway", "vacation", "holiday", "weekend", "retreat", "souvenir", "postcard", "photograph", "landmark", "monument", "museum", "gallery", "cathedral", "temple", "mosque", "palace", "castle", "fortress", "ruins", "archaeological", "heritage", "culture", "tradition", "festival", "cuisine", "dialect", "currency", "exchange", "tip", "gratuity", "bargain", "haggle", "marketplace", "bazaar", "taxi", "subway", "metro", "tram", "bus", "train", "ferry", "boat", "yacht", "cruise", "bicycle", "scooter", "motorcycle", "rental", "license", "map", "GPS", "compass", "route", "highway", "bridge", "tunnel", "border", "checkpoint", "embassy", "consulate", "insurance", "emergency", "evacuation", "translation", "interpreter", "phrasebook", "guidebook", "brochure", "agency", "operator", "package", "inclusive", "budget", "luxury", "premium", "standard", "economy", "backpack", "tent", "campsite", "trail", "path", "scenery", "landscape", "panorama", "sunset", "sunrise", "beach", "mountain", "valley", "waterfall", "lake", "river", "ocean", "island", "peninsula", "cliff", "cave", "desert", "jungle", "rainforest", "glacier", "volcano"],
    "home": ["house", "apartment", "condo", "townhouse", "cottage", "cabin", "mansion", "villa", "bungalow", "duplex", "penthouse", "studio", "loft", "basement", "attic", "garage", "driveway", "porch", "deck", "patio", "balcony", "terrace", "garden", "yard", "lawn", "fence", "gate", "doorway", "entrance", "hallway", "corridor", "staircase", "elevator", "lobby", "foyer", "living", "dining", "kitchen", "bedroom", "bathroom", "toilet", "shower", "bathtub", "sink", "faucet", "drain", "pipe", "plumbing", "electricity", "outlet", "switch", "light", "lamp", "chandelier", "ceiling", "floor", "wall", "roof", "chimney", "fireplace", "window", "curtain", "blind", "shutter", "door", "lock", "key", "handle", "knob", "hinge", "doorbell", "mailbox", "shelf", "cabinet", "drawer", "closet", "wardrobe", "pantry", "cupboard", "counter", "table", "chair", "sofa", "couch", "armchair", "recliner", "ottoman", "bench", "stool", "bed", "mattress", "pillow", "blanket", "sheet", "quilt", "duvet", "comforter", "rug", "carpet", "tile", "hardwood", "laminate", "vinyl", "marble", "granite", "concrete", "brick", "plaster", "paint", "wallpaper", "mirror", "frame", "painting", "photograph", "clock", "vase", "candle", "plant", "flowerpot", "aquarium", "bookshelf", "desk", "computer", "television", "stereo", "speaker", "remote", "thermostat", "heater", "radiator", "fan", "air", "humidifier", "dehumidifier", "vacuum", "mop", "broom", "dustpan", "bucket", "sponge", "detergent", "bleach", "disinfectant", "trash", "recycling", "compost", "laundry", "washer", "dryer", "iron", "ironing", "hanger", "clothesline", "hamper", "basket", "towel", "mat", "hook", "rack", "organizer", "container", "box", "bin", "bag", "toolbox", "hammer", "nail", "screw", "screwdriver", "wrench", "pliers", "drill", "saw", "tape", "glue", "sandpaper", "paintbrush", "roller", "ladder", "stepstool", "flashlight", "battery", "extension", "surge", "timer", "sensor", "alarm", "detector", "camera", "intercom", "sprinkler", "hose", "rake", "shovel", "wheelbarrow", "lawnmower", "trimmer", "fertilizer", "pesticide", "mulch", "compost", "greenhouse", "shed", "gazebo", "pergola", "fountain", "pond", "pathway", "stepping"],
}

# Georgian translations for common words (basic mapping)
GEORGIAN_TRANSLATIONS = {}

def get_category_theme(filename):
    """Map filename to a word bank theme."""
    name = filename.replace('.json', '').lower()
    if any(x in name for x in ['academic', 'ielts', 'education', 'university', 'school']):
        return 'academic'
    if any(x in name for x in ['animal', 'pet', 'ocean', 'marine']):
        return 'animal'
    if any(x in name for x in ['food', 'drink', 'cook', 'kitchen', 'restaurant', 'cafe', 'supermarket', 'grocery', 'fast-food']):
        return 'food'
    if any(x in name for x in ['sport', 'fitness', 'gym', 'mma', 'game']):
        return 'sport'
    if any(x in name for x in ['tech', 'computer', 'programming', 'internet', 'phone', 'app', 'social-media']):
        return 'technology'
    if any(x in name for x in ['music', 'art', 'movie', 'cinema', 'entertainment', 'youtube']):
        return 'music'
    if any(x in name for x in ['work', 'business', 'job', 'office', 'career', 'startup', 'freelanc', 'email']):
        return 'work'
    if any(x in name for x in ['emotion', 'feeling', 'mood', 'mental', 'psychology', 'personality', 'motivation', 'self-improvement']):
        return 'emotion'
    if any(x in name for x in ['health', 'body', 'medical', 'doctor', 'bathroom', 'hygiene']):
        return 'health'
    if any(x in name for x in ['travel', 'transport', 'airport', 'hotel', 'visa', 'immigration', 'taxi', 'public-transport', 'car', 'driving']):
        return 'travel'
    if any(x in name for x in ['home', 'house', 'housing', 'furniture', 'room', 'household', 'apartment', 'garden']):
        return 'home'
    return None

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python3 expand_category.py file1.json file2.json ...")
        sys.exit(1)
    
    for filename in sys.argv[1:]:
        filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), filename)
        if not os.path.exists(filepath):
            print(f"Not found: {filename}")
            continue
        
        with open(filepath, 'r') as f:
            cards = json.load(f)
        
        existing_words = {c['english'].lower() for c in cards}
        current_count = len(cards)
        
        if current_count >= 200:
            print(f"{filename}: already has {current_count} words, skipping")
            continue
        
        needed = 200 - current_count
        theme = get_category_theme(filename)
        
        if not theme:
            print(f"{filename}: no theme mapping, skipping (has {current_count})")
            continue
        
        word_bank = WORD_BANKS.get(theme, [])
        # Filter out already existing words
        new_words = [w for w in word_bank if w.lower() not in existing_words and ' ' not in w]
        
        added = 0
        category = cards[0].get('category', filename.replace('.json', '')) if cards else filename.replace('.json', '')
        
        for word in new_words[:needed]:
            cards.append({
                "english": word,
                "georgian": "",
                "pronunciation": "",
                "example_en": "",
                "example_ka": "",
                "category": category
            })
            added += 1
        
        with open(filepath, 'w') as f:
            json.dump(cards, f, ensure_ascii=False, indent=2)
        
        print(f"{filename}: {current_count} → {len(cards)} (+{added})")
