#!/usr/bin/env python3
import json

def expand_file(filepath, target, new_entries):
    with open(filepath, 'r') as f:
        data = json.load(f)
    existing_words = {e['english'].lower() for e in data}
    category = data[0].get('category', '')
    added = 0
    for entry in new_entries:
        if entry['english'].lower() not in existing_words:
            entry['category'] = category
            data.append(entry)
            existing_words.add(entry['english'].lower())
            added += 1
            if len(data) >= target:
                break
    data = data[:target]
    with open(filepath, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"{filepath}: {len(data)} entries (added {added})")

# clothes-fashion.json new entries
clothes_new = [
    {"english":"blouse","georgian":"ბლუზა","pronunciation":"/blaʊz/","example_en":"She wore a silk blouse.","example_ka":"მან აბრეშუმის ბლუზა ჩაიცვა.","level":"beginner"},
    {"english":"vest","georgian":"ჟილეტი","pronunciation":"/vest/","example_en":"He wore a vest over his shirt.","example_ka":"მან პერანგზე ჟილეტი ჩაიცვა.","level":"beginner"},
    {"english":"hoodie","georgian":"ჰუდი","pronunciation":"/ˈhʊdi/","example_en":"I love wearing my hoodie.","example_ka":"ჰუდის ტარება მიყვარს.","level":"beginner"},
    {"english":"cardigan","georgian":"კარდიგანი","pronunciation":"/ˈkɑːrdɪɡən/","example_en":"She put on a warm cardigan.","example_ka":"მან თბილი კარდიგანი ჩაიცვა.","level":"beginner"},
    {"english":"raincoat","georgian":"საწვიმარი","pronunciation":"/ˈreɪnkoʊt/","example_en":"Take your raincoat, it will rain.","example_ka":"საწვიმარი წაიღე, იწვიმებს.","level":"beginner"},
    {"english":"sneakers","georgian":"კედები","pronunciation":"/ˈsniːkərz/","example_en":"I bought new sneakers for running.","example_ka":"სირბილისთვის ახალი კედები ვიყიდე.","level":"beginner"},
    {"english":"slippers","georgian":"ჩუსტები","pronunciation":"/ˈslɪpərz/","example_en":"I wear slippers at home.","example_ka":"სახლში ჩუსტებს ვიცვამ.","level":"beginner"},
    {"english":"heels","georgian":"ქუსლიანი ფეხსაცმელი","pronunciation":"/hiːlz/","example_en":"She wore high heels to the party.","example_ka":"წვეულებაზე ქუსლიანი ფეხსაცმელი ჩაიცვა.","level":"intermediate"},
    {"english":"lace","georgian":"მაქმანი","pronunciation":"/leɪs/","example_en":"The dress has beautiful lace.","example_ka":"კაბას ლამაზი მაქმანი აქვს.","level":"intermediate"},
    {"english":"denim","georgian":"ჯინსის ქსოვილი","pronunciation":"/ˈdenɪm/","example_en":"Denim jackets are popular.","example_ka":"ჯინსის ქურთუკები პოპულარულია.","level":"beginner"},
    {"english":"velvet","georgian":"ხავერდი","pronunciation":"/ˈvelvɪt/","example_en":"She loves velvet dresses.","example_ka":"ხავერდის კაბები უყვარს.","level":"intermediate"},
    {"english":"linen","georgian":"სელი","pronunciation":"/ˈlɪnɪn/","example_en":"Linen is cool in summer.","example_ka":"სელი ზაფხულში გრილია.","level":"intermediate"},
    {"english":"polyester","georgian":"პოლიესტერი","pronunciation":"/ˌpɒliˈestər/","example_en":"This shirt is made of polyester.","example_ka":"ეს პერანგი პოლიესტერისგანაა.","level":"intermediate"},
    {"english":"nylon","georgian":"ნეილონი","pronunciation":"/ˈnaɪlɒn/","example_en":"Nylon stockings are durable.","example_ka":"ნეილონის წინდები გამძლეა.","level":"intermediate"},
    {"english":"suede","georgian":"ზამშა","pronunciation":"/sweɪd/","example_en":"He has suede shoes.","example_ka":"მას ზამშის ფეხსაცმელი აქვს.","level":"intermediate"},
    {"english":"corduroy","georgian":"ველვეტი","pronunciation":"/ˈkɔːrdərɔɪ/","example_en":"Corduroy pants are warm.","example_ka":"ველვეტის შარვალი თბილია.","level":"intermediate"},
    {"english":"fleece","georgian":"ფლისი","pronunciation":"/fliːs/","example_en":"Wear a fleece jacket when hiking.","example_ka":"ლაშქრობისას ფლისის ქურთუკი ჩაიცვი.","level":"intermediate"},
    {"english":"cashmere","georgian":"კაშმირი","pronunciation":"/ˈkæʃmɪr/","example_en":"Cashmere sweaters are expensive.","example_ka":"კაშმირის სვიტერები ძვირია.","level":"intermediate"},
    {"english":"satin","georgian":"ატლასი","pronunciation":"/ˈsætɪn/","example_en":"The satin dress shines beautifully.","example_ka":"ატლასის კაბა ლამაზად ბრწყინავს.","level":"intermediate"},
    {"english":"chiffon","georgian":"შიფონი","pronunciation":"/ʃɪˈfɒn/","example_en":"Chiffon is a very light fabric.","example_ka":"შიფონი ძალიან მსუბუქი ქსოვილია.","level":"intermediate"},
    {"english":"tweed","georgian":"ტვიდი","pronunciation":"/twiːd/","example_en":"He wore a tweed jacket.","example_ka":"მან ტვიდის ქურთუკი ჩაიცვა.","level":"intermediate"},
    {"english":"fur","georgian":"ბეწვი","pronunciation":"/fɜːr/","example_en":"She wore a fur coat.","example_ka":"მან ბეწვის პალტო ჩაიცვა.","level":"beginner"},
    {"english":"stitch","georgian":"ნაკერი","pronunciation":"/stɪtʃ/","example_en":"The stitch came undone.","example_ka":"ნაკერი გაიხსნა.","level":"intermediate"},
    {"english":"hem","georgian":"კალთა","pronunciation":"/hem/","example_en":"The hem needs to be shorter.","example_ka":"კალთა უფრო მოკლე უნდა იყოს.","level":"intermediate"},
    {"english":"tailor","georgian":"მკერავი","pronunciation":"/ˈteɪlər/","example_en":"The tailor fixed my suit.","example_ka":"მკერავმა კოსტიუმი შემიკეთა.","level":"intermediate"},
    {"english":"iron","georgian":"უთო","pronunciation":"/ˈaɪərn/","example_en":"Please iron my shirt.","example_ka":"პერანგი გამიუთოვე.","level":"beginner"},
    {"english":"hanger","georgian":"საკიდი","pronunciation":"/ˈhæŋər/","example_en":"Hang your coat on the hanger.","example_ka":"პალტო საკიდზე ჩამოკიდე.","level":"beginner"},
    {"english":"runway","georgian":"პოდიუმი","pronunciation":"/ˈrʌnweɪ/","example_en":"Models walk on the runway.","example_ka":"მოდელები პოდიუმზე დადიან.","level":"intermediate"},
    {"english":"designer","georgian":"დიზაინერი","pronunciation":"/dɪˈzaɪnər/","example_en":"She is a famous designer.","example_ka":"ის ცნობილი დიზაინერია.","level":"intermediate"},
    {"english":"embroidery","georgian":"ნაქარგი","pronunciation":"/ɪmˈbrɔɪdəri/","example_en":"The embroidery is beautiful.","example_ka":"ნაქარგი ლამაზია.","level":"intermediate"},
    {"english":"vintage","georgian":"ვინტაჟური","pronunciation":"/ˈvɪntɪdʒ/","example_en":"She loves vintage clothes.","example_ka":"ვინტაჟური ტანსაცმელი უყვარს.","level":"intermediate"},
    {"english":"style","georgian":"სტილი","pronunciation":"/staɪl/","example_en":"She has a unique style.","example_ka":"მას უნიკალური სტილი აქვს.","level":"beginner"},
    {"english":"trend","georgian":"ტენდენცია","pronunciation":"/trend/","example_en":"This trend is popular now.","example_ka":"ეს ტენდენცია ახლა პოპულარულია.","level":"intermediate"},
    {"english":"elegant","georgian":"ელეგანტური","pronunciation":"/ˈelɪɡənt/","example_en":"She looks very elegant.","example_ka":"ის ძალიან ელეგანტურად გამოიყურება.","level":"intermediate"},
    {"english":"casual","georgian":"ყოველდღიური","pronunciation":"/ˈkæʒuəl/","example_en":"I prefer casual clothing.","example_ka":"ყოველდღიურ ტანსაცმელს ვამჯობინებ.","level":"intermediate"},
    {"english":"formal","georgian":"ოფიციალური","pronunciation":"/ˈfɔːrml/","example_en":"Wear formal clothes to the event.","example_ka":"ღონისძიებაზე ოფიციალური ტანსაცმელი ჩაიცვი.","level":"intermediate"},
    {"english":"accessory","georgian":"აქსესუარი","pronunciation":"/əkˈsesəri/","example_en":"A scarf is a nice accessory.","example_ka":"შარფი კარგი აქსესუარია.","level":"intermediate"},
    {"english":"brooch","georgian":"ბროში","pronunciation":"/broʊtʃ/","example_en":"She pinned a brooch on her jacket.","example_ka":"მან ბროში ქურთუკზე მიამაგრა.","level":"intermediate"},
    {"english":"cufflink","georgian":"მანჟეტის ღილი","pronunciation":"/ˈkʌflɪŋk/","example_en":"He wore gold cufflinks.","example_ka":"მან ოქროს მანჟეტის ღილები ატარებდა.","level":"intermediate"},
    {"english":"pendant","georgian":"კულონი","pronunciation":"/ˈpendənt/","example_en":"She wore a silver pendant.","example_ka":"მან ვერცხლის კულონი ატარებდა.","level":"intermediate"},
    {"english":"bow tie","georgian":"პეპელა","pronunciation":"/ˈboʊ taɪ/","example_en":"He wore a bow tie to the wedding.","example_ka":"ქორწილში პეპელა ჩაიკეთა.","level":"intermediate"},
    {"english":"suspenders","georgian":"ამწევები","pronunciation":"/səˈspendərz/","example_en":"He wears suspenders instead of a belt.","example_ka":"ქამრის ნაცვლად ამწევებს ატარებს.","level":"intermediate"},
    {"english":"apron","georgian":"წინსაფარი","pronunciation":"/ˈeɪprən/","example_en":"The chef wears an apron.","example_ka":"მზარეულს წინსაფარი აცვია.","level":"beginner"},
    {"english":"robe","georgian":"ხალათი","pronunciation":"/roʊb/","example_en":"She wore a bathrobe after the shower.","example_ka":"შხაპის შემდეგ ხალათი ჩაიცვა.","level":"beginner"},
    {"english":"gown","georgian":"ხალათი","pronunciation":"/ɡaʊn/","example_en":"She wore a beautiful evening gown.","example_ka":"მან ლამაზი საღამოს კაბა ჩაიცვა.","level":"intermediate"},
    {"english":"tuxedo","georgian":"ტუქსედო","pronunciation":"/tʌkˈsiːdoʊ/","example_en":"He rented a tuxedo for the gala.","example_ka":"გალა-საღამოსთვის ტუქსედო იქირავა.","level":"intermediate"},
    {"english":"overalls","georgian":"კომბინეზონი","pronunciation":"/ˈoʊvərɔːlz/","example_en":"He wears overalls at work.","example_ka":"სამსახურში კომბინეზონს იცვამს.","level":"intermediate"},
    {"english":"poncho","georgian":"პონჩო","pronunciation":"/ˈpɒntʃoʊ/","example_en":"She wore a poncho in the rain.","example_ka":"წვიმაში პონჩო ჩაიცვა.","level":"intermediate"},
    {"english":"cape","georgian":"მოსასხამი","pronunciation":"/keɪp/","example_en":"The hero wore a red cape.","example_ka":"გმირს წითელი მოსასხამი ჰქონდა.","level":"intermediate"},
    {"english":"beret","georgian":"ბერეტი","pronunciation":"/bəˈreɪ/","example_en":"She wore a black beret.","example_ka":"მან შავი ბერეტი დაიხურა.","level":"intermediate"},
    {"english":"cap","georgian":"კეპი","pronunciation":"/kæp/","example_en":"He always wears a baseball cap.","example_ka":"ის ყოველთვის ბეისბოლის კეპს ატარებს.","level":"beginner"},
    {"english":"turban","georgian":"ჩალმა","pronunciation":"/ˈtɜːrbən/","example_en":"He wears a turban.","example_ka":"ის ჩალმას ატარებს.","level":"intermediate"},
    {"english":"headband","georgian":"თავსაბამი","pronunciation":"/ˈhedbænd/","example_en":"She wore a headband while exercising.","example_ka":"ვარჯიშის დროს თავსაბამს იკეთებდა.","level":"beginner"},
    {"english":"veil","georgian":"საბურველი","pronunciation":"/veɪl/","example_en":"The bride wore a white veil.","example_ka":"პატარძალმა თეთრი საბურველი დაიხურა.","level":"intermediate"},
    {"english":"mittens","georgian":"ხელთათმანები","pronunciation":"/ˈmɪtənz/","example_en":"Children wear mittens in snow.","example_ka":"ბავშვები თოვლში ხელთათმანებს იცვამენ.","level":"beginner"},
    {"english":"stockings","georgian":"წუღები","pronunciation":"/ˈstɒkɪŋz/","example_en":"She wore silk stockings.","example_ka":"მან აბრეშუმის წუღები ჩაიცვა.","level":"intermediate"},
    {"english":"tights","georgian":"კოლგოტი","pronunciation":"/taɪts/","example_en":"She wore black tights.","example_ka":"მან შავი კოლგოტი ჩაიცვა.","level":"beginner"},
    {"english":"leggings","georgian":"ლეგინსი","pronunciation":"/ˈleɡɪŋz/","example_en":"Leggings are comfortable for yoga.","example_ka":"ლეგინსი იოგასთვის მოსახერხებელია.","level":"beginner"},
    {"english":"bikini","georgian":"ბიკინი","pronunciation":"/bɪˈkiːni/","example_en":"She wore a bikini at the beach.","example_ka":"სანაპიროზე ბიკინი ჩაიცვა.","level":"beginner"},
    {"english":"swimsuit","georgian":"საცურაო კოსტიუმი","pronunciation":"/ˈswɪmsuːt/","example_en":"I need a new swimsuit.","example_ka":"ახალი საცურაო კოსტიუმი მჭირდება.","level":"beginner"},
    {"english":"tracksuit","georgian":"სპორტული კოსტიუმი","pronunciation":"/ˈtræksuːt/","example_en":"He wears a tracksuit to the gym.","example_ka":"სპორტდარბაზში სპორტულ კოსტიუმს იცვამს.","level":"beginner"},
    {"english":"anorak","georgian":"ანორაკი","pronunciation":"/ˈænəræk/","example_en":"He wore an anorak in the wind.","example_ka":"ქარში ანორაკი ჩაიცვა.","level":"intermediate"},
    {"english":"parka","georgian":"პარკა","pronunciation":"/ˈpɑːrkə/","example_en":"A parka keeps you warm in winter.","example_ka":"პარკა ზამთარში გათბობს.","level":"intermediate"},
    {"english":"windbreaker","georgian":"ქარსაწინააღმდეგო ქურთუკი","pronunciation":"/ˈwɪndbreɪkər/","example_en":"Wear a windbreaker on windy days.","example_ka":"ქარიან დღეებში ქარსაწინააღმდეგო ქურთუკი ჩაიცვი.","level":"intermediate"},
    {"english":"blazer","georgian":"ბლეიზერი","pronunciation":"/ˈbleɪzər/","example_en":"She wore a navy blazer.","example_ka":"მან მუქი ლურჯი ბლეიზერი ჩაიცვა.","level":"intermediate"},
    {"english":"waistcoat","georgian":"ჟილეტი","pronunciation":"/ˈweɪskoʊt/","example_en":"He wore a waistcoat with his suit.","example_ka":"კოსტიუმთან ჟილეტი ჩაიცვა.","level":"intermediate"},
    {"english":"dungarees","georgian":"კომბინეზონი","pronunciation":"/ˌdʌŋɡəˈriːz/","example_en":"She wore denim dungarees.","example_ka":"მან ჯინსის კომბინეზონი ჩაიცვა.","level":"intermediate"},
    {"english":"camisole","georgian":"კამიზოლი","pronunciation":"/ˈkæmɪsoʊl/","example_en":"She wore a lace camisole.","example_ka":"მან მაქმანის კამიზოლი ჩაიცვა.","level":"intermediate"},
    {"english":"tunic","georgian":"ტუნიკა","pronunciation":"/ˈtjuːnɪk/","example_en":"She wore a long tunic.","example_ka":"მან გრძელი ტუნიკა ჩაიცვა.","level":"intermediate"},
    {"english":"crop top","georgian":"მოკლე მაისური","pronunciation":"/krɒp tɒp/","example_en":"She wore a crop top in summer.","example_ka":"ზაფხულში მოკლე მაისური ჩაიცვა.","level":"beginner"},
    {"english":"tank top","georgian":"მაისური","pronunciation":"/tæŋk tɒp/","example_en":"He wore a tank top to the gym.","example_ka":"სპორტდარბაზში მაისური ჩაიცვა.","level":"beginner"},
    {"english":"polo shirt","georgian":"პოლო მაისური","pronunciation":"/ˈpoʊloʊ ʃɜːrt/","example_en":"He wore a polo shirt to the game.","example_ka":"თამაშზე პოლო მაისური ჩაიცვა.","level":"beginner"},
    {"english":"flannel","georgian":"ფლანელი","pronunciation":"/ˈflænl/","example_en":"He wore a flannel shirt.","example_ka":"მან ფლანელის პერანგი ჩაიცვა.","level":"intermediate"},
    {"english":"corset","georgian":"კორსეტი","pronunciation":"/ˈkɔːrsɪt/","example_en":"Corsets were popular in the past.","example_ka":"კორსეტი წარსულში პოპულარული იყო.","level":"intermediate"},
    {"english":"sarong","georgian":"სარონგი","pronunciation":"/səˈrɒŋ/","example_en":"She wore a sarong at the resort.","example_ka":"კურორტზე სარონგი ჩაიცვა.","level":"intermediate"},
    {"english":"kimono","georgian":"კიმონო","pronunciation":"/kɪˈmoʊnoʊ/","example_en":"She wore a Japanese kimono.","example_ka":"მან იაპონური კიმონო ჩაიცვა.","level":"intermediate"},
    {"english":"toga","georgian":"ტოგა","pronunciation":"/ˈtoʊɡə/","example_en":"Romans wore togas.","example_ka":"რომაელები ტოგას ატარებდნენ.","level":"intermediate"},
    {"english":"kaftan","georgian":"ყაფთანი","pronunciation":"/ˈkæftæn/","example_en":"She wore a colorful kaftan.","example_ka":"მან ფერადი ყაფთანი ჩაიცვა.","level":"intermediate"},
    {"english":"shawl","georgian":"შალი","pronunciation":"/ʃɔːl/","example_en":"She wrapped a shawl around her shoulders.","example_ka":"მან შალი მხრებზე შემოისხა.","level":"intermediate"},
    {"english":"stole","georgian":"სტოლა","pronunciation":"/stoʊl/","example_en":"She wore a fur stole.","example_ka":"მან ბეწვის სტოლა ატარებდა.","level":"intermediate"},
    {"english":"muffler","georgian":"შარფი","pronunciation":"/ˈmʌflər/","example_en":"He wrapped a muffler around his neck.","example_ka":"მან შარფი კისერზე შემოიხვია.","level":"intermediate"},
    {"english":"bandana","georgian":"ბანდანა","pronunciation":"/bænˈdænə/","example_en":"He wore a red bandana.","example_ka":"მან წითელი ბანდანა დაიხურა.","level":"beginner"},
    {"english":"visor","georgian":"მზისფარი","pronunciation":"/ˈvaɪzər/","example_en":"She wore a visor while golfing.","example_ka":"გოლფის დროს მზისფარს იკეთებდა.","level":"intermediate"},
    {"english":"fedora","georgian":"ფედორა","pronunciation":"/fɪˈdɔːrə/","example_en":"He wore a classic fedora.","example_ka":"მან კლასიკური ფედორა დაიხურა.","level":"intermediate"},
    {"english":"beanie","georgian":"ქუდი","pronunciation":"/ˈbiːni/","example_en":"Wear a beanie in cold weather.","example_ka":"ცივ ამინდში ქუდი დაიხურე.","level":"beginner"},
    {"english":"bonnet","georgian":"ჩეპიხი","pronunciation":"/ˈbɒnɪt/","example_en":"The baby wore a cute bonnet.","example_ka":"ჩვილს საყვარელი ჩეპიხი ეხურა.","level":"intermediate"},
    {"english":"tiara","georgian":"ტიარა","pronunciation":"/tiˈɑːrə/","example_en":"The princess wore a sparkling tiara.","example_ka":"პრინცესამ ბრწყინვალე ტიარა დაიხურა.","level":"intermediate"},
    {"english":"crown","georgian":"გვირგვინი","pronunciation":"/kraʊn/","example_en":"The queen wore a golden crown.","example_ka":"დედოფალმა ოქროს გვირგვინი დაიდგა.","level":"beginner"},
    {"english":"anklet","georgian":"ტერფსაბამი","pronunciation":"/ˈæŋklɪt/","example_en":"She wore a silver anklet.","example_ka":"მან ვერცხლის ტერფსაბამი ატარებდა.","level":"intermediate"},
    {"english":"choker","georgian":"ჩოკერი","pronunciation":"/ˈtʃoʊkər/","example_en":"She wore a velvet choker.","example_ka":"მან ხავერდის ჩოკერი ატარებდა.","level":"intermediate"},
    {"english":"clutch","georgian":"კლაჩი","pronunciation":"/klʌtʃ/","example_en":"She carried a small clutch.","example_ka":"მან პატარა კლაჩი ატარებდა.","level":"intermediate"},
    {"english":"tote","georgian":"ტოტ ჩანთა","pronunciation":"/toʊt/","example_en":"She uses a tote bag for shopping.","example_ka":"საყიდლებისთვის ტოტ ჩანთას იყენებს.","level":"intermediate"},
    {"english":"satchel","georgian":"სკოლის ჩანთა","pronunciation":"/ˈsætʃəl/","example_en":"He carried a leather satchel.","example_ka":"მან ტყავის ჩანთა ატარებდა.","level":"intermediate"},
    {"english":"fanny pack","georgian":"წელის ჩანთა","pronunciation":"/ˈfæni pæk/","example_en":"He wore a fanny pack while hiking.","example_ka":"ლაშქრობისას წელის ჩანთა ატარებდა.","level":"beginner"},
    {"english":"briefcase","georgian":"პორტფელი","pronunciation":"/ˈbriːfkeɪs/","example_en":"He carries a briefcase to work.","example_ka":"სამსახურში პორტფელს ატარებს.","level":"intermediate"},
    {"english":"luggage","georgian":"ბარგი","pronunciation":"/ˈlʌɡɪdʒ/","example_en":"Don't forget your luggage.","example_ka":"ბარგი არ დაგავიწყდეს.","level":"beginner"},
    {"english":"suitcase","georgian":"ჩემოდანი","pronunciation":"/ˈsuːtkeɪs/","example_en":"I packed my suitcase for the trip.","example_ka":"მოგზაურობისთვის ჩემოდანი ჩავალაგე.","level":"beginner"},
    {"english":"garment","georgian":"სამოსი","pronunciation":"/ˈɡɑːrmənt/","example_en":"This garment needs dry cleaning.","example_ka":"ეს სამოსი ქიმწმენდას საჭიროებს.","level":"intermediate"},
    {"english":"attire","georgian":"ჩაცმულობა","pronunciation":"/əˈtaɪər/","example_en":"Formal attire is required.","example_ka":"ოფიციალური ჩაცმულობა მოითხოვება.","level":"intermediate"},
    {"english":"apparel","georgian":"ტანსაცმელი","pronunciation":"/əˈpærəl/","example_en":"This store sells sports apparel.","example_ka":"ეს მაღაზია სპორტულ ტანსაცმელს ყიდის.","level":"intermediate"},
    {"english":"thread","georgian":"ძაფი","pronunciation":"/θred/","example_en":"I need a needle and thread.","example_ka":"ნემსი და ძაფი მჭირდება.","level":"beginner"},
    {"english":"needle","georgian":"ნემსი","pronunciation":"/ˈniːdl/","example_en":"She sewed with a needle.","example_ka":"მან ნემსით იკერა.","level":"beginner"},
    {"english":"sew","georgian":"კერვა","pronunciation":"/soʊ/","example_en":"She can sew very well.","example_ka":"ის ძალიან კარგად კერავს.","level":"beginner"},
    {"english":"knit","georgian":"ქსოვა","pronunciation":"/nɪt/","example_en":"She knits scarves in winter.","example_ka":"ზამთარში შარფებს ქსოვს.","level":"intermediate"},
    {"english":"weave","georgian":"ქსოვა","pronunciation":"/wiːv/","example_en":"They weave carpets by hand.","example_ka":"ხალიჩებს ხელით ქსოვენ.","level":"intermediate"},
    {"english":"dye","georgian":"საღებავი","pronunciation":"/daɪ/","example_en":"She dyed her shirt blue.","example_ka":"მან პერანგი ლურჯად შეღება.","level":"intermediate"},
    {"english":"plaid","georgian":"შოტლანდიური ნიმუში","pronunciation":"/plæd/","example_en":"He wore a plaid shirt.","example_ka":"მან შოტლანდიური ნიმუშის პერანგი ჩაიცვა.","level":"intermediate"},
    {"english":"polka dot","georgian":"წერტილოვანი","pronunciation":"/ˈpoʊlkə dɒt/","example_en":"She wore a polka dot dress.","example_ka":"მან წერტილოვანი კაბა ჩაიცვა.","level":"intermediate"},
    {"english":"floral","georgian":"ყვავილოვანი","pronunciation":"/ˈflɔːrəl/","example_en":"She loves floral patterns.","example_ka":"ყვავილოვანი ნიმუშები უყვარს.","level":"intermediate"},
    {"english":"checkered","georgian":"უჯრედებიანი","pronunciation":"/ˈtʃekərd/","example_en":"He wore a checkered shirt.","example_ka":"მან უჯრედებიანი პერანგი ჩაიცვა.","level":"intermediate"},
    {"english":"plain","georgian":"უბრალო","pronunciation":"/pleɪn/","example_en":"I prefer plain T-shirts.","example_ka":"უბრალო მაისურებს ვამჯობინებ.","level":"beginner"},
    {"english":"wrinkle","georgian":"ნაოჭი","pronunciation":"/ˈrɪŋkl/","example_en":"Iron out the wrinkles.","example_ka":"ნაოჭები გაუთოვე.","level":"intermediate"},
    {"english":"stain","georgian":"ლაქა","pronunciation":"/steɪn/","example_en":"There is a stain on my shirt.","example_ka":"პერანგზე ლაქა მაქვს.","level":"beginner"},
    {"english":"fold","georgian":"დაკეცვა","pronunciation":"/foʊld/","example_en":"Fold your clothes neatly.","example_ka":"ტანსაცმელი ლამაზად დაკეცე.","level":"beginner"},
    {"english":"hang","georgian":"ჩამოკიდება","pronunciation":"/hæŋ/","example_en":"Hang your jacket on the hook.","example_ka":"ქურთუკი კაუჭზე ჩამოკიდე.","level":"beginner"},
    {"english":"mend","georgian":"შეკეთება","pronunciation":"/mend/","example_en":"She mended the torn shirt.","example_ka":"მან დახეული პერანგი შეაკეთა.","level":"intermediate"},
    {"english":"alteration","georgian":"გადაკეთება","pronunciation":"/ˌɔːltəˈreɪʃn/","example_en":"The dress needs alterations.","example_ka":"კაბას გადაკეთება სჭირდება.","level":"intermediate"},
    {"english":"fitting","georgian":"მორგება","pronunciation":"/ˈfɪtɪŋ/","example_en":"I have a fitting at the tailor.","example_ka":"მკერავთან მორგება მაქვს.","level":"intermediate"},
    {"english":"mannequin","georgian":"მანეკენი","pronunciation":"/ˈmænɪkɪn/","example_en":"The mannequin displayed a nice dress.","example_ka":"მანეკენზე ლამაზი კაბა იყო გამოფენილი.","level":"intermediate"},
    {"english":"boutique","georgian":"ბუტიკი","pronunciation":"/buːˈtiːk/","example_en":"She shops at a boutique.","example_ka":"ის ბუტიკში ყიდულობს.","level":"intermediate"},
    {"english":"couture","georgian":"კუტიურე","pronunciation":"/kuːˈtjʊr/","example_en":"She wore a couture gown.","example_ka":"მან კუტიურეს კაბა ჩაიცვა.","level":"intermediate"},
    {"english":"textile","georgian":"ტექსტილი","pronunciation":"/ˈtekstaɪl/","example_en":"The textile industry is large.","example_ka":"ტექსტილის ინდუსტრია დიდია.","level":"intermediate"},
    {"english":"seam","georgian":"ნაკერი","pronunciation":"/siːm/","example_en":"The seam ripped apart.","example_ka":"ნაკერი გაიხა.","level":"intermediate"},
    {"english":"cuff","georgian":"მანჟეტი","pronunciation":"/kʌf/","example_en":"He rolled up his cuffs.","example_ka":"მან მანჟეტები აიკეცა.","level":"intermediate"},
    {"english":"lapel","georgian":"ლაცკანი","pronunciation":"/ləˈpel/","example_en":"He pinned a flower on his lapel.","example_ka":"მან ლაცკანზე ყვავილი მიამაგრა.","level":"intermediate"},
    {"english":"pleat","georgian":"ნაკეცი","pronunciation":"/pliːt/","example_en":"The skirt has pleats.","example_ka":"ქვედაკაბას ნაკეცები აქვს.","level":"intermediate"},
    {"english":"ruffle","georgian":"ქარვასლა","pronunciation":"/ˈrʌfl/","example_en":"The dress has ruffles.","example_ka":"კაბას ქარვასლები აქვს.","level":"intermediate"},
    {"english":"buckle","georgian":"ბალთა","pronunciation":"/ˈbʌkl/","example_en":"The belt buckle is silver.","example_ka":"ქამრის ბალთა ვერცხლისფერია.","level":"intermediate"},
    {"english":"clasp","georgian":"საკეტი","pronunciation":"/klæsp/","example_en":"The necklace clasp is broken.","example_ka":"ყელსაბამის საკეტი გატეხილია.","level":"intermediate"},
    {"english":"lining","georgian":"საფენი","pronunciation":"/ˈlaɪnɪŋ/","example_en":"The coat has a silk lining.","example_ka":"პალტოს აბრეშუმის საფენი აქვს.","level":"intermediate"},
    {"english":"hood","georgian":"კაპიუშონი","pronunciation":"/hʊd/","example_en":"Put your hood up, it's raining.","example_ka":"კაპიუშონი აიწიე, წვიმს.","level":"beginner"},
    {"english":"drawstring","georgian":"თასმა","pronunciation":"/ˈdrɔːstrɪŋ/","example_en":"Pull the drawstring to tighten.","example_ka":"მოსაჭერად თასმა გაიწიე.","level":"intermediate"},
    {"english":"snap","georgian":"კნოპი","pronunciation":"/snæp/","example_en":"The jacket closes with snaps.","example_ka":"ქურთუკი კნოპებით იკეტება.","level":"intermediate"},
    {"english":"velcro","georgian":"ველკრო","pronunciation":"/ˈvelkroʊ/","example_en":"The shoes have velcro straps.","example_ka":"ფეხსაცმელს ველკროს თასმები აქვს.","level":"intermediate"},
    {"english":"patch","georgian":"ლატა","pronunciation":"/pætʃ/","example_en":"She sewed a patch on her jeans.","example_ka":"მან ჯინსზე ლატა მიაკერა.","level":"beginner"},
    {"english":"fringe","georgian":"ფარფლი","pronunciation":"/frɪndʒ/","example_en":"The scarf has fringe.","example_ka":"შარფს ფარფლი აქვს.","level":"intermediate"},
    {"english":"sequin","georgian":"პულეტი","pronunciation":"/ˈsiːkwɪn/","example_en":"The dress is covered in sequins.","example_ka":"კაბა პულეტებით არის დაფარული.","level":"intermediate"},
    {"english":"rhinestone","georgian":"შტრასი","pronunciation":"/ˈraɪnstoʊn/","example_en":"Her phone case has rhinestones.","example_ka":"ტელეფონის ქეისს შტრასები აქვს.","level":"intermediate"},
    {"english":"tassel","georgian":"ფუნჯი","pronunciation":"/ˈtæsl/","example_en":"The curtain has tassels.","example_ka":"ფარდას ფუნჯები აქვს.","level":"intermediate"},
    {"english":"ribbon","georgian":"ლენტი","pronunciation":"/ˈrɪbən/","example_en":"She tied a ribbon in her hair.","example_ka":"მან თმაში ლენტი შეიკრა.","level":"beginner"},
    {"english":"elastic","georgian":"რეზინი","pronunciation":"/ɪˈlæstɪk/","example_en":"The waistband has elastic.","example_ka":"წელის ზოლს რეზინი აქვს.","level":"intermediate"},
    {"english":"spandex","georgian":"სპანდექსი","pronunciation":"/ˈspændeks/","example_en":"Spandex is very stretchy.","example_ka":"სპანდექსი ძალიან ელასტიურია.","level":"intermediate"},
    {"english":"crease","georgian":"ნაკეცი","pronunciation":"/kriːs/","example_en":"Iron out the crease in your pants.","example_ka":"შარვლის ნაკეცი გაუთოვე.","level":"intermediate"},
    {"english":"shrink","georgian":"შეკუმშვა","pronunciation":"/ʃrɪŋk/","example_en":"This shirt may shrink in the wash.","example_ka":"ეს პერანგი რეცხვისას შეიძლება შეიკუმშოს.","level":"intermediate"},
    {"english":"fade","georgian":"გაფერმკრთალება","pronunciation":"/feɪd/","example_en":"The color will fade over time.","example_ka":"ფერი დროთა განმავლობაში გაფერმკრთალდება.","level":"intermediate"},
    {"english":"bleach","georgian":"გაუფერულება","pronunciation":"/bliːtʃ/","example_en":"Don't bleach colored clothes.","example_ka":"ფერად ტანსაცმელს არ გაუფერულო.","level":"intermediate"},
    {"english":"detergent","georgian":"სარეცხი საშუალება","pronunciation":"/dɪˈtɜːrdʒənt/","example_en":"Use mild detergent for silk.","example_ka":"აბრეშუმისთვის რბილი სარეცხი საშუალება გამოიყენე.","level":"intermediate"},
    {"english":"clothesline","georgian":"საშრობი თოკი","pronunciation":"/ˈkloʊðzlaɪn/","example_en":"Hang the clothes on the clothesline.","example_ka":"ტანსაცმელი საშრობ თოკზე გაფინე.","level":"beginner"},
    {"english":"dryer","georgian":"საშრობი","pronunciation":"/ˈdraɪər/","example_en":"Put the clothes in the dryer.","example_ka":"ტანსაცმელი საშრობში ჩადე.","level":"beginner"},
    {"english":"closet","georgian":"კარადა","pronunciation":"/ˈklɒzɪt/","example_en":"My closet is full of clothes.","example_ka":"ჩემი კარადა ტანსაცმლით სავსეა.","level":"beginner"},
    {"english":"drawer","georgian":"უჯრა","pronunciation":"/drɔːr/","example_en":"Put your socks in the drawer.","example_ka":"წინდები უჯრაში ჩადე.","level":"beginner"},
    {"english":"hamper","georgian":"სარეცხის კალათა","pronunciation":"/ˈhæmpər/","example_en":"Put dirty clothes in the hamper.","example_ka":"ბინძური ტანსაცმელი სარეცხის კალათაში ჩადე.","level":"intermediate"},
    {"english":"mothball","georgian":"ნაფტალინი","pronunciation":"/ˈmɒθbɔːl/","example_en":"Use mothballs to protect wool.","example_ka":"მატყლის დასაცავად ნაფტალინი გამოიყენე.","level":"intermediate"},
    {"english":"thimble","georgian":"თითსაცმელი","pronunciation":"/ˈθɪmbl/","example_en":"Use a thimble when sewing.","example_ka":"კერვისას თითსაცმელი გამოიყენე.","level":"intermediate"},
    {"english":"bobbin","georgian":"ძეწკვი","pronunciation":"/ˈbɒbɪn/","example_en":"Put thread on the bobbin.","example_ka":"ძაფი ძეწკვზე გადაახვიე.","level":"intermediate"},
    {"english":"scissors","georgian":"მაკრატელი","pronunciation":"/ˈsɪzərz/","example_en":"Cut the fabric with scissors.","example_ka":"ქსოვილი მაკრატლით გაჭერი.","level":"beginner"},
    {"english":"pin","georgian":"ქინძისთავა","pronunciation":"/pɪn/","example_en":"Use a pin to hold the fabric.","example_ka":"ქსოვილის დასაჭერად ქინძისთავა გამოიყენე.","level":"beginner"},
    {"english":"measurement","georgian":"გაზომვა","pronunciation":"/ˈmeʒərmənt/","example_en":"Take your measurements before ordering.","example_ka":"შეკვეთამდე გაზომვები გააკეთე.","level":"intermediate"},
    {"english":"tape measure","georgian":"სანტიმეტრი","pronunciation":"/teɪp ˈmeʒər/","example_en":"Use a tape measure for accuracy.","example_ka":"სიზუსტისთვის სანტიმეტრი გამოიყენე.","level":"intermediate"},
]

# clothing-fashion.json new entries
clothing_new = [
    {"english":"hoodie","georgian":"ჰუდი","pronunciation":"/ˈhʊdi/","example_en":"I love my hoodie.","example_ka":"ჩემი ჰუდი მიყვარს.","level":"A1"},
    {"english":"cardigan","georgian":"კარდიგანი","pronunciation":"/ˈkɑːrdɪɡən/","example_en":"She put on a cardigan.","example_ka":"მან კარდიგანი ჩაიცვა.","level":"A2"},
    {"english":"blouse","georgian":"ბლუზა","pronunciation":"/blaʊz/","example_en":"She wore a silk blouse.","example_ka":"მან აბრეშუმის ბლუზა ჩაიცვა.","level":"A2"},
    {"english":"vest","georgian":"ჟილეტი","pronunciation":"/vest/","example_en":"He wore a vest over his shirt.","example_ka":"მან პერანგზე ჟილეტი ჩაიცვა.","level":"A2"},
    {"english":"raincoat","georgian":"საწვიმარი","pronunciation":"/ˈreɪnkoʊt/","example_en":"Take your raincoat.","example_ka":"საწვიმარი წაიღე.","level":"A1"},
    {"english":"sneakers","georgian":"კედები","pronunciation":"/ˈsniːkərz/","example_en":"I bought new sneakers.","example_ka":"ახალი კედები ვიყიდე.","level":"A1"},
    {"english":"slippers","georgian":"ჩუსტები","pronunciation":"/ˈslɪpərz/","example_en":"I wear slippers at home.","example_ka":"სახლში ჩუსტებს ვიცვამ.","level":"A1"},
    {"english":"heels","georgian":"ქუსლიანი ფეხსაცმელი","pronunciation":"/hiːlz/","example_en":"She wore high heels.","example_ka":"მან მაღალქუსლიანი ფეხსაცმელი ჩაიცვა.","level":"A2"},
    {"english":"lace","georgian":"მაქმანი","pronunciation":"/leɪs/","example_en":"The dress has beautiful lace.","example_ka":"კაბას ლამაზი მაქმანი აქვს.","level":"B1"},
    {"english":"polyester","georgian":"პოლიესტერი","pronunciation":"/ˌpɒliˈestər/","example_en":"This shirt is polyester.","example_ka":"ეს პერანგი პოლიესტერისაა.","level":"B1"},
    {"english":"nylon","georgian":"ნეილონი","pronunciation":"/ˈnaɪlɒn/","example_en":"Nylon is durable.","example_ka":"ნეილონი გამძლეა.","level":"B1"},
    {"english":"suede","georgian":"ზამშა","pronunciation":"/sweɪd/","example_en":"He has suede shoes.","example_ka":"მას ზამშის ფეხსაცმელი აქვს.","level":"B1"},
    {"english":"corduroy","georgian":"ველვეტი","pronunciation":"/ˈkɔːrdərɔɪ/","example_en":"Corduroy pants are warm.","example_ka":"ველვეტის შარვალი თბილია.","level":"B1"},
    {"english":"fleece","georgian":"ფლისი","pronunciation":"/fliːs/","example_en":"Wear a fleece jacket.","example_ka":"ფლისის ქურთუკი ჩაიცვი.","level":"A2"},
    {"english":"cashmere","georgian":"კაშმირი","pronunciation":"/ˈkæʃmɪr/","example_en":"Cashmere is soft and warm.","example_ka":"კაშმირი რბილი და თბილია.","level":"B1"},
    {"english":"satin","georgian":"ატლასი","pronunciation":"/ˈsætɪn/","example_en":"The satin dress shines.","example_ka":"ატლასის კაბა ბრწყინავს.","level":"B1"},
    {"english":"chiffon","georgian":"შიფონი","pronunciation":"/ʃɪˈfɒn/","example_en":"Chiffon is very light.","example_ka":"შიფონი ძალიან მსუბუქია.","level":"B1"},
    {"english":"tweed","georgian":"ტვიდი","pronunciation":"/twiːd/","example_en":"He wore a tweed jacket.","example_ka":"მან ტვიდის ქურთუკი ჩაიცვა.","level":"B1"},
    {"english":"fur","georgian":"ბეწვი","pronunciation":"/fɜːr/","example_en":"She wore a fur coat.","example_ka":"მან ბეწვის პალტო ჩაიცვა.","level":"A2"},
    {"english":"trend","georgian":"ტენდენცია","pronunciation":"/trend/","example_en":"This trend is popular.","example_ka":"ეს ტენდენცია პოპულარულია.","level":"A2"},
    {"english":"elegant","georgian":"ელეგანტური","pronunciation":"/ˈelɪɡənt/","example_en":"She looks elegant.","example_ka":"ის ელეგანტურად გამოიყურება.","level":"A2"},
    {"english":"casual","georgian":"ყოველდღიური","pronunciation":"/ˈkæʒuəl/","example_en":"I prefer casual clothes.","example_ka":"ყოველდღიურ ტანსაცმელს ვამჯობინებ.","level":"A2"},
    {"english":"formal","georgian":"ოფიციალური","pronunciation":"/ˈfɔːrml/","example_en":"Wear formal attire.","example_ka":"ოფიციალური ტანსაცმელი ჩაიცვი.","level":"A2"},
    {"english":"accessory","georgian":"აქსესუარი","pronunciation":"/əkˈsesəri/","example_en":"A scarf is a nice accessory.","example_ka":"შარფი კარგი აქსესუარია.","level":"A2"},
    {"english":"brooch","georgian":"ბროში","pronunciation":"/broʊtʃ/","example_en":"She pinned a brooch.","example_ka":"მან ბროში მიამაგრა.","level":"B1"},
    {"english":"pendant","georgian":"კულონი","pronunciation":"/ˈpendənt/","example_en":"She wore a silver pendant.","example_ka":"მან ვერცხლის კულონი ატარებდა.","level":"B1"},
    {"english":"bow tie","georgian":"პეპელა","pronunciation":"/ˈboʊ taɪ/","example_en":"He wore a bow tie.","example_ka":"მან პეპელა ჩაიკეთა.","level":"A2"},
    {"english":"suspenders","georgian":"ამწევები","pronunciation":"/səˈspendərz/","example_en":"He wears suspenders.","example_ka":"ის ამწევებს ატარებს.","level":"B1"},
    {"english":"apron","georgian":"წინსაფარი","pronunciation":"/ˈeɪprən/","example_en":"The chef wears an apron.","example_ka":"მზარეულს წინსაფარი აცვია.","level":"A1"},
    {"english":"robe","georgian":"ხალათი","pronunciation":"/roʊb/","example_en":"She wore a bathrobe.","example_ka":"მან ხალათი ჩაიცვა.","level":"A1"},
    {"english":"gown","georgian":"საღამოს კაბა","pronunciation":"/ɡaʊn/","example_en":"She wore an evening gown.","example_ka":"მან საღამოს კაბა ჩაიცვა.","level":"B1"},
    {"english":"tuxedo","georgian":"ტუქსედო","pronunciation":"/tʌkˈsiːdoʊ/","example_en":"He rented a tuxedo.","example_ka":"მან ტუქსედო იქირავა.","level":"B1"},
    {"english":"overalls","georgian":"კომბინეზონი","pronunciation":"/ˈoʊvərɔːlz/","example_en":"He wears overalls at work.","example_ka":"სამსახურში კომბინეზონს იცვამს.","level":"A2"},
    {"english":"poncho","georgian":"პონჩო","pronunciation":"/ˈpɒntʃoʊ/","example_en":"She wore a poncho.","example_ka":"მან პონჩო ჩაიცვა.","level":"B1"},
    {"english":"cape","georgian":"მოსასხამი","pronunciation":"/keɪp/","example_en":"The hero wore a cape.","example_ka":"გმირს მოსასხამი ჰქონდა.","level":"A2"},
    {"english":"beret","georgian":"ბერეტი","pronunciation":"/bəˈreɪ/","example_en":"She wore a black beret.","example_ka":"მან შავი ბერეტი დაიხურა.","level":"A2"},
    {"english":"cap","georgian":"კეპი","pronunciation":"/kæp/","example_en":"He wears a baseball cap.","example_ka":"ის ბეისბოლის კეპს ატარებს.","level":"A1"},
    {"english":"headband","georgian":"თავსაბამი","pronunciation":"/ˈhedbænd/","example_en":"She wore a headband.","example_ka":"მან თავსაბამი დაიხურა.","level":"A1"},
    {"english":"veil","georgian":"საბურველი","pronunciation":"/veɪl/","example_en":"The bride wore a veil.","example_ka":"პატარძალმა საბურველი დაიხურა.","level":"B1"},
    {"english":"tights","georgian":"კოლგოტი","pronunciation":"/taɪts/","example_en":"She wore black tights.","example_ka":"მან შავი კოლგოტი ჩაიცვა.","level":"A1"},
    {"english":"leggings","georgian":"ლეგინსი","pronunciation":"/ˈleɡɪŋz/","example_en":"Leggings are comfortable.","example_ka":"ლეგინსი მოსახერხებელია.","level":"A1"},
    {"english":"bikini","georgian":"ბიკინი","pronunciation":"/bɪˈkiːni/","example_en":"She wore a bikini.","example_ka":"მან ბიკინი ჩაიცვა.","level":"A1"},
    {"english":"swimsuit","georgian":"საცურაო კოსტიუმი","pronunciation":"/ˈswɪmsuːt/","example_en":"I need a new swimsuit.","example_ka":"ახალი საცურაო კოსტიუმი მჭირდება.","level":"A1"},
    {"english":"tracksuit","georgian":"სპორტული კოსტიუმი","pronunciation":"/ˈtræksuːt/","example_en":"He wears a tracksuit.","example_ka":"ის სპორტულ კოსტიუმს იცვამს.","level":"A1"},
    {"english":"parka","georgian":"პარკა","pronunciation":"/ˈpɑːrkə/","example_en":"A parka is warm.","example_ka":"პარკა თბილია.","level":"A2"},
    {"english":"blazer","georgian":"ბლეიზერი","pronunciation":"/ˈbleɪzər/","example_en":"She wore a navy blazer.","example_ka":"მან მუქი ლურჯი ბლეიზერი ჩაიცვა.","level":"A2"},
    {"english":"tunic","georgian":"ტუნიკა","pronunciation":"/ˈtjuːnɪk/","example_en":"She wore a long tunic.","example_ka":"მან გრძელი ტუნიკა ჩაიცვა.","level":"B1"},
    {"english":"polo shirt","georgian":"პოლო მაისური","pronunciation":"/ˈpoʊloʊ ʃɜːrt/","example_en":"He wore a polo shirt.","example_ka":"მან პოლო მაისური ჩაიცვა.","level":"A1"},
    {"english":"flannel","georgian":"ფლანელი","pronunciation":"/ˈflænl/","example_en":"He wore a flannel shirt.","example_ka":"მან ფლანელის პერანგი ჩაიცვა.","level":"A2"},
    {"english":"kimono","georgian":"კიმონო","pronunciation":"/kɪˈmoʊnoʊ/","example_en":"She wore a kimono.","example_ka":"მან კიმონო ჩაიცვა.","level":"B1"},
    {"english":"shawl","georgian":"შალი","pronunciation":"/ʃɔːl/","example_en":"She wrapped a shawl around her.","example_ka":"მან შალი შემოისხა.","level":"A2"},
    {"english":"bandana","georgian":"ბანდანა","pronunciation":"/bænˈdænə/","example_en":"He wore a bandana.","example_ka":"მან ბანდანა დაიხურა.","level":"A1"},
    {"english":"beanie","georgian":"ქუდი","pronunciation":"/ˈbiːni/","example_en":"Wear a beanie in winter.","example_ka":"ზამთარში ქუდი დაიხურე.","level":"A1"},
    {"english":"fedora","georgian":"ფედორა","pronunciation":"/fɪˈdɔːrə/","example_en":"He wore a fedora.","example_ka":"მან ფედორა დაიხურა.","level":"B1"},
    {"english":"crown","georgian":"გვირგვინი","pronunciation":"/kraʊn/","example_en":"The queen wore a crown.","example_ka":"დედოფალმა გვირგვინი დაიდგა.","level":"A1"},
    {"english":"anklet","georgian":"ტერფსაბამი","pronunciation":"/ˈæŋklɪt/","example_en":"She wore an anklet.","example_ka":"მან ტერფსაბამი ატარებდა.","level":"B1"},
    {"english":"choker","georgian":"ჩოკერი","pronunciation":"/ˈtʃoʊkər/","example_en":"She wore a choker.","example_ka":"მან ჩოკერი ატარებდა.","level":"B1"},
    {"english":"clutch","georgian":"კლაჩი","pronunciation":"/klʌtʃ/","example_en":"She carried a clutch.","example_ka":"მან კლაჩი ატარებდა.","level":"B1"},
    {"english":"tote bag","georgian":"ტოტ ჩანთა","pronunciation":"/toʊt bæɡ/","example_en":"She uses a tote bag.","example_ka":"ის ტოტ ჩანთას იყენებს.","level":"A2"},
    {"english":"satchel","georgian":"სკოლის ჩანთა","pronunciation":"/ˈsætʃəl/","example_en":"He carried a satchel.","example_ka":"მან ჩანთა ატარებდა.","level":"A2"},
    {"english":"briefcase","georgian":"პორტფელი","pronunciation":"/ˈbriːfkeɪs/","example_en":"He carries a briefcase.","example_ka":"ის პორტფელს ატარებს.","level":"A2"},
    {"english":"suitcase","georgian":"ჩემოდანი","pronunciation":"/ˈsuːtkeɪs/","example_en":"I packed my suitcase.","example_ka":"ჩემოდანი ჩავალაგე.","level":"A1"},
    {"english":"luggage","georgian":"ბარგი","pronunciation":"/ˈlʌɡɪdʒ/","example_en":"Don't forget your luggage.","example_ka":"ბარგი არ დაგავიწყდეს.","level":"A1"},
    {"english":"garment","georgian":"სამოსი","pronunciation":"/ˈɡɑːrmənt/","example_en":"This garment is expensive.","example_ka":"ეს სამოსი ძვირია.","level":"B1"},
    {"english":"attire","georgian":"ჩაცმულობა","pronunciation":"/əˈtaɪər/","example_en":"Formal attire is required.","example_ka":"ოფიციალური ჩაცმულობა მოითხოვება.","level":"B1"},
    {"english":"thread","georgian":"ძაფი","pronunciation":"/θred/","example_en":"I need thread and a needle.","example_ka":"ძაფი და ნემსი მჭირდება.","level":"A1"},
    {"english":"needle","georgian":"ნემსი","pronunciation":"/ˈniːdl/","example_en":"She sewed with a needle.","example_ka":"მან ნემსით იკერა.","level":"A1"},
    {"english":"sew","georgian":"კერვა","pronunciation":"/soʊ/","example_en":"She can sew well.","example_ka":"ის კარგად კერავს.","level":"A2"},
    {"english":"knit","georgian":"ქსოვა","pronunciation":"/nɪt/","example_en":"She knits scarves.","example_ka":"ის შარფებს ქსოვს.","level":"A2"},
    {"english":"dye","georgian":"საღებავი","pronunciation":"/daɪ/","example_en":"She dyed the fabric.","example_ka":"მან ქსოვილი შეღება.","level":"B1"},
    {"english":"plaid","georgian":"შოტლანდიური ნიმუში","pronunciation":"/plæd/","example_en":"He wore a plaid shirt.","example_ka":"მან შოტლანდიური პერანგი ჩაიცვა.","level":"A2"},
    {"english":"polka dot","georgian":"წერტილოვანი","pronunciation":"/ˈpoʊlkə dɒt/","example_en":"She wore a polka dot dress.","example_ka":"მან წერტილოვანი კაბა ჩაიცვა.","level":"A2"},
    {"english":"floral","georgian":"ყვავილოვანი","pronunciation":"/ˈflɔːrəl/","example_en":"She loves floral patterns.","example_ka":"ყვავილოვანი ნიმუშები უყვარს.","level":"A2"},
    {"english":"checkered","georgian":"უჯრედებიანი","pronunciation":"/ˈtʃekərd/","example_en":"He wore a checkered shirt.","example_ka":"მან უჯრედებიანი პერანგი ჩაიცვა.","level":"A2"},
    {"english":"plain","georgian":"უბრალო","pronunciation":"/pleɪn/","example_en":"I prefer plain shirts.","example_ka":"უბრალო პერანგებს ვამჯობინებ.","level":"A1"},
    {"english":"stain","georgian":"ლაქა","pronunciation":"/steɪn/","example_en":"There is a stain on my shirt.","example_ka":"პერანგზე ლაქა მაქვს.","level":"A2"},
    {"english":"fold","georgian":"დაკეცვა","pronunciation":"/foʊld/","example_en":"Fold your clothes.","example_ka":"ტანსაცმელი დაკეცე.","level":"A1"},
    {"english":"wrinkle","georgian":"ნაოჭი","pronunciation":"/ˈrɪŋkl/","example_en":"Iron out the wrinkles.","example_ka":"ნაოჭები გაუთოვე.","level":"A2"},
    {"english":"mend","georgian":"შეკეთება","pronunciation":"/mend/","example_en":"She mended the shirt.","example_ka":"მან პერანგი შეაკეთა.","level":"B1"},
    {"english":"hood","georgian":"კაპიუშონი","pronunciation":"/hʊd/","example_en":"Put your hood up.","example_ka":"კაპიუშონი აიწიე.","level":"A1"},
    {"english":"cuff","georgian":"მანჟეტი","pronunciation":"/kʌf/","example_en":"He rolled up his cuffs.","example_ka":"მან მანჟეტები აიკეცა.","level":"A2"},
    {"english":"seam","georgian":"ნაკერი","pronunciation":"/siːm/","example_en":"The seam ripped.","example_ka":"ნაკერი გაიხა.","level":"B1"},
    {"english":"lapel","georgian":"ლაცკანი","pronunciation":"/ləˈpel/","example_en":"He pinned a flower on his lapel.","example_ka":"მან ლაცკანზე ყვავილი მიამაგრა.","level":"B1"},
    {"english":"pleat","georgian":"ნაკეცი","pronunciation":"/pliːt/","example_en":"The skirt has pleats.","example_ka":"ქვედაკაბას ნაკეცები აქვს.","level":"B1"},
    {"english":"buckle","georgian":"ბალთა","pronunciation":"/ˈbʌkl/","example_en":"The belt buckle is silver.","example_ka":"ქამრის ბალთა ვერცხლისფერია.","level":"A2"},
    {"english":"lining","georgian":"საფენი","pronunciation":"/ˈlaɪnɪŋ/","example_en":"The coat has a silk lining.","example_ka":"პალტოს აბრეშუმის საფენი აქვს.","level":"B1"},
    {"english":"ribbon","georgian":"ლენტი","pronunciation":"/ˈrɪbən/","example_en":"She tied a ribbon in her hair.","example_ka":"მან თმაში ლენტი შეიკრა.","level":"A1"},
    {"english":"scissors","georgian":"მაკრატელი","pronunciation":"/ˈsɪzərz/","example_en":"Cut with scissors.","example_ka":"მაკრატლით გაჭერი.","level":"A1"},
    {"english":"pin","georgian":"ქინძისთავა","pronunciation":"/pɪn/","example_en":"Use a pin to hold it.","example_ka":"დასაჭერად ქინძისთავა გამოიყენე.","level":"A1"},
    {"english":"closet","georgian":"კარადა","pronunciation":"/ˈklɒzɪt/","example_en":"My closet is full.","example_ka":"ჩემი კარადა სავსეა.","level":"A1"},
    {"english":"drawer","georgian":"უჯრა","pronunciation":"/drɔːr/","example_en":"Put socks in the drawer.","example_ka":"წინდები უჯრაში ჩადე.","level":"A1"},
    {"english":"mannequin","georgian":"მანეკენი","pronunciation":"/ˈmænɪkɪn/","example_en":"The mannequin displays clothes.","example_ka":"მანეკენზე ტანსაცმელია გამოფენილი.","level":"B1"},
    {"english":"boutique","georgian":"ბუტიკი","pronunciation":"/buːˈtiːk/","example_en":"She shops at a boutique.","example_ka":"ის ბუტიკში ყიდულობს.","level":"B1"},
    {"english":"textile","georgian":"ტექსტილი","pronunciation":"/ˈtekstaɪl/","example_en":"The textile industry is large.","example_ka":"ტექსტილის ინდუსტრია დიდია.","level":"B1"},
    {"english":"couture","georgian":"კუტიურე","pronunciation":"/kuːˈtjʊr/","example_en":"She wore couture.","example_ka":"მან კუტიურე ჩაიცვა.","level":"B1"},
    {"english":"dryer","georgian":"საშრობი","pronunciation":"/ˈdraɪər/","example_en":"Put clothes in the dryer.","example_ka":"ტანსაცმელი საშრობში ჩადე.","level":"A1"},
    {"english":"detergent","georgian":"სარეცხი საშუალება","pronunciation":"/dɪˈtɜːrdʒənt/","example_en":"Use mild detergent.","example_ka":"რბილი სარეცხი საშუალება გამოიყენე.","level":"A2"},
    {"english":"bleach","georgian":"გაუფერულება","pronunciation":"/bliːtʃ/","example_en":"Don't bleach colored clothes.","example_ka":"ფერად ტანსაცმელს არ გაუფერულო.","level":"B1"},
    {"english":"shrink","georgian":"შეკუმშვა","pronunciation":"/ʃrɪŋk/","example_en":"This may shrink in wash.","example_ka":"ეს რეცხვისას შეიძლება შეიკუმშოს.","level":"B1"},
    {"english":"fade","georgian":"გაფერმკრთალება","pronunciation":"/feɪd/","example_en":"The color will fade.","example_ka":"ფერი გაფერმკრთალდება.","level":"B1"},
    {"english":"elastic","georgian":"რეზინი","pronunciation":"/ɪˈlæstɪk/","example_en":"The band has elastic.","example_ka":"ზოლს რეზინი აქვს.","level":"A2"},
    {"english":"velcro","georgian":"ველკრო","pronunciation":"/ˈvelkroʊ/","example_en":"Shoes with velcro are easy.","example_ka":"ველკროიანი ფეხსაცმელი ადვილია.","level":"A2"},
    {"english":"patch","georgian":"ლატა","pronunciation":"/pætʃ/","example_en":"She sewed a patch.","example_ka":"მან ლატა მიაკერა.","level":"A2"},
    {"english":"snap","georgian":"კნოპი","pronunciation":"/snæp/","example_en":"The jacket has snaps.","example_ka":"ქურთუკს კნოპები აქვს.","level":"A2"},
    {"english":"cufflink","georgian":"მანჟეტის ღილი","pronunciation":"/ˈkʌflɪŋk/","example_en":"He wore gold cufflinks.","example_ka":"მან ოქროს მანჟეტის ღილები ატარებდა.","level":"B1"},
    {"english":"tiara","georgian":"ტიარა","pronunciation":"/tiˈɑːrə/","example_en":"The princess wore a tiara.","example_ka":"პრინცესამ ტიარა დაიხურა.","level":"B1"},
    {"english":"turban","georgian":"ჩალმა","pronunciation":"/ˈtɜːrbən/","example_en":"He wears a turban.","example_ka":"ის ჩალმას ატარებს.","level":"B1"},
    {"english":"stockings","georgian":"წუღები","pronunciation":"/ˈstɒkɪŋz/","example_en":"She wore silk stockings.","example_ka":"მან აბრეშუმის წუღები ჩაიცვა.","level":"A2"},
    {"english":"mittens","georgian":"თბილი ხელთათმანები","pronunciation":"/ˈmɪtənz/","example_en":"Children wear mittens.","example_ka":"ბავშვები ხელთათმანებს იცვამენ.","level":"A1"},
    {"english":"crop top","georgian":"მოკლე მაისური","pronunciation":"/krɒp tɒp/","example_en":"She wore a crop top.","example_ka":"მან მოკლე მაისური ჩაიცვა.","level":"A1"},
    {"english":"tank top","georgian":"უსახელო მაისური","pronunciation":"/tæŋk tɒp/","example_en":"He wore a tank top.","example_ka":"მან უსახელო მაისური ჩაიცვა.","level":"A1"},
    {"english":"windbreaker","georgian":"ქარსაწინააღმდეგო ქურთუკი","pronunciation":"/ˈwɪndbreɪkər/","example_en":"Wear a windbreaker.","example_ka":"ქარსაწინააღმდეგო ქურთუკი ჩაიცვი.","level":"A2"},
    {"english":"anorak","georgian":"ანორაკი","pronunciation":"/ˈænəræk/","example_en":"He wore an anorak.","example_ka":"მან ანორაკი ჩაიცვა.","level":"B1"},
    {"english":"corset","georgian":"კორსეტი","pronunciation":"/ˈkɔːrsɪt/","example_en":"Corsets were once popular.","example_ka":"კორსეტი ოდესღაც პოპულარული იყო.","level":"B1"},
    {"english":"toga","georgian":"ტოგა","pronunciation":"/ˈtoʊɡə/","example_en":"Romans wore togas.","example_ka":"რომაელები ტოგას ატარებდნენ.","level":"B1"},
    {"english":"kaftan","georgian":"ყაფთანი","pronunciation":"/ˈkæftæn/","example_en":"She wore a kaftan.","example_ka":"მან ყაფთანი ჩაიცვა.","level":"B1"},
    {"english":"sarong","georgian":"სარონგი","pronunciation":"/səˈrɒŋ/","example_en":"She wore a sarong.","example_ka":"მან სარონგი ჩაიცვა.","level":"B1"},
    {"english":"bonnet","georgian":"ჩეპიხი","pronunciation":"/ˈbɒnɪt/","example_en":"The baby wore a bonnet.","example_ka":"ჩვილს ჩეპიხი ეხურა.","level":"B1"},
    {"english":"visor","georgian":"მზისფარი","pronunciation":"/ˈvaɪzər/","example_en":"She wore a visor.","example_ka":"მან მზისფარი დაიხურა.","level":"A2"},
    {"english":"fanny pack","georgian":"წელის ჩანთა","pronunciation":"/ˈfæni pæk/","example_en":"He wore a fanny pack.","example_ka":"მან წელის ჩანთა ატარებდა.","level":"A1"},
    {"english":"hamper","georgian":"სარეცხის კალათა","pronunciation":"/ˈhæmpər/","example_en":"Put dirty clothes in the hamper.","example_ka":"ბინძური ტანსაცმელი სარეცხის კალათაში ჩადე.","level":"A2"},
    {"english":"clothesline","georgian":"საშრობი თოკი","pronunciation":"/ˈkloʊðzlaɪn/","example_en":"Hang clothes on the clothesline.","example_ka":"ტანსაცმელი საშრობ თოკზე გაფინე.","level":"A1"},
    {"english":"thimble","georgian":"თითსაცმელი","pronunciation":"/ˈθɪmbl/","example_en":"Use a thimble when sewing.","example_ka":"კერვისას თითსაცმელი გამოიყენე.","level":"B1"},
    {"english":"tape measure","georgian":"სანტიმეტრი","pronunciation":"/teɪp ˈmeʒər/","example_en":"Use a tape measure.","example_ka":"სანტიმეტრი გამოიყენე.","level":"A2"},
    {"english":"fitting","georgian":"მორგება","pronunciation":"/ˈfɪtɪŋ/","example_en":"I have a fitting today.","example_ka":"დღეს მორგება მაქვს.","level":"B1"},
    {"english":"alteration","georgian":"გადაკეთება","pronunciation":"/ˌɔːltəˈreɪʃn/","example_en":"The dress needs alterations.","example_ka":"კაბას გადაკეთება სჭირდება.","level":"B1"},
    {"english":"sequin","georgian":"პულეტი","pronunciation":"/ˈsiːkwɪn/","example_en":"The dress has sequins.","example_ka":"კაბას პულეტები აქვს.","level":"B1"},
    {"english":"fringe","georgian":"ფარფლი","pronunciation":"/frɪndʒ/","example_en":"The scarf has fringe.","example_ka":"შარფს ფარფლი აქვს.","level":"B1"},
    {"english":"tassel","georgian":"ფუნჯი","pronunciation":"/ˈtæsl/","example_en":"The curtain has tassels.","example_ka":"ფარდას ფუნჯები აქვს.","level":"B1"},
    {"english":"ruffle","georgian":"ქარვასლა","pronunciation":"/ˈrʌfl/","example_en":"The dress has ruffles.","example_ka":"კაბას ქარვასლები აქვს.","level":"B1"},
    {"english":"drawstring","georgian":"თასმა","pronunciation":"/ˈdrɔːstrɪŋ/","example_en":"Pull the drawstring.","example_ka":"თასმა გაიწიე.","level":"A2"},
    {"english":"clasp","georgian":"საკეტი","pronunciation":"/klæsp/","example_en":"The clasp is broken.","example_ka":"საკეტი გატეხილია.","level":"B1"},
    {"english":"spandex","georgian":"სპანდექსი","pronunciation":"/ˈspændeks/","example_en":"Spandex is stretchy.","example_ka":"სპანდექსი ელასტიურია.","level":"B1"},
    {"english":"crease","georgian":"ნაოჭი","pronunciation":"/kriːs/","example_en":"Iron the crease.","example_ka":"ნაოჭი გაუთოვე.","level":"B1"},
    {"english":"mothball","georgian":"ნაფტალინი","pronunciation":"/ˈmɒθbɔːl/","example_en":"Use mothballs for wool.","example_ka":"მატყლისთვის ნაფტალინი გამოიყენე.","level":"B1"},
    {"english":"bobbin","georgian":"ძეწკვი","pronunciation":"/ˈbɒbɪn/","example_en":"Put thread on the bobbin.","example_ka":"ძაფი ძეწკვზე გადაახვიე.","level":"B1"},
    {"english":"measurement","georgian":"გაზომვა","pronunciation":"/ˈmeʒərmənt/","example_en":"Take your measurements.","example_ka":"გაზომვები გააკეთე.","level":"A2"},
    {"english":"apparel","georgian":"ტანსაცმელი","pronunciation":"/əˈpærəl/","example_en":"This store sells apparel.","example_ka":"ეს მაღაზია ტანსაცმელს ყიდის.","level":"B1"},
    {"english":"dungarees","georgian":"კომბინეზონი","pronunciation":"/ˌdʌŋɡəˈriːz/","example_en":"She wore dungarees.","example_ka":"მან კომბინეზონი ჩაიცვა.","level":"B1"},
    {"english":"camisole","georgian":"კამიზოლი","pronunciation":"/ˈkæmɪsoʊl/","example_en":"She wore a camisole.","example_ka":"მან კამიზოლი ჩაიცვა.","level":"B1"},
    {"english":"waistcoat","georgian":"ჟილეტი","pronunciation":"/ˈweɪskoʊt/","example_en":"He wore a waistcoat.","example_ka":"მან ჟილეტი ჩაიცვა.","level":"B1"},
    {"english":"stole","georgian":"სტოლა","pronunciation":"/stoʊl/","example_en":"She wore a fur stole.","example_ka":"მან ბეწვის სტოლა ატარებდა.","level":"B1"},
]

# colors-shapes.json new entries
colors_new = [
    {"english":"beige","georgian":"ბეჟი","pronunciation":"/beɪʒ/","example_en":"The walls are beige.","example_ka":"კედლები ბეჟია.","level":"beginner"},
    {"english":"turquoise","georgian":"ფირუზისფერი","pronunciation":"/ˈtɜːrkwɔɪz/","example_en":"She wore a turquoise necklace.","example_ka":"მან ფირუზისფერი ყელსაბამი ატარებდა.","level":"intermediate"},
    {"english":"maroon","georgian":"წაბლისფერი","pronunciation":"/məˈruːn/","example_en":"He wore a maroon shirt.","example_ka":"მან წაბლისფერი პერანგი ჩაიცვა.","level":"intermediate"},
    {"english":"navy","georgian":"მუქი ლურჯი","pronunciation":"/ˈneɪvi/","example_en":"She wore a navy dress.","example_ka":"მან მუქი ლურჯი კაბა ჩაიცვა.","level":"beginner"},
    {"english":"cream","georgian":"კრემისფერი","pronunciation":"/kriːm/","example_en":"The curtains are cream colored.","example_ka":"ფარდები კრემისფერია.","level":"beginner"},
    {"english":"coral","georgian":"მარჯნისფერი","pronunciation":"/ˈkɒrəl/","example_en":"She painted her nails coral.","example_ka":"მან ფრჩხილები მარჯნისფრად შეიღება.","level":"intermediate"},
    {"english":"crimson","georgian":"ალისფერი","pronunciation":"/ˈkrɪmzn/","example_en":"The sunset was crimson.","example_ka":"მზის ჩასვლა ალისფერი იყო.","level":"intermediate"},
    {"english":"scarlet","georgian":"ჟოლოსფერი","pronunciation":"/ˈskɑːrlɪt/","example_en":"She wore a scarlet dress.","example_ka":"მან ჟოლოსფერი კაბა ჩაიცვა.","level":"intermediate"},
    {"english":"olive","georgian":"ზეთისხილისფერი","pronunciation":"/ˈɒlɪv/","example_en":"He wore olive green pants.","example_ka":"მან ზეთისხილისფერი შარვალი ჩაიცვა.","level":"intermediate"},
    {"english":"teal","georgian":"ჩაისფერი","pronunciation":"/tiːl/","example_en":"The bathroom is teal.","example_ka":"აბაზანა ჩაისფერია.","level":"intermediate"},
    {"english":"ivory","georgian":"სპილოს ძვლისფერი","pronunciation":"/ˈaɪvəri/","example_en":"The wedding dress was ivory.","example_ka":"საქორწილო კაბა სპილოს ძვლისფერი იყო.","level":"intermediate"},
    {"english":"tan","georgian":"რუხი ყავისფერი","pronunciation":"/tæn/","example_en":"He has tan shoes.","example_ka":"მას რუხი ყავისფერი ფეხსაცმელი აქვს.","level":"beginner"},
    {"english":"khaki","georgian":"ხაკისფერი","pronunciation":"/ˈkɑːki/","example_en":"He wore khaki pants.","example_ka":"მან ხაკისფერი შარვალი ჩაიცვა.","level":"beginner"},
    {"english":"magenta","georgian":"მაგენტა","pronunciation":"/məˈdʒentə/","example_en":"The flower is magenta.","example_ka":"ყვავილი მაგენტაა.","level":"intermediate"},
    {"english":"lavender","georgian":"ლავანდისფერი","pronunciation":"/ˈlævəndər/","example_en":"She painted the room lavender.","example_ka":"მან ოთახი ლავანდისფრად შეღება.","level":"intermediate"},
    {"english":"indigo","georgian":"ინდიგო","pronunciation":"/ˈɪndɪɡoʊ/","example_en":"The sky turned indigo at dusk.","example_ka":"მიბინდისას ცა ინდიგოსფერი გახდა.","level":"intermediate"},
    {"english":"aqua","georgian":"აკვამარინი","pronunciation":"/ˈækwə/","example_en":"The pool water is aqua.","example_ka":"აუზის წყალი აკვამარინისფერია.","level":"intermediate"},
    {"english":"peach","georgian":"ატმისფერი","pronunciation":"/piːtʃ/","example_en":"She wore a peach blouse.","example_ka":"მან ატმისფერი ბლუზა ჩაიცვა.","level":"beginner"},
    {"english":"mint","georgian":"პიტნისფერი","pronunciation":"/mɪnt/","example_en":"The room is mint green.","example_ka":"ოთახი პიტნისფერი მწვანეა.","level":"beginner"},
    {"english":"rust","georgian":"ჟანგისფერი","pronunciation":"/rʌst/","example_en":"She wore a rust colored jacket.","example_ka":"მან ჟანგისფერი ქურთუკი ჩაიცვა.","level":"intermediate"},
    {"english":"charcoal","georgian":"ნახშირისფერი","pronunciation":"/ˈtʃɑːrkoʊl/","example_en":"He wore a charcoal suit.","example_ka":"მან ნახშირისფერი კოსტიუმი ჩაიცვა.","level":"intermediate"},
    {"english":"plum","georgian":"ქლიავისფერი","pronunciation":"/plʌm/","example_en":"She wore a plum dress.","example_ka":"მან ქლიავისფერი კაბა ჩაიცვა.","level":"intermediate"},
    {"english":"burgundy","georgian":"ბორდოსფერი","pronunciation":"/ˈbɜːrɡəndi/","example_en":"He wore a burgundy tie.","example_ka":"მან ბორდოსფერი ჰალსტუხი ჩაიკეთა.","level":"intermediate"},
    {"english":"cyan","georgian":"ცისფერი","pronunciation":"/ˈsaɪæn/","example_en":"The printer needs cyan ink.","example_ka":"პრინტერს ცისფერი მელანი სჭირდება.","level":"intermediate"},
    {"english":"amber","georgian":"ქარვისფერი","pronunciation":"/ˈæmbər/","example_en":"The traffic light turned amber.","example_ka":"შუქნიშანი ქარვისფერი გახდა.","level":"intermediate"},
    {"english":"bronze","georgian":"ბრინჯაოსფერი","pronunciation":"/brɒnz/","example_en":"She won a bronze medal.","example_ka":"მან ბრინჯაოს მედალი მოიგო.","level":"beginner"},
    {"english":"copper","georgian":"სპილენძისფერი","pronunciation":"/ˈkɒpər/","example_en":"Her hair is copper colored.","example_ka":"მისი თმა სპილენძისფერია.","level":"intermediate"},
    {"english":"sapphire","georgian":"საფირონისფერი","pronunciation":"/ˈsæfaɪər/","example_en":"She has sapphire blue eyes.","example_ka":"მას საფირონისფერი ლურჯი თვალები აქვს.","level":"intermediate"},
    {"english":"emerald","georgian":"ზურმუხტისფერი","pronunciation":"/ˈemərəld/","example_en":"The lake is emerald green.","example_ka":"ტბა ზურმუხტისფერი მწვანეა.","level":"intermediate"},
    {"english":"ruby","georgian":"ლალისფერი","pronunciation":"/ˈruːbi/","example_en":"She wore ruby red lipstick.","example_ka":"მან ლალისფერი წითელი პომადა წაისვა.","level":"intermediate"},
    {"english":"dull","georgian":"მქრქალი","pronunciation":"/dʌl/","example_en":"The color looks dull.","example_ka":"ფერი მქრქალად გამოიყურება.","level":"beginner"},
    {"english":"vivid","georgian":"მკვეთრი","pronunciation":"/ˈvɪvɪd/","example_en":"The painting has vivid colors.","example_ka":"ნახატს მკვეთრი ფერები აქვს.","level":"intermediate"},
    {"english":"faded","georgian":"გაფერმკრთალებული","pronunciation":"/ˈfeɪdɪd/","example_en":"The jeans are faded.","example_ka":"ჯინსი გაფერმკრთალებულია.","level":"beginner"},
    {"english":"pale","georgian":"ფერმკრთალი","pronunciation":"/peɪl/","example_en":"She has pale skin.","example_ka":"მას ფერმკრთალი კანი აქვს.","level":"beginner"},
    {"english":"transparent","georgian":"გამჭვირვალე","pronunciation":"/trænsˈpærənt/","example_en":"The glass is transparent.","example_ka":"მინა გამჭვირვალეა.","level":"beginner"},
    {"english":"opaque","georgian":"გაუმჭვირვალე","pronunciation":"/oʊˈpeɪk/","example_en":"The curtain is opaque.","example_ka":"ფარდა გაუმჭვირვალეა.","level":"intermediate"},
    {"english":"matte","georgian":"მატი","pronunciation":"/mæt/","example_en":"I prefer matte finish.","example_ka":"მატი დამუშავება მირჩევნია.","level":"intermediate"},
    {"english":"glossy","georgian":"პრიალა","pronunciation":"/ˈɡlɒsi/","example_en":"The photo has a glossy finish.","example_ka":"ფოტოს პრიალა დამუშავება აქვს.","level":"intermediate"},
    {"english":"shiny","georgian":"ბრწყინვალე","pronunciation":"/ˈʃaɪni/","example_en":"The car is shiny.","example_ka":"მანქანა ბრწყინვალეა.","level":"beginner"},
    {"english":"metallic","georgian":"მეტალური","pronunciation":"/məˈtælɪk/","example_en":"She has a metallic phone case.","example_ka":"მას მეტალური ტელეფონის ქეისი აქვს.","level":"intermediate"},
    {"english":"neon","georgian":"ნეონისფერი","pronunciation":"/ˈniːɒn/","example_en":"She wore neon green shoes.","example_ka":"მან ნეონისფერი მწვანე ფეხსაცმელი ჩაიცვა.","level":"beginner"},
    {"english":"pastel","georgian":"პასტელური","pronunciation":"/pæˈstel/","example_en":"She likes pastel colors.","example_ka":"მას პასტელური ფერები მოსწონს.","level":"intermediate"},
    {"english":"multicolored","georgian":"მრავალფერი","pronunciation":"/ˌmʌltiˈkʌlərd/","example_en":"The rainbow is multicolored.","example_ka":"ცისარტყელა მრავალფერია.","level":"beginner"},
    {"english":"monochrome","georgian":"ერთფეროვანი","pronunciation":"/ˈmɒnəkroʊm/","example_en":"The photo is monochrome.","example_ka":"ფოტო ერთფეროვანია.","level":"intermediate"},
    {"english":"shade","georgian":"ტონი","pronunciation":"/ʃeɪd/","example_en":"I like this shade of blue.","example_ka":"ლურჯის ეს ტონი მომწონს.","level":"beginner"},
    {"english":"hue","georgian":"ელფერი","pronunciation":"/hjuː/","example_en":"The sunset has a warm hue.","example_ka":"მზის ჩასვლას თბილი ელფერი აქვს.","level":"intermediate"},
    {"english":"tint","georgian":"შეფერილობა","pronunciation":"/tɪnt/","example_en":"The glass has a green tint.","example_ka":"მინას მწვანე შეფერილობა აქვს.","level":"intermediate"},
    {"english":"tone","georgian":"ტონი","pronunciation":"/toʊn/","example_en":"Choose a warm tone for the room.","example_ka":"ოთახისთვის თბილი ტონი აირჩიე.","level":"beginner"},
    {"english":"spectrum","georgian":"სპექტრი","pronunciation":"/ˈspektrəm/","example_en":"The rainbow shows the color spectrum.","example_ka":"ცისარტყელა ფერის სპექტრს აჩვენებს.","level":"intermediate"},
    {"english":"pigment","georgian":"პიგმენტი","pronunciation":"/ˈpɪɡmənt/","example_en":"This pigment is natural.","example_ka":"ეს პიგმენტი ბუნებრივია.","level":"intermediate"},
    {"english":"pentagon","georgian":"ხუთკუთხედი","pronunciation":"/ˈpentəɡɒn/","example_en":"A pentagon has five sides.","example_ka":"ხუთკუთხედს ხუთი გვერდი აქვს.","level":"beginner"},
    {"english":"hexagon","georgian":"ექვსკუთხედი","pronunciation":"/ˈheksəɡɒn/","example_en":"A hexagon has six sides.","example_ka":"ექვსკუთხედს ექვსი გვერდი აქვს.","level":"beginner"},
    {"english":"octagon","georgian":"რვაკუთხედი","pronunciation":"/ˈɒktəɡɒn/","example_en":"A stop sign is an octagon.","example_ka":"გაჩერების ნიშანი რვაკუთხედია.","level":"beginner"},
    {"english":"sphere","georgian":"სფერო","pronunciation":"/sfɪər/","example_en":"The earth is a sphere.","example_ka":"დედამიწა სფეროა.","level":"beginner"},
    {"english":"cube","georgian":"კუბი","pronunciation":"/kjuːb/","example_en":"An ice cube melted.","example_ka":"ყინულის კუბი დადნა.","level":"beginner"},
    {"english":"cone","georgian":"კონუსი","pronunciation":"/koʊn/","example_en":"The ice cream is in a cone.","example_ka":"ნაყინი კონუსშია.","level":"beginner"},
    {"english":"cylinder","georgian":"ცილინდრი","pronunciation":"/ˈsɪlɪndər/","example_en":"The can is a cylinder.","example_ka":"ქილა ცილინდრია.","level":"beginner"},
    {"english":"pyramid","georgian":"პირამიდა","pronunciation":"/ˈpɪrəmɪd/","example_en":"The pyramid has a square base.","example_ka":"პირამიდას კვადრატული ფუძე აქვს.","level":"beginner"},
    {"english":"prism","georgian":"პრიზმა","pronunciation":"/ˈprɪzm/","example_en":"Light passes through a prism.","example_ka":"შუქი პრიზმაში გადის.","level":"intermediate"},
    {"english":"crescent","georgian":"ნახევარმთვარე","pronunciation":"/ˈkresənt/","example_en":"The moon is a crescent tonight.","example_ka":"დღეს მთვარე ნახევარმთვარეა.","level":"beginner"},
    {"english":"cross","georgian":"ჯვარი","pronunciation":"/krɒs/","example_en":"Draw a cross on the paper.","example_ka":"ფურცელზე ჯვარი დახატე.","level":"beginner"},
    {"english":"arrow","georgian":"ისარი","pronunciation":"/ˈæroʊ/","example_en":"Follow the arrow sign.","example_ka":"ისრის ნიშანს მიჰყევი.","level":"beginner"},
    {"english":"spiral","georgian":"სპირალი","pronunciation":"/ˈspaɪrəl/","example_en":"The staircase is a spiral.","example_ka":"კიბე სპირალურია.","level":"beginner"},
    {"english":"zigzag","georgian":"ზიგზაგი","pronunciation":"/ˈzɪɡzæɡ/","example_en":"The road goes in a zigzag.","example_ka":"გზა ზიგზაგით მიდის.","level":"beginner"},
    {"english":"arc","georgian":"რკალი","pronunciation":"/ɑːrk/","example_en":"The rainbow forms an arc.","example_ka":"ცისარტყელა რკალს ქმნის.","level":"beginner"},
    {"english":"angle","georgian":"კუთხე","pronunciation":"/ˈæŋɡl/","example_en":"A right angle is 90 degrees.","example_ka":"მართი კუთხე 90 გრადუსია.","level":"beginner"},
    {"english":"parallel","georgian":"პარალელური","pronunciation":"/ˈpærəlel/","example_en":"The lines are parallel.","example_ka":"ხაზები პარალელურია.","level":"beginner"},
    {"english":"perpendicular","georgian":"მართობული","pronunciation":"/ˌpɜːrpənˈdɪkjələr/","example_en":"The lines are perpendicular.","example_ka":"ხაზები მართობულია.","level":"intermediate"},
    {"english":"diagonal","georgian":"დიაგონალი","pronunciation":"/daɪˈæɡənl/","example_en":"Draw a diagonal line.","example_ka":"დიაგონალური ხაზი გავლე.","level":"beginner"},
    {"english":"horizontal","georgian":"ჰორიზონტალური","pronunciation":"/ˌhɒrɪˈzɒntl/","example_en":"The line is horizontal.","example_ka":"ხაზი ჰორიზონტალურია.","level":"beginner"},
    {"english":"vertical","georgian":"ვერტიკალური","pronunciation":"/ˈvɜːrtɪkl/","example_en":"The line is vertical.","example_ka":"ხაზი ვერტიკალურია.","level":"beginner"},
    {"english":"symmetry","georgian":"სიმეტრია","pronunciation":"/ˈsɪmɪtri/","example_en":"The building has perfect symmetry.","example_ka":"შენობას იდეალური სიმეტრია აქვს.","level":"intermediate"},
    {"english":"asymmetry","georgian":"ასიმეტრია","pronunciation":"/eɪˈsɪmɪtri/","example_en":"The design uses asymmetry.","example_ka":"დიზაინი ასიმეტრიას იყენებს.","level":"intermediate"},
    {"english":"pattern","georgian":"ნიმუში","pronunciation":"/ˈpætərn/","example_en":"I like this pattern.","example_ka":"ეს ნიმუში მომწონს.","level":"beginner"},
    {"english":"solid","georgian":"მყარი","pronunciation":"/ˈsɒlɪd/","example_en":"Ice is solid water.","example_ka":"ყინული მყარი წყალია.","level":"beginner"},
    {"english":"hollow","georgian":"ღრუ","pronunciation":"/ˈhɒloʊ/","example_en":"The tree trunk is hollow.","example_ka":"ხის ტანი ღრუა.","level":"beginner"},
    {"english":"edge","Georgian":"კიდე","pronunciation":"/edʒ/","example_en":"Be careful near the edge.","example_ka":"კიდესთან ფრთხილად იყავი.","level":"beginner"},
    {"english":"corner","georgian":"კუთხე","pronunciation":"/ˈkɔːrnər/","example_en":"The shop is on the corner.","example_ka":"მაღაზია კუთხეშია.","level":"beginner"},
    {"english":"surface","georgian":"ზედაპირი","pronunciation":"/ˈsɜːrfɪs/","example_en":"The surface is smooth.","example_ka":"ზედაპირი გლუვია.","level":"beginner"},
    {"english":"border","georgian":"საზღვარი","pronunciation":"/ˈbɔːrdər/","example_en":"Draw a border around the picture.","example_ka":"სურათის ირგვლივ საზღვარი დახატე.","level":"beginner"},
    {"english":"outline","georgian":"მონახაზი","pronunciation":"/ˈaʊtlaɪn/","example_en":"Draw the outline first.","example_ka":"ჯერ მონახაზი დახატე.","level":"beginner"},
    {"english":"silhouette","georgian":"სილუეტი","pronunciation":"/ˌsɪluˈet/","example_en":"I saw her silhouette.","example_ka":"მისი სილუეტი დავინახე.","level":"intermediate"},
    {"english":"shadow","georgian":"ჩრდილი","pronunciation":"/ˈʃædoʊ/","example_en":"The tree casts a shadow.","example_ka":"ხე ჩრდილს ქმნის.","level":"beginner"},
    {"english":"reflection","georgian":"ანარეკლი","pronunciation":"/rɪˈflekʃn/","example_en":"I see my reflection in the water.","example_ka":"წყალში ჩემს ანარეკლს ვხედავ.","level":"beginner"},
    {"english":"dimension","georgian":"განზომილება","pronunciation":"/dɪˈmenʃn/","example_en":"This has three dimensions.","example_ka":"ამას სამი განზომილება აქვს.","level":"intermediate"},
    {"english":"radius","georgian":"რადიუსი","pronunciation":"/ˈreɪdiəs/","example_en":"The radius of the circle is five.","example_ka":"წრის რადიუსი ხუთია.","level":"intermediate"},
    {"english":"diameter","georgian":"დიამეტრი","pronunciation":"/daɪˈæmɪtər/","example_en":"The diameter is ten centimeters.","example_ka":"დიამეტრი ათი სანტიმეტრია.","level":"intermediate"},
    {"english":"circumference","georgian":"წრეწირი","pronunciation":"/sərˈkʌmfərəns/","example_en":"Calculate the circumference.","example_ka":"წრეწირი გამოთვალე.","level":"intermediate"},
    {"english":"area","georgian":"ფართობი","pronunciation":"/ˈeəriə/","example_en":"Calculate the area of the square.","example_ka":"კვადრატის ფართობი გამოთვალე.","level":"beginner"},
    {"english":"volume","georgian":"მოცულობა","pronunciation":"/ˈvɒljuːm/","example_en":"Calculate the volume of the box.","example_ka":"ყუთის მოცულობა გამოთვალე.","level":"beginner"},
    {"english":"perimeter","georgian":"პერიმეტრი","pronunciation":"/pəˈrɪmɪtər/","example_en":"Walk around the perimeter.","example_ka":"პერიმეტრის გარშემო იარე.","level":"intermediate"},
    {"english":"polygon","georgian":"მრავალკუთხედი","pronunciation":"/ˈpɒlɪɡɒn/","example_en":"A polygon has many sides.","example_ka":"მრავალკუთხედს ბევრი გვერდი აქვს.","level":"intermediate"},
    {"english":"trapezoid","georgian":"ტრაპეცია","pronunciation":"/ˈtræpɪzɔɪd/","example_en":"A trapezoid has four sides.","example_ka":"ტრაპეციას ოთხი გვერდი აქვს.","level":"intermediate"},
    {"english":"parallelogram","georgian":"პარალელოგრამი","pronunciation":"/ˌpærəˈleləɡræm/","example_en":"A parallelogram has parallel sides.","example_ka":"პარალელოგრამს პარალელური გვერდები აქვს.","level":"intermediate"},
    {"english":"ellipse","georgian":"ელიფსი","pronunciation":"/ɪˈlɪps/","example_en":"The orbit is an ellipse.","example_ka":"ორბიტა ელიფსია.","level":"intermediate"},
    {"english":"semicircle","georgian":"ნახევარწრე","pronunciation":"/ˈsemisɜːrkl/","example_en":"The arch is a semicircle.","example_ka":"თაღი ნახევარწრეა.","level":"beginner"},
    {"english":"rhombus","georgian":"რომბი","pronunciation":"/ˈrɒmbəs/","example_en":"A rhombus has equal sides.","example_ka":"რომბს თანაბარი გვერდები აქვს.","level":"intermediate"},
    {"english":"vertex","georgian":"წვერო","pronunciation":"/ˈvɜːrteks/","example_en":"A triangle has three vertices.","example_ka":"სამკუთხედს სამი წვერო აქვს.","level":"intermediate"},
    {"english":"ray","georgian":"სხივი","pronunciation":"/reɪ/","example_en":"A ray of light entered the room.","example_ka":"სინათლის სხივი ოთახში შემოვიდა.","level":"beginner"},
    {"english":"segment","georgian":"მონაკვეთი","pronunciation":"/ˈseɡmənt/","example_en":"Draw a line segment.","example_ka":"ხაზის მონაკვეთი დახატე.","level":"intermediate"},
    {"english":"point","georgian":"წერტილი","pronunciation":"/pɔɪnt/","example_en":"Mark the point on the map.","example_ka":"რუკაზე წერტილი მონიშნე.","level":"beginner"},
    {"english":"grid","georgian":"ბადე","pronunciation":"/ɡrɪd/","example_en":"Draw a grid on the paper.","example_ka":"ფურცელზე ბადე დახატე.","level":"beginner"},
    {"english":"tile","georgian":"ფილა","pronunciation":"/taɪl/","example_en":"The floor has square tiles.","example_ka":"იატაკზე კვადრატული ფილაა.","level":"beginner"},
    {"english":"mosaic","georgian":"მოზაიკა","pronunciation":"/moʊˈzeɪɪk/","example_en":"The wall has a beautiful mosaic.","example_ka":"კედელზე ლამაზი მოზაიკაა.","level":"intermediate"},
    {"english":"fractal","georgian":"ფრაქტალი","pronunciation":"/ˈfræktl/","example_en":"Snowflakes are fractals.","example_ka":"ფიფქები ფრაქტალებია.","level":"intermediate"},
    {"english":"contour","Georgian":"კონტური","pronunciation":"/ˈkɒntʊr/","example_en":"Follow the contour of the hill.","example_ka":"მთის კონტურს მიჰყევი.","level":"intermediate"},
    {"english":"stretch","georgian":"გაჭიმვა","pronunciation":"/stretʃ/","example_en":"Stretch the fabric.","example_ka":"ქსოვილი გაჭიმე.","level":"beginner"},
    {"english":"bend","georgian":"მოხრა","pronunciation":"/bend/","example_en":"Bend the wire carefully.","example_ka":"მავთული ფრთხილად მოხარე.","level":"beginner"},
    {"english":"twist","georgian":"გრეხა","pronunciation":"/twɪst/","example_en":"Twist the rope tightly.","example_ka":"თოკი მაგრად დაგრიხე.","level":"beginner"},
    {"english":"fold","georgian":"დაკეცვა","pronunciation":"/foʊld/","example_en":"Fold the paper in half.","example_ka":"ქაღალდი შუაზე დაკეცე.","level":"beginner"},
    {"english":"stack","georgian":"დაწყობა","pronunciation":"/stæk/","example_en":"Stack the boxes neatly.","example_ka":"ყუთები ლამაზად დააწყე.","level":"beginner"},
    {"english":"arrange","georgian":"მოწყობა","pronunciation":"/əˈreɪndʒ/","example_en":"Arrange the flowers in a circle.","example_ka":"ყვავილები წრეში მოაწყვე.","level":"beginner"},
    {"english":"align","georgian":"გასწორება","pronunciation":"/əˈlaɪn/","example_en":"Align the text to the left.","example_ka":"ტექსტი მარცხნივ გაასწორე.","level":"intermediate"},
    {"english":"rotate","georgian":"ბრუნვა","pronunciation":"/ˈroʊteɪt/","example_en":"Rotate the image 90 degrees.","example_ka":"სურათი 90 გრადუსით შეაბრუნე.","level":"intermediate"},
    {"english":"flip","georgian":"გადაბრუნება","pronunciation":"/flɪp/","example_en":"Flip the card over.","example_ka":"ბარათი გადააბრუნე.","level":"beginner"},
    {"english":"scale","georgian":"მასშტაბი","pronunciation":"/skeɪl/","example_en":"The map has a scale.","example_ka":"რუკას მასშტაბი აქვს.","level":"beginner"},
    {"english":"proportion","georgian":"პროპორცია","pronunciation":"/prəˈpɔːrʃn/","example_en":"The proportions are perfect.","example_ka":"პროპორციები იდეალურია.","level":"intermediate"},
    {"english":"size","georgian":"ზომა","pronunciation":"/saɪz/","example_en":"What size is the box?","example_ka":"ყუთის ზომა რაა?","level":"beginner"},
    {"english":"shape","georgian":"ფორმა","pronunciation":"/ʃeɪp/","example_en":"What shape is this?","example_ka":"ეს რა ფორმისაა?","level":"beginner"},
    {"english":"form","georgian":"ფორმა","pronunciation":"/fɔːrm/","example_en":"The building has an unusual form.","example_ka":"შენობას უჩვეულო ფორმა აქვს.","level":"beginner"},
    {"english":"figure","georgian":"ფიგურა","pronunciation":"/ˈfɪɡjər/","example_en":"Draw a geometric figure.","example_ka":"გეომეტრიული ფიგურა დახატე.","level":"beginner"},
    {"english":"design","georgian":"დიზაინი","pronunciation":"/dɪˈzaɪn/","example_en":"I like the design of this building.","example_ka":"ამ შენობის დიზაინი მომწონს.","level":"beginner"},
    {"english":"geometry","georgian":"გეომეტრია","pronunciation":"/dʒiˈɒmɪtri/","example_en":"I study geometry at school.","example_ka":"სკოლაში გეომეტრიას ვსწავლობ.","level":"beginner"},
    {"english":"measure","georgian":"გაზომვა","pronunciation":"/ˈmeʒər/","example_en":"Measure the length of the table.","example_ka":"მაგიდის სიგრძე გაზომე.","level":"beginner"},
    {"english":"length","georgian":"სიგრძე","pronunciation":"/leŋθ/","example_en":"The length of the room is five meters.","example_ka":"ოთახის სიგრძე ხუთი მეტრია.","level":"beginner"},
    {"english":"width","georgian":"სიგანე","pronunciation":"/wɪdθ/","example_en":"The width is three meters.","example_ka":"სიგანე სამი მეტრია.","level":"beginner"},
    {"english":"height","georgian":"სიმაღლე","pronunciation":"/haɪt/","example_en":"The height of the tree is ten meters.","example_ka":"ხის სიმაღლე ათი მეტრია.","level":"beginner"},
    {"english":"depth","georgian":"სიღრმე","pronunciation":"/depθ/","example_en":"The depth of the pool is two meters.","example_ka":"აუზის სიღრმე ორი მეტრია.","level":"beginner"},
    {"english":"equal","georgian":"თანაბარი","pronunciation":"/ˈiːkwəl/","example_en":"The sides are equal.","example_ka":"გვერდები თანაბარია.","level":"beginner"},
    {"english":"unequal","georgian":"არათანაბარი","pronunciation":"/ʌnˈiːkwəl/","example_en":"The sides are unequal.","example_ka":"გვერდები არათანაბარია.","level":"beginner"},
    {"english":"tiny","georgian":"ციცქნა","pronunciation":"/ˈtaɪni/","example_en":"The insect is tiny.","example_ka":"მწერი ციცქნაა.","level":"beginner"},
    {"english":"enormous","georgian":"უზარमაზარი","pronunciation":"/ɪˈnɔːrməs/","example_en":"The whale is enormous.","example_ka":"ვეშაპი უზარმაზარია.","level":"beginner"},
    {"english":"massive","georgian":"მასიური","pronunciation":"/ˈmæsɪv/","example_en":"The boulder is massive.","example_ka":"ლოდი მასიურია.","level":"beginner"},
    {"english":"compact","georgian":"კომპაქტური","pronunciation":"/kəmˈpækt/","example_en":"The car is compact.","example_ka":"მანქანა კომპაქტურია.","level":"beginner"},
    {"english":"spacious","georgian":"ვრცელი","pronunciation":"/ˈspeɪʃəs/","example_en":"The room is spacious.","example_ka":"ოთახი ვრცელია.","level":"intermediate"},
]

DIR = "/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/"

expand_file(DIR + "clothes-fashion.json", 200, clothes_new)
expand_file(DIR + "clothing-fashion.json", 200, clothing_new)
expand_file(DIR + "colors-shapes.json", 200, colors_new)
