#!/usr/bin/env python3
import json

with open('/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/top-5000-words.json', 'r') as f:
    data = json.load(f)
existing = set(w['english'].lower() for w in data)
print(f"Starting with {len(data)} entries")

batch = [
# A2 adverbs & function words
{"english":"however","georgian":"თუმცა","pronunciation":"ჰაუევერ","example_en":"However, I disagree.","example_ka":"თუმცა, მე არ ვეთანხმები.","category":"top-5000","level":"A2"},
{"english":"though","georgian":"მიუხედავად","pronunciation":"ძოუ","example_en":"Even though it rained, we went.","example_ka":"მიუხედავად წვიმისა, წავედით.","category":"top-5000","level":"A2"},
{"english":"quite","georgian":"საკმაოდ","pronunciation":"ქვაით","example_en":"It's quite good.","example_ka":"საკმაოდ კარგია.","category":"top-5000","level":"A2"},
{"english":"perhaps","georgian":"ალბათ","pronunciation":"ფერჰეფს","example_en":"Perhaps you are right.","example_ka":"ალბათ მართალი ხარ.","category":"top-5000","level":"A2"},
{"english":"rather","georgian":"საკმაოდ","pronunciation":"რაძერ","example_en":"I would rather stay.","example_ka":"დარჩენა მჯობინდა.","category":"top-5000","level":"A2"},
{"english":"instead","georgian":"ამის ნაცვლად","pronunciation":"ინსთედ","example_en":"I'll have tea instead.","example_ka":"ამის ნაცვლად ჩაის დავლევ.","category":"top-5000","level":"A2"},
{"english":"actually","georgian":"სინამდვილეში","pronunciation":"ექჩუალი","example_en":"Actually, I changed my mind.","example_ka":"სინამდვილეში, აზრი შევიცვალე.","category":"top-5000","level":"A2"},
{"english":"almost","georgian":"თითქმის","pronunciation":"ოლმოსთ","example_en":"I almost forgot.","example_ka":"თითქმის დამავიწყდა.","category":"top-5000","level":"A2"},
{"english":"probably","georgian":"ალბათ","pronunciation":"პრობებლი","example_en":"He will probably come.","example_ka":"ალბათ მოვა.","category":"top-5000","level":"A2"},
{"english":"especially","georgian":"განსაკუთრებით","pronunciation":"ისფეშალი","example_en":"I love fruits, especially apples.","example_ka":"ხილი მიყვარს, განსაკუთრებით ვაშლი.","category":"top-5000","level":"A2"},
{"english":"quickly","georgian":"სწრაფად","pronunciation":"ქვიქლი","example_en":"Come quickly!","example_ka":"სწრაფად მოდი!","category":"top-5000","level":"A2"},
{"english":"finally","georgian":"ბოლოს","pronunciation":"ფაინალი","example_en":"I finally finished.","example_ka":"ბოლოს და ბოლოს დავასრულე.","category":"top-5000","level":"A2"},
{"english":"exactly","georgian":"ზუსტად","pronunciation":"იგზექთლი","example_en":"That's exactly right.","example_ka":"ზუსტად ასეა.","category":"top-5000","level":"A2"},
{"english":"usually","georgian":"ჩვეულებრივ","pronunciation":"იუჟუალი","example_en":"I usually wake up early.","example_ka":"ჩვეულებრივ ადრე ვიღვიძებ.","category":"top-5000","level":"A2"},
{"english":"sometimes","georgian":"ზოგჯერ","pronunciation":"სამთაიმზ","example_en":"Sometimes I walk to work.","example_ka":"ზოგჯერ ფეხით მივდივარ სამსახურში.","category":"top-5000","level":"A2"},
{"english":"often","georgian":"ხშირად","pronunciation":"ოფენ","example_en":"I often read at night.","example_ka":"ხშირად ღამით ვკითხულობ.","category":"top-5000","level":"A2"},
{"english":"certainly","georgian":"რა თქმა უნდა","pronunciation":"სერთენლი","example_en":"Certainly, I'll help you.","example_ka":"რა თქმა უნდა, დაგეხმარები.","category":"top-5000","level":"A2"},
{"english":"clearly","georgian":"ნათლად","pronunciation":"ქლიარლი","example_en":"Speak clearly.","example_ka":"ნათლად ილაპარაკე.","category":"top-5000","level":"A2"},
{"english":"recently","georgian":"ახლახან","pronunciation":"რისენთლი","example_en":"I recently moved.","example_ka":"ახლახან გადავედი.","category":"top-5000","level":"A2"},
{"english":"simply","georgian":"უბრალოდ","pronunciation":"სიმფლი","example_en":"Simply the best.","example_ka":"უბრალოდ საუკეთესო.","category":"top-5000","level":"A2"},
{"english":"easily","georgian":"ადვილად","pronunciation":"იზილი","example_en":"I can do it easily.","example_ka":"ადვილად შემიძლია.","category":"top-5000","level":"A2"},
# A2 verbs
{"english":"create","georgian":"შექმნა","pronunciation":"ქრიეით","example_en":"Create something new.","example_ka":"რაღაც ახალი შექმენი.","category":"top-5000","level":"A2"},
{"english":"allow","georgian":"ნებართვა","pronunciation":"ელაუ","example_en":"Allow me to help.","example_ka":"ნება მიბოძეთ დაგეხმაროთ.","category":"top-5000","level":"A2"},
{"english":"add","georgian":"დამატება","pronunciation":"ედ","example_en":"Add some sugar.","example_ka":"ცოტა შაქარი დაამატე.","category":"top-5000","level":"A2"},
{"english":"spend","georgian":"ხარჯვა","pronunciation":"სფენდ","example_en":"I spend time reading.","example_ka":"დროს კითხვით ვატარებ.","category":"top-5000","level":"A2"},
{"english":"offer","georgian":"შეთავაზება","pronunciation":"ოფერ","example_en":"He offered me a job.","example_ka":"მან სამუშაო შემომთავაზა.","category":"top-5000","level":"A2"},
{"english":"consider","georgian":"განხილვა","pronunciation":"ქონსიდერ","example_en":"Consider this option.","example_ka":"ეს ვარიანტი განიხილე.","category":"top-5000","level":"A2"},
{"english":"appear","georgian":"გამოჩენა","pronunciation":"ეფიარ","example_en":"Stars appear at night.","example_ka":"ვარსკვლავები ღამით ჩანან.","category":"top-5000","level":"A2"},
{"english":"serve","georgian":"მომსახურება","pronunciation":"სერვ","example_en":"They serve good food.","example_ka":"კარგ საკვებს ემსახურებიან.","category":"top-5000","level":"A2"},
{"english":"expect","georgian":"მოლოდინი","pronunciation":"იქსფექთ","example_en":"I expect good results.","example_ka":"კარგ შედეგებს ველოდები.","category":"top-5000","level":"A2"},
{"english":"reach","georgian":"მიღწევა","pronunciation":"რიჩ","example_en":"We reached the top.","example_ka":"მწვერვალს მივაღწიეთ.","category":"top-5000","level":"A2"},
{"english":"remain","georgian":"დარჩენა","pronunciation":"რიმეინ","example_en":"Please remain seated.","example_ka":"გთხოვთ, იჯდეთ.","category":"top-5000","level":"A2"},
{"english":"suggest","georgian":"შეთავაზება","pronunciation":"სეჯესთ","example_en":"I suggest we leave.","example_ka":"გთავაზობთ წავიდეთ.","category":"top-5000","level":"A2"},
{"english":"raise","georgian":"აწევა","pronunciation":"რეიზ","example_en":"Raise your hand.","example_ka":"ხელი აწიე.","category":"top-5000","level":"A2"},
{"english":"pass","georgian":"გავლა","pronunciation":"ფას","example_en":"Pass me the salt.","example_ka":"მარილი მომაწოდე.","category":"top-5000","level":"A2"},
{"english":"require","georgian":"მოთხოვნა","pronunciation":"რიქვაიერ","example_en":"This requires patience.","example_ka":"ეს მოთმინებას მოითხოვს.","category":"top-5000","level":"A2"},
{"english":"report","georgian":"ანგარიში","pronunciation":"რიფორთ","example_en":"Write a report.","example_ka":"ანგარიში დაწერე.","category":"top-5000","level":"A2"},
{"english":"decide","georgian":"გადაწყვეტა","pronunciation":"დისაიდ","example_en":"I can't decide.","example_ka":"ვერ ვწყვეტ.","category":"top-5000","level":"A2"},
{"english":"pull","georgian":"მოზიდვა","pronunciation":"ფულ","example_en":"Pull the door.","example_ka":"კარი მოზიდე.","category":"top-5000","level":"A2"},
{"english":"develop","georgian":"განვითარება","pronunciation":"დიველოფ","example_en":"We need to develop a plan.","example_ka":"გეგმის შემუშავება გვჭირდება.","category":"top-5000","level":"A2"},
{"english":"provide","georgian":"უზრუნველყოფა","pronunciation":"ფროვაიდ","example_en":"We provide services.","example_ka":"მომსახურებას ვუზრუნველყოფთ.","category":"top-5000","level":"A2"},
{"english":"draw","georgian":"ხატვა","pronunciation":"დრო","example_en":"Can you draw a cat?","example_ka":"კატას დახატავ?","category":"top-5000","level":"A2"},
{"english":"agree","georgian":"თანხმობა","pronunciation":"ეგრი","example_en":"I agree with you.","example_ka":"გეთანხმები.","category":"top-5000","level":"A2"},
{"english":"support","georgian":"მხარდაჭერა","pronunciation":"სეფორთ","example_en":"I support your decision.","example_ka":"შენს გადაწყვეტილებას ვუჭერ მხარს.","category":"top-5000","level":"A2"},
{"english":"receive","georgian":"მიღება","pronunciation":"რისივ","example_en":"I received your letter.","example_ka":"შენი წერილი მივიღე.","category":"top-5000","level":"A2"},
{"english":"enjoy","georgian":"სიამოვნება","pronunciation":"ინჯოი","example_en":"Enjoy your meal.","example_ka":"გემრიელად მიირთვით.","category":"top-5000","level":"A2"},
{"english":"carry","georgian":"ტარება","pronunciation":"ქერი","example_en":"Carry this bag.","example_ka":"ეს ჩანთა წაიღე.","category":"top-5000","level":"A2"},
{"english":"include","georgian":"მოიცავს","pronunciation":"ინქლუდ","example_en":"The price includes tax.","example_ka":"ფასი გადასახადს მოიცავს.","category":"top-5000","level":"A2"},
{"english":"continue","georgian":"გაგრძელება","pronunciation":"ქონთინიუ","example_en":"Please continue.","example_ka":"გთხოვთ, გააგრძელეთ.","category":"top-5000","level":"A2"},
{"english":"set","georgian":"დაყენება","pronunciation":"სეთ","example_en":"Set the alarm.","example_ka":"მაღვიძარა დააყენე.","category":"top-5000","level":"A2"},
{"english":"lead","georgian":"ხელმძღვანელობა","pronunciation":"ლიდ","example_en":"She leads the team.","example_ka":"ის გუნდს ხელმძღვანელობს.","category":"top-5000","level":"A2"},
{"english":"kill","georgian":"მოკვლა","pronunciation":"ქილ","example_en":"Don't kill the spider.","example_ka":"ობობა ნუ მოკლავ.","category":"top-5000","level":"A2"},
{"english":"begin","georgian":"დაწყება","pronunciation":"ბიგინ","example_en":"Let's begin.","example_ka":"დავიწყოთ.","category":"top-5000","level":"A2"},
{"english":"cost","georgian":"ღირებულება","pronunciation":"ქოსთ","example_en":"How much does it cost?","example_ka":"რა ღირს?","category":"top-5000","level":"A2"},
{"english":"drive","georgian":"მართვა","pronunciation":"დრაივ","example_en":"I can drive a car.","example_ka":"მანქანის ტარება შემიძლია.","category":"top-5000","level":"A2"},
{"english":"fly","georgian":"ფრენა","pronunciation":"ფლაი","example_en":"Birds fly south.","example_ka":"ფრინველები სამხრეთით ფრინავენ.","category":"top-5000","level":"A2"},
{"english":"break","georgian":"გატეხვა","pronunciation":"ბრეიქ","example_en":"Don't break the glass.","example_ka":"ჭიქა არ გატეხო.","category":"top-5000","level":"A2"},
{"english":"wear","georgian":"ჩაცმა","pronunciation":"ვეარ","example_en":"I wear a jacket.","example_ka":"ქურთუკს ვიცვამ.","category":"top-5000","level":"A2"},
{"english":"sing","georgian":"სიმღერა","pronunciation":"სინგ","example_en":"She sings beautifully.","example_ka":"ის ლამაზად მღერის.","category":"top-5000","level":"A2"},
{"english":"dance","georgian":"ცეკვა","pronunciation":"დენს","example_en":"Let's dance.","example_ka":"ვიცეკვოთ.","category":"top-5000","level":"A2"},
{"english":"cook","georgian":"მომზადება (საჭმელი)","pronunciation":"ქუქ","example_en":"I love to cook.","example_ka":"საჭმლის კეთება მიყვარს.","category":"top-5000","level":"A2"},
{"english":"wash","georgian":"რეცხვა","pronunciation":"ვოშ","example_en":"Wash your hands.","example_ka":"ხელები დაიბანე.","category":"top-5000","level":"A2"},
{"english":"teach","georgian":"სწავლება","pronunciation":"თიჩ","example_en":"She teaches English.","example_ka":"ის ინგლისურს ასწავლის.","category":"top-5000","level":"A2"},
{"english":"choose","georgian":"არჩევა","pronunciation":"ჩუზ","example_en":"Choose one.","example_ka":"ერთი აირჩიე.","category":"top-5000","level":"A2"},
{"english":"finish","georgian":"დასრულება","pronunciation":"ფინიშ","example_en":"I need to finish.","example_ka":"დასრულება მჭირდება.","category":"top-5000","level":"A2"},
{"english":"throw","georgian":"სროლა","pronunciation":"თროუ","example_en":"Throw me the ball.","example_ka":"ბურთი გადმომისროლე.","category":"top-5000","level":"A2"},
{"english":"catch","georgian":"დაჭერა","pronunciation":"ქეჩ","example_en":"Catch the ball.","example_ka":"ბურთი დაიჭირე.","category":"top-5000","level":"A2"},
{"english":"fill","georgian":"შევსება","pronunciation":"ფილ","example_en":"Fill the glass.","example_ka":"ჭიქა შეავსე.","category":"top-5000","level":"A2"},
{"english":"drop","georgian":"ჩაგდება","pronunciation":"დროფ","example_en":"Don't drop it.","example_ka":"არ ჩააგდო.","category":"top-5000","level":"A2"},
{"english":"push","georgian":"მიწოლა","pronunciation":"ფუშ","example_en":"Push the button.","example_ka":"ღილაკს მიაწოლე.","category":"top-5000","level":"A2"},
{"english":"fight","georgian":"ბრძოლა","pronunciation":"ფაით","example_en":"Don't fight.","example_ka":"ნუ ჩხუბობთ.","category":"top-5000","level":"A2"},
{"english":"wish","georgian":"სურვილი","pronunciation":"ვიშ","example_en":"I wish you happiness.","example_ka":"ბედნიერებას გისურვებ.","category":"top-5000","level":"A2"},
{"english":"hope","georgian":"იმედი","pronunciation":"ჰოუფ","example_en":"I hope so.","example_ka":"ვიმედოვნებ.","category":"top-5000","level":"A2"},
{"english":"forget","georgian":"დავიწყება","pronunciation":"ფორგეთ","example_en":"Don't forget!","example_ka":"არ დაგავიწყდეს!","category":"top-5000","level":"A2"},
{"english":"explain","georgian":"ახსნა","pronunciation":"იქსფლეინ","example_en":"Please explain.","example_ka":"გთხოვთ ახსენით.","category":"top-5000","level":"A2"},
{"english":"save","georgian":"გადარჩენა / შენახვა","pronunciation":"სეივ","example_en":"Save your money.","example_ka":"ფული დაიზოგე.","category":"top-5000","level":"A2"},
{"english":"arrive","georgian":"ჩამოსვლა","pronunciation":"ერაივ","example_en":"When will you arrive?","example_ka":"როდის ჩამოხვალ?","category":"top-5000","level":"A2"},
{"english":"return","georgian":"დაბრუნება","pronunciation":"რითერნ","example_en":"I will return soon.","example_ka":"მალე დავბრუნდები.","category":"top-5000","level":"A2"},
{"english":"join","georgian":"შეერთება","pronunciation":"ჯოინ","example_en":"Join our team.","example_ka":"ჩვენს გუნდში გაწევრიანდი.","category":"top-5000","level":"A2"},
{"english":"fix","georgian":"შეკეთება","pronunciation":"ფიქს","example_en":"Can you fix it?","example_ka":"შეგიძლია შეაკეთო?","category":"top-5000","level":"A2"},
{"english":"guess","georgian":"გამოცნობა","pronunciation":"გეს","example_en":"Guess what happened.","example_ka":"გამოიცანი რა მოხდა.","category":"top-5000","level":"A2"},
# A2 nouns
{"english":"weather","georgian":"ამინდი","pronunciation":"ვეძერ","example_en":"The weather is nice.","example_ka":"ამინდი კარგია.","category":"top-5000","level":"A2"},
{"english":"age","georgian":"ასაკი","pronunciation":"ეიჯ","example_en":"What is your age?","example_ka":"რამდენი წლის ხარ?","category":"top-5000","level":"A2"},
{"english":"language","georgian":"ენა","pronunciation":"ლენგვიჯ","example_en":"I speak two languages.","example_ka":"ორ ენაზე ვლაპარაკობ.","category":"top-5000","level":"A2"},
{"english":"road","georgian":"გზა","pronunciation":"როუდ","example_en":"The road is long.","example_ka":"გზა გრძელია.","category":"top-5000","level":"A2"},
{"english":"heart","georgian":"გული","pronunciation":"ჰართ","example_en":"My heart beats fast.","example_ka":"გული სწრაფად მიცემს.","category":"top-5000","level":"A2"},
{"english":"face","georgian":"სახე","pronunciation":"ფეის","example_en":"She has a beautiful face.","example_ka":"ლამაზი სახე აქვს.","category":"top-5000","level":"A2"},
{"english":"voice","georgian":"ხმა","pronunciation":"ვოის","example_en":"She has a nice voice.","example_ka":"ლამაზი ხმა აქვს.","category":"top-5000","level":"A2"},
{"english":"price","georgian":"ფასი","pronunciation":"ფრაის","example_en":"What is the price?","example_ka":"რა ფასია?","category":"top-5000","level":"A2"},
{"english":"news","georgian":"ახალი ამბები","pronunciation":"ნიუზ","example_en":"I watch the news.","example_ka":"ახალ ამბებს ვუყურებ.","category":"top-5000","level":"A2"},
{"english":"paper","georgian":"ქაღალდი","pronunciation":"ფეიფერ","example_en":"Give me some paper.","example_ka":"ქაღალდი მომეცი.","category":"top-5000","level":"A2"},
{"english":"letter","georgian":"წერილი","pronunciation":"ლეთერ","example_en":"I wrote a letter.","example_ka":"წერილი დავწერე.","category":"top-5000","level":"A2"},
{"english":"war","georgian":"ომი","pronunciation":"ვორ","example_en":"War is terrible.","example_ka":"ომი საშინელია.","category":"top-5000","level":"A2"},
{"english":"peace","georgian":"მშვიდობა","pronunciation":"ფის","example_en":"We want peace.","example_ka":"მშვიდობა გვინდა.","category":"top-5000","level":"A2"},
{"english":"class","georgian":"კლასი","pronunciation":"ქლას","example_en":"I have a class now.","example_ka":"ახლა გაკვეთილი მაქვს.","category":"top-5000","level":"A2"},
{"english":"animal","georgian":"ცხოველი","pronunciation":"ენიმალ","example_en":"I love animals.","example_ka":"ცხოველები მიყვარს.","category":"top-5000","level":"A2"},
{"english":"bird","georgian":"ფრინველი","pronunciation":"ბერდ","example_en":"A bird is singing.","example_ka":"ფრინველი მღერის.","category":"top-5000","level":"A2"},
{"english":"fish","georgian":"თევზი","pronunciation":"ფიშ","example_en":"I like fish.","example_ka":"თევზი მომწონს.","category":"top-5000","level":"A2"},
{"english":"tree","georgian":"ხე","pronunciation":"თრი","example_en":"The tree is tall.","example_ka":"ხე მაღალია.","category":"top-5000","level":"A2"},
{"english":"flower","georgian":"ყვავილი","pronunciation":"ფლაუერ","example_en":"I bought flowers.","example_ka":"ყვავილები ვიყიდე.","category":"top-5000","level":"A2"},
{"english":"mountain","georgian":"მთა","pronunciation":"მაუნთენ","example_en":"The mountain is high.","example_ka":"მთა მაღალია.","category":"top-5000","level":"A2"},
{"english":"sea","georgian":"ზღვა","pronunciation":"სი","example_en":"I love the sea.","example_ka":"ზღვა მიყვარს.","category":"top-5000","level":"A2"},
{"english":"snow","georgian":"თოვლი","pronunciation":"სნოუ","example_en":"It is snowing.","example_ka":"თოვს.","category":"top-5000","level":"A2"},
{"english":"fire","georgian":"ცეცხლი","pronunciation":"ფაიერ","example_en":"The fire is warm.","example_ka":"ცეცხლი თბილია.","category":"top-5000","level":"A2"},
{"english":"sky","georgian":"ცა","pronunciation":"სქაი","example_en":"The sky is blue.","example_ka":"ცა ლურჯია.","category":"top-5000","level":"A2"},
{"english":"star","georgian":"ვარსკვლავი","pronunciation":"სთარ","example_en":"Stars shine at night.","example_ka":"ვარსკვლავები ღამით ანათებენ.","category":"top-5000","level":"A2"},
{"english":"moon","georgian":"მთვარე","pronunciation":"მუნ","example_en":"The moon is full.","example_ka":"მთვარე სავსეა.","category":"top-5000","level":"A2"},
{"english":"bread","georgian":"პური","pronunciation":"ბრედ","example_en":"I need bread.","example_ka":"პური მჭირდება.","category":"top-5000","level":"A2"},
{"english":"milk","georgian":"რძე","pronunciation":"მილქ","example_en":"I drink milk.","example_ka":"რძეს ვსვამ.","category":"top-5000","level":"A2"},
{"english":"tea","georgian":"ჩაი","pronunciation":"თი","example_en":"I drink tea every morning.","example_ka":"ყოველ დილით ჩაის ვსვამ.","category":"top-5000","level":"A2"},
{"english":"coffee","georgian":"ყავა","pronunciation":"ქოფი","example_en":"I need coffee.","example_ka":"ყავა მჭირდება.","category":"top-5000","level":"A2"},
{"english":"brother","georgian":"ძმა","pronunciation":"ბრაძერ","example_en":"My brother is tall.","example_ka":"ჩემი ძმა მაღალია.","category":"top-5000","level":"A2"},
{"english":"sister","georgian":"და","pronunciation":"სისთერ","example_en":"My sister is older.","example_ka":"ჩემი და უფროსია.","category":"top-5000","level":"A2"},
{"english":"son","georgian":"ვაჟიშვილი","pronunciation":"სან","example_en":"My son is five.","example_ka":"ჩემი ვაჟი ხუთი წლისაა.","category":"top-5000","level":"A2"},
{"english":"daughter","georgian":"ქალიშვილი","pronunciation":"დოთერ","example_en":"My daughter goes to school.","example_ka":"ჩემი ქალიშვილი სკოლაში დადის.","category":"top-5000","level":"A2"},
{"english":"husband","georgian":"ქმარი","pronunciation":"ჰაზბენდ","example_en":"Her husband works here.","example_ka":"მისი ქმარი აქ მუშაობს.","category":"top-5000","level":"A2"},
{"english":"wife","georgian":"ცოლი","pronunciation":"ვაიფ","example_en":"My wife is a doctor.","example_ka":"ჩემი ცოლი ექიმია.","category":"top-5000","level":"A2"},
{"english":"king","georgian":"მეფე","pronunciation":"ქინგ","example_en":"The king ruled wisely.","example_ka":"მეფე ბრძნულად მართავდა.","category":"top-5000","level":"A2"},
{"english":"pain","georgian":"ტკივილი","pronunciation":"ფეინ","example_en":"I feel pain.","example_ka":"ტკივილს ვგრძნობ.","category":"top-5000","level":"A2"},
{"english":"blood","georgian":"სისხლი","pronunciation":"ბლად","example_en":"I saw blood.","example_ka":"სისხლი ვნახე.","category":"top-5000","level":"A2"},
{"english":"death","georgian":"სიკვდილი","pronunciation":"დეთ","example_en":"Life and death.","example_ka":"სიცოცხლე და სიკვდილი.","category":"top-5000","level":"A2"},
{"english":"dream","georgian":"ოცნება / სიზმარი","pronunciation":"დრიმ","example_en":"I had a dream.","example_ka":"სიზმარი ვნახე.","category":"top-5000","level":"A2"},
{"english":"chance","georgian":"შანსი","pronunciation":"ჩენს","example_en":"Give me a chance.","example_ka":"შანსი მომეცი.","category":"top-5000","level":"A2"},
{"english":"ground","georgian":"მიწა","pronunciation":"გრაუნდ","example_en":"Sit on the ground.","example_ka":"მიწაზე დაჯექი.","category":"top-5000","level":"A2"},
{"english":"town","georgian":"ქალაქი (პატარა)","pronunciation":"თაუნ","example_en":"I live in a small town.","example_ka":"პატარა ქალაქში ვცხოვრობ.","category":"top-5000","level":"A2"},
{"english":"village","georgian":"სოფელი","pronunciation":"ვილიჯ","example_en":"My village is beautiful.","example_ka":"ჩემი სოფელი ლამაზია.","category":"top-5000","level":"A2"},
{"english":"store","georgian":"მაღაზია","pronunciation":"სთორ","example_en":"I went to the store.","example_ka":"მაღაზიაში წავედი.","category":"top-5000","level":"A2"},
{"english":"hospital","georgian":"საავადმყოფო","pronunciation":"ჰოსფითალ","example_en":"He is in the hospital.","example_ka":"ის საავადმყოფოშია.","category":"top-5000","level":"A2"},
{"english":"hotel","georgian":"სასტუმრო","pronunciation":"ჰოთელ","example_en":"We stayed at a hotel.","example_ka":"სასტუმროში დავრჩით.","category":"top-5000","level":"A2"},
{"english":"restaurant","georgian":"რესტორანი","pronunciation":"რესთორენთ","example_en":"Let's go to a restaurant.","example_ka":"რესტორანში წავიდეთ.","category":"top-5000","level":"A2"},
{"english":"bank","georgian":"ბანკი","pronunciation":"ბენქ","example_en":"I went to the bank.","example_ka":"ბანკში წავედი.","category":"top-5000","level":"A2"},
{"english":"park","georgian":"პარკი","pronunciation":"ფარქ","example_en":"Let's go to the park.","example_ka":"პარკში წავიდეთ.","category":"top-5000","level":"A2"},
# A2 adjectives
{"english":"special","georgian":"განსაკუთრებული","pronunciation":"სფეშალ","example_en":"Today is a special day.","example_ka":"დღეს განსაკუთრებული დღეა.","category":"top-5000","level":"A2"},
{"english":"clear","georgian":"ნათელი","pronunciation":"ქლიარ","example_en":"Is that clear?","example_ka":"ეს გასაგებია?","category":"top-5000","level":"A2"},
{"english":"certain","georgian":"გარკვეული","pronunciation":"სერთენ","example_en":"I am certain.","example_ka":"დარწმუნებული ვარ.","category":"top-5000","level":"A2"},
{"english":"common","georgian":"გავრცელებული","pronunciation":"ქომენ","example_en":"It is a common problem.","example_ka":"ეს გავრცელებული პრობლემაა.","category":"top-5000","level":"A2"},
{"english":"poor","georgian":"ღარიბი","pronunciation":"ფუარ","example_en":"The family is poor.","example_ka":"ოჯახი ღარიბია.","category":"top-5000","level":"A2"},
{"english":"rich","georgian":"მდიდარი","pronunciation":"რიჩ","example_en":"He is rich.","example_ka":"ის მდიდარია.","category":"top-5000","level":"A2"},
{"english":"wrong","georgian":"არასწორი","pronunciation":"რონგ","example_en":"You are wrong.","example_ka":"შენ ცდები.","category":"top-5000","level":"A2"},
{"english":"fine","georgian":"კარგად","pronunciation":"ფაინ","example_en":"I am fine.","example_ka":"კარგად ვარ.","category":"top-5000","level":"A2"},
{"english":"deep","georgian":"ღრმა","pronunciation":"დიფ","example_en":"The river is deep.","example_ka":"მდინარე ღრმაა.","category":"top-5000","level":"A2"},
{"english":"wide","georgian":"ფართო","pronunciation":"ვაიდ","example_en":"The road is wide.","example_ka":"გზა ფართოა.","category":"top-5000","level":"A2"},
{"english":"tall","georgian":"მაღალი","pronunciation":"თოლ","example_en":"He is tall.","example_ka":"ის მაღალია.","category":"top-5000","level":"A2"},
{"english":"safe","georgian":"უსაფრთხო","pronunciation":"სეიფ","example_en":"You are safe here.","example_ka":"აქ უსაფრთხოდ ხარ.","category":"top-5000","level":"A2"},
{"english":"dangerous","georgian":"საშიში","pronunciation":"დეინჯერეს","example_en":"It is dangerous.","example_ka":"ეს საშიშია.","category":"top-5000","level":"A2"},
{"english":"busy","georgian":"დაკავებული","pronunciation":"ბიზი","example_en":"I am busy.","example_ka":"დაკავებული ვარ.","category":"top-5000","level":"A2"},
{"english":"quiet","georgian":"წყნარი","pronunciation":"ქვაიეთ","example_en":"Be quiet.","example_ka":"ჩუმად იყავი.","category":"top-5000","level":"A2"},
{"english":"loud","georgian":"ხმამაღალი","pronunciation":"ლაუდ","example_en":"The music is loud.","example_ka":"მუსიკა ხმამაღალია.","category":"top-5000","level":"A2"},
{"english":"fresh","georgian":"ახალი / სუფთა","pronunciation":"ფრეშ","example_en":"Fresh air.","example_ka":"სუფთა ჰაერი.","category":"top-5000","level":"A2"},
{"english":"dry","georgian":"მშრალი","pronunciation":"დრაი","example_en":"The weather is dry.","example_ka":"ამინდი მშრალია.","category":"top-5000","level":"A2"},
{"english":"wet","georgian":"სველი","pronunciation":"ვეთ","example_en":"The road is wet.","example_ka":"გზა სველია.","category":"top-5000","level":"A2"},
{"english":"hungry","georgian":"მშიერი","pronunciation":"ჰანგრი","example_en":"I am hungry.","example_ka":"მშია.","category":"top-5000","level":"A2"},
{"english":"thirsty","georgian":"მწყურვალი","pronunciation":"თერსთი","example_en":"I am thirsty.","example_ka":"მწყურია.","category":"top-5000","level":"A2"},
{"english":"tired","georgian":"დაღლილი","pronunciation":"თაიერდ","example_en":"I am tired.","example_ka":"დაღლილი ვარ.","category":"top-5000","level":"A2"},
{"english":"sick","georgian":"ავადმყოფი","pronunciation":"სიქ","example_en":"I feel sick.","example_ka":"ავად ვარ.","category":"top-5000","level":"A2"},
{"english":"healthy","georgian":"ჯანმრთელი","pronunciation":"ჰელთი","example_en":"Stay healthy.","example_ka":"ჯანმრთელი იყავი.","category":"top-5000","level":"A2"},
{"english":"angry","georgian":"გაბრაზებული","pronunciation":"ენგრი","example_en":"Don't be angry.","example_ka":"ნუ გაბრაზდები.","category":"top-5000","level":"A2"},
{"english":"afraid","georgian":"შეშინებული","pronunciation":"ეფრეიდ","example_en":"Don't be afraid.","example_ka":"ნუ გეშინია.","category":"top-5000","level":"A2"},
{"english":"alive","georgian":"ცოცხალი","pronunciation":"ელაივ","example_en":"He is alive.","example_ka":"ის ცოცხალია.","category":"top-5000","level":"A2"},
{"english":"dead","georgian":"მკვდარი","pronunciation":"დედ","example_en":"The plant is dead.","example_ka":"მცენარე დაჭკნა.","category":"top-5000","level":"A2"},
{"english":"famous","georgian":"ცნობილი","pronunciation":"ფეიმეს","example_en":"He is famous.","example_ka":"ის ცნობილია.","category":"top-5000","level":"A2"},
{"english":"foreign","georgian":"უცხო","pronunciation":"ფორენ","example_en":"Foreign languages are useful.","example_ka":"უცხო ენები სასარგებლოა.","category":"top-5000","level":"A2"},
{"english":"main","georgian":"მთავარი","pronunciation":"მეინ","example_en":"The main street.","example_ka":"მთავარი ქუჩა.","category":"top-5000","level":"A2"},
{"english":"green","georgian":"მწვანე","pronunciation":"გრინ","example_en":"The grass is green.","example_ka":"ბალახი მწვანეა.","category":"top-5000","level":"A2"},
{"english":"red","georgian":"წითელი","pronunciation":"რედ","example_en":"The car is red.","example_ka":"მანქანა წითელია.","category":"top-5000","level":"A2"},
{"english":"blue","georgian":"ლურჯი","pronunciation":"ბლუ","example_en":"The sky is blue.","example_ka":"ცა ლურჯია.","category":"top-5000","level":"A2"},
{"english":"yellow","georgian":"ყვითელი","pronunciation":"იელოუ","example_en":"The sun is yellow.","example_ka":"მზე ყვითელია.","category":"top-5000","level":"A2"},
{"english":"likely","georgian":"სავარაუდო","pronunciation":"ლაიქლი","example_en":"It is likely to rain.","example_ka":"სავარაუდოდ იწვიმებს.","category":"top-5000","level":"A2"},
{"english":"single","georgian":"მარტოხელა / ერთი","pronunciation":"სინგლ","example_en":"I am single.","example_ka":"მარტოხელა ვარ.","category":"top-5000","level":"A2"},
{"english":"natural","georgian":"ბუნებრივი","pronunciation":"ნეჩურალ","example_en":"It is natural.","example_ka":"ეს ბუნებრივია.","category":"top-5000","level":"A2"},
{"english":"similar","georgian":"მსგავსი","pronunciation":"სიმილერ","example_en":"They are similar.","example_ka":"ისინი მსგავსია.","category":"top-5000","level":"A2"},
{"english":"central","georgian":"ცენტრალური","pronunciation":"სენთრალ","example_en":"The central park.","example_ka":"ცენტრალური პარკი.","category":"top-5000","level":"A2"},
{"english":"serious","georgian":"სერიოზული","pronunciation":"სირიეს","example_en":"This is serious.","example_ka":"ეს სერიოზულია.","category":"top-5000","level":"A2"},
{"english":"general","georgian":"ზოგადი","pronunciation":"ჯენერალ","example_en":"In general, I agree.","example_ka":"ზოგადად ვეთანხმები.","category":"top-5000","level":"A2"},
{"english":"final","georgian":"საბოლოო","pronunciation":"ფაინალ","example_en":"The final answer.","example_ka":"საბოლოო პასუხი.","category":"top-5000","level":"A2"},
{"english":"huge","georgian":"უზარმაზარი","pronunciation":"ჰიუჯ","example_en":"The building is huge.","example_ka":"შენობა უზარმაზარია.","category":"top-5000","level":"A2"},
{"english":"popular","georgian":"პოპულარული","pronunciation":"ფოფიულერ","example_en":"This song is popular.","example_ka":"ეს სიმღერა პოპულარულია.","category":"top-5000","level":"A2"},
{"english":"traditional","georgian":"ტრადიციული","pronunciation":"თრედიშენალ","example_en":"Traditional food.","example_ka":"ტრადიციული საკვები.","category":"top-5000","level":"A2"},
{"english":"cultural","georgian":"კულტურული","pronunciation":"ქალჩურალ","example_en":"Cultural heritage.","example_ka":"კულტურული მემკვიდრეობა.","category":"top-5000","level":"A2"},
{"english":"private","georgian":"კერძო / პირადი","pronunciation":"ფრაივეთ","example_en":"This is private.","example_ka":"ეს კერძოა.","category":"top-5000","level":"A2"},
{"english":"past","georgian":"წარსული","pronunciation":"ფასთ","example_en":"In the past.","example_ka":"წარსულში.","category":"top-5000","level":"A2"},
{"english":"significant","georgian":"მნიშვნელოვანი","pronunciation":"სიგნიფიქენთ","example_en":"A significant change.","example_ka":"მნიშვნელოვანი ცვლილება.","category":"top-5000","level":"A2"},
{"english":"medical","georgian":"სამედიცინო","pronunciation":"მედიქალ","example_en":"Medical help.","example_ka":"სამედიცინო დახმარება.","category":"top-5000","level":"A2"},
{"english":"entire","georgian":"მთლიანი","pronunciation":"ინთაიერ","example_en":"The entire team.","example_ka":"მთლიანი გუნდი.","category":"top-5000","level":"A2"},
{"english":"recent","georgian":"ბოლოდროინდელი","pronunciation":"რისენთ","example_en":"Recent news.","example_ka":"ბოლოდროინდელი ამბები.","category":"top-5000","level":"A2"},
{"english":"legal","georgian":"ლეგალური / სამართლებრივი","pronunciation":"ლიგალ","example_en":"Legal advice.","example_ka":"სამართლებრივი რჩევა.","category":"top-5000","level":"A2"},
{"english":"religious","georgian":"რელიგიური","pronunciation":"რილიჯეს","example_en":"Religious beliefs.","example_ka":"რელიგიური რწმენა.","category":"top-5000","level":"A2"},
{"english":"physical","georgian":"ფიზიკური","pronunciation":"ფიზიქალ","example_en":"Physical exercise.","example_ka":"ფიზიკური ვარჯიში.","category":"top-5000","level":"A2"},
{"english":"environmental","georgian":"გარემოსდაცვითი","pronunciation":"ინვაირონმენთალ","example_en":"Environmental protection.","example_ka":"გარემოს დაცვა.","category":"top-5000","level":"A2"},
{"english":"financial","georgian":"ფინანსური","pronunciation":"ფაინენშალ","example_en":"Financial problems.","example_ka":"ფინანსური პრობლემები.","category":"top-5000","level":"A2"},
{"english":"various","georgian":"სხვადასხვა","pronunciation":"ვეარიეს","example_en":"Various options.","example_ka":"სხვადასხვა ვარიანტი.","category":"top-5000","level":"A2"},
{"english":"difficult","georgian":"რთული","pronunciation":"დიფიქალთ","example_en":"The question is difficult.","example_ka":"კითხვა რთულია.","category":"top-5000","level":"A2"},
]

added = 0
for w in batch:
    key = w['english'].lower()
    if key not in existing:
        data.append(w)
        existing.add(key)
        added += 1

print(f"Added {added} new words from batch 2. Total: {len(data)}")

with open('/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/top-5000-words.json', 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved!")
