#!/usr/bin/env python3
import json

with open('/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/top-5000-words.json', 'r') as f:
    data = json.load(f)
existing = set(w['english'].lower() for w in data)
print(f"Starting with {len(data)} entries")

batch = [
# B1 verbs
{"english":"achieve","georgian":"მიღწევა","pronunciation":"ეჩივ","example_en":"I want to achieve my goals.","example_ka":"მიზნების მიღწევა მინდა.","category":"top-5000","level":"B1"},
{"english":"announce","georgian":"გამოცხადება","pronunciation":"ენაუნს","example_en":"They announced the winner.","example_ka":"გამარჯვებული გამოაცხადეს.","category":"top-5000","level":"B1"},
{"english":"apply","georgian":"მიმართვა","pronunciation":"ეფლაი","example_en":"I applied for the job.","example_ka":"სამუშაოზე მივმართე.","category":"top-5000","level":"B1"},
{"english":"approach","georgian":"მიდგომა","pronunciation":"ეფროუჩ","example_en":"She approached slowly.","example_ka":"ის ნელ-ნელა მოუახლოვდა.","category":"top-5000","level":"B1"},
{"english":"arrange","georgian":"მოწყობა","pronunciation":"ერეინჯ","example_en":"Arrange a meeting.","example_ka":"შეხვედრა მოაწყე.","category":"top-5000","level":"B1"},
{"english":"attempt","georgian":"მცდელობა","pronunciation":"ეთემფთ","example_en":"He attempted to escape.","example_ka":"მან გაქცევა სცადა.","category":"top-5000","level":"B1"},
{"english":"attend","georgian":"დასწრება","pronunciation":"ეთენდ","example_en":"I attended the meeting.","example_ka":"შეხვედრას დავესწარი.","category":"top-5000","level":"B1"},
{"english":"avoid","georgian":"თავის არიდება","pronunciation":"ევოიდ","example_en":"Avoid mistakes.","example_ka":"შეცდომებს თავი აარიდე.","category":"top-5000","level":"B1"},
{"english":"behave","georgian":"ქცევა","pronunciation":"ბიჰეივ","example_en":"Behave yourself.","example_ka":"თავი დაიჭირე.","category":"top-5000","level":"B1"},
{"english":"belong","georgian":"ეკუთვნის","pronunciation":"ბილონგ","example_en":"This belongs to me.","example_ka":"ეს ჩემია.","category":"top-5000","level":"B1"},
{"english":"borrow","georgian":"სესხება","pronunciation":"ბოროუ","example_en":"Can I borrow your pen?","example_ka":"შეიძლება კალამი მისესხო?","category":"top-5000","level":"B1"},
{"english":"celebrate","georgian":"ზეიმი","pronunciation":"სელიბრეით","example_en":"Let's celebrate!","example_ka":"ვიზეიმოთ!","category":"top-5000","level":"B1"},
{"english":"communicate","georgian":"კომუნიკაცია","pronunciation":"ქომიუნიქეით","example_en":"We need to communicate better.","example_ka":"უკეთესი კომუნიკაცია გვჭირდება.","category":"top-5000","level":"B1"},
{"english":"compare","georgian":"შედარება","pronunciation":"ქომფეარ","example_en":"Compare these two.","example_ka":"ეს ორი შეადარე.","category":"top-5000","level":"B1"},
{"english":"compete","georgian":"შეჯიბრება","pronunciation":"ქომფით","example_en":"Teams compete for the prize.","example_ka":"გუნდები პრიზისთვის იჯიბრებიან.","category":"top-5000","level":"B1"},
{"english":"complain","georgian":"ჩივილი","pronunciation":"ქომფლეინ","example_en":"Don't complain.","example_ka":"ნუ ჩივი.","category":"top-5000","level":"B1"},
{"english":"concern","georgian":"შეშფოთება","pronunciation":"ქონსერნ","example_en":"I am concerned.","example_ka":"შეშფოთებული ვარ.","category":"top-5000","level":"B1"},
{"english":"confirm","georgian":"დადასტურება","pronunciation":"ქონფერმ","example_en":"Please confirm your booking.","example_ka":"გთხოვთ დაადასტუროთ ჯავშანი.","category":"top-5000","level":"B1"},
{"english":"connect","georgian":"დაკავშირება","pronunciation":"ქონექთ","example_en":"Connect to the internet.","example_ka":"ინტერნეტთან დაუკავშირდი.","category":"top-5000","level":"B1"},
{"english":"contain","georgian":"შეიცავს","pronunciation":"ქონთეინ","example_en":"This box contains books.","example_ka":"ეს ყუთი წიგნებს შეიცავს.","category":"top-5000","level":"B1"},
{"english":"control","georgian":"კონტროლი","pronunciation":"ქონთროლ","example_en":"Control your emotions.","example_ka":"ემოციები აკონტროლე.","category":"top-5000","level":"B1"},
{"english":"convince","georgian":"დარწმუნება","pronunciation":"ქონვინს","example_en":"I convinced him.","example_ka":"დავარწმუნე ის.","category":"top-5000","level":"B1"},
{"english":"correct","georgian":"სწორი","pronunciation":"ქორექთ","example_en":"Is this correct?","example_ka":"ეს სწორია?","category":"top-5000","level":"B1"},
{"english":"cover","georgian":"დაფარვა","pronunciation":"ქავერ","example_en":"Cover yourself with a blanket.","example_ka":"საბნით დაიფარე.","category":"top-5000","level":"B1"},
{"english":"cross","georgian":"გადაკვეთა","pronunciation":"ქროს","example_en":"Cross the street carefully.","example_ka":"ქუჩა ფრთხილად გადაკვეთე.","category":"top-5000","level":"B1"},
{"english":"damage","georgian":"დაზიანება","pronunciation":"დემიჯ","example_en":"The storm caused damage.","example_ka":"ქარიშხალმა ზიანი მიაყენა.","category":"top-5000","level":"B1"},
{"english":"deal","georgian":"გარიგება","pronunciation":"დილ","example_en":"We made a deal.","example_ka":"შეთანხმებას მივაღწიეთ.","category":"top-5000","level":"B1"},
{"english":"deliver","georgian":"მიწოდება","pronunciation":"დილივერ","example_en":"They deliver food.","example_ka":"ისინი საკვებს მიაწვდიან.","category":"top-5000","level":"B1"},
{"english":"demand","georgian":"მოთხოვნა","pronunciation":"დიმანდ","example_en":"They demand better pay.","example_ka":"უკეთეს ხელფასს მოითხოვენ.","category":"top-5000","level":"B1"},
{"english":"depend","georgian":"დამოკიდებულება","pronunciation":"დიფენდ","example_en":"It depends on you.","example_ka":"შენზეა დამოკიდებული.","category":"top-5000","level":"B1"},
{"english":"describe","georgian":"აღწერა","pronunciation":"დისქრაიბ","example_en":"Describe what you see.","example_ka":"აღწერე რას ხედავ.","category":"top-5000","level":"B1"},
{"english":"design","georgian":"დიზაინი","pronunciation":"დიზაინ","example_en":"She designed the website.","example_ka":"მან ვებსაიტი დააპროექტა.","category":"top-5000","level":"B1"},
{"english":"destroy","georgian":"განადგურება","pronunciation":"დისთროი","example_en":"War destroys everything.","example_ka":"ომი ყველაფერს ანადგურებს.","category":"top-5000","level":"B1"},
{"english":"discover","georgian":"აღმოჩენა","pronunciation":"დისქავერ","example_en":"I discovered a new place.","example_ka":"ახალი ადგილი აღმოვაჩინე.","category":"top-5000","level":"B1"},
{"english":"discuss","georgian":"განხილვა","pronunciation":"დისქას","example_en":"Let's discuss it.","example_ka":"მოდი, განვიხილოთ.","category":"top-5000","level":"B1"},
{"english":"earn","georgian":"შოვნა","pronunciation":"ერნ","example_en":"I earn good money.","example_ka":"კარგ ფულს ვშოულობ.","category":"top-5000","level":"B1"},
{"english":"encourage","georgian":"წახალისება","pronunciation":"ინქარიჯ","example_en":"I encourage you to try.","example_ka":"გიწახალისებ სცადო.","category":"top-5000","level":"B1"},
{"english":"establish","georgian":"დაარსება","pronunciation":"ისთებლიშ","example_en":"They established a company.","example_ka":"კომპანია დაარსეს.","category":"top-5000","level":"B1"},
{"english":"examine","georgian":"გამოკვლევა","pronunciation":"იგზემინ","example_en":"The doctor examined me.","example_ka":"ექიმმა გამომიკვლია.","category":"top-5000","level":"B1"},
{"english":"exist","georgian":"არსებობა","pronunciation":"იგზისთ","example_en":"Dinosaurs no longer exist.","example_ka":"დინოზავრები აღარ არსებობენ.","category":"top-5000","level":"B1"},
{"english":"express","georgian":"გამოხატვა","pronunciation":"იქსფრეს","example_en":"Express your feelings.","example_ka":"გრძნობები გამოხატე.","category":"top-5000","level":"B1"},
{"english":"fail","georgian":"ჩავარდნა","pronunciation":"ფეილ","example_en":"Don't be afraid to fail.","example_ka":"ნუ გეშინია წარუმატებლობის.","category":"top-5000","level":"B1"},
{"english":"gain","georgian":"მოპოვება","pronunciation":"გეინ","example_en":"I gained experience.","example_ka":"გამოცდილება მივიღე.","category":"top-5000","level":"B1"},
{"english":"gather","georgian":"შეკრება","pronunciation":"გეძერ","example_en":"People gathered in the park.","example_ka":"ხალხი პარკში შეიკრიბა.","category":"top-5000","level":"B1"},
{"english":"handle","georgian":"გამკლავება","pronunciation":"ჰენდლ","example_en":"I can handle it.","example_ka":"გავუმკლავდები.","category":"top-5000","level":"B1"},
{"english":"identify","georgian":"იდენტიფიცირება","pronunciation":"აიდენთიფაი","example_en":"Identify the problem.","example_ka":"პრობლემა გამოავლინე.","category":"top-5000","level":"B1"},
{"english":"ignore","georgian":"უგულებელყოფა","pronunciation":"იგნორ","example_en":"Don't ignore me.","example_ka":"ნუ მიგნორებ.","category":"top-5000","level":"B1"},
{"english":"imagine","georgian":"წარმოდგენა","pronunciation":"იმეჯინ","example_en":"Imagine a better world.","example_ka":"წარმოიდგინე უკეთესი სამყარო.","category":"top-5000","level":"B1"},
{"english":"improve","georgian":"გაუმჯობესება","pronunciation":"იმფრუვ","example_en":"I want to improve my English.","example_ka":"ინგლისურის გაუმჯობესება მინდა.","category":"top-5000","level":"B1"},
{"english":"increase","georgian":"ზრდა","pronunciation":"ინქრის","example_en":"Prices increased.","example_ka":"ფასები გაიზარდა.","category":"top-5000","level":"B1"},
{"english":"indicate","georgian":"მიუთითებს","pronunciation":"ინდიქეით","example_en":"The sign indicates danger.","example_ka":"ნიშანი საფრთხეზე მიუთითებს.","category":"top-5000","level":"B1"},
{"english":"influence","georgian":"გავლენა","pronunciation":"ინფლუენს","example_en":"Music influences my mood.","example_ka":"მუსიკა ჩემს განწყობაზე მოქმედებს.","category":"top-5000","level":"B1"},
{"english":"insist","georgian":"დაჟინება","pronunciation":"ინსისთ","example_en":"I insist on going.","example_ka":"წასვლაზე ვჟინავ.","category":"top-5000","level":"B1"},
{"english":"intend","georgian":"აპირებს","pronunciation":"ინთენდ","example_en":"I intend to finish today.","example_ka":"დღეს დასრულებას ვაპირებ.","category":"top-5000","level":"B1"},
{"english":"introduce","georgian":"გაცნობა / წარდგენა","pronunciation":"ინთროდიუს","example_en":"Let me introduce myself.","example_ka":"ნება მიბოძეთ წარმოგიდგინო თავი.","category":"top-5000","level":"B1"},
{"english":"invest","georgian":"ინვესტირება","pronunciation":"ინვესთ","example_en":"Invest in your future.","example_ka":"მომავალში დააბანდე.","category":"top-5000","level":"B1"},
{"english":"involve","georgian":"ჩართვა","pronunciation":"ინვოლვ","example_en":"This involves everyone.","example_ka":"ეს ყველას ეხება.","category":"top-5000","level":"B1"},
{"english":"manage","georgian":"მართვა","pronunciation":"მენიჯ","example_en":"I manage a team.","example_ka":"გუნდს ვმართავ.","category":"top-5000","level":"B1"},
{"english":"measure","georgian":"გაზომვა","pronunciation":"მეჟერ","example_en":"Measure the distance.","example_ka":"მანძილი გაზომე.","category":"top-5000","level":"B1"},
{"english":"mention","georgian":"ხსენება","pronunciation":"მენშენ","example_en":"He mentioned your name.","example_ka":"მან შენი სახელი ახსენა.","category":"top-5000","level":"B1"},
{"english":"notice","georgian":"შემჩნევა","pronunciation":"ნოთის","example_en":"I noticed a mistake.","example_ka":"შეცდომა შევამჩნიე.","category":"top-5000","level":"B1"},
{"english":"obtain","georgian":"მიღება / მოპოვება","pronunciation":"ობთეინ","example_en":"I obtained permission.","example_ka":"ნებართვა მივიღე.","category":"top-5000","level":"B1"},
{"english":"occur","georgian":"მოხდა","pronunciation":"ოქერ","example_en":"An accident occurred.","example_ka":"ავარია მოხდა.","category":"top-5000","level":"B1"},
{"english":"organize","georgian":"ორგანიზება","pronunciation":"ორგენაიზ","example_en":"Organize your time.","example_ka":"დროის ორგანიზება გაუკეთე.","category":"top-5000","level":"B1"},
{"english":"perform","georgian":"შესრულება","pronunciation":"ფერფორმ","example_en":"She performed well.","example_ka":"მან კარგად შეასრულა.","category":"top-5000","level":"B1"},
{"english":"permit","georgian":"ნებართვა","pronunciation":"ფერმით","example_en":"Smoking is not permitted.","example_ka":"მოწევა აკრძალულია.","category":"top-5000","level":"B1"},
{"english":"persuade","georgian":"დარწმუნება","pronunciation":"ფერსუეიდ","example_en":"I persuaded him to stay.","example_ka":"დავარწმუნე დარჩენილიყო.","category":"top-5000","level":"B1"},
{"english":"predict","georgian":"პროგნოზირება","pronunciation":"ფრიდიქთ","example_en":"It's hard to predict.","example_ka":"პროგნოზირება რთულია.","category":"top-5000","level":"B1"},
{"english":"prefer","georgian":"ურჩევნია","pronunciation":"ფრიფერ","example_en":"I prefer tea.","example_ka":"ჩაი მირჩევნია.","category":"top-5000","level":"B1"},
{"english":"prepare","georgian":"მომზადება","pronunciation":"ფრიფეარ","example_en":"Prepare for the exam.","example_ka":"გამოცდისთვის მოემზადე.","category":"top-5000","level":"B1"},
{"english":"present","georgian":"წარდგენა / საჩუქარი","pronunciation":"ფრეზენთ","example_en":"I present the results.","example_ka":"შედეგებს წარმოგიდგენთ.","category":"top-5000","level":"B1"},
{"english":"prevent","georgian":"აღკვეთა","pronunciation":"ფრივენთ","example_en":"Prevent accidents.","example_ka":"ავარიების თავიდან აცილება.","category":"top-5000","level":"B1"},
{"english":"promise","georgian":"დაპირება","pronunciation":"ფრომის","example_en":"I promise to help.","example_ka":"გპირდები, დაგეხმარები.","category":"top-5000","level":"B1"},
{"english":"protect","georgian":"დაცვა","pronunciation":"ფროთექთ","example_en":"Protect the environment.","example_ka":"გარემო დაიცავი.","category":"top-5000","level":"B1"},
{"english":"prove","georgian":"დამტკიცება","pronunciation":"ფრუვ","example_en":"Prove it.","example_ka":"დაამტკიცე.","category":"top-5000","level":"B1"},
{"english":"publish","georgian":"გამოქვეყნება","pronunciation":"ფაბლიშ","example_en":"She published a book.","example_ka":"მან წიგნი გამოაქვეყნა.","category":"top-5000","level":"B1"},
{"english":"recommend","georgian":"რეკომენდაცია","pronunciation":"რეკომენდ","example_en":"I recommend this book.","example_ka":"ამ წიგნს გირჩევ.","category":"top-5000","level":"B1"},
{"english":"reduce","georgian":"შემცირება","pronunciation":"რიდიუს","example_en":"Reduce your expenses.","example_ka":"ხარჯები შეამცირე.","category":"top-5000","level":"B1"},
{"english":"reflect","georgian":"ასახვა / ფიქრი","pronunciation":"რიფლექთ","example_en":"The mirror reflects light.","example_ka":"სარკე სინათლეს ასახავს.","category":"top-5000","level":"B1"},
{"english":"refuse","georgian":"უარი","pronunciation":"რიფიუზ","example_en":"He refused to help.","example_ka":"მან დახმარებაზე უარი თქვა.","category":"top-5000","level":"B1"},
{"english":"relate","georgian":"დაკავშირება","pronunciation":"რილეით","example_en":"These ideas relate to each other.","example_ka":"ეს იდეები ერთმანეთთან არის დაკავშირებული.","category":"top-5000","level":"B1"},
{"english":"release","georgian":"გამოშვება","pronunciation":"რილის","example_en":"They released a new song.","example_ka":"ახალი სიმღერა გამოუშვეს.","category":"top-5000","level":"B1"},
{"english":"rely","georgian":"ენდობა","pronunciation":"რილაი","example_en":"I rely on you.","example_ka":"შენ გენდობი.","category":"top-5000","level":"B1"},
{"english":"replace","georgian":"შეცვლა","pronunciation":"რიფლეის","example_en":"Replace the old one.","example_ka":"ძველი შეცვალე.","category":"top-5000","level":"B1"},
{"english":"represent","georgian":"წარმოადგენს","pronunciation":"რეფრიზენთ","example_en":"He represents our company.","example_ka":"ის ჩვენს კომპანიას წარმოადგენს.","category":"top-5000","level":"B1"},
{"english":"request","georgian":"მოთხოვნა","pronunciation":"რიქვესთ","example_en":"I request your help.","example_ka":"შენი დახმარების მოთხოვნა მინდა.","category":"top-5000","level":"B1"},
{"english":"respond","georgian":"პასუხი","pronunciation":"რისფონდ","example_en":"Please respond quickly.","example_ka":"გთხოვთ სწრაფად უპასუხეთ.","category":"top-5000","level":"B1"},
{"english":"reveal","georgian":"გამჟღავნება","pronunciation":"რივილ","example_en":"He revealed the truth.","example_ka":"მან სიმართლე გამოამჟღავნა.","category":"top-5000","level":"B1"},
{"english":"satisfy","georgian":"დაკმაყოფილება","pronunciation":"სეთისფაი","example_en":"The answer satisfied me.","example_ka":"პასუხმა დამაკმაყოფილა.","category":"top-5000","level":"B1"},
{"english":"search","georgian":"ძებნა","pronunciation":"სერჩ","example_en":"Search for information.","example_ka":"ინფორმაცია მოძებნე.","category":"top-5000","level":"B1"},
{"english":"select","georgian":"შერჩევა","pronunciation":"სილექთ","example_en":"Select the best option.","example_ka":"საუკეთესო ვარიანტი აირჩიე.","category":"top-5000","level":"B1"},
{"english":"share","georgian":"გაზიარება","pronunciation":"შეარ","example_en":"Share your thoughts.","example_ka":"აზრები გააზიარე.","category":"top-5000","level":"B1"},
{"english":"solve","georgian":"გადაჭრა","pronunciation":"სოლვ","example_en":"Solve the problem.","example_ka":"პრობლემა გადაჭერი.","category":"top-5000","level":"B1"},
{"english":"struggle","georgian":"ბრძოლა","pronunciation":"სთრაგლ","example_en":"He struggled to survive.","example_ka":"ის გადარჩენისთვის იბრძოდა.","category":"top-5000","level":"B1"},
{"english":"succeed","georgian":"წარმატება","pronunciation":"სექსიდ","example_en":"You will succeed.","example_ka":"წარმატებას მიაღწევ.","category":"top-5000","level":"B1"},
{"english":"suffer","georgian":"ტანჯვა","pronunciation":"საფერ","example_en":"He suffered from pain.","example_ka":"ის ტკივილით იტანჯებოდა.","category":"top-5000","level":"B1"},
{"english":"supply","georgian":"მიწოდება","pronunciation":"სეფლაი","example_en":"Supply food and water.","example_ka":"საკვები და წყალი მიაწოდე.","category":"top-5000","level":"B1"},
{"english":"suppose","georgian":"ვარაუდი","pronunciation":"სეფოუზ","example_en":"I suppose you are right.","example_ka":"ვვარაუდობ, რომ მართალი ხარ.","category":"top-5000","level":"B1"},
{"english":"survive","georgian":"გადარჩენა","pronunciation":"სერვაივ","example_en":"He survived the accident.","example_ka":"ის ავარიას გადაურჩა.","category":"top-5000","level":"B1"},
{"english":"suspect","georgian":"ეჭვი","pronunciation":"სესფექთ","example_en":"I suspect he is lying.","example_ka":"მეჭვება, რომ ტყუის.","category":"top-5000","level":"B1"},
{"english":"threaten","georgian":"მუქარა","pronunciation":"თრეთენ","example_en":"Don't threaten me.","example_ka":"ნუ მემუქრები.","category":"top-5000","level":"B1"},
{"english":"transfer","georgian":"გადატანა","pronunciation":"თრენსფერ","example_en":"Transfer the money.","example_ka":"ფული გადარიცხე.","category":"top-5000","level":"B1"},
{"english":"translate","georgian":"თარგმნა","pronunciation":"თრენსლეით","example_en":"Translate this text.","example_ka":"ეს ტექსტი გადათარგმნე.","category":"top-5000","level":"B1"},
{"english":"treat","georgian":"მოპყრობა","pronunciation":"თრით","example_en":"Treat people with respect.","example_ka":"ხალხს პატივისცემით მოეპყარი.","category":"top-5000","level":"B1"},
{"english":"warn","georgian":"გაფრთხილება","pronunciation":"ვორნ","example_en":"I warned you.","example_ka":"გაგაფრთხილე.","category":"top-5000","level":"B1"},
{"english":"wonder","georgian":"კითხვის დასმა / გაოცება","pronunciation":"ვანდერ","example_en":"I wonder why.","example_ka":"საინტერესოა, რატომ.","category":"top-5000","level":"B1"},
# B1 nouns
{"english":"accident","georgian":"ავარია / უბედური შემთხვევა","pronunciation":"ექსიდენთ","example_en":"There was an accident.","example_ka":"ავარია მოხდა.","category":"top-5000","level":"B1"},
{"english":"advantage","georgian":"უპირატესობა","pronunciation":"ედვანთიჯ","example_en":"It's an advantage.","example_ka":"ეს უპირატესობაა.","category":"top-5000","level":"B1"},
{"english":"agreement","georgian":"შეთანხმება","pronunciation":"ეგრიმენთ","example_en":"We signed an agreement.","example_ka":"შეთანხმება ხელი მოვაწერეთ.","category":"top-5000","level":"B1"},
{"english":"army","georgian":"ჯარი","pronunciation":"არმი","example_en":"He joined the army.","example_ka":"ის ჯარში წავიდა.","category":"top-5000","level":"B1"},
{"english":"attitude","georgian":"დამოკიდებულება","pronunciation":"ეთიტიუდ","example_en":"Change your attitude.","example_ka":"დამოკიდებულება შეიცვალე.","category":"top-5000","level":"B1"},
{"english":"audience","georgian":"აუდიტორია","pronunciation":"ოდიენს","example_en":"The audience applauded.","example_ka":"აუდიტორიამ იტაშა.","category":"top-5000","level":"B1"},
{"english":"average","georgian":"საშუალო","pronunciation":"ევერიჯ","example_en":"The average price.","example_ka":"საშუალო ფასი.","category":"top-5000","level":"B1"},
{"english":"background","georgian":"ფონი / წარსული","pronunciation":"ბექგრაუნდ","example_en":"Tell me about your background.","example_ka":"მომიყევი შენი წარსულის შესახებ.","category":"top-5000","level":"B1"},
{"english":"behavior","georgian":"ქცევა","pronunciation":"ბიჰეივიერ","example_en":"Good behavior is important.","example_ka":"კარგი ქცევა მნიშვნელოვანია.","category":"top-5000","level":"B1"},
{"english":"benefit","georgian":"სარგებელი","pronunciation":"ბენიფით","example_en":"The benefits are clear.","example_ka":"სარგებელი ნათელია.","category":"top-5000","level":"B1"},
{"english":"border","georgian":"საზღვარი","pronunciation":"ბორდერ","example_en":"We crossed the border.","example_ka":"საზღვარი გადავკვეთეთ.","category":"top-5000","level":"B1"},
{"english":"brain","georgian":"ტვინი","pronunciation":"ბრეინ","example_en":"Use your brain.","example_ka":"ტვინი გამოიყენე.","category":"top-5000","level":"B1"},
{"english":"budget","georgian":"ბიუჯეტი","pronunciation":"ბაჯეთ","example_en":"Stay within the budget.","example_ka":"ბიუჯეტის ფარგლებში დარჩი.","category":"top-5000","level":"B1"},
{"english":"campaign","georgian":"კამპანია","pronunciation":"ქემფეინ","example_en":"The election campaign.","example_ka":"საარჩევნო კამპანია.","category":"top-5000","level":"B1"},
{"english":"career","georgian":"კარიერა","pronunciation":"ქერიერ","example_en":"Build your career.","example_ka":"კარიერა ააშენე.","category":"top-5000","level":"B1"},
{"english":"character","georgian":"პერსონაჟი / ხასიათი","pronunciation":"ქერექთერ","example_en":"He has a strong character.","example_ka":"ძლიერი ხასიათი აქვს.","category":"top-5000","level":"B1"},
{"english":"climate","georgian":"კლიმატი","pronunciation":"ქლაიმეთ","example_en":"The climate is changing.","example_ka":"კლიმატი იცვლება.","category":"top-5000","level":"B1"},
{"english":"coast","georgian":"სანაპირო","pronunciation":"ქოუსთ","example_en":"The coast is beautiful.","example_ka":"სანაპირო ლამაზია.","category":"top-5000","level":"B1"},
{"english":"competition","georgian":"კონკურენცია","pronunciation":"ქომფეთიშენ","example_en":"The competition is strong.","example_ka":"კონკურენცია ძლიერია.","category":"top-5000","level":"B1"},
{"english":"condition","georgian":"მდგომარეობა / პირობა","pronunciation":"ქონდიშენ","example_en":"The condition is good.","example_ka":"მდგომარეობა კარგია.","category":"top-5000","level":"B1"},
{"english":"conflict","georgian":"კონფლიქტი","pronunciation":"ქონფლიქთ","example_en":"Avoid conflict.","example_ka":"კონფლიქტს თავი აარიდე.","category":"top-5000","level":"B1"},
{"english":"connection","georgian":"კავშირი","pronunciation":"ქონექშენ","example_en":"I have no internet connection.","example_ka":"ინტერნეტ კავშირი არ მაქვს.","category":"top-5000","level":"B1"},
{"english":"consequence","georgian":"შედეგი","pronunciation":"ქონსიქვენს","example_en":"Every action has consequences.","example_ka":"ყოველ მოქმედებას შედეგი აქვს.","category":"top-5000","level":"B1"},
{"english":"conversation","georgian":"საუბარი","pronunciation":"ქონვერსეიშენ","example_en":"We had a nice conversation.","example_ka":"კარგი საუბარი გვქონდა.","category":"top-5000","level":"B1"},
{"english":"crisis","georgian":"კრიზისი","pronunciation":"ქრაისის","example_en":"An economic crisis.","example_ka":"ეკონომიკური კრიზისი.","category":"top-5000","level":"B1"},
{"english":"culture","georgian":"კულტურა","pronunciation":"ქალჩერ","example_en":"Georgian culture is rich.","example_ka":"ქართული კულტურა მდიდარია.","category":"top-5000","level":"B1"},
{"english":"customer","georgian":"მომხმარებელი","pronunciation":"ქასთომერ","example_en":"The customer is always right.","example_ka":"მომხმარებელი ყოველთვის მართალია.","category":"top-5000","level":"B1"},
{"english":"debate","georgian":"დებატები","pronunciation":"დიბეით","example_en":"A political debate.","example_ka":"პოლიტიკური დებატები.","category":"top-5000","level":"B1"},
{"english":"decision","georgian":"გადაწყვეტილება","pronunciation":"დისიჟენ","example_en":"Make a decision.","example_ka":"გადაწყვეტილება მიიღე.","category":"top-5000","level":"B1"},
{"english":"defense","georgian":"თავდაცვა","pronunciation":"დიფენს","example_en":"National defense.","example_ka":"ეროვნული თავდაცვა.","category":"top-5000","level":"B1"},
{"english":"degree","georgian":"ხარისხი / გრადუსი","pronunciation":"დიგრი","example_en":"She has a university degree.","example_ka":"მას უნივერსიტეტის ხარისხი აქვს.","category":"top-5000","level":"B1"},
{"english":"development","georgian":"განვითარება","pronunciation":"დიველოფმენთ","example_en":"Economic development.","example_ka":"ეკონომიკური განვითარება.","category":"top-5000","level":"B1"},
{"english":"difference","georgian":"განსხვავება","pronunciation":"დიფერენს","example_en":"What is the difference?","example_ka":"რა განსხვავებაა?","category":"top-5000","level":"B1"},
{"english":"direction","georgian":"მიმართულება","pronunciation":"დირექშენ","example_en":"What direction should I go?","example_ka":"რომელი მიმართულებით წავიდე?","category":"top-5000","level":"B1"},
{"english":"distance","georgian":"მანძილი","pronunciation":"დისთანს","example_en":"The distance is 5 km.","example_ka":"მანძილი 5 კმ-ია.","category":"top-5000","level":"B1"},
{"english":"economy","georgian":"ეკონომიკა","pronunciation":"იქონომი","example_en":"The economy is growing.","example_ka":"ეკონომიკა იზრდება.","category":"top-5000","level":"B1"},
{"english":"edge","georgian":"კიდე / პირი","pronunciation":"ეჯ","example_en":"The edge of the table.","example_ka":"მაგიდის კიდე.","category":"top-5000","level":"B1"},
{"english":"effect","georgian":"ეფექტი","pronunciation":"იფექთ","example_en":"The effect is clear.","example_ka":"ეფექტი ნათელია.","category":"top-5000","level":"B1"},
{"english":"election","georgian":"არჩევნები","pronunciation":"ილექშენ","example_en":"The election is next week.","example_ka":"არჩევნები მომავალ კვირაშია.","category":"top-5000","level":"B1"},
{"english":"emotion","georgian":"ემოცია","pronunciation":"იმოუშენ","example_en":"Show your emotions.","example_ka":"ემოციები გამოხატე.","category":"top-5000","level":"B1"},
{"english":"employee","georgian":"თანამშრომელი","pronunciation":"ემფლოიი","example_en":"A new employee started today.","example_ka":"ახალი თანამშრომელი დღეს დაიწყო.","category":"top-5000","level":"B1"},
{"english":"energy","georgian":"ენერგია","pronunciation":"ენერჯი","example_en":"Save energy.","example_ka":"ენერგია დაზოგე.","category":"top-5000","level":"B1"},
{"english":"environment","georgian":"გარემო","pronunciation":"ინვაირონმენთ","example_en":"Protect the environment.","example_ka":"გარემო დაიცავი.","category":"top-5000","level":"B1"},
{"english":"equipment","georgian":"აღჭურვილობა","pronunciation":"იქვიფმენთ","example_en":"We need new equipment.","example_ka":"ახალი აღჭურვილობა გვჭირდება.","category":"top-5000","level":"B1"},
{"english":"evidence","georgian":"მტკიცებულება","pronunciation":"ევიდენს","example_en":"There is no evidence.","example_ka":"მტკიცებულება არ არსებობს.","category":"top-5000","level":"B1"},
{"english":"exchange","georgian":"გაცვლა","pronunciation":"იქსჩეინჯ","example_en":"Exchange ideas.","example_ka":"იდეების გაცვლა.","category":"top-5000","level":"B1"},
{"english":"feature","georgian":"მახასიათებელი","pronunciation":"ფიჩერ","example_en":"An important feature.","example_ka":"მნიშვნელოვანი მახასიათებელი.","category":"top-5000","level":"B1"},
{"english":"figure","georgian":"ფიგურა / რიცხვი","pronunciation":"ფიგერ","example_en":"A public figure.","example_ka":"საზოგადო მოღვაწე.","category":"top-5000","level":"B1"},
{"english":"freedom","georgian":"თავისუფლება","pronunciation":"ფრიდომ","example_en":"Freedom is important.","example_ka":"თავისუფლება მნიშვნელოვანია.","category":"top-5000","level":"B1"},
{"english":"generation","georgian":"თაობა","pronunciation":"ჯენერეიშენ","example_en":"The younger generation.","example_ka":"ახალგაზრდა თაობა.","category":"top-5000","level":"B1"},
{"english":"goal","georgian":"მიზანი","pronunciation":"გოლ","example_en":"Set a goal.","example_ka":"მიზანი დასახე.","category":"top-5000","level":"B1"},
{"english":"growth","georgian":"ზრდა","pronunciation":"გროუთ","example_en":"Economic growth.","example_ka":"ეკონომიკური ზრდა.","category":"top-5000","level":"B1"},
{"english":"guide","georgian":"გზამკვლევი","pronunciation":"გაიდ","example_en":"A travel guide.","example_ka":"სამოგზაურო გზამკვლევი.","category":"top-5000","level":"B1"},
{"english":"habit","georgian":"ჩვევა","pronunciation":"ჰებით","example_en":"A bad habit.","example_ka":"ცუდი ჩვევა.","category":"top-5000","level":"B1"},
{"english":"image","georgian":"სურათი / იმიჯი","pronunciation":"იმიჯ","example_en":"A clear image.","example_ka":"ნათელი სურათი.","category":"top-5000","level":"B1"},
{"english":"impact","georgian":"გავლენა","pronunciation":"იმფექთ","example_en":"A big impact.","example_ka":"დიდი გავლენა.","category":"top-5000","level":"B1"},
{"english":"income","georgian":"შემოსავალი","pronunciation":"ინქამ","example_en":"My income increased.","example_ka":"ჩემი შემოსავალი გაიზარდა.","category":"top-5000","level":"B1"},
{"english":"industry","georgian":"მრეწველობა","pronunciation":"ინდასთრი","example_en":"The food industry.","example_ka":"კვების მრეწველობა.","category":"top-5000","level":"B1"},
{"english":"injury","georgian":"ტრავმა","pronunciation":"ინჯერი","example_en":"He has a leg injury.","example_ka":"მას ფეხის ტრავმა აქვს.","category":"top-5000","level":"B1"},
{"english":"justice","georgian":"სამართალი","pronunciation":"ჯასთის","example_en":"Justice must prevail.","example_ka":"სამართალმა უნდა იზეიმოს.","category":"top-5000","level":"B1"},
{"english":"knowledge","georgian":"ცოდნა","pronunciation":"ნოლიჯ","example_en":"Knowledge is power.","example_ka":"ცოდნა ძალაა.","category":"top-5000","level":"B1"},
{"english":"labor","georgian":"შრომა","pronunciation":"ლეიბერ","example_en":"Physical labor.","example_ka":"ფიზიკური შრომა.","category":"top-5000","level":"B1"},
{"english":"lack","georgian":"ნაკლებობა","pronunciation":"ლექ","example_en":"Lack of time.","example_ka":"დროის ნაკლებობა.","category":"top-5000","level":"B1"},
{"english":"lesson","georgian":"გაკვეთილი","pronunciation":"ლესენ","example_en":"English lesson.","example_ka":"ინგლისურის გაკვეთილი.","category":"top-5000","level":"B1"},
{"english":"limit","georgian":"ლიმიტი / ზღვარი","pronunciation":"ლიმით","example_en":"There is a limit.","example_ka":"ზღვარი არსებობს.","category":"top-5000","level":"B1"},
{"english":"loss","georgian":"დანაკარგი","pronunciation":"ლოს","example_en":"A big loss.","example_ka":"დიდი დანაკარგი.","category":"top-5000","level":"B1"},
{"english":"majority","georgian":"უმრავლესობა","pronunciation":"მეჯორითი","example_en":"The majority agreed.","example_ka":"უმრავლესობა დაეთანხმა.","category":"top-5000","level":"B1"},
{"english":"memory","georgian":"მეხსიერება","pronunciation":"მემორი","example_en":"I have a good memory.","example_ka":"კარგი მეხსიერება მაქვს.","category":"top-5000","level":"B1"},
{"english":"method","georgian":"მეთოდი","pronunciation":"მეთოდ","example_en":"A new method.","example_ka":"ახალი მეთოდი.","category":"top-5000","level":"B1"},
{"english":"million","georgian":"მილიონი","pronunciation":"მილიენ","example_en":"A million dollars.","example_ka":"მილიონი დოლარი.","category":"top-5000","level":"B1"},
{"english":"mistake","georgian":"შეცდომა","pronunciation":"მისთეიქ","example_en":"I made a mistake.","example_ka":"შეცდომა დავუშვი.","category":"top-5000","level":"B1"},
{"english":"model","georgian":"მოდელი","pronunciation":"მოდელ","example_en":"A new car model.","example_ka":"მანქანის ახალი მოდელი.","category":"top-5000","level":"B1"},
{"english":"movement","georgian":"მოძრაობა","pronunciation":"მუვმენთ","example_en":"A political movement.","example_ka":"პოლიტიკური მოძრაობა.","category":"top-5000","level":"B1"},
{"english":"nation","georgian":"ერი","pronunciation":"ნეიშენ","example_en":"A strong nation.","example_ka":"ძლიერი ერი.","category":"top-5000","level":"B1"},
{"english":"nature","georgian":"ბუნება","pronunciation":"ნეიჩერ","example_en":"I love nature.","example_ka":"ბუნება მიყვარს.","category":"top-5000","level":"B1"},
{"english":"network","georgian":"ქსელი","pronunciation":"ნეთვორქ","example_en":"A social network.","example_ka":"სოციალური ქსელი.","category":"top-5000","level":"B1"},
{"english":"object","georgian":"საგანი / ობიექტი","pronunciation":"ობჯექთ","example_en":"A strange object.","example_ka":"უცნაური საგანი.","category":"top-5000","level":"B1"},
{"english":"opinion","georgian":"აზრი","pronunciation":"ოფინიენ","example_en":"In my opinion.","example_ka":"ჩემი აზრით.","category":"top-5000","level":"B1"},
{"english":"opportunity","georgian":"შესაძლებლობა","pronunciation":"ოფორთიუნითი","example_en":"A great opportunity.","example_ka":"შესანიშნავი შესაძლებლობა.","category":"top-5000","level":"B1"},
{"english":"organization","georgian":"ორგანიზაცია","pronunciation":"ორგენიზეიშენ","example_en":"A big organization.","example_ka":"დიდი ორგანიზაცია.","category":"top-5000","level":"B1"},
{"english":"pattern","georgian":"ნიმუში / მოდელი","pronunciation":"ფეთერნ","example_en":"A pattern of behavior.","example_ka":"ქცევის მოდელი.","category":"top-5000","level":"B1"},
{"english":"period","georgian":"პერიოდი","pronunciation":"ფირიედ","example_en":"A long period.","example_ka":"ხანგრძლივი პერიოდი.","category":"top-5000","level":"B1"},
{"english":"pleasure","georgian":"სიამოვნება","pronunciation":"ფლეჟერ","example_en":"It's my pleasure.","example_ka":"სიამოვნებაა.","category":"top-5000","level":"B1"},
{"english":"policy","georgian":"პოლიტიკა","pronunciation":"ფოლისი","example_en":"Government policy.","example_ka":"სამთავრობო პოლიტიკა.","category":"top-5000","level":"B1"},
{"english":"population","georgian":"მოსახლეობა","pronunciation":"ფოფიულეიშენ","example_en":"The world population.","example_ka":"მსოფლიო მოსახლეობა.","category":"top-5000","level":"B1"},
{"english":"position","georgian":"პოზიცია / თანამდებობა","pronunciation":"ფოზიშენ","example_en":"A good position.","example_ka":"კარგი თანამდებობა.","category":"top-5000","level":"B1"},
{"english":"pressure","georgian":"ზეწოლა","pronunciation":"ფრეშერ","example_en":"Under pressure.","example_ka":"ზეწოლის ქვეშ.","category":"top-5000","level":"B1"},
{"english":"principle","georgian":"პრინციპი","pronunciation":"ფრინსიფალ","example_en":"A basic principle.","example_ka":"ძირითადი პრინციპი.","category":"top-5000","level":"B1"},
{"english":"process","georgian":"პროცესი","pronunciation":"ფროსეს","example_en":"A long process.","example_ka":"ხანგრძლივი პროცესი.","category":"top-5000","level":"B1"},
{"english":"production","georgian":"წარმოება","pronunciation":"ფროდაქშენ","example_en":"Food production.","example_ka":"საკვების წარმოება.","category":"top-5000","level":"B1"},
{"english":"profit","georgian":"მოგება","pronunciation":"ფროფით","example_en":"The company made a profit.","example_ka":"კომპანიამ მოგება მიიღო.","category":"top-5000","level":"B1"},
{"english":"progress","georgian":"პროგრესი","pronunciation":"ფროგრეს","example_en":"We made progress.","example_ka":"პროგრესი მივიღწიეთ.","category":"top-5000","level":"B1"},
{"english":"project","georgian":"პროექტი","pronunciation":"ფროჯექთ","example_en":"A new project.","example_ka":"ახალი პროექტი.","category":"top-5000","level":"B1"},
{"english":"property","georgian":"ქონება / საკუთრება","pronunciation":"ფროფერთი","example_en":"Private property.","example_ka":"კერძო საკუთრება.","category":"top-5000","level":"B1"},
{"english":"quality","georgian":"ხარისხი","pronunciation":"ქვალითი","example_en":"High quality.","example_ka":"მაღალი ხარისხი.","category":"top-5000","level":"B1"},
{"english":"reality","georgian":"რეალობა","pronunciation":"რიელითი","example_en":"Face reality.","example_ka":"რეალობას შეხედე.","category":"top-5000","level":"B1"},
{"english":"reform","georgian":"რეფორმა","pronunciation":"რიფორმ","example_en":"Economic reform.","example_ka":"ეკონომიკური რეფორმა.","category":"top-5000","level":"B1"},
{"english":"region","georgian":"რეგიონი","pronunciation":"რიჯენ","example_en":"A mountainous region.","example_ka":"მთიანი რეგიონი.","category":"top-5000","level":"B1"},
{"english":"relationship","georgian":"ურთიერთობა","pronunciation":"რილეიშენშიფ","example_en":"A good relationship.","example_ka":"კარგი ურთიერთობა.","category":"top-5000","level":"B1"},
{"english":"religion","georgian":"რელიგია","pronunciation":"რილიჯენ","example_en":"Freedom of religion.","example_ka":"რელიგიის თავისუფლება.","category":"top-5000","level":"B1"},
{"english":"resource","georgian":"რესურსი","pronunciation":"რისორს","example_en":"Natural resources.","example_ka":"ბუნებრივი რესურსები.","category":"top-5000","level":"B1"},
{"english":"response","georgian":"პასუხი / რეაქცია","pronunciation":"რისფონს","example_en":"No response.","example_ka":"პასუხი არ მიმიღია.","category":"top-5000","level":"B1"},
{"english":"responsibility","georgian":"პასუხისმგებლობა","pronunciation":"რისფონსიბილითი","example_en":"Take responsibility.","example_ka":"პასუხისმგებლობა აიღე.","category":"top-5000","level":"B1"},
{"english":"revolution","georgian":"რევოლუცია","pronunciation":"რევოლუშენ","example_en":"A technological revolution.","example_ka":"ტექნოლოგიური რევოლუცია.","category":"top-5000","level":"B1"},
{"english":"risk","georgian":"რისკი","pronunciation":"რისქ","example_en":"Don't take the risk.","example_ka":"ნუ რისკავ.","category":"top-5000","level":"B1"},
{"english":"role","georgian":"როლი","pronunciation":"როულ","example_en":"An important role.","example_ka":"მნიშვნელოვანი როლი.","category":"top-5000","level":"B1"},
{"english":"rule","georgian":"წესი","pronunciation":"რულ","example_en":"Follow the rules.","example_ka":"წესები დაიცავი.","category":"top-5000","level":"B1"},
{"english":"safety","georgian":"უსაფრთხოება","pronunciation":"სეიფთი","example_en":"Safety first.","example_ka":"უსაფრთხოება პირველ რიგში.","category":"top-5000","level":"B1"},
{"english":"scene","georgian":"სცენა","pronunciation":"სინ","example_en":"A beautiful scene.","example_ka":"ლამაზი სცენა.","category":"top-5000","level":"B1"},
{"english":"science","georgian":"მეცნიერება","pronunciation":"საიენს","example_en":"I study science.","example_ka":"მეცნიერებას ვსწავლობ.","category":"top-5000","level":"B1"},
{"english":"secret","georgian":"საიდუმლო","pronunciation":"სიქრეთ","example_en":"Keep it a secret.","example_ka":"ეს საიდუმლოდ შეინახე.","category":"top-5000","level":"B1"},
{"english":"section","georgian":"სექცია / ნაწილი","pronunciation":"სექშენ","example_en":"The next section.","example_ka":"შემდეგი ნაწილი.","category":"top-5000","level":"B1"},
{"english":"security","georgian":"უსაფრთხოება","pronunciation":"სიქიურითი","example_en":"National security.","example_ka":"ეროვნული უსაფრთხოება.","category":"top-5000","level":"B1"},
{"english":"shape","georgian":"ფორმა","pronunciation":"შეიფ","example_en":"What shape is it?","example_ka":"რა ფორმისაა?","category":"top-5000","level":"B1"},
{"english":"situation","georgian":"სიტუაცია","pronunciation":"სიჩუეიშენ","example_en":"A difficult situation.","example_ka":"რთული სიტუაცია.","category":"top-5000","level":"B1"},
{"english":"skill","georgian":"უნარი","pronunciation":"სქილ","example_en":"Learn new skills.","example_ka":"ახალი უნარები ისწავლე.","category":"top-5000","level":"B1"},
{"english":"society","georgian":"საზოგადოება","pronunciation":"სოსაიეთი","example_en":"Modern society.","example_ka":"თანამედროვე საზოგადოება.","category":"top-5000","level":"B1"},
{"english":"solution","georgian":"გამოსავალი","pronunciation":"სოლუშენ","example_en":"Find a solution.","example_ka":"გამოსავალი იპოვე.","category":"top-5000","level":"B1"},
{"english":"source","georgian":"წყარო","pronunciation":"სორს","example_en":"A reliable source.","example_ka":"სანდო წყარო.","category":"top-5000","level":"B1"},
{"english":"spirit","georgian":"სულისკვეთება","pronunciation":"სფირით","example_en":"Team spirit.","example_ka":"გუნდური სულისკვეთება.","category":"top-5000","level":"B1"},
{"english":"standard","georgian":"სტანდარტი","pronunciation":"სთენდარდ","example_en":"High standards.","example_ka":"მაღალი სტანდარტები.","category":"top-5000","level":"B1"},
{"english":"statement","georgian":"განცხადება","pronunciation":"სთეითმენთ","example_en":"A public statement.","example_ka":"საჯარო განცხადება.","category":"top-5000","level":"B1"},
{"english":"strategy","georgian":"სტრატეგია","pronunciation":"სთრეთეჯი","example_en":"A good strategy.","example_ka":"კარგი სტრატეგია.","category":"top-5000","level":"B1"},
{"english":"structure","georgian":"სტრუქტურა","pronunciation":"სთრაქჩერ","example_en":"The structure of the building.","example_ka":"შენობის სტრუქტურა.","category":"top-5000","level":"B1"},
{"english":"success","georgian":"წარმატება","pronunciation":"სექსეს","example_en":"I wish you success.","example_ka":"წარმატებას გისურვებ.","category":"top-5000","level":"B1"},
{"english":"surface","georgian":"ზედაპირი","pronunciation":"სერფის","example_en":"A smooth surface.","example_ka":"გლუვი ზედაპირი.","category":"top-5000","level":"B1"},
{"english":"tax","georgian":"გადასახადი","pronunciation":"თექს","example_en":"Pay your taxes.","example_ka":"გადასახადები გადაიხადე.","category":"top-5000","level":"B1"},
{"english":"technology","georgian":"ტექნოლოგია","pronunciation":"თექნოლოჯი","example_en":"Modern technology.","example_ka":"თანამედროვე ტექნოლოგია.","category":"top-5000","level":"B1"},
{"english":"theory","georgian":"თეორია","pronunciation":"თიორი","example_en":"A new theory.","example_ka":"ახალი თეორია.","category":"top-5000","level":"B1"},
{"english":"threat","georgian":"საფრთხე","pronunciation":"თრეთ","example_en":"A serious threat.","example_ka":"სერიოზული საფრთხე.","category":"top-5000","level":"B1"},
{"english":"tradition","georgian":"ტრადიცია","pronunciation":"თრედიშენ","example_en":"An old tradition.","example_ka":"ძველი ტრადიცია.","category":"top-5000","level":"B1"},
{"english":"traffic","georgian":"ტრაფიკი / მოძრაობა","pronunciation":"თრეფიქ","example_en":"Traffic is heavy today.","example_ka":"დღეს მოძრაობა მძიმეა.","category":"top-5000","level":"B1"},
{"english":"truth","georgian":"სიმართლე","pronunciation":"თრუთ","example_en":"Tell the truth.","example_ka":"სიმართლე თქვი.","category":"top-5000","level":"B1"},
{"english":"valley","georgian":"ხეობა","pronunciation":"ველი","example_en":"A green valley.","example_ka":"მწვანე ხეობა.","category":"top-5000","level":"B1"},
{"english":"value","georgian":"ღირებულება","pronunciation":"ველიუ","example_en":"Family values.","example_ka":"ოჯახური ღირებულებები.","category":"top-5000","level":"B1"},
{"english":"version","georgian":"ვერსია","pronunciation":"ვერშენ","example_en":"A new version.","example_ka":"ახალი ვერსია.","category":"top-5000","level":"B1"},
{"english":"victim","georgian":"მსხვერპლი","pronunciation":"ვიქთიმ","example_en":"Help the victims.","example_ka":"მსხვერპლებს დაეხმარე.","category":"top-5000","level":"B1"},
{"english":"violence","georgian":"ძალადობა","pronunciation":"ვაიოლენს","example_en":"Stop violence.","example_ka":"ძალადობა შეაჩერე.","category":"top-5000","level":"B1"},
{"english":"wealth","georgian":"სიმდიდრე","pronunciation":"ველთ","example_en":"Wealth and health.","example_ka":"სიმდიდრე და ჯანმრთელობა.","category":"top-5000","level":"B1"},
{"english":"weapon","georgian":"იარაღი","pronunciation":"ვეფენ","example_en":"A dangerous weapon.","example_ka":"საშიში იარაღი.","category":"top-5000","level":"B1"},
{"english":"weight","georgian":"წონა","pronunciation":"ვეით","example_en":"Lose weight.","example_ka":"წონაში დაიკლე.","category":"top-5000","level":"B1"},
]

added = 0
for w in batch:
    key = w['english'].lower()
    if key not in existing:
        data.append(w)
        existing.add(key)
        added += 1

print(f"Added {added} new words from batch 3 (B1). Total: {len(data)}")

with open('/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/top-5000-words.json', 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved!")
