#!/usr/bin/env python3
import json

# Read existing
with open('/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/top-5000-words.json', 'r') as f:
    data = json.load(f)

existing = set(w['english'].lower() for w in data)
print(f"Starting with {len(data)} entries, {len(existing)} unique")

batch = [
{"english":"be","georgian":"ყოფნა","pronunciation":"ბი","example_en":"I want to be happy.","example_ka":"მე მინდა ბედნიერი ვიყო.","category":"top-5000","level":"A1"},
{"english":"have","georgian":"ქონა","pronunciation":"ჰევ","example_en":"I have a book.","example_ka":"მე მაქვს წიგნი.","category":"top-5000","level":"A1"},
{"english":"do","georgian":"კეთება","pronunciation":"დუ","example_en":"What do you do?","example_ka":"რას აკეთებ?","category":"top-5000","level":"A1"},
{"english":"not","georgian":"არა","pronunciation":"ნოთ","example_en":"I do not know.","example_ka":"მე არ ვიცი.","category":"top-5000","level":"A1"},
{"english":"he","georgian":"ის (მამრობითი)","pronunciation":"ჰი","example_en":"He is my friend.","example_ka":"ის ჩემი მეგობარია.","category":"top-5000","level":"A1"},
{"english":"she","georgian":"ის (მდედრობითი)","pronunciation":"ში","example_en":"She is a teacher.","example_ka":"ის მასწავლებელია.","category":"top-5000","level":"A1"},
{"english":"it","georgian":"ის (საგანი)","pronunciation":"ით","example_en":"It is raining.","example_ka":"წვიმს.","category":"top-5000","level":"A1"},
{"english":"we","georgian":"ჩვენ","pronunciation":"ვი","example_en":"We are students.","example_ka":"ჩვენ სტუდენტები ვართ.","category":"top-5000","level":"A1"},
{"english":"they","georgian":"ისინი","pronunciation":"ძეი","example_en":"They are coming.","example_ka":"ისინი მოდიან.","category":"top-5000","level":"A1"},
{"english":"you","georgian":"შენ / თქვენ","pronunciation":"იუ","example_en":"You are welcome.","example_ka":"არაფრის.","category":"top-5000","level":"A1"},
{"english":"I","georgian":"მე","pronunciation":"აი","example_en":"I am here.","example_ka":"მე აქ ვარ.","category":"top-5000","level":"A1"},
{"english":"this","georgian":"ეს","pronunciation":"ძის","example_en":"This is my house.","example_ka":"ეს ჩემი სახლია.","category":"top-5000","level":"A1"},
{"english":"that","georgian":"ის / რომ","pronunciation":"ძეთ","example_en":"That is interesting.","example_ka":"ის საინტერესოა.","category":"top-5000","level":"A1"},
{"english":"what","georgian":"რა","pronunciation":"ვოთ","example_en":"What is your name?","example_ka":"რა გქვია?","category":"top-5000","level":"A1"},
{"english":"which","georgian":"რომელი","pronunciation":"ვიჩ","example_en":"Which one do you want?","example_ka":"რომელი გინდა?","category":"top-5000","level":"A1"},
{"english":"who","georgian":"ვინ","pronunciation":"ჰუ","example_en":"Who is there?","example_ka":"ვინ არის იქ?","category":"top-5000","level":"A1"},
{"english":"when","georgian":"როდის","pronunciation":"ვენ","example_en":"When did you arrive?","example_ka":"როდის ჩამოხვედი?","category":"top-5000","level":"A1"},
{"english":"where","georgian":"სად","pronunciation":"ვეარ","example_en":"Where do you live?","example_ka":"სად ცხოვრობ?","category":"top-5000","level":"A1"},
{"english":"how","georgian":"როგორ","pronunciation":"ჰაუ","example_en":"How are you?","example_ka":"როგორ ხარ?","category":"top-5000","level":"A1"},
{"english":"why","georgian":"რატომ","pronunciation":"ვაი","example_en":"Why are you late?","example_ka":"რატომ დაგვიანდი?","category":"top-5000","level":"A1"},
{"english":"all","georgian":"ყველა","pronunciation":"ოლ","example_en":"All students passed.","example_ka":"ყველა სტუდენტმა ჩააბარა.","category":"top-5000","level":"A1"},
{"english":"can","georgian":"შეუძლია","pronunciation":"ქენ","example_en":"I can swim.","example_ka":"მე შემიძლია ცურვა.","category":"top-5000","level":"A1"},
{"english":"will","georgian":"მომავალი დრო","pronunciation":"ვილ","example_en":"I will come tomorrow.","example_ka":"ხვალ მოვალ.","category":"top-5000","level":"A1"},
{"english":"would","georgian":"იქნებოდა","pronunciation":"ვუდ","example_en":"I would like some water.","example_ka":"წყალი მინდა.","category":"top-5000","level":"A1"},
{"english":"there","georgian":"იქ","pronunciation":"ძეარ","example_en":"There is a cat.","example_ka":"იქ კატაა.","category":"top-5000","level":"A1"},
{"english":"their","georgian":"მათი","pronunciation":"ძეარ","example_en":"Their house is big.","example_ka":"მათი სახლი დიდია.","category":"top-5000","level":"A1"},
{"english":"about","georgian":"შესახებ","pronunciation":"ებაუთ","example_en":"Tell me about yourself.","example_ka":"მომიყევი შენს შესახებ.","category":"top-5000","level":"A1"},
{"english":"up","georgian":"ზემოთ","pronunciation":"აფ","example_en":"Look up at the sky.","example_ka":"ზემოთ შეხედე ცაში.","category":"top-5000","level":"A1"},
{"english":"out","georgian":"გარეთ","pronunciation":"აუთ","example_en":"Go out and play.","example_ka":"გარეთ გადი და ითამაშე.","category":"top-5000","level":"A1"},
{"english":"if","georgian":"თუ","pronunciation":"იფ","example_en":"If you want, come.","example_ka":"თუ გინდა, მოდი.","category":"top-5000","level":"A1"},
{"english":"just","georgian":"უბრალოდ","pronunciation":"ჯასთ","example_en":"I just arrived.","example_ka":"ახლახან მოვედი.","category":"top-5000","level":"A1"},
{"english":"also","georgian":"ასევე","pronunciation":"ოლსო","example_en":"I also like coffee.","example_ka":"მეც მომწონს ყავა.","category":"top-5000","level":"A1"},
{"english":"here","georgian":"აქ","pronunciation":"ჰიარ","example_en":"Come here please.","example_ka":"გთხოვთ, მოდი აქ.","category":"top-5000","level":"A1"},
{"english":"well","georgian":"კარგად","pronunciation":"ველ","example_en":"She speaks well.","example_ka":"ის კარგად ლაპარაკობს.","category":"top-5000","level":"A1"},
{"english":"only","georgian":"მხოლოდ","pronunciation":"ონლი","example_en":"I have only one.","example_ka":"მხოლოდ ერთი მაქვს.","category":"top-5000","level":"A1"},
{"english":"very","georgian":"ძალიან","pronunciation":"ვერი","example_en":"It is very cold.","example_ka":"ძალიან ცივა.","category":"top-5000","level":"A1"},
{"english":"then","georgian":"მაშინ","pronunciation":"ძენ","example_en":"I ate, then I left.","example_ka":"ვჭამე, მერე წავედი.","category":"top-5000","level":"A1"},
{"english":"more","georgian":"მეტი","pronunciation":"მორ","example_en":"I want more food.","example_ka":"მეტი საჭმელი მინდა.","category":"top-5000","level":"A1"},
{"english":"so","georgian":"ასე / ამიტომ","pronunciation":"სო","example_en":"I was tired, so I slept.","example_ka":"დაღლილი ვიყავი, ამიტომ დავიძინე.","category":"top-5000","level":"A1"},
{"english":"no","georgian":"არა","pronunciation":"ნო","example_en":"No, thank you.","example_ka":"არა, გმადლობთ.","category":"top-5000","level":"A1"},
{"english":"yes","georgian":"დიახ / კი","pronunciation":"იეს","example_en":"Yes, I agree.","example_ka":"დიახ, ვეთანხმები.","category":"top-5000","level":"A1"},
{"english":"my","georgian":"ჩემი","pronunciation":"მაი","example_en":"This is my book.","example_ka":"ეს ჩემი წიგნია.","category":"top-5000","level":"A1"},
{"english":"your","georgian":"შენი / თქვენი","pronunciation":"იორ","example_en":"What is your name?","example_ka":"რა გქვია?","category":"top-5000","level":"A1"},
{"english":"his","georgian":"მისი (მამრ.)","pronunciation":"ჰიზ","example_en":"His car is red.","example_ka":"მისი მანქანა წითელია.","category":"top-5000","level":"A1"},
{"english":"her","georgian":"მისი (მდედრ.)","pronunciation":"ჰერ","example_en":"Her dress is beautiful.","example_ka":"მისი კაბა ლამაზია.","category":"top-5000","level":"A1"},
{"english":"but","georgian":"მაგრამ","pronunciation":"ბათ","example_en":"I tried, but I failed.","example_ka":"ვცადე, მაგრამ ვერ შევძელი.","category":"top-5000","level":"A1"},
{"english":"or","georgian":"ან","pronunciation":"ორ","example_en":"Tea or coffee?","example_ka":"ჩაი თუ ყავა?","category":"top-5000","level":"A1"},
{"english":"and","georgian":"და","pronunciation":"ენდ","example_en":"You and I.","example_ka":"შენ და მე.","category":"top-5000","level":"A1"},
{"english":"with","georgian":"თან / -თან ერთად","pronunciation":"ვიძ","example_en":"Come with me.","example_ka":"ჩემთან ერთად მოდი.","category":"top-5000","level":"A1"},
{"english":"from","georgian":"-დან","pronunciation":"ფრომ","example_en":"I am from Georgia.","example_ka":"მე საქართველოდან ვარ.","category":"top-5000","level":"A1"},
{"english":"at","georgian":"-ში / -ზე","pronunciation":"ეთ","example_en":"I am at home.","example_ka":"სახლში ვარ.","category":"top-5000","level":"A1"},
{"english":"by","georgian":"-ით / -თან","pronunciation":"ბაი","example_en":"I go by bus.","example_ka":"ავტობუსით მივდივარ.","category":"top-5000","level":"A1"},
{"english":"for","georgian":"-თვის","pronunciation":"ფორ","example_en":"This is for you.","example_ka":"ეს შენთვისაა.","category":"top-5000","level":"A1"},
{"english":"on","georgian":"-ზე","pronunciation":"ონ","example_en":"The book is on the table.","example_ka":"წიგნი მაგიდაზეა.","category":"top-5000","level":"A1"},
{"english":"in","georgian":"-ში","pronunciation":"ინ","example_en":"I live in Tbilisi.","example_ka":"თბილისში ვცხოვრობ.","category":"top-5000","level":"A1"},
{"english":"to","georgian":"-კენ / -ში","pronunciation":"თუ","example_en":"I go to school.","example_ka":"სკოლაში მივდივარ.","category":"top-5000","level":"A1"},
{"english":"of","georgian":"-ის","pronunciation":"ოვ","example_en":"A cup of tea.","example_ka":"ჭიქა ჩაი.","category":"top-5000","level":"A1"},
{"english":"the","georgian":"არტიკლი (არ ითარგმნება)","pronunciation":"ძე","example_en":"The sun is bright.","example_ka":"მზე ნათელია.","category":"top-5000","level":"A1"},
{"english":"a","georgian":"არტიკლი (არ ითარგმნება)","pronunciation":"ე","example_en":"I have a dog.","example_ka":"მე მაქვს ძაღლი.","category":"top-5000","level":"A1"},
{"english":"some","georgian":"რამდენიმე","pronunciation":"სამ","example_en":"I need some water.","example_ka":"მჭირდება ცოტა წყალი.","category":"top-5000","level":"A1"},
{"english":"many","georgian":"ბევრი","pronunciation":"მენი","example_en":"Many people came.","example_ka":"ბევრი ხალხი მოვიდა.","category":"top-5000","level":"A1"},
{"english":"much","georgian":"ბევრი (უთვლადი)","pronunciation":"მაჩ","example_en":"How much does it cost?","example_ka":"რა ღირს?","category":"top-5000","level":"A1"},
{"english":"other","georgian":"სხვა","pronunciation":"აძერ","example_en":"The other one is better.","example_ka":"მეორე უკეთესია.","category":"top-5000","level":"A1"},
{"english":"each","georgian":"თითოეული","pronunciation":"იჩ","example_en":"Each student has a book.","example_ka":"თითოეულ სტუდენტს აქვს წიგნი.","category":"top-5000","level":"A1"},
{"english":"every","georgian":"ყოველი","pronunciation":"ევრი","example_en":"Every day is a gift.","example_ka":"ყოველი დღე საჩუქარია.","category":"top-5000","level":"A1"},
{"english":"two","georgian":"ორი","pronunciation":"თუ","example_en":"I have two cats.","example_ka":"ორი კატა მყავს.","category":"top-5000","level":"A1"},
{"english":"three","georgian":"სამი","pronunciation":"თრი","example_en":"Three friends came.","example_ka":"სამი მეგობარი მოვიდა.","category":"top-5000","level":"A1"},
{"english":"big","georgian":"დიდი","pronunciation":"ბიგ","example_en":"The house is big.","example_ka":"სახლი დიდია.","category":"top-5000","level":"A1"},
{"english":"still","georgian":"ჯერ კიდევ","pronunciation":"სთილ","example_en":"I am still waiting.","example_ka":"ჯერ კიდევ ველოდები.","category":"top-5000","level":"A1"},
{"english":"too","georgian":"ძალიან / -ც","pronunciation":"თუ","example_en":"It is too hot.","example_ka":"ძალიან ცხელა.","category":"top-5000","level":"A1"},
{"english":"never","georgian":"არასოდეს","pronunciation":"ნევერ","example_en":"I never lie.","example_ka":"არასოდეს ვტყუი.","category":"top-5000","level":"A1"},
{"english":"again","georgian":"ისევ / კიდევ","pronunciation":"ეგეინ","example_en":"Try again.","example_ka":"ისევ სცადე.","category":"top-5000","level":"A1"},
{"english":"really","georgian":"მართლა","pronunciation":"რიალი","example_en":"I really like it.","example_ka":"მართლა მომწონს.","category":"top-5000","level":"A1"},
{"english":"already","georgian":"უკვე","pronunciation":"ოლრედი","example_en":"I already ate.","example_ka":"უკვე ვჭამე.","category":"top-5000","level":"A1"},
{"english":"ask","georgian":"კითხვა / თხოვნა","pronunciation":"ასკ","example_en":"Ask me a question.","example_ka":"დამისვი კითხვა.","category":"top-5000","level":"A1"},
{"english":"try","georgian":"ცდა","pronunciation":"თრაი","example_en":"Try your best.","example_ka":"შეეცადე მაქსიმალურად.","category":"top-5000","level":"A1"},
{"english":"feel","georgian":"გრძნობა","pronunciation":"ფილ","example_en":"I feel happy.","example_ka":"ბედნიერად ვგრძნობ თავს.","category":"top-5000","level":"A1"},
{"english":"help","georgian":"დახმარება","pronunciation":"ჰელფ","example_en":"Can you help me?","example_ka":"შეგიძლია დამეხმარო?","category":"top-5000","level":"A1"},
{"english":"start","georgian":"დაწყება","pronunciation":"სთართ","example_en":"Let's start the lesson.","example_ka":"დავიწყოთ გაკვეთილი.","category":"top-5000","level":"A1"},
{"english":"keep","georgian":"შენახვა","pronunciation":"ქიფ","example_en":"Keep the change.","example_ka":"ხურდა შეინახე.","category":"top-5000","level":"A1"},
{"english":"turn","georgian":"მობრუნება","pronunciation":"თერნ","example_en":"Turn left.","example_ka":"მარცხნივ მოუხვიე.","category":"top-5000","level":"A1"},
{"english":"put","georgian":"დადება","pronunciation":"ფუთ","example_en":"Put it on the table.","example_ka":"მაგიდაზე დადე.","category":"top-5000","level":"A1"},
{"english":"mean","georgian":"ნიშნავს","pronunciation":"მინ","example_en":"What does it mean?","example_ka":"რას ნიშნავს?","category":"top-5000","level":"A1"},
{"english":"let","georgian":"ნებართვა","pronunciation":"ლეთ","example_en":"Let me go.","example_ka":"გამიშვი.","category":"top-5000","level":"A1"},
{"english":"stop","georgian":"გაჩერება","pronunciation":"სთოფ","example_en":"Stop the car.","example_ka":"მანქანა გააჩერე.","category":"top-5000","level":"A1"},
{"english":"read","georgian":"კითხვა","pronunciation":"რიდ","example_en":"I like to read books.","example_ka":"წიგნების კითხვა მიყვარს.","category":"top-5000","level":"A1"},
{"english":"speak","georgian":"ლაპარაკი","pronunciation":"სფიქ","example_en":"Do you speak English?","example_ka":"ინგლისურად ლაპარაკობ?","category":"top-5000","level":"A1"},
{"english":"learn","georgian":"სწავლა","pronunciation":"ლერნ","example_en":"I want to learn Georgian.","example_ka":"ქართულის სწავლა მინდა.","category":"top-5000","level":"A1"},
{"english":"watch","georgian":"ყურება","pronunciation":"ვოჩ","example_en":"Let's watch a movie.","example_ka":"ფილმი ვნახოთ.","category":"top-5000","level":"A1"},
{"english":"follow","georgian":"მიყოლა","pronunciation":"ფოლოუ","example_en":"Follow me.","example_ka":"გამომყევი.","category":"top-5000","level":"A1"},
{"english":"love","georgian":"სიყვარული","pronunciation":"ლავ","example_en":"I love you.","example_ka":"მიყვარხარ.","category":"top-5000","level":"A1"},
{"english":"wait","georgian":"ლოდინი","pronunciation":"ვეით","example_en":"Wait for me.","example_ka":"დამიცადე.","category":"top-5000","level":"A1"},
{"english":"buy","georgian":"ყიდვა","pronunciation":"ბაი","example_en":"I want to buy a car.","example_ka":"მანქანის ყიდვა მინდა.","category":"top-5000","level":"A1"},
{"english":"pay","georgian":"გადახდა","pronunciation":"ფეი","example_en":"I need to pay the bill.","example_ka":"ანგარიშის გადახდა მჭირდება.","category":"top-5000","level":"A1"},
{"english":"sit","georgian":"ჯდომა","pronunciation":"სით","example_en":"Please sit down.","example_ka":"გთხოვთ, დაბრძანდით.","category":"top-5000","level":"A1"},
{"english":"stand","georgian":"დგომა","pronunciation":"სთენდ","example_en":"Stand up please.","example_ka":"გთხოვთ ადექი.","category":"top-5000","level":"A1"},
{"english":"lose","georgian":"დაკარგვა","pronunciation":"ლუზ","example_en":"Don't lose your keys.","example_ka":"გასაღებები არ დაკარგო.","category":"top-5000","level":"A1"},
{"english":"win","georgian":"მოგება","pronunciation":"ვინ","example_en":"I want to win.","example_ka":"მოგება მინდა.","category":"top-5000","level":"A1"},
{"english":"send","georgian":"გაგზავნა","pronunciation":"სენდ","example_en":"Send me a message.","example_ka":"შეტყობინება გამომიგზავნე.","category":"top-5000","level":"A1"},
{"english":"build","georgian":"აშენება","pronunciation":"ბილდ","example_en":"They build houses.","example_ka":"ისინი სახლებს აშენებენ.","category":"top-5000","level":"A1"},
{"english":"stay","georgian":"დარჩენა","pronunciation":"სთეი","example_en":"Stay here.","example_ka":"აქ დარჩი.","category":"top-5000","level":"A1"},
{"english":"fall","georgian":"დაცემა","pronunciation":"ფოლ","example_en":"Be careful, don't fall.","example_ka":"ფრთხილად, არ დაეცე.","category":"top-5000","level":"A1"},
{"english":"cut","georgian":"ჭრა","pronunciation":"ქათ","example_en":"Cut the bread.","example_ka":"პური გაჭერი.","category":"top-5000","level":"A1"},
{"english":"sell","georgian":"გაყიდვა","pronunciation":"სელ","example_en":"I want to sell my car.","example_ka":"მანქანის გაყიდვა მინდა.","category":"top-5000","level":"A1"},
{"english":"sleep","georgian":"ძილი","pronunciation":"სლიფ","example_en":"I need to sleep.","example_ka":"ძილი მჭირდება.","category":"top-5000","level":"A1"},
{"english":"drink","georgian":"სმა","pronunciation":"დრინქ","example_en":"I drink water.","example_ka":"წყალს ვსვამ.","category":"top-5000","level":"A1"},
{"english":"understand","georgian":"გაგება","pronunciation":"ანდერსთენდ","example_en":"I understand you.","example_ka":"მე გიგებ.","category":"top-5000","level":"A1"},
{"english":"remember","georgian":"დამახსოვრება","pronunciation":"რიმემბერ","example_en":"Remember my name.","example_ka":"დაიმახსოვრე ჩემი სახელი.","category":"top-5000","level":"A1"},
{"english":"die","georgian":"სიკვდილი","pronunciation":"დაი","example_en":"Flowers die in winter.","example_ka":"ყვავილები ზამთარში ხმება.","category":"top-5000","level":"A1"},
{"english":"seem","georgian":"ჩანს","pronunciation":"სიმ","example_en":"You seem tired.","example_ka":"დაღლილი ჩანხარ.","category":"top-5000","level":"A1"},
{"english":"family","georgian":"ოჯახი","pronunciation":"ფემილი","example_en":"I love my family.","example_ka":"ჩემი ოჯახი მიყვარს.","category":"top-5000","level":"A1"},
{"english":"country","georgian":"ქვეყანა","pronunciation":"ქანთრი","example_en":"Georgia is a beautiful country.","example_ka":"საქართველო ლამაზი ქვეყანაა.","category":"top-5000","level":"A1"},
{"english":"student","georgian":"სტუდენტი","pronunciation":"სთიუდენთ","example_en":"She is a good student.","example_ka":"ის კარგი სტუდენტია.","category":"top-5000","level":"A1"},
{"english":"teacher","georgian":"მასწავლებელი","pronunciation":"თიჩერ","example_en":"My teacher is kind.","example_ka":"ჩემი მასწავლებელი კეთილია.","category":"top-5000","level":"A1"},
{"english":"food","georgian":"საკვები","pronunciation":"ფუდ","example_en":"Georgian food is delicious.","example_ka":"ქართული საკვები გემრიელია.","category":"top-5000","level":"A1"},
{"english":"body","georgian":"სხეული","pronunciation":"ბოდი","example_en":"Exercise is good for the body.","example_ka":"ვარჯიში სხეულისთვის კარგია.","category":"top-5000","level":"A1"},
{"english":"idea","georgian":"იდეა","pronunciation":"აიდია","example_en":"That's a great idea.","example_ka":"ეს შესანიშნავი იდეაა.","category":"top-5000","level":"A1"},
{"english":"team","georgian":"გუნდი","pronunciation":"თიმ","example_en":"Our team won.","example_ka":"ჩვენმა გუნდმა მოიგო.","category":"top-5000","level":"A1"},
{"english":"minute","georgian":"წუთი","pronunciation":"მინით","example_en":"Wait one minute.","example_ka":"ერთი წუთი დაიცადე.","category":"top-5000","level":"A1"},
{"english":"information","georgian":"ინფორმაცია","pronunciation":"ინფორმეიშენ","example_en":"I need more information.","example_ka":"მეტი ინფორმაცია მჭირდება.","category":"top-5000","level":"A1"},
{"english":"problem","georgian":"პრობლემა","pronunciation":"პრობლემ","example_en":"That's not a problem.","example_ka":"ეს პრობლემა არ არის.","category":"top-5000","level":"A1"},
{"english":"girl","georgian":"გოგონა","pronunciation":"გერლ","example_en":"The girl is playing.","example_ka":"გოგონა თამაშობს.","category":"top-5000","level":"A1"},
{"english":"boy","georgian":"ბიჭი","pronunciation":"ბოი","example_en":"The boy runs fast.","example_ka":"ბიჭი სწრაფად დარბის.","category":"top-5000","level":"A1"},
{"english":"air","georgian":"ჰაერი","pronunciation":"ეარ","example_en":"The air is fresh.","example_ka":"ჰაერი სუფთაა.","category":"top-5000","level":"A1"},
{"english":"market","georgian":"ბაზარი","pronunciation":"მარქეთ","example_en":"I go to the market.","example_ka":"ბაზარში მივდივარ.","category":"top-5000","level":"A1"},
{"english":"land","georgian":"მიწა","pronunciation":"ლენდ","example_en":"He bought land.","example_ka":"მან მიწა იყიდა.","category":"top-5000","level":"A1"},
{"english":"reason","georgian":"მიზეზი","pronunciation":"რიზენ","example_en":"What is the reason?","example_ka":"რა არის მიზეზი?","category":"top-5000","level":"A1"},
{"english":"experience","georgian":"გამოცდილება","pronunciation":"იქსფირიენს","example_en":"It was a great experience.","example_ka":"შესანიშნავი გამოცდილება იყო.","category":"top-5000","level":"A1"},
{"english":"force","georgian":"ძალა","pronunciation":"ფორს","example_en":"Don't use force.","example_ka":"ძალას ნუ იხმარ.","category":"top-5000","level":"A1"},
{"english":"moment","georgian":"მომენტი","pronunciation":"მომენთ","example_en":"Wait a moment.","example_ka":"ერთი წამით დაიცადე.","category":"top-5000","level":"A1"},
{"english":"state","georgian":"სახელმწიფო","pronunciation":"სთეით","example_en":"The state of the economy.","example_ka":"ეკონომიკის მდგომარეობა.","category":"top-5000","level":"A1"},
{"english":"river","georgian":"მდინარე","pronunciation":"რივერ","example_en":"The river is deep.","example_ka":"მდინარე ღრმაა.","category":"top-5000","level":"A1"},
{"english":"door","georgian":"კარი","pronunciation":"დორ","example_en":"Open the door.","example_ka":"კარი გააღე.","category":"top-5000","level":"A1"},
{"english":"window","georgian":"ფანჯარა","pronunciation":"ვინდოუ","example_en":"Close the window.","example_ka":"ფანჯარა დახურე.","category":"top-5000","level":"A1"},
{"english":"street","georgian":"ქუჩა","pronunciation":"სთრით","example_en":"The street is busy.","example_ka":"ქუჩა ხალხმრავალია.","category":"top-5000","level":"A1"},
{"english":"dog","georgian":"ძაღლი","pronunciation":"დოგ","example_en":"I have a dog.","example_ka":"მე მყავს ძაღლი.","category":"top-5000","level":"A1"},
{"english":"cat","georgian":"კატა","pronunciation":"ქეთ","example_en":"The cat is sleeping.","example_ka":"კატა ძინავს.","category":"top-5000","level":"A1"},
{"english":"morning","georgian":"დილა","pronunciation":"მორნინგ","example_en":"Good morning!","example_ka":"დილა მშვიდობისა!","category":"top-5000","level":"A1"},
{"english":"evening","georgian":"საღამო","pronunciation":"ივნინგ","example_en":"Good evening!","example_ka":"საღამო მშვიდობისა!","category":"top-5000","level":"A1"},
{"english":"sun","georgian":"მზე","pronunciation":"სან","example_en":"The sun is shining.","example_ka":"მზე ანათებს.","category":"top-5000","level":"A1"},
{"english":"rain","georgian":"წვიმა","pronunciation":"რეინ","example_en":"It will rain tomorrow.","example_ka":"ხვალ იწვიმებს.","category":"top-5000","level":"A1"},
{"english":"thing","georgian":"რამ / საგანი","pronunciation":"თინგ","example_en":"What is this thing?","example_ka":"ეს რა არის?","category":"top-5000","level":"A1"},
{"english":"nothing","georgian":"არაფერი","pronunciation":"ნათინგ","example_en":"Nothing happened.","example_ka":"არაფერი მომხდარა.","category":"top-5000","level":"A1"},
{"english":"something","georgian":"რაღაც","pronunciation":"სამთინგ","example_en":"I want something to eat.","example_ka":"რაღაცის ჭამა მინდა.","category":"top-5000","level":"A1"},
{"english":"everything","georgian":"ყველაფერი","pronunciation":"ევრითინგ","example_en":"Everything is fine.","example_ka":"ყველაფერი კარგადაა.","category":"top-5000","level":"A1"},
{"english":"everyone","georgian":"ყველა","pronunciation":"ევრივან","example_en":"Everyone is here.","example_ka":"ყველა აქ არის.","category":"top-5000","level":"A1"},
{"english":"someone","georgian":"ვიღაც","pronunciation":"სამვან","example_en":"Someone is calling.","example_ka":"ვიღაც რეკავს.","category":"top-5000","level":"A1"},
{"english":"happy","georgian":"ბედნიერი","pronunciation":"ჰეფი","example_en":"I am happy.","example_ka":"მე ბედნიერი ვარ.","category":"top-5000","level":"A1"},
{"english":"sad","georgian":"სევდიანი","pronunciation":"სედ","example_en":"She looks sad.","example_ka":"ის სევდიანად გამოიყურება.","category":"top-5000","level":"A1"},
{"english":"beautiful","georgian":"ლამაზი","pronunciation":"ბიუთიფულ","example_en":"The city is beautiful.","example_ka":"ქალაქი ლამაზია.","category":"top-5000","level":"A1"},
{"english":"cold","georgian":"ცივი","pronunciation":"ქოლდ","example_en":"It is cold outside.","example_ka":"გარეთ ცივა.","category":"top-5000","level":"A1"},
{"english":"hot","georgian":"ცხელი","pronunciation":"ჰოთ","example_en":"The coffee is hot.","example_ka":"ყავა ცხელია.","category":"top-5000","level":"A1"},
{"english":"fast","georgian":"სწრაფი","pronunciation":"ფასთ","example_en":"The car is fast.","example_ka":"მანქანა სწრაფია.","category":"top-5000","level":"A1"},
{"english":"slow","georgian":"ნელი","pronunciation":"სლოუ","example_en":"Walk slow.","example_ka":"ნელა იარე.","category":"top-5000","level":"A1"},
{"english":"easy","georgian":"ადვილი","pronunciation":"იზი","example_en":"The test was easy.","example_ka":"ტესტი ადვილი იყო.","category":"top-5000","level":"A1"},
{"english":"hard","georgian":"რთული","pronunciation":"ჰარდ","example_en":"The exam is hard.","example_ka":"გამოცდა რთულია.","category":"top-5000","level":"A1"},
{"english":"free","georgian":"თავისუფალი / უფასო","pronunciation":"ფრი","example_en":"This is free.","example_ka":"ეს უფასოა.","category":"top-5000","level":"A1"},
{"english":"full","georgian":"სავსე","pronunciation":"ფულ","example_en":"The glass is full.","example_ka":"ჭიქა სავსეა.","category":"top-5000","level":"A1"},
{"english":"empty","georgian":"ცარიელი","pronunciation":"ემფთი","example_en":"The room is empty.","example_ka":"ოთახი ცარიელია.","category":"top-5000","level":"A1"},
{"english":"clean","georgian":"სუფთა","pronunciation":"ქლინ","example_en":"The house is clean.","example_ka":"სახლი სუფთაა.","category":"top-5000","level":"A1"},
{"english":"dark","georgian":"ბნელი","pronunciation":"დარქ","example_en":"It is dark outside.","example_ka":"გარეთ ბნელა.","category":"top-5000","level":"A1"},
{"english":"light","georgian":"სინათლე / მსუბუქი","pronunciation":"ლაით","example_en":"Turn on the light.","example_ka":"შუქი აანთე.","category":"top-5000","level":"A1"},
{"english":"strong","georgian":"ძლიერი","pronunciation":"სთრონგ","example_en":"He is very strong.","example_ka":"ის ძალიან ძლიერია.","category":"top-5000","level":"A1"},
{"english":"weak","georgian":"სუსტი","pronunciation":"ვიქ","example_en":"I feel weak.","example_ka":"სუსტად ვგრძნობ თავს.","category":"top-5000","level":"A1"},
{"english":"true","georgian":"მართალი","pronunciation":"თრუ","example_en":"Is that true?","example_ka":"ეს მართალია?","category":"top-5000","level":"A1"},
{"english":"sure","georgian":"დარწმუნებული","pronunciation":"შუარ","example_en":"Are you sure?","example_ka":"დარწმუნებული ხარ?","category":"top-5000","level":"A1"},
{"english":"ready","georgian":"მზად","pronunciation":"რედი","example_en":"I am ready.","example_ka":"მზად ვარ.","category":"top-5000","level":"A1"},
{"english":"nice","georgian":"სასიამოვნო","pronunciation":"ნაის","example_en":"Nice to meet you.","example_ka":"სასიამოვნოა შენი გაცნობა.","category":"top-5000","level":"A1"},
{"english":"simple","georgian":"მარტივი","pronunciation":"სიმფლ","example_en":"It is very simple.","example_ka":"ეს ძალიან მარტივია.","category":"top-5000","level":"A1"},
{"english":"possible","georgian":"შესაძლებელი","pronunciation":"ფოსიბლ","example_en":"Everything is possible.","example_ka":"ყველაფერი შესაძლებელია.","category":"top-5000","level":"A1"},
{"english":"best","georgian":"საუკეთესო","pronunciation":"ბესთ","example_en":"She is the best.","example_ka":"ის საუკეთესოა.","category":"top-5000","level":"A1"},
{"english":"better","georgian":"უკეთესი","pronunciation":"ბეთერ","example_en":"This is better.","example_ka":"ეს უკეთესია.","category":"top-5000","level":"A1"},
{"english":"able","georgian":"შეძლება","pronunciation":"ეიბლ","example_en":"I am able to do it.","example_ka":"შემიძლია ეს გავაკეთო.","category":"top-5000","level":"A1"},
{"english":"music","georgian":"მუსიკა","pronunciation":"მიუზიქ","example_en":"I like music.","example_ka":"მუსიკა მომწონს.","category":"top-5000","level":"A1"},
{"english":"movie","georgian":"ფილმი","pronunciation":"მუვი","example_en":"Let's watch a movie.","example_ka":"ფილმი ვნახოთ.","category":"top-5000","level":"A1"},
{"english":"phone","georgian":"ტელეფონი","pronunciation":"ფონ","example_en":"My phone is ringing.","example_ka":"ჩემი ტელეფონი რეკავს.","category":"top-5000","level":"A1"},
{"english":"color","georgian":"ფერი","pronunciation":"ქალერ","example_en":"What color is it?","example_ka":"რა ფერისაა?","category":"top-5000","level":"A1"},
{"english":"picture","georgian":"სურათი","pronunciation":"ფიქჩერ","example_en":"Take a picture.","example_ka":"სურათი გადაიღე.","category":"top-5000","level":"A1"},
{"english":"answer","georgian":"პასუხი","pronunciation":"ანსერ","example_en":"What is the answer?","example_ka":"რა არის პასუხი?","category":"top-5000","level":"A1"},
{"english":"tomorrow","georgian":"ხვალ","pronunciation":"თუმოროუ","example_en":"See you tomorrow.","example_ka":"ხვალ გნახავ.","category":"top-5000","level":"A1"},
{"english":"yesterday","georgian":"გუშინ","pronunciation":"იესთერდეი","example_en":"I saw him yesterday.","example_ka":"გუშინ ვნახე ის.","category":"top-5000","level":"A1"},
{"english":"enough","georgian":"საკმარისი","pronunciation":"ინაფ","example_en":"That's enough.","example_ka":"ეს საკმარისია.","category":"top-5000","level":"A1"},
{"english":"together","georgian":"ერთად","pronunciation":"თუგეძერ","example_en":"Let's go together.","example_ka":"ერთად წავიდეთ.","category":"top-5000","level":"A1"},
{"english":"between","georgian":"შორის","pronunciation":"ბიტვინ","example_en":"Between you and me.","example_ka":"ჩვენ შორის.","category":"top-5000","level":"A1"},
{"english":"through","georgian":"გავლით","pronunciation":"თრუ","example_en":"Go through the door.","example_ka":"კარში გაიარე.","category":"top-5000","level":"A1"},
{"english":"into","georgian":"-ში (შიგნით)","pronunciation":"ინთუ","example_en":"Come into the house.","example_ka":"სახლში შემოდი.","category":"top-5000","level":"A1"},
{"english":"over","georgian":"ზემოთ / გადა","pronunciation":"ოვერ","example_en":"Jump over the wall.","example_ka":"კედელზე გადახტი.","category":"top-5000","level":"A1"},
{"english":"under","georgian":"ქვეშ","pronunciation":"ანდერ","example_en":"The cat is under the table.","example_ka":"კატა მაგიდის ქვეშაა.","category":"top-5000","level":"A1"},
]

# Filter out duplicates
added = 0
for w in batch:
    key = w['english'].lower()
    if key not in existing:
        data.append(w)
        existing.add(key)
        added += 1

print(f"Added {added} new words from batch 1. Total: {len(data)}")

with open('/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/top-5000-words.json', 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Saved!")
