import json

# Read existing
with open('/Users/aiagent/.openclaw/workspace/english-app/flashcard-app/content/top-5000-words.json', 'r') as f:
    data = json.load(f)

existing = set(w['english'].lower() for w in data)
print(f"Existing: {len(existing)} unique words, {len(data)} entries")

# New words to add - organized by frequency/level
new_words = [
# ===== A1 LEVEL (most common 500) =====
# Basic verbs
{"english": "be", "georgian": "ყოფნა", "pronunciation": "ბი", "example_en": "I want to be happy.", "example_ka": "მე მინდა ბედნიერი ვიყო.", "category": "top-5000", "level": "A1"},
{"english": "have", "georgian": "ქონა", "pronunciation": "ჰევ", "example_en": "I have a book.", "example_ka": "მე მაქვს წიგნი.", "category": "top-5000", "level": "A1"},
{"english": "do", "georgian": "კეთება", "pronunciation": "დუ", "example_en": "What do you do?", "example_ka": "რას აკეთებ?", "category": "top-5000", "level": "A1"},
{"english": "not", "georgian": "არა", "pronunciation": "ნოთ", "example_en": "I do not know.", "example_ka": "მე არ ვიცი.", "category": "top-5000", "level": "A1"},
{"english": "he", "georgian": "ის (მამრობითი)", "pronunciation": "ჰი", "example_en": "He is my friend.", "example_ka": "ის ჩემი მეგობარია.", "category": "top-5000", "level": "A1"},
{"english": "she", "georgian": "ის (მდედრობითი)", "pronunciation": "ში", "example_en": "She is a teacher.", "example_ka": "ის მასწავლებელია.", "category": "top-5000", "level": "A1"},
{"english": "it", "georgian": "ის (საგანი)", "pronunciation": "ით", "example_en": "It is raining.", "example_ka": "წვიმს.", "category": "top-5000", "level": "A1"},
{"english": "we", "georgian": "ჩვენ", "pronunciation": "ვი", "example_en": "We are students.", "example_ka": "ჩვენ სტუდენტები ვართ.", "category": "top-5000", "level": "A1"},
{"english": "they", "georgian": "ისინი", "pronunciation": "ძეი", "example_en": "They are coming.", "example_ka": "ისინი მოდიან.", "category": "top-5000", "level": "A1"},
{"english": "you", "georgian": "შენ / თქვენ", "pronunciation": "იუ", "example_en": "You are welcome.", "example_ka": "არაფრის.", "category": "top-5000", "level": "A1"},
{"english": "I", "georgian": "მე", "pronunciation": "აი", "example_en": "I am here.", "example_ka": "მე აქ ვარ.", "category": "top-5000", "level": "A1"},
{"english": "this", "georgian": "ეს", "pronunciation": "ძის", "example_en": "This is my house.", "example_ka": "ეს ჩემი სახლია.", "category": "top-5000", "level": "A1"},
{"english": "that", "georgian": "ის / რომ", "pronunciation": "ძეთ", "example_en": "That is interesting.", "example_ka": "ის საინტერესოა.", "category": "top-5000", "level": "A1"},
{"english": "what", "georgian": "რა", "pronunciation": "ვოთ", "example_en": "What is your name?", "example_ka": "რა გქვია?", "category": "top-5000", "level": "A1"},
{"english": "which", "georgian": "რომელი", "pronunciation": "ვიჩ", "example_en": "Which one do you want?", "example_ka": "რომელი გინდა?", "category": "top-5000", "level": "A1"},
{"english": "who", "georgian": "ვინ", "pronunciation": "ჰუ", "example_en": "Who is there?", "example_ka": "ვინ არის იქ?", "category": "top-5000", "level": "A1"},
{"english": "when", "georgian": "როდის", "pronunciation": "ვენ", "example_en": "When did you arrive?", "example_ka": "როდის ჩამოხვედი?", "category": "top-5000", "level": "A1"},
{"english": "where", "georgian": "სად", "pronunciation": "ვეარ", "example_en": "Where do you live?", "example_ka": "სად ცხოვრობ?", "category": "top-5000", "level": "A1"},
{"english": "how", "georgian": "როგორ", "pronunciation": "ჰაუ", "example_en": "How are you?", "example_ka": "როგორ ხარ?", "category": "top-5000", "level": "A1"},
{"english": "why", "georgian": "რატომ", "pronunciation": "ვაი", "example_en": "Why are you late?", "example_ka": "რატომ დაგვიანდი?", "category": "top-5000", "level": "A1"},
{"english": "all", "georgian": "ყველა", "pronunciation": "ოლ", "example_en": "All students passed.", "example_ka": "ყველა სტუდენტმა ჩააბარა.", "category": "top-5000", "level": "A1"},
{"english": "can", "georgian": "შეუძლია", "pronunciation": "ქენ", "example_en": "I can swim.", "example_ka": "მე შემიძლია ცურვა.", "category": "top-5000", "level": "A1"},
{"english": "will", "georgian": "მომავალი დრო", "pronunciation": "ვილ", "example_en": "I will come tomorrow.", "example_ka": "ხვალ მოვალ.", "category": "top-5000", "level": "A1"},
{"english": "would", "georgian": "იქნებოდა", "pronunciation": "ვუდ", "example_en": "I would like some water.", "example_ka": "წყალი მინდა.", "category": "top-5000", "level": "A1"},
{"english": "there", "georgian": "იქ", "pronunciation": "ძეარ", "example_en": "There is a cat.", "example_ka": "იქ კატაა.", "category": "top-5000", "level": "A1"},
{"english": "their", "georgian": "მათი", "pronunciation": "ძეარ", "example_en": "Their house is big.", "example_ka": "მათი სახლი დიდია.", "category": "top-5000", "level": "A1"},
{"english": "about", "georgian": "შესახებ", "pronunciation": "ებაუთ", "example_en": "Tell me about yourself.", "example_ka": "მომიყევი შენს შესახებ.", "category": "top-5000", "level": "A1"},
{"english": "up", "georgian": "ზემოთ", "pronunciation": "აფ", "example_en": "Look up at the sky.", "example_ka": "ზემოთ შეხედე ცაში.", "category": "top-5000", "level": "A1"},
{"english": "out", "georgian": "გარეთ", "pronunciation": "აუთ", "example_en": "Go out and play.", "example_ka": "გარეთ გადი და ითამაშე.", "category": "top-5000", "level": "A1"},
{"english": "if", "georgian": "თუ", "pronunciation": "იფ", "example_en": "If you want, come.", "example_ka": "თუ გინდა, მოდი.", "category": "top-5000", "level": "A1"},
{"english": "just", "georgian": "უბრალოდ", "pronunciation": "ჯასთ", "example_en": "I just arrived.", "example_ka": "ახლახან მოვედი.", "category": "top-5000", "level": "A1"},
{"english": "also", "georgian": "ასევე", "pronunciation": "ოლსო", "example_en": "I also like coffee.", "example_ka": "მეც მომწონს ყავა.", "category": "top-5000", "level": "A1"},
{"english": "here", "georgian": "აქ", "pronunciation": "ჰიარ", "example_en": "Come here please.", "example_ka": "გთხოვთ, მოდი აქ.", "category": "top-5000", "level": "A1"},
{"english": "well", "georgian": "კარგად", "pronunciation": "ველ", "example_en": "She speaks well.", "example_ka": "ის კარგად ლაპარაკობს.", "category": "top-5000", "level": "A1"},
{"english": "only", "georgian": "მხოლოდ", "pronunciation": "ონლი", "example_en": "I have only one.", "example_ka": "მხოლოდ ერთი მაქვს.", "category": "top-5000", "level": "A1"},
{"english": "very", "georgian": "ძალიან", "pronunciation": "ვერი", "example_en": "It is very cold.", "example_ka": "ძალიან ცივა.", "category": "top-5000", "level": "A1"},
{"english": "then", "georgian": "მაშინ", "pronunciation": "ძენ", "example_en": "I ate, then I left.", "example_ka": "ვჭამე, მერე წავედი.", "category": "top-5000", "level": "A1"},
{"english": "more", "georgian": "მეტი", "pronunciation": "მორ", "example_en": "I want more food.", "example_ka": "მეტი საჭმელი მინდა.", "category": "top-5000", "level": "A1"},
{"english": "so", "georgian": "ასე / ამიტომ", "pronunciation": "სო", "example_en": "I was tired, so I slept.", "example_ka": "დაღლილი ვიყავი, ამიტომ დავიძინე.", "category": "top-5000", "level": "A1"},
{"english": "no", "georgian": "არა", "pronunciation": "ნო", "example_en": "No, thank you.", "example_ka": "არა, გმადლობთ.", "category": "top-5000", "level": "A1"},
{"english": "yes", "georgian": "დიახ / კი", "pronunciation": "იეს", "example_en": "Yes, I agree.", "example_ka": "დიახ, ვეთანხმები.", "category": "top-5000", "level": "A1"},
{"english": "my", "georgian": "ჩემი", "pronunciation": "მაი", "example_en": "This is my book.", "example_ka": "ეს ჩემი წიგნია.", "category": "top-5000", "level": "A1"},
{"english": "your", "georgian": "შენი / თქვენი", "pronunciation": "იორ", "example_en": "What is your name?", "example_ka": "რა გქვია?", "category": "top-5000", "level": "A1"},
{"english": "his", "georgian": "მისი (მამრ.)", "pronunciation": "ჰიზ", "example_en": "His car is red.", "example_ka": "მისი მანქანა წითელია.", "category": "top-5000", "level": "A1"},
{"english": "her", "georgian": "მისი (მდედრ.)", "pronunciation": "ჰერ", "example_en": "Her dress is beautiful.", "example_ka": "მისი კაბა ლამაზია.", "category": "top-5000", "level": "A1"},
{"english": "but", "georgian": "მაგრამ", "pronunciation": "ბათ", "example_en": "I tried, but I failed.", "example_ka": "ვცადე, მაგრამ ვერ შევძელი.", "category": "top-5000", "level": "A1"},
{"english": "or", "georgian": "ან", "pronunciation": "ორ", "example_en": "Tea or coffee?", "example_ka": "ჩაი თუ ყავა?", "category": "top-5000", "level": "A1"},
{"english": "and", "georgian": "და", "pronunciation": "ენდ", "example_en": "You and I.", "example_ka": "შენ და მე.", "category": "top-5000", "level": "A1"},
{"english": "with", "georgian": "თან / -თან ერთად", "pronunciation": "ვიძ", "example_en": "Come with me.", "example_ka": "ჩემთან ერთად მოდი.", "category": "top-5000", "level": "A1"},
{"english": "from", "georgian": "-დან", "pronunciation": "ფრომ", "example_en": "I am from Georgia.", "example_ka": "მე საქართველოდან ვარ.", "category": "top-5000", "level": "A1"},
{"english": "at", "georgian": "-ში / -ზე", "pronunciation": "ეთ", "example_en": "I am at home.", "example_ka": "სახლში ვარ.", "category": "top-5000", "level": "A1"},
{"english": "by", "georgian": "-ით / -თან", "pronunciation": "ბაი", "example_en": "I go by bus.", "example_ka": "ავტობუსით მივდივარ.", "category": "top-5000", "level": "A1"},
{"english": "for", "georgian": "-თვის", "pronunciation": "ფორ", "example_en": "This is for you.", "example_ka": "ეს შენთვისაა.", "category": "top-5000", "level": "A1"},
{"english": "on", "georgian": "-ზე", "pronunciation": "ონ", "example_en": "The book is on the table.", "example_ka": "წიგნი მაგიდაზეა.", "category": "top-5000", "level": "A1"},
{"english": "in", "georgian": "-ში", "pronunciation": "ინ", "example_en": "I live in Tbilisi.", "example_ka": "თბილისში ვცხოვრობ.", "category": "top-5000", "level": "A1"},
{"english": "to", "georgian": "-კენ / -ში", "pronunciation": "თუ", "example_en": "I go to school.", "example_ka": "სკოლაში მივდივარ.", "category": "top-5000", "level": "A1"},
{"english": "of", "georgian": "-ის", "pronunciation": "ოვ", "example_en": "A cup of tea.", "example_ka": "ჭიქა ჩაი.", "category": "top-5000", "level": "A1"},
{"english": "the", "georgian": "არტიკლი (არ ითარგმნება)", "pronunciation": "ძე", "example_en": "The sun is bright.", "example_ka": "მზე ნათელია.", "category": "top-5000", "level": "A1"},
{"english": "a", "georgian": "არტიკლი (არ ითარგმნება)", "pronunciation": "ე", "example_en": "I have a dog.", "example_ka": "მე მაქვს ძაღლი.", "category": "top-5000", "level": "A1"},
{"english": "some", "georgian": "რამდენიმე", "pronunciation": "სამ", "example_en": "I need some water.", "example_ka": "მჭირდება ცოტა წყალი.", "category": "top-5000", "level": "A1"},
{"english": "many", "georgian": "ბევრი", "pronunciation": "მენი", "example_en": "Many people came.", "example_ka": "ბევრი ხალხი მოვიდა.", "category": "top-5000", "level": "A1"},
{"english": "much", "georgian": "ბევრი (უთვლადი)", "pronunciation": "მაჩ", "example_en": "How much does it cost?", "example_ka": "რა ღირს?", "category": "top-5000", "level": "A1"},
{"english": "other", "georgian": "სხვა", "pronunciation": "აძერ", "example_en": "The other one is better.", "example_ka": "მეორე უკეთესია.", "category": "top-5000", "level": "A1"},
{"english": "each", "georgian": "თითოეული", "pronunciation": "იჩ", "example_en": "Each student has a book.", "example_ka": "თითოეულ სტუდენტს აქვს წიგნი.", "category": "top-5000", "level": "A1"},
{"english": "every", "georgian": "ყოველი", "pronunciation": "ევრი", "example_en": "Every day is a gift.", "example_ka": "ყოველი დღე საჩუქარია.", "category": "top-5000", "level": "A1"},
{"english": "two", "georgian": "ორი", "pronunciation": "თუ", "example_en": "I have two cats.", "example_ka": "ორი კატა მყავს.", "category": "top-5000", "level": "A1"},
{"english": "three", "georgian": "სამი", "pronunciation": "თრი", "example_en": "Three friends came.", "example_ka": "სამი მეგობარი მოვიდა.", "category": "top-5000", "level": "A1"},
{"english": "big", "georgian": "დიდი", "pronunciation": "ბიგ", "example_en": "The house is big.", "example_ka": "სახლი დიდია.", "category": "top-5000", "level": "A1"},
{"english": "still", "georgian": "ჯერ კიდევ", "pronunciation": "სთილ", "example_en": "I am still waiting.", "example_ka": "ჯერ კიდევ ველოდები.", "category": "top-5000", "level": "A1"},
{"english": "too", "georgian": "ძალიან / -ც", "pronunciation": "თუ", "example_en": "It is too hot.", "example_ka": "ძალიან ცხელა.", "category": "top-5000", "level": "A1"},
{"english": "never", "georgian": "არასოდეს", "pronunciation": "ნევერ", "example_en": "I never lie.", "example_ka": "არასოდეს ვტყუი.", "category": "top-5000", "level": "A1"},
{"english": "again", "georgian": "ისევ / კიდევ", "pronunciation": "ეგეინ", "example_en": "Try again.", "example_ka": "ისევ სცადე.", "category": "top-5000", "level": "A1"},
{"english": "really", "georgian": "მართლა", "pronunciation": "რიალი", "example_en": "I really like it.", "example_ka": "მართლა მომწონს.", "category": "top-5000", "level": "A1"},
{"english": "already", "georgian": "უკვე", "pronunciation": "ოლრედი", "example_en": "I already ate.", "example_ka": "უკვე ვჭამე.", "category": "top-5000", "level": "A1"},
{"english": "ask", "georgian": "კითხვა / თხოვნა", "pronunciation": "ასკ", "example_en": "Ask me a question.", "example_ka": "დამისვი კითხვა.", "category": "top-5000", "level": "A1"},
{"english": "try", "georgian": "ცდა", "pronunciation": "თრაი", "example_en": "Try your best.", "example_ka": "შეეცადე მაქსიმალურად.", "category": "top-5000", "level": "A1"},
{"english": "feel", "georgian": "გრძნობა", "pronunciation": "ფილ", "example_en": "I feel happy.", "example_ka": "ბედნიერად ვგრძნობ თავს.", "category": "top-5000", "level": "A1"},
{"english": "help", "georgian": "დახმარება", "pronunciation": "ჰელფ", "example_en": "Can you help me?", "example_ka": "შეგიძლია დამეხმარო?", "category": "top-5000", "level": "A1"},
{"english": "start", "georgian": "დაწყება", "pronunciation": "სთართ", "example_en": "Let's start the lesson.", "example_ka": "დავიწყოთ გაკვეთილი.", "category": "top-5000", "level": "A1"},
{"english": "keep", "georgian": "შენახვა", "pronunciation": "ქიფ", "example_en": "Keep the change.", "example_ka": "ხურდა შეინახე.", "category": "top-5000", "level": "A1"},
{"english": "turn", "georgian": "მობრუნება", "pronunciation": "თერნ", "example_en": "Turn left.", "example_ka": "მარცხნივ მოუხვიე.", "category": "top-5000", "level": "A1"},
{"english": "put", "georgian": "დადება", "pronunciation": "ფუთ", "example_en": "Put it on the table.", "example_ka": "მაგიდაზე დადე.", "category": "top-5000", "level": "A1"},
{"english": "mean", "georgian": "ნიშნავს", "pronunciation": "მინ", "example_en": "What does it mean?", "example_ka": "რას ნიშნავს?", "category": "top-5000", "level": "A1"},
{"english": "let", "georgian": "ნებართვა / გაშვება", "pronunciation": "ლეთ", "example_en": "Let me go.", "example_ka": "გამიშვი.", "category": "top-5000", "level": "A1"},
{"english": "stop", "georgian": "გაჩერება", "pronunciation": "სთოფ", "example_en": "Stop the car.", "example_ka": "მანქანა გააჩერე.", "category": "top-5000", "level": "A1"},
{"english": "read", "georgian": "კითხვა", "pronunciation": "რიდ", "example_en": "I like to read books.", "example_ka": "წიგნების კითხვა მიყვარს.", "category": "top-5000", "level": "A1"},
{"english": "speak", "georgian": "ლაპარაკი", "pronunciation": "სფიქ", "example_en": "Do you speak English?", "example_ka": "ინგლისურად ლაპარაკობ?", "category": "top-5000", "level": "A1"},
{"english": "learn", "georgian": "სწავლა", "pronunciation": "ლერნ", "example_en": "I want to learn Georgian.", "example_ka": "ქართულის სწავლა მინდა.", "category": "top-5000", "level": "A1"},
{"english": "watch", "georgian": "ყურება", "pronunciation": "ვოჩ", "example_en": "Let's watch a movie.", "example_ka": "ფილმი ვნახოთ.", "category": "top-5000", "level": "A1"},
{"english": "follow", "georgian": "მიყოლა", "pronunciation": "ფოლოუ", "example_en": "Follow me.", "example_ka": "გამომყევი.", "category": "top-5000", "level": "A1"},
{"english": "love", "georgian": "სიყვარული / უყვარს", "pronunciation": "ლავ", "example_en": "I love you.", "example_ka": "მიყვარხარ.", "category": "top-5000", "level": "A1"},
{"english": "wait", "georgian": "ლოდინი", "pronunciation": "ვეით", "example_en": "Wait for me.", "example_ka": "დამიცადე.", "category": "top-5000", "level": "A1"},
{"english": "buy", "georgian": "ყიდვა", "pronunciation": "ბაი", "example_en": "I want to buy a car.", "example_ka": "მანქანის ყიდვა მინდა.", "category": "top-5000", "level": "A1"},
{"english": "pay", "georgian": "გადახდა", "pronunciation": "ფეი", "example_en": "I need to pay the bill.", "example_ka": "ანგარიშის გადახდა მჭირდება.", "category": "top-5000", "level": "A1"},
{"english": "sit", "georgian": "ჯდომა", "pronunciation": "სით", "example_en": "Please sit down.", "example_ka": "გთხოვთ, დაბრძანდით.", "category": "top-5000", "level": "A1"},
{"english": "stand", "georgian": "დგომა", "pronunciation": "სთენდ", "example_en": "Stand up please.", "example_ka": "გთხოვთ ადექი.", "category": "top-5000", "level": "A1"},
{"english": "lose", "georgian": "დაკარგვა", "pronunciation": "ლუზ", "example_en": "Don't lose your keys.", "example_ka": "გასაღებები არ დაკარგო.", "category": "top-5000", "level": "A1"},
{"english": "win", "georgian": "მოგება", "pronunciation": "ვინ", "example_en": "I want to win.", "example_ka": "მოგება მინდა.", "category": "top-5000", "level": "A1"},
{"english": "send", "georgian": "გაგზავნა", "pronunciation": "სენდ", "example_en": "Send me a message.", "example_ka": "შეტყობინება გამომიგზავნე.", "category": "top-5000", "level": "A1"},
{"english": "build", "georgian": "აშენება", "pronunciation": "ბილდ", "example_en": "They build houses.", "example_ka": "ისინი სახლებს აშენებენ.", "category": "top-5000", "level": "A1"},
{"english": "stay", "georgian": "დარჩენა", "pronunciation": "სთეი", "example_en": "Stay here.", "example_ka": "აქ დარჩი.", "category": "top-5000", "level": "A1"},
{"english": "fall", "georgian": "დაცემა", "pronunciation": "ფოლ", "example_en": "Be careful, don't fall.", "example_ka": "ფრთხილად, არ დაეცე.", "category": "top-5000", "level": "A1"},
{"english": "cut", "georgian": "ჭრა", "pronunciation": "ქათ", "example_en": "Cut the bread.", "example_ka": "პური გაჭერი.", "category": "top-5000", "level": "A1"},
{"english": "sell", "georgian": "გაყიდვა", "pronunciation": "სელ", "example_en": "I want to sell my car.", "example_ka": "მანქანის გაყიდვა მინდა.", "category": "top-5000", "level": "A1"},
{"english": "sleep", "georgian": "ძილი", "pronunciation": "სლიფ", "example_en": "I need to sleep.", "example_ka": "ძილი მჭირდება.", "category": "top-5000", "level": "A1"},
{"english": "drink", "georgian": "სმა", "pronunciation": "დრინქ", "example_en": "I drink water.", "example_ka": "წყალს ვსვამ.", "category": "top-5000", "level": "A1"},
{"english": "understand", "georgian": "გაგება", "pronunciation": "ანდერსთენდ", "example_en": "I understand you.", "example_ka": "მე გიგებ.", "category": "top-5000", "level": "A1"},
{"english": "remember", "georgian": "დამახსოვრება", "pronunciation": "რიმემბერ", "example_en": "Remember my name.", "example_ka": "დაიმახსოვრე ჩემი სახელი.", "category": "top-5000", "level": "A1"},
{"english": "die", "georgian": "სიკვდილი / კვდება", "pronunciation": "დაი", "example_en": "Flowers die in winter.", "example_ka": "ყვავილები ზამთარში ხმება.", "category": "top-5000", "level": "A1"},
{"english": "seem", "georgian": "ჩანს / მოჩანს", "pronunciation": "სიმ", "example_en": "You seem tired.", "example_ka": "დაღლილი ჩანხარ.", "category": "top-5000", "level": "A1"},
# Basic nouns
{"english": "family", "georgian": "ოჯახი", "pronunciation": "ფემილი", "example_en": "I love my family.", "example_ka": "ჩემი ოჯახი მიყვარს.", "category": "top-5000", "level": "A1"},
{"english": "country", "georgian": "ქვეყანა", "pronunciation": "ქანთრი", "example_en": "Georgia is a beautiful country.", "example_ka": "საქართველო ლამაზი ქვეყანაა.", "category": "top-5000", "level": "A1"},
{"english": "student", "georgian": "სტუდენტი", "pronunciation": "სთიუდენთ", "example_en": "She is a good student.", "example_ka": "ის კარგი სტუდენტია.", "category": "top-5000", "level": "A1"},
{"english": "teacher", "georgian": "მასწავლებელი", "pronunciation": "თიჩერ", "example_en": "My teacher is kind.", "example_ka": "ჩემი მასწავლებელი კეთილია.", "category": "top-5000", "level": "A1"},
{"english": "food", "georgian": "საკვები", "pronunciation": "ფუდ", "example_en": "Georgian food is delicious.", "example_ka": "ქართული საკვები გემრიელია.", "category": "top-5000", "level": "A1"},
{"english": "body", "georgian": "სხეული", "pronunciation": "ბოდი", "example_en": "Exercise is good for the body.", "example_ka": "ვარჯიში სხეულისთვის კარგია.", "category": "top-5000", "level": "A1"},
{"english": "idea", "georgian": "იდეა", "pronunciation": "აიდია", "example_en": "That's a great idea.", "example_ka": "ეს შესანიშნავი იდეაა.", "category": "top-5000", "level": "A1"},
{"english": "team", "georgian": "გუნდი", "pronunciation": "თიმ", "example_en": "Our team won.", "example_ka": "ჩვენმა გუნდმა მოიგო.", "category": "top-5000", "level": "A1"},
{"english": "minute", "georgian": "წუთი", "pronunciation": "მინით", "example_en": "Wait one minute.", "example_ka": "ერთი წუთი დაიცადე.", "category": "top-5000", "level": "A1"},
{"english": "information", "georgian": "ინფორმაცია", "pronunciation": "ინფორმეიშენ", "example_en": "I need more information.", "example_ka": "მეტი ინფორმაცია მჭირდება.", "category": "top-5000", "level": "A1"},
{"english": "problem", "georgian": "პრობლემა", "pronunciation": "პრობლემ", "example_en": "That's not a problem.", "example_ka": "ეს პრობლემა არ არის.", "category": "top-5000", "level": "A1"},
{"english": "girl", "georgian": "გოგონა", "pronunciation": "გერლ", "example_en": "The girl is playing.", "example_ka": "გოგონა თამაშობს.", "category": "top-5000", "level": "A1"},
{"english": "boy", "georgian": "ბიჭი", "pronunciation": "ბოი", "example_en": "The boy runs fast.", "example_ka": "ბიჭი სწრაფად დარბის.", "category": "top-5000", "level": "A1"},
{"english": "air", "georgian": "ჰაერი", "pronunciation": "ეარ", "example_en": "The air is fresh.", "example_ka": "ჰაერი სუფთაა.", "category": "top-5000", "level": "A1"},
{"english": "market", "georgian": "ბაზარი", "pronunciation": "მარქეთ", "example_en": "I go to the market.", "example_ka": "ბაზარში მივდივარ.", "category": "top-5000", "level": "A1"},
{"english": "land", "georgian": "მიწა", "pronunciation": "ლენდ", "example_en": "He bought land.", "example_ka": "მან მიწა იყიდა.", "category": "top-5000", "level": "A1"},
{"english": "reason", "georgian": "მიზეზი", "pronunciation": "რიზენ", "example_en": "What is the reason?", "example_ka": "რა არის მიზეზი?", "category": "top-5000", "level": "A1"},
{"english": "experience", "georgian": "გამოცდილება", "pronunciation": "იქსპირიენს", "example_en": "It was a great experience.", "example_ka": "შესანიშნავი გამოცდილება იყო.", "category": "top-5000", "level": "A1"},
{"english": "force", "georgian": "ძალა", "pronunciation": "ფორს", "example_en": "Don't use force.", "example_ka": "ძალას ნუ იხმარ.", "category": "top-5000", "level": "A1"},
{"english": "moment", "georgian": "მომენტი / წამი", "pronunciation": "მომენთ", "example_en": "Wait a moment.", "example_ka": "ერთი წამით დაიცადე.", "category": "top-5000", "level": "A1"},
{"english": "state", "georgian": "სახელმწიფო / მდგომარეობა", "pronunciation": "სთეით", "example_en": "The state of the economy.", "example_ka": "ეკონომიკის მდგომარეობა.", "category": "top-5000", "level": "A1"},
{"english": "river", "georgian": "მდინარე", "pronunciation": "რივერ", "example_en": "The river is deep.", "example_ka": "მდინარე ღრმაა.", "category": "top-5000", "level": "A1"},
{"english": "door", "georgian": "კარი", "pronunciation": "დორ", "example_en": "Open the door.", "example_ka": "კარი გააღე.", "category": "top-5000", "level": "A1"},
{"english": "window", "georgian": "ფანჯარა", "pronunciation": "ვინდოუ", "example_en": "Close the window.", "example_ka": "ფანჯარა დახურე.", "category": "top-5000", "level": "A1"},
{"english": "street", "georgian": "ქუჩა", "pronunciation": "სთრით", "example_en": "The street is busy.", "example_ka": "ქუჩა ხალხმრავალია.", "category": "top-5000", "level": "A1"},
{"english": "dog", "georgian": "ძაღლი", "pronunciation": "დოგ", "example_en": "I have a dog.", "example_ka": "მე მყავს ძაღლი.", "category": "top-5000", "level": "A1"},
{"english": "cat", "georgian": "კატა", "pronunciation": "ქეთ", "example_en": "The cat is sleeping.", "example_ka": "კატა ძინავს.", "category": "top-5000", "level": "A1"},
{"english": "morning", "georgian": "დილა", "pronunciation": "მორნინგ", "example_en": "Good morning!", "example_ka": "დილა მშვიდობისა!", "category": "top-5000", "level": "A1"},
{"english": "evening", "georgian": "საღამო", "pronunciation": "ივნინგ", "example_en": "Good evening!", "example_ka": "საღამო მშვიდობისა!", "category": "top-5000", "level": "A1"},
{"english": "sun", "georgian": "მზე", "pronunciation": "სან", "example_en": "The sun is shining.", "example_ka": "მზე ანათებს.", "category": "top-5000", "level": "A1"},
{"english": "rain", "georgian": "წვიმა", "pronunciation": "რეინ", "example_en": "It will rain tomorrow.", "example_ka": "ხვალ იწვიმებს.", "category": "top-5000", "level": "A1"},
{"english": "thing", "georgian": "რამ / საგანი", "pronunciation": "თინგ", "example_en": "What is this thing?", "example_ka": "ეს რა არის?", "category": "top-5000", "level": "A1"},
{"english": "nothing", "georgian": "არაფერი", "pronunciation": "ნათინგ", "example_en": "Nothing happened.", "example_ka": "არაფერი მომხდარა.", "category": "top-5000", "level": "A1"},
{"english": "something", "georgian": "რაღაც", "pronunciation": "სამთინგ", "example_en": "I want something to eat.", "example_ka": "რაღაცის ჭამა მინდა.", "category": "top-5000", "level": "A1"},
{"english": "everything", "georgian": "ყველაფერი", "pronunciation": "ევრითინგ", "example_en": "Everything is fine.", "example_ka": "ყველაფერი კარგადაა.", "category": "top-5000", "level": "A1"},
{"english": "everyone", "georgian": "ყველა", "pronunciation": "ევრივან", "example_en": "Everyone is here.", "example_ka": "ყველა აქ არის.", "category": "top-5000", "level": "A1"},
{"english": "someone", "georgian": "ვიღაც", "pronunciation": "სამვან", "example_en": "Someone is calling.", "example_ka": "ვიღაც რეკავს.", "category": "top-5000", "level": "A1"},
{"english": "no one", "georgian": "არავინ", "pronunciation": "ნო ვან", "example_en": "No one came.", "example_ka": "არავინ მოვიდა.", "category": "top-5000", "level": "A1"},
{"english": "car", "georgian": "მანქანა", "pronunciation": "ქარ", "example_en": "I drive a car.", "example_ka": "მანქანას ვატარებ.", "category": "top-5000", "level": "A1"},
# Adjectives A1
{"english": "happy", "georgian": "ბედნიერი", "pronunciation": "ჰეფი", "example_en": "I am happy.", "example_ka": "მე ბედნიერი ვარ.", "category": "top-5000", "level": "A1"},
{"english": "sad", "georgian": "სევდიანი", "pronunciation": "სედ", "example_en": "She looks sad.", "example_ka": "ის სევდიანად გამოიყურება.", "category": "top-5000", "level": "A1"},
{"english": "beautiful", "georgian": "ლამაზი", "pronunciation": "ბიუთიფულ", "example_en": "The city is beautiful.", "example_ka": "ქალაქი ლამაზია.", "category": "top-5000", "level": "A1"},
{"english": "cold", "georgian": "ცივი", "pronunciation": "ქოლდ", "example_en": "It is cold outside.", "example_ka": "გარეთ ცივა.", "category": "top-5000", "level": "A1"},
{"english": "hot", "georgian": "ცხელი", "pronunciation": "ჰოთ", "example_en": "The coffee is hot.", "example_ka": "ყავა ცხელია.", "category": "top-5000", "level": "A1"},
{"english": "fast", "georgian": "სწრაფი", "pronunciation": "ფასთ", "example_en": "The car is fast.", "example_ka": "მანქანა სწრაფია.", "category": "top-5000", "level": "A1"},
{"english": "slow", "georgian": "ნელი", "pronunciation": "სლოუ", "example_en": "Walk slow.", "example_ka": "ნელა იარე.", "category": "top-5000", "level": "A1"},
{"english": "easy", "georgian": "ადვილი", "pronunciation": "იზი", "example_en": "The test was easy.", "example_ka": "ტესტი ადვილი იყო.", "category": "top-5000", "level": "A1"},
{"english": "hard", "georgian": "რთული / მაგარი", "pronunciation": "ჰარდ", "example_en": "The exam is hard.", "example_ka": "გამოცდა რთულია.", "category": "top-5000", "level": "A1"},
{"english": "free", "georgian": "თავისუფალი / უფასო", "pronunciation": "ფრი", "example_en": "This is free.", "example_ka": "ეს უფასოა.", "category": "top-5000", "level": "A1"},
{"english": "full", "georgian": "სავსე", "pronunciation": "ფულ", "example_en": "The glass is full.", "example_ka": "ჭიქა სავსეა.", "category": "top-5000", "level": "A1"},
{"english": "empty", "georgian": "ცარიელი", "pronunciation": "ემფთი", "example_en": "The room is empty.", "example_ka": "ოთახი ცარიელია.", "category": "top-5000", "level": "A1"},
{"english": "clean", "georgian": "სუფთა", "pronunciation": "ქლინ", "example_en": "The house is clean.", "example_ka": "სახლი სუფთაა.", "category": "top-5000", "level": "A1"},
{"english": "dark", "georgian": "ბნელი", "pronunciation": "დარქ", "example_en": "It is dark outside.", "example_ka": "გარეთ ბნელა.", "category": "top-5000", "level": "A1"},
{"english": "light", "georgian": "სინათლე / მსუბუქი", "pronunciation": "ლაით", "example_en": "Turn on the light.", "example_ka": "შუქი აანთე.", "category": "top-5000", "level": "A1"},
{"english": "strong", "georgian": "ძლიერი", "pronunciation": "სთრონგ", "example_en": "He is very strong.", "example_ka": "ის ძალიან ძლიერია.", "category": "top-5000", "level": "A1"},
{"english": "weak", "georgian": "სუსტი", "pronunciation": "ვიქ", "example_en": "I feel weak.", "example_ka": "სუსტად ვგრძნობ თავს.", "category": "top-5000", "level": "A1"},
{"english": "true", "georgian": "მართალი / ჭეშმარიტი", "pronunciation": "თრუ", "example_en": "Is that true?", "example_ka": "ეს მართალია?", "category": "top-5000", "level": "A1"},
{"english": "sure", "georgian": "დარწმუნებული", "pronunciation": "შუარ", "example_en": "Are you sure?", "example_ka": "დარწმუნებული ხარ?", "category": "top-5000", "level": "A1"},
{"english": "ready", "georgian": "მზად", "pronunciation": "რედი", "example_en": "I am ready.", "example_ka": "მზად ვარ.", "category": "top-5000", "level": "A1"},
{"english": "nice", "georgian": "სასიამოვნო / კარგი", "pronunciation": "ნაის", "example_en": "Nice to meet you.", "example_ka": "სასიამოვნოა შენი გაცნობა.", "category": "top-5000", "level": "A1"},
{"english": "simple", "georgian": "მარტივი", "pronunciation": "სიმფლ", "example_en": "It is very simple.", "example_ka": "ეს ძალიან მარტივია.", "category": "top-5000", "level": "A1"},
{"english": "possible", "georgian": "შესაძლებელი", "pronunciation": "ფოსიბლ", "example_en": "Everything is possible.", "example_ka": "ყველაფერი შესაძლებელია.", "category": "top-5000", "level": "A1"},
{"english": "best", "georgian": "საუკეთესო", "pronunciation": "ბესთ", "example_en": "She is the best.", "example_ka": "ის საუკეთესოა.", "category": "top-5000", "level": "A1"},
{"english": "better", "georgian": "უკეთესი", "pronunciation": "ბეთერ", "example_en": "This is better.", "example_ka": "ეს უკეთესია.", "category": "top-5000", "level": "A1"},
{"english": "able", "georgian": "შეძლება", "pronunciation": "ეიბლ", "example_en": "I am able to do it.", "example_ka": "შემიძლია ეს გავაკეთო.", "category": "top-5000", "level": "A1"},
# More nouns A1
{"english": "music", "georgian": "მუსიკა", "pronunciation": "მიუზიქ", "example_en": "I like music.", "example_ka": "მუსიკა მომწონს.", "category": "top-5000", "level": "A1"},
{"english": "movie", "georgian": "ფილმი", "pronunciation": "მუვი", "example_en": "Let's watch a movie.", "example_ka": "ფილმი ვნახოთ.", "category": "top-5000", "level": "A1"},
{"english": "phone", "georgian": "ტელეფონი", "pronunciation": "ფონ", "example_en": "My phone is ringing.", "example_ka": "ჩემი ტელეფონი რეკავს.", "category": "top-5000", "level": "A1"},
{"english": "color", "georgian": "ფერი", "pronunciation": "ქალერ", "example_en": "What color is it?", "example_ka": "რა ფერისაა?", "category": "top-5000", "level": "A1"},
{"english": "picture", "georgian": "სურათი", "pronunciation": "ფიქჩერ", "example_en": "Take a picture.", "example_ka": "სურათი გადაიღე.", "category": "top-5000", "level": "A1"},
{"english": "answer", "georgian": "პასუხი", "pronunciation": "ანსერ", "example_en": "What is the answer?", "example_ka": "რა არის პასუხი?", "category": "top-5000", "level": "A1"},
{"english": "today", "georgian": "დღეს", "pronunciation": "თუდეი", "example_en": "I am busy today.", "example_ka": "დღეს დაკავებული ვარ.", "category": "top-5000", "level": "A1"},
{"english": "tomorrow", "georgian": "ხვალ", "pronunciation": "თუმოროუ", "example_en": "See you tomorrow.", "example_ka": "ხვალ გნახავ.", "category": "top-5000", "level": "A1"},
{"english": "yesterday", "georgian": "გუშინ", "pronunciation": "იესთერდეი", "example_en": "I saw him yesterday.", "example_ka": "გუშინ ვნახე ის.", "category": "top-5000", "level": "A1"},
{"english": "enough", "georgian": "საკმარისი", "pronunciation": "ინაფ", "example_en": "That's enough.", "example_ka": "ეს საკმარისია.", "category": "top-5000", "level": "A1"},
{"english": "together", "georgian": "ერთად", "pronunciation": "თუგეძერ", "example_en": "Let's go together.", "example_ka": "ერთად წავიდეთ.", "category": "top-5000", "level": "A1"},
{"english": "between", "georgian": "შორის", "pronunciation": "ბიტვინ", "example_en": "Between you and me.", "example_ka": "ჩვენ შორის.", "category": "top-5000", "level": "A1"},
{"english": "through", "georgian": "გავლით", "pronunciation": "თრუ", "example_en": "Go through the door.", "example_ka": "კარში გაიარე.", "category": "top-5000", "level": "A1"},
{"english": "into", "georgian": "-ში (შიგნით)", "pronunciation": "ინთუ", "example_en": "Come into the house.", "example_ka": "სახლში შემოდი.", "category": "top-5000", "level": "A1"},
{"english": "over", "georgian": "ზემოთ / გადა", "pronunciation": "ოვერ", "example_en": "Jump over the wall.", "example_ka": "კედელზე გადახტი.", "category": "top-5000", "level": "A1"},
{"english": "under", "georgian": "ქვეშ", "pronunciation": "ანდერ", "example_en": "The cat is under the table.", "example_ka": "კატა მაგიდის ქვეშაა.", "category": "top-5000", "level": "A1"},
{"english": "before", "georgian": "მანამდე / სანამ", "pronunciation": "ბიფორ", "example_en": "Come before noon.", "example_ka": "შუადღემდე მოდი.", "category": "top-5000", "level": "A1"},

# ===== A2 LEVEL =====
{"english": "however", "georgian": "თუმცა", "pronunciation": "ჰაუევერ", "example_en": "However, I disagree.", "example_ka": "თუმცა, მე არ ვეთანხმები.", "category": "top-5000", "level": "A2"},
{"english": "though", "georgian": "მიუხედავად", "pronunciation": "ძოუ", "example_en": "Even though it rained, we went.", "example_ka": "მიუხედავად წვიმისა, წავედით.", "category": "top-5000", "level": "A2"},
{"english": "quite", "georgian": "საკმაოდ", "pronunciation": "ქვაით", "example_en": "It's quite good.", "example_ka": "საკმაოდ კარგია.", "category": "top-5000", "level": "A2"},
{"english": "perhaps", "georgian": "ალბათ", "pronunciation": "ფერჰეფს", "example_en": "Perhaps you are right.", "example_ka": "ალბათ მართალი ხარ.", "category": "top-5000", "level": "A2"},
{"english": "rather", "georgian": "საკმაოდ / უფრო", "pronunciation": "რაძერ", "example_en": "I would rather stay.", "example_ka": "დარჩენა მჯობინდა.", "category": "top-5000", "level": "A2"},
{"english": "instead", "georgian": "ამის ნაცვლად", "pronunciation": "ინსთედ", "example_en": "I'll have tea instead.", "example_ka": "ამის ნაცვლად ჩაის დავლევ.", "category": "top-5000", "level": "A2"},
{"english": "actually", "georgian": "სინამდვილეში", "pronunciation": "ექჩუალი", "example_en": "Actually, I changed my mind.", "example_ka": "სინამდვილეში, აზრი შევიცვალე.", "category": "top-5000", "level": "A2"},
{"english": "almost", "georgian": "თითქმის", "pronunciation": "ოლმოსთ", "example_en": "I almost forgot.", "example_ka": "თითქმის დამავიწყდა.", "category": "top-5000", "level": "A2"},
{"english": "probably", "georgian": "ალბათ", "pronunciation": "პრობებლი", "example_en": "He will probably come.", "example_ka": "ალბათ მოვა.", "category": "top-5000", "level": "A2"},
{"english": "especially", "georgian": "განსაკუთრებით", "pronunciation": "ისფეშალი", "example_en": "I love fruits, especially apples.", "example_ka": "ხილი მიყვარს, განსაკუთრებით ვაშლი.", "category": "top-5000", "level": "A2"},
{"english": "quickly", "georgian": "სწრაფად", "pronunciation": "ქვიქლი", "example_en": "Come quickly!", "example_ka": "სწრაფად მოდი!", "category": "top-5000", "level": "A2"},
{"english": "finally", "georgian": "საბოლოოდ / ბოლოს", "pronunciation": "ფაინალი", "example_en": "I finally finished.", "example_ka": "ბოლოს და ბოლოს დავასრულე.", "category": "top-5000", "level": "A2"},
{"english": "exactly", "georgian": "ზუსტად", "pronunciation": "იგზექთლი", "example_en": "That's exactly right.", "example_ka": "ზუსტად ასეა.", "category": "top-5000", "level": "A2"},
{"english": "usually", "georgian": "ჩვეულებრივ", "pronunciation": "იუჟუალი", "example_en": "I usually wake up early.", "example_ka": "ჩვეულებრივ ადრე ვიღვიძებ.", "category": "top-5000", "level": "A2"},
{"english": "sometimes", "georgian": "ზოგჯერ", "pronunciation": "სამთაიმზ", "example_en": "Sometimes I walk to work.", "example_ka": "ზოგჯერ ფეხით მივდივარ სამსახურში.", "category": "top-5000", "level": "A2"},
{"english": "often", "georgian": "ხშირად", "pronunciation": "ოფენ", "example_en": "I often read at night.", "example_ka": "ხშირად ღამით ვკითხულობ.", "category": "top-5000", "level": "A2"},
{"english": "certainly", "georgian": "რა თქმა უნდა", "pronunciation": "სერთენლი", "example_en": "Certainly, I'll help you.", "example_ka": "რა თქმა უნდა, დაგეხმარები.", "category": "top-5000", "level": "A2"},
{"english": "clearly", "georgian": "ნათლად", "pronunciation": "ქლიარლი", "example_en": "Speak clearly.", "example_ka": "ნათლად ილაპარაკე.", "category": "top-5000", "level": "A2"},
{"english": "recently", "georgian": "ახლახან", "pronunciation": "რისენთლი", "example_en": "I recently moved.", "example_ka": "ახლახან გადავედი.", "category": "top-5000", "level": "A2"},
{"english": "simply", "georgian": "უბრალოდ", "pronunciation": "სიმფლი", "example_en": "Simply the best.", "example_ka": "უბრალოდ საუკეთესო.", "category": "top-5000", "level": "A2"},
{"english": "easily", "georgian": "ადვილად", "pronunciation": "იზილი", "example_en": "I can do it easily.", "example_ka": "ადვილად შემიძლია.", "category": "top-5000", "level": "A2"},
# A2 verbs
{"english": "create", "georgian": "შექმნა", "pronunciation": "ქრიეით", "example_en": "Create something new.", "example_ka": "რაღაც ახალი შექმენი.", "category": "top-5000", "level": "A2"},
{"english": "allow", "georgian": "ნებართვა / უფლების მიცემა", "pronunciation": "ელაუ", "example_en": "Allow me to help.", "example_ka": "ნება მიბოძეთ დაგეხმაროთ.", "category": "top-5000", "level": "A2"},
{"english": "add", "georgian": "დამატება", "pronunciation": "ედ", "example_en": "Add some sugar.", "example_ka": "ცოტა შაქარი დაამატე.", "category": "top-5000", "level": "A2"},
{"english": "spend", "georgian": "ხარჯვა / გატარება", "pronunciation": "სფენდ", "example_en": "I spend time reading.", "example_ka": "დროს კითხვით ვატარებ.", "category": "top-5000", "level": "A2"},
{"english": "offer", "georgian": "შეთავაზება", "pronunciation": "ოფერ", "example_en": "He offered me a job.", "example_ka": "მან სამუშაო შემომთავაზა.", "category": "top-5000", "level": "A2"},
{"english": "consider", "georgian": "განხილვა / ჩათვლა", "pronunciation": "ქონსიდერ", "example_en": "Consider this option.", "example_ka": "ეს ვარიანტი განიხილე.", "category": "top-5000", "level": "A2"},
{"english": "appear", "georgian": "გამოჩენა", "pronunciation": "ეფიარ", "example_en": "Stars appear at night.", "example_ka": "ვარსკვლავები ღამით ჩანან.", "category": "top-5000", "level": "A2"},
{"english": "serve", "georgian": "მომსახურება", "pronunciation": "სერვ", "example_en": "They serve good food.", "example_ka": "კარგ საკვებს ემსახურებიან.", "category": "top-5000", "level": "A2"},
{"english": "expect", "georgian": "მოლოდინი", "pronunciation": "იქსფექთ", "example_en": "I expect good results.", "example_ka": "კარგ შედეგებს ველოდები.", "category": "top-5000", "level": "A2"},
{"english": "reach", "georgian": "მიღწევა", "pronunciation": "რიჩ", "example_en": "We reached the top.", "example_ka": "მწვერვალს მივაღწიეთ.", "category": "top-5000", "level": "A2"},
{"english": "remain", "georgian": "დარჩენა", "pronunciation": "რიმეინ", "example_en": "Please remain seated.", "example_ka": "გთხოვთ, იჯდეთ.", "category": "top-5000", "level": "A2"},
{"english": "suggest", "georgian": "შეთავაზება / წინადადება", "pronunciation": "სეჯესთ", "example_en": "I suggest we leave.", "example_ka": "გთავაზობთ წავიდეთ.", "category": "top-5000", "level": "A2"},
{"english": "raise", "georgian": "აწევა / აღზრდა", "pronunciation": "რეიზ", "example_en": "Raise your hand.", "example_ka": "ხელი აწიე.", "category": "top-5000", "level": "A2"},
{"english": "pass", "georgian": "გავლა / გადაცემა", "pronunciation": "ფას", "example_en": "Pass me the salt.", "example_ka": "მარილი მომაწოდე.", "category": "top-5000", "level": "A2"},
{"english": "require", "georgian": "მოთხოვნა", "pronunciation": "რიქვაიერ", "example_en": "This requires patience.", "example_ka": "ეს მოთმინებას მოითხოვს.", "category": "top-5000", "level": "A2"},
{"english": "report", "georgian": "მოხსენება / ანგარიში", "pronunciation": "რიფორთ", "example_en": "Write a report.", "example_ka": "ანგარიში დაწერე.", "category": "top-5000", "level": "A2"},
{"english": "decide", "georgian": "გადაწყვეტა", "pronunciation": "დისაიდ", "example_en": "I can't decide.", "example_ka": "ვერ ვწყვეტ.", "category": "top-5000", "level": "A2"},
{"english": "pull", "georgian": "მოზიდვა", "pronunciation": "ფულ", "example_en": "Pull the door.", "example_ka": "კარი მოზიდე.", "category": "top-5000", "level": "A2"},
{"english": "develop", "georgian": "განვითარება", "pronunciation": "დიველოფ", "example_en": "We need to develop a plan.", "example_ka": "გეგმის შემუშავება გვჭირდება.", "category": "top-5000", "level": "A2"},
{"english": "provide", "georgian": "უზრუნველყოფა", "pronunciation": "ფროვაიდ", "example_en": "We provide services.", "example_ka": "მომსახურებას ვუზრუნველყოფთ.", "category": "top-5000", "level": "A2"},
{"english": "draw", "georgian": "ხატვა", "pronunciation": "დრო", "example_en": "Can you draw a cat?", "example_ka": "კატას დახატავ?", "category": "top-5000", "level": "A2"},
{"english": "agree", "georgian": "თანხმობა", "pronunciation": "ეგრი", "example_en": "I agree with you.", "example_ka": "გეთანხმები.", "category": "top-5000", "level": "A2"},
{"english": "support", "georgian": "მხარდაჭერა", "pronunciation": "სეფორთ", "example_en": "I support your decision.", "example_ka": "შენს გადაწყვეტილებას ვუჭერ მხარს.", "category": "top-5000", "level": "A2"},
{"english": "receive", "georgian": "მიღება", "pronunciation": "რისივ", "example_en": "I received your letter.", "example_ka": "შენი წერილი მივიღე.", "category": "top-5000", "level": "A2"},
{"english": "enjoy", "georgian": "სიამოვნება", "pronunciation": "ინჯოი", "example_en": "Enjoy your meal.", "example_ka": "გემრიელად მიირთვით.", "category": "top-5000", "level": "A2"},
{"english": "carry", "georgian": "ტარება / წაღება", "pronunciation": "ქერი", "example_en": "Carry this bag.", "example_ka": "ეს ჩანთა წაიღე.", "category": "top-5000", "level": "A2"},
{"english": "include", "georgian": "მოიცავს", "pronunciation": "ინქლუდ", "example_en": "The price includes tax.", "example_ka": "ფასი გადასახადს მოიცავს.", "category": "top-5000", "level": "A2"},
{"english": "continue", "georgian": "გაგრძელება", "pronunciation": "ქონთინიუ", "example_en": "Please continue.", "example_ka": "გთხოვთ, გააგრძელეთ.", "category": "top-5000", "level": "A2"},
{"english": "set", "georgian": "დაყენება / კომპლექტი", "pronunciation": "სეთ", "example_en": "Set the alarm.", "example_ka": "მაღვიძარა დააყენე.", "category": "top-5000", "level": "A2"},
{"english": "lead", "georgian": "ხელმძღვანელობა", "pronunciation": "ლიდ", "example_en": "She leads the team.", "example_ka": "ის გუნდს ხელმძღვანელობს.", "category": "top-5000", "level": "A2"},
{"english": "kill", "georgian": "მოკვლა", "pronunciation": "ქილ", "example_en": "Don't kill the spider.", "example_ka": "ობობა ნუ მოკლავ.", "category": "top-5000", "level": "A2"},
{"english": "begin", "georgian": "დაწყება", "pronunciation": "ბიგინ", "example_en": "Let's begin.", "example_ka": "დავიწყოთ.", "category": "top-5000", "level": "A2"},
{"english": "cost", "georgian": "ღირს / ღირებულება", "pronunciation": "ქოსთ", "example_en": "How much does it cost?", "example_ka": "რა ღირს?", "category": "top-5000", "level": "A2"},
{"english": "drive", "georgian": "მართვა / ტარება", "pronunciation": "დრაივ", "example_en": "I can drive a car.", "example_ka": "მანქანის ტარება შემიძლია.", "category": "top-5000", "level": "A2"},
{"english": "fly", "georgian": "ფრენა", "pronunciation": "ფლაი", "example_en": "Birds fly south.", "example_ka": "ფრინველები სამხრეთით ფრინავენ.", "category": "top-5000", "level": "A2"},
{"english": "break", "georgian": "გატეხვა / შესვენება", "pronunciation": "ბრეიქ", "example_en": "Don't break the glass.", "example_ka": "ჭიქა არ გატეხო.", "category": "top-5000", "level": "A2"},
{"english": "wear", "georgian": "ტარება (ტანსაცმელი)", "pronunciation": "ვეარ", "example_en": "I wear a jacket.", "example_ka": "ქურთუკს ვიცვამ.", "category": "top-5000", "level": "A2"},
{"english": "sing", "georgian": "სიმღერა", "pronunciation": "სინგ", "example_en": "She sings beautifully.", "example_ka": "ის ლამაზად მღერის.", "category": "top-5000", "level": "A2"},
{"english": "dance", "georgian": "ცეკვა", "pronunciation": "დენს", "example_en": "Let's dance.", "example_ka": "ვიცეკვოთ.", "category": "top-5000", "level": "A2"},
{"english": "cook", "georgian": "მზარეულობა / მომზადება", "pronunciation": "ქუქ", "example_en": "I love to cook.", "example_ka": "საჭმლის კეთება მიყვარს.", "category": "top-5000", "level": "A2"},
{"english": "wash", "georgian": "რეცხვა", "pronunciation": "ვოშ", "example_en": "Wash your hands.", "example_ka": "ხელები დაიბანე.", "category": "top-5000", "level": "A2"},
{"english": "teach", "georgian": "სწავლება", "pronunciation": "თიჩ", "example_en": "She teaches English.", "example_ka": "ის ინგლისურს ასწავლის.", "category": "top-5000", "level": "A2"},
{"english": "choose", "georgian": "არჩევა", "pronunciation": "ჩუზ", "example_en": "Choose one.", "example_ka": "ერთი აირჩიე.", "category": "top-5000", "level": "A2"},
{"english": "finish", "georgian": "დასრულება", "pronunciation": "ფინიშ", "example_en": "I need to finish.", "example_ka": "დასრულება მჭირდება.", "category": "top-5000", "level": "A2"},
{"english": "throw", "georgian": "სროლა / გადაგდება", "pronunciation": "თროუ", "example_en": "Throw me the ball.", "example_ka": "ბურთი გადმომისროლე.", "category": "top-5000", "level": "A2"},
{"english": "catch", "georgian": "დაჭერა", "pronunciation": "ქეჩ", "example_en": "Catch the ball.", "example_ka": "ბურთი დაიჭირე.", "category": "top-5000", "level": "A2"},
{"english": "fill", "georgian": "შევსება", "pronunciation": "ფილ", "example_en": "Fill the glass.", "example_ka": "ჭიქა შეავსე.", "category": "top-5000", "level": "A2"},
{"english": "drop", "georgian": "ჩაგდება / ვარდნა", "pronunciation": "დროფ", "example_en": "Don't drop it.", "example_ka": "არ ჩააგდო.", "category": "top-5000", "level": "A2"},
{"english": "push", "georgian": "ბიძგება / მიწოლა", "pronunciation": "ფუშ", "example_en": "Push the button.", "example_ka": "ღილაკს მიაწოლე.", "category": "top-5000", "level": "A2"},
{"english": "close", "georgian": "დახურვა", "pronunciation": "ქლოუზ", "example_en": "Close the door.", "example_ka": "კარი დახურე.", "category": "top-5000", "level": "A2"},
{"english": "fight", "georgian": "ბრძოლა / ჩხუბი", "pronunciation": "ფაით", "example_en": "Don't fight.", "example_ka": "ნუ ჩხუბობთ.", "category": "top-5000", "level": "A2"},
{"english": "wish", "georgian": "სურვილი", "pronunciation": "ვიშ", "example_en": "I wish you happiness.", "example_ka": "ბედნიერებას გისურვებ.", "category": "top-5000", "level": "A2"},
{"english": "hope", "georgian": "იმედი", "pronunciation": "ჰოუფ", "example_en": "I hope so.", "example_ka": "ვიმედოვნებ.", "category": "top-5000", "level": "A2"},
{"english": "forget", "georgian": "დავიწყება", "pronunciation": "ფორგეთ", "example_en": "Don't forget!", "example_ka": "არ დაგავიწყდეს!", "category": "top-5000", "level": "A2"},
{"english": "explain", "georgian": "ახსნა", "pronunciation": "იქსფლეინ", "example_en": "Please explain.", "example_ka": "გთხოვთ ახსენით.", "category": "top-5000", "level": "A2"},
{"english": "save", "georgian": "გადარჩენა / შენახვა", "pronunciation": "სეივ", "example_en": "Save your money.", "example_ka": "ფული დაიზოგე.", "category": "top-5000", "level": "A2"},
{"english": "arrive", "georgian": "ჩამოსვლა", "pronunciation": "ერაივ", "example_en": "When will you arrive?", "example_ka": "როდის ჩამოხვალ?", "category": "top-5000", "level": "A2"},
{"english": "return", "georgian": "დაბრუნება", "pronunciation": "რითერნ", "example_en": "I will return soon.", "example_ka": "მალე დავბრუნდები.", "category": "top-5000", "level": "A2"},
{"english": "join", "georgian": "შეერთება / გაწევრიანება", "pronunciation": "ჯოინ", "example_en": "Join our team.", "example_ka": "ჩვენს გუნდში გაწევრიანდი.", "category": "top-5000", "level": "A2"},
{"english": "fix", "georgian": "შეკეთება", "pronunciation": "ფიქს", "example_en": "Can you fix it?", "example_ka": "შეგიძლია შეაკეთო?", "category": "top-5000", "level": "A2"},
{"english": "guess", "georgian": "გამოცნობა", "pronunciation": "გეს", "example_en": "Guess what happened.", "example_ka": "გამოიცანი რა მოხდა.", "category": "top-5000", "level": "A2"},
# A2 nouns
{"english": "weather", "georgian": "ამინდი", "pronunciation": "ვეძერ", "example_en": "The weather is nice.", "example_ka": "ამინდი კარგია.", "category": "top-5000", "level": "A2"},
{"english": "age", "georgian": "ასაკი", "pronunciation": "ეიჯ", "example_en": "What is your age?", "example_ka": "რამდენი წლის ხარ?", "category": "top-5000", "level": "A2"},
{"english": "language", "georgian": "ენა", "pronunciation": "ლენგვიჯ", "example_en": "I speak two languages.", "example_ka": "ორ ენაზე ვლაპარაკობ.", "category": "top-5000", "level": "A2"},
{"english": "road", "georgian": "გზა", "pronunciation": "როუდ", "example_en": "The road is long.", "example_ka": "გზა გრძელია.", "category": "top-5000", "level": "A2"},
{"english": "heart", "georgian": "გული", "pronunciation": "ჰართ", "example_en": "My heart beats fast.", "example_ka": "გული სწრაფად მიცემს.", "category": "top-5000", "level": "A2"},
{"english": "face", "georgian": "სახე", "pronunciation": "ფეის", "example_en": "She has a beautiful face.", "example_ka": "ლამაზი სახე აქვს.", "category": "top-5000", "level": "A2"},
{"english": "voice", "georgian": "ხმა", "pronunciation": "ვოის", "example_en": "She has a nice voice.", "example_ka": "ლამაზი ხმა აქვს.", "category": "top-5000", "level": "A2"},
{"english": "price", "georgian": "ფასი", "pronunciation": "ფრაის", "example_en": "What is the price?", "example_ka": "რა ფასია?", "category": "top-5000", "level": "A2"},
{"english": "news", "georgian": "სიახლეები / ახალი ამბები", "pronunciation": "ნიუზ", "example_en": "I watch the news.", "example_ka": "ახალ ამბებს ვუყურებ.", "category": "top-5000", "level": "A2"},
{"english": "paper", "georgian": "ქაღალდი", "pronunciation": "ფეიფერ", "example_en": "Give me some paper.", "example_ka": "ქაღალდი მომეცი.", "category": "top-5000", "level": "A2"},
{"english": "letter", "georgian": "წერილი / ასო", "pronunciation": "ლეთერ", "example_en": "I wrote a letter.", "example_ka": "წერილი დავწერე.", "category": "top-5000", "level": "A2"},
{"english": "war", "georgian": "ომი", "pronunciation": "ვორ", "example_en": "War is terrible.", "example_ka": "ომი საშინელია.", "category": "top-5000", "level": "A2"},
{"english": "peace", "georgian": "მშვიდობა", "pronunciation": "ფის", "example_en": "We want peace.", "example_ka": "მშვიდობა გვინდა.", "category": "top-5000", "level": "A2"},
{"english": "class", "georgian": "კლასი / გაკვეთილი", "pronunciation": "ქლას", "example_en": "I have a class now.", "example_ka": "ახლა გაკვეთილი მაქვს.", "category": "top-5000", "level": "A2"},
{"english": "money", "georgian": "ფული", "pronunciation": "მანი", "example_en": "I need money.", "example_ka": "ფული მჭირდება.", "category": "top-5000", "level": "A2"},
{"english": "animal", "georgian": "ცხოველი", "pronunciation": "ენიმალ", "example_en": "I love animals.", "example_ka": "ცხოველები მიყვარს.", "category": "top-5000", "level": "A2"},
{"english": "bird", "georgian": "ფრინველი", "pronunciation": "ბერდ", "example_en": "A bird is singing.", "example_ka": "ფრინველი მღერის.", "category": "top-5000", "level": "A2"},
{"english": "fish", "georgian": "თევზი", "pronunciation": "ფიშ", "example_en": "I like fish.", "example_ka": "თევზი მომწონს.", "category": "top-5000", "level": "A2"},
{"english": "tree", "georgian": "ხე", "pronunciation": "თრი", "example_en": "The tree is tall.", "example_ka": "ხე მაღალია.", "category": "top-5000", "level": "A2"},
{"english": "flower", "georgian": "ყვავილი", "pronunciation": "ფლაუერ", "example_en": "I bought flowers.", "example_ka": "ყვავილები ვიყიდე.", "category": "top-5000", "level": "A2"},
{"english": "mountain", "georgian": "მთა", "pronunciation": "მაუნთენ", "example_en": "The mountain is high.", "example_ka": "მთა მაღალია.", "category": "top-5000", "level": "A2"},
{"english": "sea", "georgian": "ზღვა", "pronunciation": "სი", "example_en": "I love the sea.", "example_ka": "ზღვა მიყვარს.", "category": "top-5000", "level": "A2"},
{"english": "snow", "georgian": "თოვლი", "pronunciation": "სნოუ", "example_en": "It is snowing.", "example_ka": "თოვს.", "category": "top-5000", "level": "A2"},
{"english": "fire", "georgian": "ცეცხლი", "pronunciation": "ფაიერ", "example_en": "The fire is warm.", "example_ka": "ცეცხლი თბილია.", "category": "top-5000", "level": "A2"},
{"english": "sky", "georgian": "ცა", "pronunciation": "სქაი", "example_en": "The sky is blue.", "example_ka": "ცა ლურჯია.", "category": "top-5000", "level": "A2"},
{"english": "star", "georgian": "ვარსკვლავი", "pronunciation": "სთარ", "example_en": "Stars shine at night.", "example_ka": "ვარსკვლავები ღამით ანათებენ.", "category": "top-5000", "level": "A2"},
{"english": "moon", "georgian": "მთვარე", "pronunciation": "მუნ", "example_en": "The moon is full.", "example_ka": "მთვარე სავსეა.", "category": "top-5000", "level": "A2"},
{"english": "bread", "georgian": "პური", "pronunciation": "ბრედ", "example_en": "I need bread.", "example_ka": "პური მჭირდება.", "category": "top-5000", "level": "A2"},
{"english": "milk", "georgian": "რძე", "pronunciation": "მილქ", "example_en": "I drink milk.", "example_ka": "რძეს ვსვამ.", "category": "top-5000", "level": "A2"},
{"english": "tea", "georgian": "ჩაი", "pronunciation": "თი", "example_en": "I drink tea every morning.", "example_ka": "ყოველ დილით ჩაის ვსვამ.", "category": "top-5000", "level": "A2"},
{"english": "coffee", "georgian": "ყავა", "pronunciation": "ქოფი", "example_en": "I need coffee.", "example_ka": "ყავა მჭირდება.", "category": "top-5000", "level": "A2"},
{"english": "brother", "georgian": "ძმა", "pronunciation": "ბრაძერ", "example_en": "My brother is tall.", "example_ka": "ჩემი ძმა მაღალია.", "category": "top-5000", "level": "A2"},
{"english": "sister", "georgian": "და", "pronunciation": "სისთერ", "example_en": "My sister is older.", "example_ka": "ჩემი და უფროსია.", "category": "top-5000", "level": "A2"},
{"english": "son", "georgian": "ვაჟი / ვაჟიშვილი", "pronunciation": "სან", "example_en": "My son is five.", "example_ka": "ჩემი ვაჟი ხუთი წლისაა.", "category": "top-5000", "level": "A2"},
{"english": "daughter", "georgian": "ქალიშვილი", "pronunciation": "დოთერ", "example_en": "My daughter goes to school.", "example_ka": "ჩემი ქალიშვილი სკოლაში დადის.", "category": "top-5000", "level": "A2"},
{"english": "husband", "georgian": "ქმარი", "pronunciation": "ჰაზბენდ", "example_en": "Her husband works here.", "example_ka": "მისი ქმარი აქ მუშაობს.", "category": "top-5000", "level": "A2"},
{"english": "wife", "georgian": "ცოლი", "pronunciation": "ვაიფ", "example_en": "My wife is a doctor.", "example_ka": "ჩემი ცოლი ექიმია.", "category": "top-5000", "level": "A2"},
{"english": "king", "georgian": "მეფე", "pronunciation": "ქინგ", "example_en": "The king ruled wisely.", "example_ka": "მეფე ბრძნულად მართავდა.", "category": "top-5000", "level": "A2"},
{"english": "pain", "georgian": "ტკივილი", "pronunciation": "ფეინ", "example_en": "I feel pain.", "example_ka": "ტკივილს ვგრძნობ.", "category": "top-5000", "level": "A2"},
{"english": "blood", "georgian": "სისხლი", "pronunciation": "ბლად", "example_en": "I saw blood.", "example_ka": "სისხლი ვნახე.", "category": "top-5000", "level": "A2"},
{"english": "death", "georgian": "სიკვდილი", "pronunciation": "დეთ", "example_en": "Life and death.", "example_ka": "სიცოცხლე და სიკვდილი.", "category": "top-5000", "level": "A2"},
{"english": "market", "georgian": "ბაზარი / ბაზარი", "pronunciation": "მარქეთ", "example_en": "Go to the market.", "example_ka": "ბაზარში წადი.", "category": "top-5000", "level": "A2"},
{"english": "dream", "georgian": "ოცნება / სიზმარი", "pronunciation": "დრიმ", "example_en": "I had a dream.", "example_ka": "სიზმარი ვნახე.", "category": "top-5000", "level": "A2"},
{"english": "chance", "georgian": "შანსი", "pronunciation": "ჩენს", "example_en": "Give me a chance.", "example_ka": "შანსი მომეცი.", "category": "top-5000", "level": "A2"},
{"english": "ground", "georgian": "მიწა / ნიადაგი", "pronunciation": "გრაუნდ", "example_en": "Sit on the ground.", "example_ka": "მიწაზე დაჯექი.", "category": "top-5000", "level": "A2"},
{"english": "town", "georgian": "ქალაქი (პატარა)", "pronunciation": "თაუნ", "example_en": "I live in a small town.", "example_ka": "პატარა ქალაქში ვცხოვრობ.", "category": "top-5000", "level": "A2"},
{"english": "village", "georgian": "სოფელი", "pronunciation": "ვილიჯ", "example_en": "My village is beautiful.", "example_ka": "ჩემი სოფელი ლამაზია.", "category": "top-5000", "level": "A2"},
{"english": "church", "georgian": "ეკლესია", "pronunciation": "ჩერჩ", "example_en": "The church is old.", "example_ka": "ეკლესია ძველია.", "category": "top-5000", "level": "A2"},
{"english": "store", "georgian": "მაღაზია", "pronunciation": "სთორ", "example_en": "I went to the store.", "example_ka": "მაღაზიაში წავედი.", "category": "top-5000", "level": "A2"},
{"english": "hospital", "georgian": "საავადმყოფო", "pronunciation": "ჰოსფითალ", "example_en": "He is in the hospital.", "example_ka": "ის საავადმყოფოშია.", "category": "top-5000", "level": "A2"},
{"english": "hotel", "georgian": "სასტუმრო", "pronunciation": "ჰოთელ", "example_en": "We stayed at a hotel.", "example_ka": "სასტუმროში დავრჩით.", "category": "top-5000", "level": "A2"},
{"english": "restaurant", "georgian": "რესტორანი", "pronunciation": "რესთორენთ", "example_en": "Let's go to a restaurant.", "example_ka": "რესტორანში წავიდეთ.", "category": "top-5000", "level": "A2"},
{"english": "bank", "georgian": "ბანკი", "pronunciation": "ბენქ", "example_en": "I went to the bank.", "example_ka": "ბანკში წავედი.", "category": "top-5000", "level": "A2"},
{"english": "park", "georgian": "პარკი", "pronunciation": "ფარქ", "example_en": "Let's go to the park.", "example_ka": "პარკში წავიდეთ.", "category": "top-5000", "level": "A2"},
# A2 adjectives
{"english": "important", "georgian": "მნიშვნელოვანი", "pronunciation": "იმფორთენთ", "example_en": "This is important.", "example_ka": "ეს მნიშვნელოვანია.", "category": "top-5000", "level": "A2"},
{"english": "different", "georgian": "განსხვავებული", "pronunciation": "დიფერენთ", "example_en": "We are all different.", "example_ka": "ყველა განსხვავებულები ვართ.", "category": "top-5000", "level": "A2"},
{"english": "same", "georgian": "იგივე / ერთნაირი", "pronunciation": "სეიმ", "example_en": "We have the same idea.", "example_ka": "ერთნაირი იდეა გვაქვს.", "category": "top-5000", "level": "A2"},
{"english": "young", "georgian": "ახალგაზრდა", "pronunciation": "იანგ", "example_en": "She is young.", "example_ka": "ის ახალგაზრდაა.", "category": "top-5000", "level": "A2"},
{"english": "special", "georgian": "განსაკუთრებული", "pronunciation": "სფეშალ", "example_en": "Today is a special day.", "example_ka": "დღეს განსაკუთრებული დღეა.", "category": "top-5000", "level": "A2"},
{"english": "clear", "georgian": "ნათელი / გასაგები", "pronunciation": "ქლიარ", "example_en": "Is that clear?", "example_ka": "ეს გასაგებია?", "category": "top-5000", "level": "A2"},
{"english": "certain", "georgian": "დარწმუნებული / გარკვეული", "pronunciation": "სერთენ", "example_en": "I am certain.", "example_ka": "დარწმუნებული ვარ.", "category": "top-5000", "level": "A2"},
{"english": "common", "georgian": "გავრცელებული / საერთო", "pronunciation": "ქომენ", "example_en": "It is a common problem.", "example_ka": "ეს გავრცელებული პრობლემაა.", "category": "top-5000", "level": "A2"},
{"english": "poor", "georgian": "ღარიბი", "pronunciation": "ფუარ", "example_en": "The family is poor.", "example_ka": "ოჯახი ღარიბია.", "category": "top-5000", "level": "A2"},
{"english": "rich", "georgian": "მდიდარი", "pronunciation": "რიჩ", "example_en": "He is rich.", "example_ka": "ის მდიდარია.", "category": "top-5000", "level": "A2"},
{"english": "wrong", "georgian": "არასწორი", "pronunciation": "რონგ", "example_en": "You are wrong.", "example_ka": "შენ ცდები.", "category": "top-5000", "level": "A2"},
{"english": "fine", "georgian": "კარგად / ჯარიმა", "pronunciation": "ფაინ", "example_en": "I am fine.", "example_ka": "კარგად ვარ.", "category": "top-5000", "level": "A2"},
{"english": "real", "georgian": "ნამდვილი", "pronunciation": "რიალ", "example_en": "Is this real?", "example_ka": "ეს ნამდვილია?", "category": "top-5000", "level": "A2"},
{"english": "deep", "georgian": "ღრმა", "pronunciation": "დიფ", "example_en": "The river is deep.", "example_ka": "მდინარე ღრმაა.", "category": "top-5000", "level": "A2"},
{"english": "wide", "georgian": "ფართო", "pronunciation": "ვაიდ", "example_en": "The road is wide.", "example_ka": "გზა ფართოა.", "category": "top-5000", "level": "A2"},
{"english": "tall", "georgian": "მაღალი (ადამიანი)", "pronunciation": "თოლ", "example_en": "He is tall.", "example_ka": "ის მაღალია.", "category": "top-5000", "level": "A2"},
{"english": "safe", "georgian": "უსაფრთხო", "pronunciation": "სეიფ", "example_en": "You are safe here.", "example_ka": "აქ უსაფრთხოდ ხარ.", "category": "top-5000", "level": "A2"},
{"english": "dangerous", "georgian": "საშიში", "pronunciation": "დეინჯერეს", "example_en": "It is dangerous.", "example_ka": "ეს საშიშია.", "category": "top-5000", "level": "A2"},
{"english": "busy", "georgian": "დაკავებული", "pronunciation": "ბიზი", "example_en": "I am busy.", "example_ka": "დაკავებული ვარ.", "category": "top-5000", "level": "A2"},
{"english": "quiet", "georgian": "ჩუმი / წყნარი", "pronunciation": "ქვაიეთ", "example_en": "Be quiet.", "example_ka": "ჩუმად იყავი.", "category": "top-5000", "level": "A2"},
{"english": "loud", "georgian": "ხმამაღალი", "pronunciation": "ლაუდ", "example_en": "The music is loud.", "example_ka": "მუსიკა ხმამაღალია.", "category": "top-5000", "level": "A2"},
{"english": "fresh", "georgian": "ახალი / სუფთა", "pronunciation": "ფრეშ", "example_en": "Fresh air.", "example_ka": "სუფთა ჰაერი.", "category": "top-5000", "level": "A2"},
{"english": "dry", "georgian": "მშრალი", "pronunciation": "დრაი", "example_en": "The weather is dry.", "example_ka": "ამინდი მშრალია.", "category": "top-5000", "level": "A2"},
{"english": "wet", "georgian": "სველი", "pronunciation": "ვეთ", "example_en": "The road is wet.", "example_ka": "გზა სველია.", "category": "top-5000", "level": "A2"},
{"english": "hungry", "georgian": "მშიერი", "pronunciation": "ჰანგრი", "example_en": "I am hungry.", "example_ka": "მშია.", "category": "top-5000", "level": "A2"},
{"english": "thirsty", "georgian": "მწყურვალი", "pronunciation": "თერსთი", "example_en": "I am thirsty.", "example_ka": "მწყურია.", "category": "top-5000", "level": "A2"},
{"english": "tired", "georgian": "დაღლილი", "pronunciation": "თაიერდ", "example_en": "I am tired.", "example_ka": "დაღლილი ვარ.", "category": "top-5000", "level": "A2"},
{"english": "sick", "georgian": "ავადმყოფი", "pronunciation": "სიქ", "example_en": "I feel sick.", "example_ka": "ავად ვარ.", "category": "top-5000", "level": "A2"},
{"english": "healthy", "georgian": "ჯანმრთელი", "pronunciation": "ჰელთი", "example_en": "Stay healthy.", "example_ka": "ჯანმრთელი იყავი.", "category": "top-5000", "level": "A2"},
{"english": "angry", "georgian": "გაბრაზებული", "pronunciation": "ენგრი", "example_en": "Don't be angry.", "example_ka": "ნუ გაბრაზდები.", "category": "top-5000", "level": "A2"},
{"english": "afraid", "georgian": "შეშინებული", "pronunciation": "ეფრეიდ", "example_en": "Don't be afraid.", "example_ka": "ნუ გეშინია.", "category": "top-5000", "level": "A2"},
{"english": "alive", "georgian": "ცოცხალი", "pronunciation": "ელაივ", "example_en": "He is alive.", "example_ka": "ის ცოცხალია.", "category": "top-5000", "level": "A2"},
{"english": "dead", "georgian": "მკვდარი", "pronunciation": "დედ", "example_en": "The plant is dead.", "example_ka": "მცენარე დაჭკნა.", "category": "top-5000", "level": "A2"},
{"english": "famous", "georgian": "ცნობილი", "pronunciation": "ფეიმეს", "example_en": "He is famous.", "example_ka": "ის ცნობილია.", "category": "top-5000", "level": "A2"},
{"english": "foreign", "georgian": "უცხო / საზღვარგარეთის", "pronunciation": "ფორენ", "example_en": "Foreign languages are useful.", "example_ka": "უცხო ენები სასარგებლოა.", "category": "top-5000", "level": "A2"},
{"english": "main", "georgian": "მთავარი", "pronunciation": "მეინ", "example_en": "The main street.", "example_ka": "მთავარი ქუჩა.", "category": "top-5000", "level": "A2"},
{"english": "green", "georgian": "მწვანე", "pronunciation": "გრინ", "example_en": "The grass is green.", "example_ka": "ბალახი მწვანეა.", "category": "top-5000", "level": "A2"},
{"english": "red", "georgian": "წითელი", "pronunciation": "რედ", "example_en": "The car is red.", "example_ka": "მანქანა წითელია.", "category": "top-5000", "level": "A2"},
{"english": "blue", "georgian": "ლურჯი", "pronunciation": "ბლუ", "example_en": "The sky is blue.", "example_ka": "ცა ლურჯია.", "category": "top-5000", "level": "A2"},
{"english": "yellow", "georgian": "ყვითელი", "pronunciation": "იელოუ", "example_en": "The sun is yellow.", "example_ka": "მზე ყვითელია.", "category": "top-5000", "level": "A2"},

# ===== B1 LEVEL =====
{"english": "achieve", "georgian": "მიღწევა", "pronunciation": "ეჩივ", "example_en": "I want to achieve my goals.", "example_ka": "მიზნების მიღწევა მინდა.", "category": "top-5000", "level": "B1"},
{"english": "announce", "georgian": "გამოცხადება", "pronunciation": "ენაუნს", "example_en": "They announced the winner.", "example_ka": "გამარჯვებული გამოაცხადეს.", "category": "top-5000", "level": "B1"},
{"english": "apply", "georgian": "მიმართვა / გამოყენება", "pronunciation": "ეფლაი", "example_en": "I applied for the job.", "example_ka": "სამუშაოზე მივმართე.", "category": "top-5000", "level": "B1"},
{"english": "approach", "georgian": "მიდგომა / მიახლოება", "pronunciation": "ეფროუჩ", "example_en": "She approached slowly.", "example_ka": "ის ნელ-ნელა მოუახლოვდა.", "category": "top-5000", "level": "B1"},
{"english": "arrange", "georgian": "მოწყობა", "pronunciation": "ერეინჯ", "example_en": "Arrange a meeting.", "example_ka": "შეხვედრა მოაწყე.", "category": "top-5000", "level": "B1"},
{"english": "attach", "georgian": "მიმაგრება", "pronunciation": "ეთეჩ", "example_en": "Attach the file.", "example_ka": "ფაილი მიამაგრე.", "category": "top-5000", "level": "B1"},
{"english": "attempt", "georgian": "მცდელობა", "pronunciation": "ეთემფთ", "example_en": "He attempted to escape.", "example_ka": "მან გაქცევა სცადა.", "category": "top-5000", "level": "B1"},
{"english": "attend", "georgian": "დასწრება", "pronunciation": "ეთენდ", "example_en": "I attended the meeting.", "example_ka": "შეხვედრას დავესწარი.", "category": "top-5000", "level": "B1"},
{"english": "avoid", "georgian": "თავის არიდება", "pronunciation": "ევოიდ", "example_en": "Avoid mistakes.", "example_ka": "შეცდომებს თავი აარიდე.", "category": "top-5000", "level": "B1"},
{"english": "behave", "georgian": "ქცევა / მოქცევა", "pronunciation": "ბიჰეივ", "example_en": "Behave yourself.", "example_ka": "თავი დაიჭირე.", "category": "top-5000", "level": "B1"},
{"english": "belong", "georgian": "კუთვნება / ეკუთვნის", "pronunciation": "ბილონგ", "example_en": "This book belongs to me.", "example_ka": "ეს წიგნი ჩემია.", "category": "top-5000", "level": "B1"},
{"english": "borrow", "georgian": "სესხება (აღება)", "pronunciation": "ბოროუ", "example_en": "Can I borrow your pen?", "example_ka": "შეიძლება კალამი მისესხო?", "category": "top-5000", "level": "B1"},
{"english": "celebrate", "georgian": "აღნიშვნა / ზეიმი", "pronunciation": "სელიბრეით", "example_en": "Let's celebrate!", "example_ka": "ვიზეიმოთ!", "category": "top-5000", "level": "B1"},
{"english": "communicate", "georgian": "კომუნიკაცია", "pronunciation": "ქომიუნიქეით", "example_en": "We need to communicate better.", "example_ka": "უკეთესი კომუნიკაცია გვჭირდება.", "category": "top-5000", "level": "B1"},
{"english": "compare", "georgian": "შედარება", "pronunciation": "ქომფეარ", "example_en": "Compare these two.", "example_ka": "ეს ორი შეადარე.", "category": "top-5000", "level": "B1"},
{"english": "compete", "georgian": "კონკურენცია / შეჯიბრება", "pronunciation": "ქომფით", "example_en": "Teams compete for the prize.", "example_ka": "გუნდები პრიზისთვის იჯიბრებიან.", "category": "top-5000", "level": "B1"},
{"english": "complain", "georgian": "ჩივილი", "pronunciation": "ქომფლეინ", "example_en": "Don't complain.", "example_ka": "ნუ ჩივი.", "category": "top-5000", "level": "B1"},
{"english": "concern", "georgian": "შეშფოთება / ეხება", "pronunciation": "ქონსერნ", "example_en": "I am concerned.", "example_ka": "შეშფოთებული ვარ.", "category": "top-5000", "level": "B1"},
{"english": "confirm", "georgian": "დადასტურება", "pronunciation": "ქონფერმ", "example_en": "Please confirm your booking.", "example_ka": "გთხოვთ დაადასტუროთ ჯავშანი.", "category": "top-5000", "level": "B1"},
{"english": "connect", "georgian": "დაკავშირება", "pronunciation": "ქონექთ", "example_en": "Connect to the internet.", "example_ka": "ინტერნეტთან დაუკავშირდი.", "category": "top-5000", "level": "B1"},
{"english": "contain", "georgian": "შეიცავს", "pronunciation": "ქონთეინ", "example_en": "This box contains books.", "example_ka": "ეს ყუთი წიგნებს შეიცავს.", "category": "top-5000", "level": "B1"},
{"english": "control", "georgian": "კონტროლი", "pronunciation": "ქონთროლ", "example_en": "Control your emotions.", "example_ka": "ემოციები აკონტროლე.", "category": "top-5000", "level": "B1"},
{"english": "convince", "georgian": "დარწმუნება", "pronunciation": "ქონვინს", "example_en": "I convinced him.", "example_ka": "დავარწმუნე ის.", "category": "top-5000", "level": "B1"},
{"english": "correct", "georgian": "სწორი / გასწორება", "pronunciation": "ქორექთ", "example_en": "Is this correct?", "example_ka": "ეს სწორია?", "category": "top-5000", "level": "B1"},
{"english": "cover", "georgian": "დაფარვა / საფარი", "pronunciation": "ქავერ", "example_en": "Cover yourself with a blanket.", "example_ka": "საბნით დაიფარე.", "category": "top-5000", "level": "B1"},
{"english": "cross", "georgian": "გადაკვეთა / ჯვარი", "pronunciation": "ქროს", "example_en": "Cross the street carefully.", "example_ka": "ქუჩა ფრთხილად გადაკვეთე.", "category": "top-5000", "level": "B1"},
{"english": "damage", "georgian": "დაზიანება", "pronunciation": "დემიჯ", "example_en": "The storm caused damage.", "example_ka": "ქარიშხალმა ზიანი მიაყენა.", "category": "top-5000", "level": "B1"},
{"english": "deal", "georgian": "გარიგება / საქმე", "pronunciation": "დილ", "example_en": "We made a deal.", "example_ka": "შეთანხმებას მივაღწიეთ.", "category": "top-5000", "level": "B1"},
{"english": "deliver", "georgian": "მიწოდება / მიტანა", "pronunciation": "დილივერ", "example_en": "They deliver food.", "example_ka": "ისინი საკვებს მიაწვდიან.", "category": "top-5000", "level": "B1"},
{"english": "demand", "georgian": "მოთხოვნა", "pronunciation": "დიმანდ", "example_en": "They demand better pay.", "example_ka": "უკეთეს ხელფასს მოითხოვენ.", "category": "top-5000", "level": "B1"},
{"english": "depend", "georgian": "დამოკიდებულება", "pronunciation": "დიფენდ", "example_en": "It depends on you.", "example_ka": "ეს შენზე არის დამოკიდებული.", "category": "top-5000", "level": "B1"},
{"english": "describe", "georgian": "აღწერა", "pronunciation": "დისქრაიბ", "example_en": "Describe what you see.", "example_ka": "აღწერე რას ხედავ.", "category": "top-5000", "level": "B1"},
{"english": "design", "georgian": "დიზაინი / დაპროექტება", "pronunciation": "დიზაინ", "example_en": "She designed the website.", "example_ka": "მან ვებსაიტი დააპროექტა.", "category": "top-5000", "level": "B1"},
{"english": "destroy", "georgian": "განადგურება", "pronunciation": "დისთროი", "example_en": "War destroys everything.", "example_ka": "ომი ყველაფერს ანადგურებს.", "category": "top-5000", "level": "B1"},
{"english": "discover", "georgian": "აღმოჩენა", "pronunciation": "დისქავერ", "example_en": "I discovered a new place.", "example_ka": "ახალი ადგილი აღმოვაჩინე.", "category": "top-5000", "level": "B1"},
{"english": "discuss", "georgian": "განხილვა", "pronunciation": "დისქას", "example_en": "Let's discuss it.", "example_ka": "მოდი, განვიხილოთ.", "category": "top-5000", "level": "B1"},
{"english": "earn", "georgian": "შოვნა / გამომუშავება", "pronunciation": "ერნ", "example_en": "I earn money.", "example_ka": "ფულს ვშოულობ.", "category": "top-5000", "level": "B1"},
{"english": "encourage", "georgian": "წახალისება", "pronunciation": "ინქარიჯ", "example_en": "I encourage you to try.", "example_ka": "გიწახალისებ სცადო.", "category": "top-5000", "level": "B1"},
{"english": "establish", "georgian": "დაარსება", "pronunciation": "ისთებლიშ", "example_en": "They established a company.", "example_ka": "კომპანია დაარსეს.", "category": "top-5000", "level": "B1"},
{"english": "examine", "georgian": "გამოკვლევა", "pronunciation": "იგზემინ", "example_en": "The doctor examined me.", "example_ka": "ექიმმა გამომიკვლია.", "category": "top-5000", "level": "B1"},
{"english": "exist", "georgian": "არსებობა", "pronunciation": "იგზისთ", "example_en": "Dinosaurs no longer exist.", "example_ka": "დინოზავრები აღარ არსებობენ.", "category": "top-5000", "level": "B1"},
{"english": "express", "georgian": "გამოხატვა", "pronunciation": "იქსფრეს", "example_en": "Express your feelings.", "example_ka": "გრძნობები გამოხატე.", "category": "top-5000", "level": "B1"},
{"english": "fail", "georgian": "ჩავარდნა / წარუმატებლობა", "pronunciation": "ფეილ", "example_en": "Don't be afraid to fail.", "example_ka": "ნუ გეშინია წარუმატებლობის.", "category": "top-5000", "level": "B1"},
{"english": "gain", "georgian": "მოპოვება / მოგება", "pronunciation": "გეინ", "example_en": "I gained experience.", "example_ka": "გამოცდილება მივიღე.", "category": "top-5000", "level": "B1"},
{"english": "gather", "georgian": "შეკრება", "pronunciation": "გეძერ", "example_en": "People gathered in the park.", "example_ka": "ხალხი პარკში შეიკრიბა.", "category": "top-5000", "level": "B1"},
{"english": "handle", "georgian": "გამკლავება / სახელური", "pronunciation": "ჰენდლ", "example_en": "I can handle it.", "example_ka": "გავუმკლავდები.", "category": "top-5000", "level": "B1"},
{"english": "identify", "georgian": "იდენტიფიცირება", "pronunciation": "აიდენთიფაი", "example_en": "Identify the problem.", "example_ka": "პრობლემა გამოავლინე.", "category": "top-5000", "level": "B1"},
{"english": "ignore", "georgian": "უგულებელყოფა", "pronunciation": "იგნორ", "example_en": "Don't ignore me.", "example_ka": "ნუ მიგნორებ.", "category": "top-5000", "level": "B1"},
{"english": "imagine", "georgian": "წარმოდგენა", "pronunciation": "იმეჯინ", "example_en": "Imagine a better world.", "example_ka": "წარმოიდგინე უკეთესი სამყარო.", "category": "top-5000", "level": "B1"},
{"english": "improve", "georgian": "გაუმჯობესება", "pronunciation": "იმფრუვ", "example_en": "I want to improve my English.", "example_ka": "ინგლისურის გაუმჯობესება მინდა.", "category": "top-5000", "level": "B1"},
{"english": "increase", "georgian": "ზრდა / გაზრდა", "pronunciation": "ინქრის