#!/usr/bin/env python3
"""Generate top-5000-words.json with real frequency-ordered English words and Georgian translations."""
import json

# Complete word list: (english, georgian, pronunciation, example_en, example_ka)
# Organized in frequency order based on corpus linguistics data

data = []

def add(english, georgian, pronunciation, example_en, example_ka, level):
    data.append({
        "english": english,
        "georgian": georgian,
        "pronunciation": pronunciation,
        "example_en": example_en,
        "example_ka": example_ka,
        "category": "top-5000",
        "level": level
    })

def a1(e, g, p, ex_en, ex_ka): add(e, g, p, ex_en, ex_ka, "A1")
def a2(e, g, p, ex_en, ex_ka): add(e, g, p, ex_en, ex_ka, "A2")
def b1(e, g, p, ex_en, ex_ka): add(e, g, p, ex_en, ex_ka, "B1")
def b2(e, g, p, ex_en, ex_ka): add(e, g, p, ex_en, ex_ka, "B2")
def c1(e, g, p, ex_en, ex_ka): add(e, g, p, ex_en, ex_ka, "C1")

# ============ A1: Words 1-1000 ============
# 1-50: Most basic function words and verbs
a1("the", "ეს/ის (არტიკლი)", "დი", "The cat is on the table.", "კატა მაგიდაზეა.")
a1("be", "ყოფნა", "ბი", "I want to be happy.", "მინდა ბედნიერი ვიყო.")
a1("to", "-კენ/რომ", "თუ", "I go to school.", "სკოლაში მივდივარ.")
a1("of", "-ის", "ოვ", "A cup of tea.", "ერთი ჭიქა ჩაი.")
a1("and", "და", "ენდ", "You and me.", "შენ და მე.")
a1("a", "ერთი (არტიკლი)", "ეი", "I have a dog.", "ძაღლი მყავს.")
a1("in", "-ში", "ინ", "He is in the room.", "ის ოთახშია.")
a1("that", "რომ/ის", "დეთ", "I know that you are right.", "ვიცი რომ მართალი ხარ.")
a1("have", "ქონა", "ჰევ", "I have two brothers.", "ორი ძმა მყავს.")
a1("I", "მე", "აი", "I am a student.", "მე სტუდენტი ვარ.")
a1("it", "ის (საგანი)", "იტ", "It is raining.", "წვიმს.")
a1("for", "-თვის", "ფორ", "This is for you.", "ეს შენთვისაა.")
a1("not", "არა", "ნოთ", "I am not tired.", "დაღლილი არ ვარ.")
a1("on", "-ზე", "ონ", "The book is on the table.", "წიგნი მაგიდაზეა.")
a1("with", "-თან/-ით", "ვიზ", "Come with me.", "წამოდი ჩემთან.")
a1("he", "ის (მამრ.)", "ჰი", "He is my friend.", "ის ჩემი მეგობარია.")
a1("as", "როგორც", "ეზ", "As you wish.", "როგორც გინდა.")
a1("you", "შენ/თქვენ", "იუ", "You are welcome.", "არაფრის.")
a1("do", "კეთება", "დუ", "What do you do?", "რას აკეთებ?")
a1("at", "-ში/-ზე/-თან", "ეთ", "I am at home.", "სახლში ვარ.")
a1("this", "ეს", "დის", "This is my house.", "ეს ჩემი სახლია.")
a1("but", "მაგრამ", "ბათ", "I tried but failed.", "ვცადე მაგრამ ვერ შევძელი.")
a1("his", "მისი (მამრ.)", "ჰიზ", "His name is John.", "მის სახელია ჯონი.")
a1("by", "-ით/-თან", "ბაი", "Made by hand.", "ხელით გაკეთებული.")
a1("from", "-დან", "ფრომ", "I am from Georgia.", "საქართველოდან ვარ.")
a1("they", "ისინი", "დეი", "They are students.", "ისინი სტუდენტები არიან.")
a1("we", "ჩვენ", "ვი", "We are a team.", "ჩვენ გუნდი ვართ.")
a1("say", "თქმა", "სეი", "What did you say?", "რა თქვი?")
a1("her", "მისი (მდედრ.)", "ჰერ", "Her dress is beautiful.", "მისი კაბა ლამაზია.")
a1("she", "ის (მდედრ.)", "ში", "She is a doctor.", "ის ექიმია.")
a1("or", "ან", "ორ", "Tea or coffee?", "ჩაი თუ ყავა?")
a1("an", "ერთი (არტიკლი)", "ენ", "An apple a day.", "ერთი ვაშლი დღეში.")
a1("will", "მომავალი დრო", "ვილ", "I will come tomorrow.", "ხვალ მოვალ.")
a1("my", "ჩემი", "მაი", "This is my book.", "ეს ჩემი წიგნია.")
a1("one", "ერთი", "ვან", "I have one question.", "ერთი კითხვა მაქვს.")
a1("all", "ყველა", "ოლ", "All people are equal.", "ყველა თანასწორია.")
a1("would", "იქნებოდა", "ვუდ", "I would like water.", "წყალი მინდა.")
a1("there", "იქ/არის", "დეარ", "There is a park nearby.", "ახლოს პარკია.")
a1("their", "მათი", "დეარ", "Their house is big.", "მათი სახლი დიდია.")
a1("what", "რა", "ვოთ", "What is your name?", "რა გქვია?")
a1("so", "ასე/ამიტომ", "სო", "I am tired so I rest.", "დაღლილი ვარ, ამიტომ ვისვენებ.")
a1("up", "ზემოთ", "აფ", "Stand up!", "ადექი!")
a1("out", "გარეთ", "აუთ", "Go out!", "გადი გარეთ!")
a1("if", "თუ", "იფ", "If you want, come.", "თუ გინდა, მოდი.")
a1("about", "შესახებ", "ებაუთ", "Tell me about yourself.", "მომიყევი შენს შესახებ.")
a1("who", "ვინ", "ჰუ", "Who are you?", "ვინ ხარ?")
a1("get", "მიღება", "გეთ", "I will get the book.", "წიგნს ავიღებ.")
a1("which", "რომელი", "ვიჩ", "Which one do you want?", "რომელი გინდა?")
a1("go", "წასვლა", "გო", "Let's go home.", "სახლში წავიდეთ.")
a1("me", "მე (ობიექტ.)", "მი", "Tell me the truth.", "მითხარი სიმართლე.")
# 51-100
a1("when", "როდის", "ვენ", "When will you come?", "როდის მოხვალ?")
a1("make", "გაკეთება", "მეიქ", "Make a wish.", "ისურვე.")
a1("can", "შეუძლია", "ქენ", "I can swim.", "ცურვა შემიძლია.")
a1("like", "მოწონება/მსგავსი", "ლაიქ", "I like music.", "მუსიკა მომწონს.")
a1("time", "დრო", "თაიმ", "What time is it?", "რომელი საათია?")
a1("no", "არა", "ნო", "No, thank you.", "არა, გმადლობთ.")
a1("just", "უბრალოდ/ახლახან", "ჯასთ", "I just arrived.", "ახლახან მოვედი.")
a1("him", "მას (მამრ.)", "ჰიმ", "I saw him yesterday.", "გუშინ ვნახე.")
a1("know", "ცოდნა", "ნოუ", "I know the answer.", "პასუხი ვიცი.")
a1("take", "აღება", "თეიქ", "Take my hand.", "ხელი მომეცი.")
a1("people", "ხალხი", "ფიფლ", "People are kind.", "ხალხი კეთილია.")
a1("into", "შიგნით", "ინთუ", "Go into the room.", "ოთახში შედი.")
a1("year", "წელი", "იარ", "This year is great.", "ეს წელი კარგია.")
a1("your", "შენი", "იორ", "Your idea is great.", "შენი იდეა კარგია.")
a1("good", "კარგი", "გუდ", "Good morning!", "დილა მშვიდობისა!")
a1("some", "რამდენიმე", "სამ", "Give me some water.", "ცოტა წყალი მომეცი.")
a1("could", "შეეძლო", "ქუდ", "Could you help me?", "დამეხმარები?")
a1("them", "მათ", "დემ", "I gave them a gift.", "საჩუქარი მივეცი.")
a1("see", "ხედვა", "სი", "I can see the mountain.", "მთა მჩანს.")
a1("other", "სხვა", "აზერ", "The other side.", "მეორე მხარე.")
a1("than", "ვიდრე", "დენ", "Better than before.", "უკეთესი ვიდრე ადრე.")
a1("then", "მერე/მაშინ", "დენ", "And then what?", "და მერე რა?")
a1("now", "ახლა", "ნაუ", "Do it now.", "ახლა გააკეთე.")
a1("look", "ყურება", "ლუქ", "Look at this!", "ამას შეხედე!")
a1("only", "მხოლოდ", "ონლი", "I have only one.", "მხოლოდ ერთი მაქვს.")
a1("come", "მოსვლა", "ქამ", "Come here!", "მოდი აქ!")
a1("its", "მისი (საგნის)", "იცს", "The dog wagged its tail.", "ძაღლმა კუდი დაუქნია.")
a1("over", "ზემოთ/დასრულებული", "ოვერ", "The game is over.", "თამაში დამთავრდა.")
a1("think", "ფიქრი", "სინქ", "I think you are right.", "ვფიქრობ მართალი ხარ.")
a1("also", "ასევე", "ოლსო", "I also like it.", "მეც მომწონს.")
a1("back", "უკან/ზურგი", "ბექ", "Come back soon!", "მალე დაბრუნდი!")
a1("after", "შემდეგ", "აფთერ", "After school.", "სკოლის შემდეგ.")
a1("use", "გამოყენება", "იუზ", "I use my phone daily.", "ტელეფონს ყოველდღე ვიყენებ.")
a1("two", "ორი", "თუ", "I have two cats.", "ორი კატა მყავს.")
a1("how", "როგორ", "ჰაუ", "How are you?", "როგორ ხარ?")
a1("our", "ჩვენი", "აუარ", "This is our home.", "ეს ჩვენი სახლია.")
a1("work", "სამუშაო/მუშაობა", "ვორქ", "I work every day.", "ყოველდღე ვმუშაობ.")
a1("first", "პირველი", "ფერსთ", "This is my first time.", "ეს პირველი ჯერია.")
a1("well", "კარგად", "ველ", "I feel well.", "კარგად ვარ.")
a1("way", "გზა/ხერხი", "ვეი", "This is the way.", "ეს არის გზა.")
a1("even", "თუნდაც", "ივენ", "Even I can do it.", "მეც კი შემიძლია.")
a1("new", "ახალი", "ნიუ", "I bought a new car.", "ახალი მანქანა ვიყიდე.")
a1("want", "სურვილი", "ვონთ", "I want to learn.", "სწავლა მინდა.")
a1("because", "იმიტომ რომ", "ბიქოზ", "I stay because I care.", "ვრჩები იმიტომ რომ მაინტერესებს.")
a1("any", "ნებისმიერი", "ენი", "Any questions?", "კითხვები?")
a1("these", "ესენი", "დიზ", "These are my friends.", "ესენი ჩემი მეგობრები არიან.")
a1("give", "მიცემა", "გივ", "Give me a chance.", "შანსი მომეცი.")
a1("day", "დღე", "დეი", "Have a nice day!", "კარგი დღე!")
a1("most", "ყველაზე მეტი", "მოსთ", "Most people agree.", "უმეტესობა ეთანხმება.")
a1("find", "პოვნა", "ფაინდ", "I need to find my keys.", "გასაღებები უნდა ვიპოვო.")
# 101-200
a1("here", "აქ", "ჰიარ", "Come here!", "მოდი აქ!")
a1("thing", "რამ/საგანი", "სინგ", "What is this thing?", "ეს რა არის?")
a1("many", "ბევრი", "მენი", "I have many books.", "ბევრი წიგნი მაქვს.")
a1("very", "ძალიან", "ვერი", "Very good!", "ძალიან კარგი!")
a1("still", "ჯერ კიდევ", "სთილ", "I am still waiting.", "ჯერ კიდევ ველოდები.")
a1("own", "საკუთარი", "ოუნ", "I have my own room.", "საკუთარი ოთახი მაქვს.")
a1("great", "შესანიშნავი/დიდი", "გრეით", "That is a great idea!", "შესანიშნავი იდეაა!")
a1("tell", "თქმა/მოყოლა", "თელ", "Tell me a story.", "ამბავი მომიყევი.")
a1("much", "ბევრი", "მაჩ", "Thank you very much.", "დიდი მადლობა.")
a1("should", "უნდა", "შუდ", "You should rest.", "უნდა დაისვენო.")
a1("long", "გრძელი", "ლონგ", "It is a long road.", "გრძელი გზაა.")
a1("where", "სად", "ვეარ", "Where are you?", "სად ხარ?")
a1("life", "ცხოვრება", "ლაიფ", "Life is beautiful.", "ცხოვრება ლამაზია.")
a1("those", "ისინი", "დოუზ", "Those are mine.", "ისინი ჩემია.")
a1("made", "გაკეთებული", "მეიდ", "Made of wood.", "ხისგან გაკეთებული.")
a1("world", "სამყარო", "ვორლდ", "The world is big.", "სამყარო დიდია.")
a1("live", "ცხოვრება", "ლივ", "I live in Tbilisi.", "თბილისში ვცხოვრობ.")
a1("hand", "ხელი", "ჰენდ", "Give me your hand.", "ხელი მომეცი.")
a1("high", "მაღალი", "ჰაი", "The mountain is high.", "მთა მაღალია.")
a1("old", "ძველი/მოხუცი", "ოლდ", "How old are you?", "რამდენი წლის ხარ?")
a1("keep", "შენახვა", "ქიფ", "Keep going!", "გააგრძელე!")
a1("last", "ბოლო", "ლასთ", "This is the last one.", "ეს უკანასკნელია.")
a1("never", "არასოდეს", "ნევერ", "I never give up.", "არასოდეს დავნებდები.")
a1("let", "ნება/უშვებს", "ლეთ", "Let me help you.", "ნება მომეცი დაგეხმარო.")
a1("before", "ადრე/წინ", "ბიფორ", "Before class.", "გაკვეთილამდე.")
a1("big", "დიდი", "ბიგ", "I have a big family.", "დიდი ოჯახი მყავს.")
a1("right", "სწორი/მარჯვენა", "რაით", "You are right.", "მართალი ხარ.")
a1("may", "შეიძლება", "მეი", "May I come in?", "შემიძლია შემოვიდე?")
a1("call", "დარეკვა", "ქოლ", "Call me later.", "მოგვიანებით დამირეკე.")
a1("such", "ისეთი", "საჩ", "Such a nice day!", "რა კარგი დღეა!")
a1("between", "შორის", "ბითვინ", "Between you and me.", "ჩვენს შორის.")
a1("need", "საჭიროება", "ნიდ", "I need your help.", "შენი დახმარება მჭირდება.")
a1("become", "გახდომა", "ბიქამ", "She became a teacher.", "მასწავლებელი გახდა.")
a1("head", "თავი", "ჰედ", "My head hurts.", "თავი მტკივა.")
a1("through", "გავლით", "სრუ", "Walk through the door.", "კარში გაიარე.")
a1("put", "დადება", "ფუთ", "Put it on the table.", "მაგიდაზე დადე.")
a1("start", "დაწყება", "სთართ", "Let's start!", "დავიწყოთ!")
a1("might", "შეიძლება", "მაით", "It might rain.", "შეიძლება იწვიმოს.")
a1("show", "ჩვენება", "შოუ", "Show me the way.", "გზა მაჩვენე.")
a1("try", "ცდა", "თრაი", "Try again!", "კიდევ სცადე!")
a1("too", "ძალიან/ასევე", "თუ", "Me too.", "მეც.")
a1("must", "უნდა", "მასთ", "You must study.", "უნდა ისწავლო.")
a1("each", "თითოეული", "იჩ", "Each student passed.", "თითოეულმა ჩააბარა.")
a1("every", "ყოველი", "ევრი", "Every day is a gift.", "ყოველი დღე საჩუქარია.")
a1("us", "ჩვენ (ობიექტ.)", "ას", "Join us!", "შემოგვიერთდი!")
a1("both", "ორივე", "ბოზ", "Both are good.", "ორივე კარგია.")
a1("part", "ნაწილი", "ფართ", "Part of the plan.", "გეგმის ნაწილი.")
a1("end", "დასასრული", "ენდ", "The end.", "დასასრული.")
a1("house", "სახლი", "ჰაუს", "I bought a house.", "სახლი ვიყიდე.")
a1("same", "იგივე", "სეიმ", "The same idea.", "იგივე იდეა.")
# 151-250
a1("another", "სხვა/კიდევ ერთი", "ენაზერ", "Another chance.", "კიდევ ერთი შანსი.")
a1("while", "სანამ", "ვაილ", "Wait while I come.", "დამელოდე.")
a1("learn", "სწავლა", "ლერნ", "I want to learn English.", "ინგლისურის სწავლა მინდა.")
a1("ask", "კითხვა/თხოვნა", "ასქ", "Ask me anything.", "რაც გინდა მკითხე.")
a1("feel", "გრძნობა", "ფილ", "I feel happy.", "ბედნიერად ვგრძნობ თავს.")
a1("leave", "დატოვება/წასვლა", "ლივ", "I have to leave.", "უნდა წავიდე.")
a1("turn", "მოხვევა/ჯერი", "თერნ", "Turn left.", "მარცხნივ მოუხვიე.")
a1("play", "თამაში", "ფლეი", "Let's play!", "ვითამაშოთ!")
a1("move", "გადაადგილება", "მუვ", "Don't move!", "არ გაინძრე!")
a1("small", "პატარა", "სმოლ", "A small dog.", "პატარა ძაღლი.")
a1("number", "რიცხვი/ნომერი", "ნამბერ", "What is your number?", "რა ნომერი გაქვს?")
a1("off", "გამორთული", "ოფ", "Turn off the light.", "შუქი გამორთე.")
a1("always", "ყოველთვის", "ოლვეიზ", "I always wake up early.", "ყოველთვის ადრე ვდგები.")
a1("something", "რაღაც", "სამსინგ", "I need something.", "რაღაც მჭირდება.")
a1("change", "ცვლილება", "ჩეინჯ", "Change is good.", "ცვლილება კარგია.")
a1("point", "წერტილი/აზრი", "ფოინთ", "I see your point.", "აზრს ვხედავ.")
a1("help", "დახმარება", "ჰელფ", "Can you help me?", "დამეხმარები?")
a1("different", "განსხვავებული", "დიფერენთ", "We are all different.", "ყველა განსხვავებულია.")
a1("home", "სახლი", "ჰოუმ", "I am going home.", "სახლში მივდივარ.")
a1("away", "შორს", "ევეი", "Go away!", "წადი!")
a1("run", "სირბილი", "რან", "I run every morning.", "ყოველ დილით ვირბენ.")
a1("place", "ადგილი", "ფლეის", "A nice place.", "კარგი ადგილი.")
a1("school", "სკოლა", "სქულ", "I go to school.", "სკოლაში მივდივარ.")
a1("country", "ქვეყანა", "ქანთრი", "My country is beautiful.", "ჩემი ქვეყანა ლამაზია.")
a1("name", "სახელი", "ნეიმ", "What is your name?", "რა გქვია?")
a1("three", "სამი", "სრი", "I have three sisters.", "სამი და მყავს.")
a1("read", "კითხვა", "რიდ", "I love to read.", "კითხვა მიყვარს.")
a1("write", "წერა", "რაით", "I write every day.", "ყოველდღე ვწერ.")
a1("little", "პატარა/ცოტა", "ლითლ", "A little bit more.", "კიდევ ცოტა.")
a1("together", "ერთად", "თუგეზერ", "We work together.", "ერთად ვმუშაობთ.")
a1("open", "გახსნა/ღია", "ოფენ", "Open the door.", "კარი გააღე.")
a1("close", "დახურვა/ახლოს", "ქლოუზ", "Close the window.", "ფანჯარა დახურე.")
a1("water", "წყალი", "ვოთერ", "Drink some water.", "წყალი დალიე.")
a1("food", "საკვები", "ფუდ", "The food is delicious.", "საკვები გემრიელია.")
a1("money", "ფული", "მანი", "I need money.", "ფული მჭირდება.")
a1("friend", "მეგობარი", "ფრენდ", "He is my best friend.", "ის საუკეთესო მეგობარია.")
a1("mother", "დედა", "მაზერ", "My mother is kind.", "ჩემი დედა კეთილია.")
a1("father", "მამა", "ფაზერ", "My father works hard.", "ჩემი მამა ბევრს მუშაობს.")
a1("love", "სიყვარული", "ლავ", "I love you.", "მიყვარხარ.")
a1("city", "ქალაქი", "სითი", "Tbilisi is a big city.", "თბილისი დიდი ქალაქია.")
a1("door", "კარი", "დორ", "Open the door.", "კარი გააღე.")
a1("car", "მანქანა", "ქარ", "I drive a car.", "მანქანას ვმართავ.")
a1("book", "წიგნი", "ბუქ", "I read a book.", "წიგნი წავიკითხე.")
a1("family", "ოჯახი", "ფემილი", "Family is important.", "ოჯახი მნიშვნელოვანია.")
a1("child", "ბავშვი", "ჩაილდ", "The child is sleeping.", "ბავშვი სძინავს.")
a1("man", "კაცი", "მენ", "The man is tall.", "კაცი მაღალია.")
a1("woman", "ქალი", "ვუმენ", "The woman is strong.", "ქალი ძლიერია.")
a1("girl", "გოგონა", "გერლ", "The girl is happy.", "გოგონა ბედნიერია.")
a1("boy", "ბიჭი", "ბოი", "The boy plays football.", "ბიჭი ფეხბურთს თამაშობს.")
a1("night", "ღამე", "ნაით", "Good night!", "ძილი ნებისა!")
# 201-300
a1("morning", "დილა", "მორნინგ", "Good morning!", "დილა მშვიდობისა!")
a1("today", "დღეს", "თუდეი", "Today is Monday.", "დღეს ორშაბათია.")
a1("young", "ახალგაზრდა", "იანგ", "She is young.", "ის ახალგაზრდაა.")
a1("room", "ოთახი", "რუმ", "The room is clean.", "ოთახი სუფთაა.")
a1("question", "კითხვა", "ქვესჩენ", "I have a question.", "კითხვა მაქვს.")
a1("answer", "პასუხი", "ენსერ", "I know the answer.", "პასუხი ვიცი.")
a1("problem", "პრობლემა", "ფრობლემ", "No problem!", "პრობლემა არაა!")
a1("idea", "იდეა", "აიდია", "Good idea.", "კარგი იდეა.")
a1("word", "სიტყვა", "ვორდ", "What does this word mean?", "ეს სიტყვა რას ნიშნავს?")
a1("understand", "გაგება", "ანდერსთენდ", "I understand.", "მესმის.")
a1("walk", "სიარული", "ვოქ", "Let's walk.", "გავიაროთ.")
a1("sit", "ჯდომა", "სით", "Please sit down.", "დაბრძანდით.")
a1("eat", "ჭამა", "იტ", "I eat breakfast.", "საუზმეს ვჭამ.")
a1("sleep", "ძილი", "სლიფ", "I need to sleep.", "ძილი მჭირდება.")
a1("drink", "სმა", "დრინქ", "I drink coffee.", "ყავას ვსვამ.")
a1("speak", "საუბარი", "სფიქ", "Do you speak English?", "ინგლისურად ლაპარაკობ?")
a1("hear", "მოსმენა", "ჰიარ", "I can hear you.", "გისმენ.")
a1("stop", "გაჩერება", "სთოფ", "Stop the car!", "მანქანა გააჩერე!")
a1("wait", "ლოდინი", "ვეიტ", "Wait for me!", "დამელოდე!")
a1("bring", "მოტანა", "ბრინგ", "Bring me water.", "წყალი მომიტანე.")
a1("watch", "ყურება/საათი", "ვოჩ", "Watch this video.", "ეს ვიდეო ნახე.")
a1("begin", "დაწყება", "ბიგინ", "Let's begin.", "დავიწყოთ.")
a1("buy", "ყიდვა", "ბაი", "I want to buy it.", "ყიდვა მინდა.")
a1("sell", "გაყიდვა", "სელ", "I want to sell.", "გაყიდვა მინდა.")
a1("pay", "გადახდა", "ფეი", "I will pay.", "გადავიხდი.")
a1("send", "გაგზავნა", "სენდ", "Send me a message.", "მომწერე.")
a1("meet", "შეხვედრა", "მიტ", "Nice to meet you!", "სასიამოვნოა!")
a1("talk", "საუბარი", "თოქ", "We need to talk.", "საუბარი გვჭირდება.")
a1("stand", "დგომა", "სთენდ", "Stand up please.", "ადექი, გთხოვთ.")
a1("die", "სიკვდილი", "დაი", "Flowers die in winter.", "ზამთარში ყვავილები ხმება.")
a1("land", "მიწა/ქვეყანა", "ლენდ", "The land is green.", "მიწა მწვანეა.")
a1("build", "აშენება", "ბილდ", "Build a house.", "სახლი ააშენე.")
a1("light", "სინათლე/მსუბუქი", "ლაით", "Turn on the light.", "შუქი აანთე.")
a1("face", "სახე", "ფეის", "Your face is familiar.", "სახეს გიცნობ.")
a1("white", "თეთრი", "ვაიტ", "The snow is white.", "თოვლი თეთრია.")
a1("black", "შავი", "ბლექ", "Black coffee.", "შავი ყავა.")
a1("red", "წითელი", "რედ", "The apple is red.", "ვაშლი წითელია.")
a1("blue", "ლურჯი", "ბლუ", "The sky is blue.", "ცა ლურჯია.")
a1("green", "მწვანე", "გრინ", "The grass is green.", "ბალახი მწვანეა.")
a1("dog", "ძაღლი", "დოგ", "I have a dog.", "ძაღლი მყავს.")
a1("cat", "კატა", "ქეთ", "The cat is sleeping.", "კატა სძინავს.")
a1("table", "მაგიდა", "თეიბლ", "Put it on the table.", "მაგიდაზე დადე.")
a1("bed", "საწოლი", "ბედ", "I need a new bed.", "ახალი საწოლი მჭირდება.")
a1("window", "ფანჯარა", "ვინდოუ", "Open the window.", "ფანჯარა გააღე.")
a1("chair", "სკამი", "ჩეარ", "Sit on the chair.", "სკამზე დაჯექი.")
a1("eye", "თვალი", "აი", "She has blue eyes.", "ლურჯი თვალები აქვს.")
a1("heart", "გული", "ჰართ", "My heart is full.", "გულით სავსე ვარ.")
a1("sun", "მზე", "სან", "The sun is shining.", "მზე ანათებს.")
a1("rain", "წვიმა", "რეინ", "It is raining.", "წვიმს.")
a1("tree", "ხე", "თრი", "The tree is tall.", "ხე მაღალია.")
# 251-350
a1("street", "ქუჩა", "სთრიტ", "The street is busy.", "ქუჩა ხალხმრავალია.")
a1("picture", "სურათი", "ფიქჩერ", "Take a picture.", "სურათი გადაიღე.")
a1("brother", "ძმა", "ბრაზერ", "He is my brother.", "ის ჩემი ძმაა.")
a1("sister", "და", "სისთერ", "She is my sister.", "ის ჩემი დაა.")
a1("baby", "ჩვილი/ბავშვი", "ბეიბი", "The baby is cute.", "ბავშვი საყვარელია.")
a1("husband", "ქმარი", "ჰაზბენდ", "Her husband is kind.", "მისი ქმარი კეთილია.")
a1("wife", "ცოლი", "ვაიფ", "My wife cooks well.", "ცოლი კარგად ამზადებს.")
a1("son", "ვაჟი", "სან", "My son is smart.", "ვაჟი ჭკვიანია.")
a1("daughter", "ქალიშვილი", "დოთერ", "My daughter sings.", "ქალიშვილი მღერის.")
a1("teacher", "მასწავლებელი", "თიჩერ", "The teacher is patient.", "მასწავლებელი მოთმინებაა.")
a1("student", "სტუდენტი", "სთუდენთ", "I am a student.", "სტუდენტი ვარ.")
a1("doctor", "ექიმი", "დოქთორ", "I need a doctor.", "ექიმი მჭირდება.")
a1("music", "მუსიკა", "მიუზიქ", "I love music.", "მუსიკა მიყვარს.")
a1("happy", "ბედნიერი", "ჰეფი", "I am happy.", "ბედნიერი ვარ.")
a1("beautiful", "ლამაზი", "ბიუთიფულ", "You are beautiful.", "ლამაზი ხარ.")
a1("strong", "ძლიერი", "სთრონგ", "He is strong.", "ძლიერია.")
a1("important", "მნიშვნელოვანი", "იმფორთენთ", "Education is important.", "განათლება მნიშვნელოვანია.")
a1("ready", "მზად", "რედი", "I am ready.", "მზად ვარ.")
a1("grow", "ზრდა", "გროუ", "Children grow fast.", "ბავშვები სწრაფად იზრდებიან.")
a1("power", "ძალა", "ფაუერ", "Knowledge is power.", "ცოდნა ძალაა.")
a1("side", "მხარე/გვერდი", "საიდ", "This side.", "ეს მხარე.")
a1("state", "მდგომარეობა/სახელმწიფო", "სთეიტ", "What state?", "რა მდგომარეობა?")
a1("set", "დაყენება/ნაკრები", "სეთ", "Set the alarm.", "მაღვიძარა დააყენე.")
a1("line", "ხაზი/რიგი", "ლაინ", "Wait in line.", "რიგში დადექი.")
a1("story", "ამბავი", "სთორი", "Tell me a story.", "ამბავი მომიყევი.")
a1("mean", "ნიშნავს", "მინ", "What does it mean?", "რას ნიშნავს?")
a1("kind", "კეთილი/სახეობა", "ქაინდ", "She is kind.", "ის კეთილია.")
a1("often", "ხშირად", "ოფენ", "I often walk.", "ხშირად ვსეირნობ.")
a1("sure", "დარწმუნებული", "შუარ", "Are you sure?", "დარწმუნებული ხარ?")
a1("hard", "რთული/მაგარი", "ჰარდ", "The exam was hard.", "გამოცდა რთული იყო.")
a1("real", "ნამდვილი", "რიალ", "Is this real?", "ეს ნამდვილია?")
a1("hold", "დაჭერა", "ჰოლდ", "Hold my hand.", "ხელი დამიჭირე.")
a1("early", "ადრე", "ერლი", "I wake up early.", "ადრე ვდგები.")
a1("lose", "დაკარგვა", "ლუზ", "Don't lose hope.", "იმედი ნუ დაკარგავ.")
a1("mind", "გონება/აზრი", "მაინდ", "I changed my mind.", "აზრი შევიცვალე.")
a1("body", "სხეული", "ბოდი", "The human body.", "ადამიანის სხეული.")
a1("lead", "ხელმძღვანელობა", "ლიდ", "She leads the team.", "გუნდს ხელმძღვანელობს.")
a1("fact", "ფაქტი", "ფექთ", "That is a fact.", "ეს ფაქტია.")
a1("group", "ჯგუფი", "გრუფ", "A group of friends.", "მეგობრების ჯგუფი.")
a1("enough", "საკმარისი", "ინაფ", "I have enough.", "საკმარისი მაქვს.")
a1("case", "შემთხვევა", "ქეის", "In that case.", "ამ შემთხვევაში.")
a1("game", "თამაში", "გეიმ", "Let's play a game.", "ვითამაშოთ.")
a1("system", "სისტემა", "სისთემ", "The system works.", "სისტემა მუშაობს.")
a1("best", "საუკეთესო", "ბესთ", "You are the best!", "შენ საუკეთესო ხარ!")
a1("later", "მოგვიანებით", "ლეითერ", "See you later.", "მოგვიანებით.")
a1("true", "სწორი/ჭეშმარიტი", "თრუ", "That is true.", "ეს სიმართლეა.")
a1("since", "მას შემდეგ", "სინს", "Since morning.", "დილიდან.")
a1("during", "განმავლობაში", "დიურინგ", "During summer.", "ზაფხულში.")
a1("along", "გასწვრივ", "ელონგ", "Walk along the river.", "მდინარის გასწვრივ.")
a1("class", "კლასი", "ქლას", "Class starts at 9.", "გაკვეთილი 9-ზე.")
# 351-500
a1("half", "ნახევარი", "ჰაფ", "Half of the cake.", "ნამცხვრის ნახევარი.")
a1("age", "ასაკი", "ეიჯ", "What is your age?", "რამდენი წლის ხარ?")
a1("air", "ჰაერი", "ეარ", "Fresh air.", "სუფთა ჰაერი.")
a1("language", "ენა", "ლენგვიჯ", "I speak three languages.", "სამ ენაზე ვლაპარაკობ.")
a1("person", "ადამიანი", "ფერსონ", "A good person.", "კარგი ადამიანი.")
a1("reason", "მიზეზი", "რიზონ", "The reason is clear.", "მიზეზი ნათელია.")
a1("road", "გზა", "როუდ", "The road is long.", "გზა გრძელია.")
a1("sea", "ზღვა", "სი", "The sea is calm.", "ზღვა მშვიდია.")
a1("fire", "ცეცხლი", "ფაიარ", "The fire is hot.", "ცეცხლი ცხელია.")
a1("five", "ხუთი", "ფაივ", "I have five fingers.", "ხუთი თითი მაქვს.")
a1("four", "ოთხი", "ფორ", "Four books.", "ოთხი წიგნი.")
a1("six", "ექვსი", "სიქს", "Six chairs.", "ექვსი სკამი.")
a1("seven", "შვიდი", "სევენ", "Seven days.", "შვიდი დღე.")
a1("eight", "რვა", "ეიტ", "Eight o'clock.", "რვა საათი.")
a1("nine", "ცხრა", "ნაინ", "Nine hours.", "ცხრა საათი.")
a1("ten", "ათი", "თენ", "Ten fingers.", "ათი თითი.")
a1("hundred", "ასი", "ჰანდრედ", "A hundred people.", "ასი ადამიანი.")
a1("thousand", "ათასი", "საუზენდ", "A thousand stars.", "ათასი ვარსკვლავი.")
a1("foot", "ფეხი/ტერფი", "ფუთ", "My foot hurts.", "ფეხი მტკივა.")
a1("ear", "ყური", "იარ", "I have two ears.", "ორი ყური მაქვს.")
a1("mouth", "პირი", "მაუს", "Open your mouth.", "პირი გააღე.")
a1("nose", "ცხვირი", "ნოუზ", "My nose is cold.", "ცხვირი მეყინება.")
a1("hair", "თმა", "ჰეარ", "Long hair.", "გრძელი თმა.")
a1("arm", "მკლავი", "არმ", "My arm hurts.", "მკლავი მტკივა.")
a1("leg", "ფეხი", "ლეგ", "My leg hurts.", "ფეხი მტკივა.")
a1("finger", "თითი", "ფინგერ", "I cut my finger.", "თითი გავიჭერი.")
a1("hot", "ცხელი", "ჰოთ", "The weather is hot.", "ამინდი ცხელია.")
a1("cold", "ცივი", "ქოლდ", "The water is cold.", "წყალი ცივია.")
a1("clean", "სუფთა", "ქლინ", "The room is clean.", "ოთახი სუფთაა.")
a1("fast", "სწრაფი", "ფასთ", "The car is fast.", "მანქანა სწრაფია.")
a1("slow", "ნელი", "სლო", "Walk slow.", "ნელა იარე.")
a1("easy", "ადვილი", "იზი", "The test was easy.", "ტესტი ადვილი იყო.")
a1("poor", "ღარიბი", "ფუარ", "The poor man.", "ღარიბი კაცი.")
a1("rich", "მდიდარი", "რიჩ", "He is rich.", "ის მდიდარია.")
a1("sick", "ავადმყოფი", "სიქ", "I am sick.", "ავად ვარ.")
a1("safe", "უსაფრთხო", "სეიფ", "You are safe.", "უსაფრთხოდ ხარ.")
a1("free", "თავისუფალი/უფასო", "ფრი", "The bird is free.", "ფრინველი თავისუფალია.")
a1("dark", "ბნელი", "დარქ", "It is dark.", "ბნელაა.")
a1("quiet", "წყნარი", "ქვაიეთ", "Be quiet.", "წყნარად იყავი.")
a1("full", "სავსე", "ფულ", "The glass is full.", "ჭიქა სავსეა.")
a1("empty", "ცარიელი", "ემფთი", "The room is empty.", "ოთახი ცარიელია.")
a1("near", "ახლოს", "ნიარ", "The school is near.", "სკოლა ახლოსაა.")
a1("far", "შორს", "ფარ", "The city is far.", "ქალაქი შორსაა.")
a1("short", "მოკლე/დაბალი", "შორთ", "A short story.", "მოკლე ამბავი.")
a1("tall", "მაღალი", "თოლ", "He is tall.", "ის მაღალია.")
a1("dry", "მშრალი", "დრაი", "Dry weather.", "მშრალი ამინდი.")
a1("wet", "სველი", "ვეთ", "The ground is wet.", "მიწა სველია.")
a1("soft", "რბილი", "სოფთ", "Soft pillow.", "რბილი ბალიში.")
a1("wrong", "არასწორი", "რონგ", "You are wrong.", "შეცდომა გაქვს.")
a1("example", "მაგალითი", "იგზემფლ", "For example.", "მაგალითად.")
# 401-500
a1("able", "შეუძლია", "ეიბლ", "I am able to do it.", "შემიძლია.")
a1("hour", "საათი", "აუარ", "One hour.", "ერთი საათი.")
a1("minute", "წუთი", "მინიტ", "Wait a minute.", "ერთი წუთი.")
a1("second", "წამი/მეორე", "სექონდ", "Just a second.", "ერთი წამით.")
a1("week", "კვირა", "ვიქ", "This week.", "ამ კვირას.")
a1("month", "თვე", "მანს", "This month.", "ამ თვეში.")
a1("winter", "ზამთარი", "ვინთერ", "Winter is cold.", "ზამთარი ცივია.")
a1("spring", "გაზაფხული", "სფრინგ", "Spring is beautiful.", "გაზაფხული ლამაზია.")
a1("summer", "ზაფხული", "სამერ", "Summer is hot.", "ზაფხული ცხელია.")
a1("autumn", "შემოდგომა", "ოთემ", "Autumn leaves.", "შემოდგომის ფოთლები.")
a1("weather", "ამინდი", "ვეზერ", "How is the weather?", "როგორი ამინდია?")
a1("snow", "თოვლი", "სნოუ", "Snow is falling.", "თოვლი მოდის.")
a1("wind", "ქარი", "ვინდ", "The wind is strong.", "ქარი ძლიერია.")
a1("cloud", "ღრუბელი", "ქლაუდ", "White clouds.", "თეთრი ღრუბლები.")
a1("star", "ვარსკვლავი", "სთარ", "The stars shine.", "ვარსკვლავები ანათებენ.")
a1("moon", "მთვარე", "მუნ", "The moon is bright.", "მთვარე კაშკაშაა.")
a1("flower", "ყვავილი", "ფლაუერ", "A red flower.", "წითელი ყვავილი.")
a1("bird", "ფრინველი", "ბერდ", "The bird sings.", "ფრინველი მღერის.")
a1("fish", "თევზი", "ფიშ", "I like fish.", "თევზი მომწონს.")
a1("bread", "პური", "ბრედ", "Fresh bread.", "ახალი პური.")
a1("milk", "რძე", "მილქ", "I drink milk.", "რძეს ვსვამ.")
a1("meat", "ხორცი", "მიტ", "I eat meat.", "ხორცს ვჭამ.")
a1("sugar", "შაქარი", "შუგარ", "No sugar please.", "შაქრის გარეშე.")
a1("salt", "მარილი", "სოლთ", "Pass the salt.", "მარილი გადამომეცი.")
a1("cheese", "ყველი", "ჩიზ", "Georgian cheese.", "ქართული ყველი.")
a1("egg", "კვერცხი", "ეგ", "Fried egg.", "შემწვარი კვერცხი.")
a1("chicken", "ქათამი", "ჩიქენ", "Chicken soup.", "ქათმის წვნიანი.")
a1("fruit", "ხილი", "ფრუთ", "Fresh fruit.", "ახალი ხილი.")
a1("apple", "ვაშლი", "ეფლ", "A red apple.", "წითელი ვაშლი.")
a1("coffee", "ყავა", "ქოფი", "Morning coffee.", "დილის ყავა.")
a1("tea", "ჩაი", "თი", "Green tea.", "მწვანე ჩაი.")
a1("glass", "ჭიქა/მინა", "გლას", "A glass of water.", "ჭიქა წყალი.")
a1("cup", "ფინჯანი", "ქაფ", "A cup of tea.", "ფინჯანი ჩაი.")
a1("knife", "დანა", "ნაიფ", "A sharp knife.", "ბასრი დანა.")
a1("spoon", "კოვზი", "სფუნ", "I need a spoon.", "კოვზი მჭირდება.")
a1("kitchen", "სამზარეულო", "ქიჩენ", "She is in the kitchen.", "სამზარეულოშია.")
a1("garden", "ბაღი", "გარდენ", "A beautiful garden.", "ლამაზი ბაღი.")
a1("key", "გასაღები", "ქი", "I lost my key.", "გასაღები დავკარგე.")
a1("phone", "ტელეფონი", "ფოუნ", "My phone rings.", "ტელეფონი მირეკავს.")
a1("computer", "კომპიუტერი", "ქომფიუთერ", "I use a computer.", "კომპიუტერს ვიყენებ.")
a1("shirt", "პერანგი", "შერთ", "A new shirt.", "ახალი პერანგი.")
a1("shoe", "ფეხსაცმელი", "შუ", "New shoes.", "ახალი ფეხსაცმელი.")
a1("bag", "ჩანთა", "ბეგ", "My bag is heavy.", "ჩანთა მძიმეა.")
a1("paper", "ქაღალდი", "ფეიფერ", "A piece of paper.", "ქაღალდის ნაჭერი.")
a1("pen", "კალამი", "ფენ", "Give me a pen.", "კალამი მომეცი.")
a1("cook", "მზარეული/მომზადება", "ქუქ", "I love to cook.", "საჭმლის კეთება მიყვარს.")
a1("drive", "მართვა", "დრაივ", "I drive to work.", "მანქანით მივდივარ.")
a1("fly", "ფრენა", "ფლაი", "Birds fly.", "ფრინველები დაფრინავენ.")
a1("swim", "ცურვა", "სვიმ", "I like to swim.", "ცურვა მომწონს.")
a1("dance", "ცეკვა", "დენს", "Let's dance!", "ვიცეკვოთ!")
# 501-600
a1("sing", "სიმღერა", "სინგ", "She sings well.", "კარგად მღერის.")
a1("cut", "ჭრა", "ქათ", "Cut the paper.", "ქაღალდი გაჭერი.")
a1("break", "გატეხვა/შესვენება", "ბრეიქ", "Don't break it.", "არ გატეხო.")
a1("save", "შენახვა/გადარჩენა", "სეივ", "Save money.", "ფული დაზოგე.")
a1("spend", "ხარჯვა", "სფენდ", "Don't spend too much.", "ბევრს ნუ ხარჯავ.")
a1("choose", "არჩევა", "ჩუზ", "Choose one.", "ერთი აირჩიე.")
a1("agree", "თანხმობა", "ეგრი", "I agree.", "ვეთანხმები.")
a1("believe", "რწმენა", "ბილივ", "I believe you.", "გჯერა.")
a1("remember", "დამახსოვრება", "რიმემბერ", "I remember.", "მახსოვს.")
a1("forget", "დავიწყება", "ფორგეთ", "Don't forget.", "არ დაივიწყო.")
a1("hope", "იმედი", "ჰოუფ", "I hope so.", "იმედი მაქვს.")
a1("wish", "სურვილი", "ვიშ", "I wish you luck.", "წარმატებას გისურვებ.")
a1("dream", "ოცნება/სიზმარი", "დრიმ", "I have a dream.", "ოცნება მაქვს.")
a1("worry", "წუხილი", "ვორი", "Don't worry.", "ნუ ფიქრობ.")
a1("cry", "ტირილი", "ქრაი", "Don't cry.", "ნუ ტირი.")
a1("laugh", "სიცილი", "ლაფ", "She laughs a lot.", "ბევრს იცინის.")
a1("smile", "ღიმილი", "სმაილ", "Smile!", "გაიღიმე!")
a1("fight", "ბრძოლა", "ფაიტ", "Don't fight.", "ნუ ჩხუბობთ.")
a1("win", "მოგება", "ვინ", "I want to win.", "მოგება მინდა.")
a1("thank", "მადლობა", "სენქ", "Thank you!", "გმადლობთ!")
a1("sorry", "ბოდიში", "სორი", "I am sorry.", "ბოდიში.")
a1("please", "გთხოვთ", "ფლიზ", "Please help.", "გთხოვთ დამეხმარეთ.")
a1("hello", "გამარჯობა", "ჰელოუ", "Hello!", "გამარჯობა!")
a1("goodbye", "ნახვამდის", "გუდბაი", "Goodbye!", "ნახვამდის!")
a1("yes", "დიახ", "იეს", "Yes, I agree.", "დიახ, ვეთანხმები.")
a1("maybe", "იქნებ", "მეიბი", "Maybe tomorrow.", "იქნებ ხვალ.")
a1("earth", "დედამიწა", "ერს", "Earth is round.", "დედამიწა მრგვალია.")
a1("sky", "ცა", "სქაი", "The sky is clear.", "ცა ნათელია.")
a1("stone", "ქვა", "სთოუნ", "A heavy stone.", "მძიმე ქვა.")
a1("wall", "კედელი", "ვოლ", "The wall is high.", "კედელი მაღალია.")
a1("floor", "იატაკი", "ფლორ", "Clean floor.", "სუფთა იატაკი.")
a1("bridge", "ხიდი", "ბრიჯ", "Cross the bridge.", "ხიდი გადალახე.")
a1("lake", "ტბა", "ლეიქ", "The lake is calm.", "ტბა მშვიდია.")
a1("forest", "ტყე", "ფორესთ", "Dark forest.", "ბნელი ტყე.")
a1("field", "მინდორი/სფერო", "ფილდ", "Green field.", "მწვანე მინდორი.")
a1("village", "სოფელი", "ვილიჯ", "A small village.", "პატარა სოფელი.")
a1("gold", "ოქრო", "გოლდ", "Gold is valuable.", "ოქრო ძვირფასია.")
a1("wood", "ხე/მერქანი", "ვუდ", "Made of wood.", "ხისგან გაკეთებული.")
a1("oil", "ზეთი/ნავთობი", "ოილ", "Olive oil.", "ზეითუნის ზეთი.")
a1("farm", "ფერმა", "ფარმ", "A big farm.", "დიდი ფერმა.")
a1("animal", "ცხოველი", "ენიმალ", "I love animals.", "ცხოველები მიყვარს.")
a1("horse", "ცხენი", "ჰორს", "A fast horse.", "სწრაფი ცხენი.")
a1("cow", "ძროხა", "ქაუ", "The cow gives milk.", "ძროხა რძეს იძლევა.")
a1("lion", "ლომი", "ლაიონ", "The lion roars.", "ლომი ღრიალებს.")
a1("king", "მეფე", "ქინგ", "The king rules.", "მეფე მართავს.")
a1("peace", "მშვიდობა", "ფის", "We want peace.", "მშვიდობა გვინდა.")
a1("war", "ომი", "ვორ", "War is terrible.", "ომი საშინელებაა.")
a1("color", "ფერი", "ქალარ", "What color?", "რა ფერი?")
a1("shape", "ფორმა", "შეიფ", "A round shape.", "მრგვალი ფორმა.")
a1("size", "ზომა", "საიზ", "What size?", "რა ზომა?")
# 551-700
a1("taste", "გემო", "თეისთ", "Good taste.", "კარგი გემო.")
a1("smell", "სუნი", "სმელ", "A good smell.", "კარგი სუნი.")
a1("touch", "შეხება", "თაჩ", "Don't touch.", "არ შეეხო.")
a1("sound", "ხმა", "საუნდ", "What is that sound?", "რა ხმაა?")
a1("voice", "ხმა (ადამიანის)", "ვოის", "A beautiful voice.", "ლამაზი ხმა.")
a1("pain", "ტკივილი", "ფეინ", "I feel pain.", "ტკივილი მაქვს.")
a1("sick", "ავადმყოფი", "სიქ", "I feel sick.", "ცუდად ვარ.")
a1("health", "ჯანმრთელობა", "ჰელს", "Health is important.", "ჯანმრთელობა მნიშვნელოვანია.")
a1("hospital", "საავადმყოფო", "ჰოსფითალ", "Go to the hospital.", "საავადმყოფოში წადი.")
a1("medicine", "წამალი", "მედისინ", "Take medicine.", "წამალი მიიღე.")
a1("news", "ახალი ამბები", "ნიუზ", "I watch the news.", "ამბებს ვუყურებ.")
a1("song", "სიმღერა", "სონგ", "My favorite song.", "საყვარელი სიმღერა.")
a1("movie", "ფილმი", "მუვი", "A good movie.", "კარგი ფილმი.")
a1("sport", "სპორტი", "სფორთ", "I love sports.", "სპორტი მიყვარს.")
a1("team", "გუნდი", "თიმ", "Our team won.", "ჩვენი გუნდი მოიგო.")
a1("ball", "ბურთი", "ბოლ", "Kick the ball.", "ბურთი წაარტყი.")
a1("player", "მოთამაშე", "ფლეიერ", "A good player.", "კარგი მოთამაშე.")
a1("art", "ხელოვნება", "ართ", "Art is beautiful.", "ხელოვნება ლამაზია.")
a1("technology", "ტექნოლოგია", "თექნოლოჯი", "Modern technology.", "თანამედროვე ტექნოლოგია.")
a1("internet", "ინტერნეტი", "ინთერნეთ", "I use the internet.", "ინტერნეტს ვიყენებ.")
a1("information", "ინფორმაცია", "ინფორმეიშენ", "I need information.", "ინფორმაცია მჭირდება.")
a1("education", "განათლება", "ედიუქეიშენ", "Education matters.", "განათლება მნიშვნელოვანია.")
a1("university", "უნივერსიტეტი", "იუნივერსითი", "I study at university.", "უნივერსიტეტში ვსწავლობ.")
a1("test", "ტესტი", "თესთ", "I passed the test.", "ტესტი ჩავაბარე.")
a1("lesson", "გაკვეთილი", "ლესონ", "A good lesson.", "კარგი გაკვეთილი.")
a1("study", "სწავლა", "სთადი", "I study English.", "ინგლისურს ვსწავლობ.")
a1("restaurant", "რესტორანი", "რესთორონთ", "Let's go to a restaurant.", "რესტორანში წავიდეთ.")
a1("hotel", "სასტუმრო", "ჰოთელ", "A nice hotel.", "კარგი სასტუმრო.")
a1("airport", "აეროპორტი", "ეარფორთ", "The airport is far.", "აეროპორტი შორსაა.")
a1("train", "მატარებელი", "თრეინ", "I take the train.", "მატარებლით მივდივარ.")
a1("bus", "ავტობუსი", "ბას", "The bus is late.", "ავტობუსი აგვიანებს.")
a1("ticket", "ბილეთი", "თიქეთ", "I bought a ticket.", "ბილეთი ვიყიდე.")
a1("travel", "მოგზაურობა", "თრეველ", "I love to travel.", "მოგზაურობა მიყვარს.")
a1("passport", "პასპორტი", "ფასფორთ", "I need my passport.", "პასპორტი მჭირდება.")
a1("sign", "ნიშანი", "საინ", "Follow the sign.", "ნიშანს მიჰყევი.")
a1("enter", "შესვლა", "ენთერ", "Please enter.", "შემობრძანდით.")
a1("return", "დაბრუნება", "რითერნ", "I will return soon.", "მალე დავბრუნდები.")
a1("arrive", "ჩამოსვლა", "ერაივ", "We arrived.", "ჩავედით.")
a1("follow", "მიდევნება", "ფოლოუ", "Follow me.", "გამომყევი.")
a1("share", "გაზიარება", "შეარ", "Share with friends.", "მეგობრებს გაუზიარე.")
a1("accept", "მიღება", "ექსეფთ", "I accept.", "ვიღებ.")
a1("allow", "დაშვება/ნებართვა", "ელაუ", "Allow me.", "ნება მომეცი.")
a1("protect", "დაცვა", "ფროთექთ", "Protect the environment.", "გარემო დაიცავი.")
a1("support", "მხარდაჭერა", "საფორთ", "I support you.", "მხარს გიჭერ.")
a1("create", "შექმნა", "ქრიეიტ", "Create something new.", "ახალი შექმენი.")
a1("continue", "გაგრძელება", "ქონთინიუ", "Please continue.", "გააგრძელე.")
a1("happen", "მოხდა", "ჰეფენ", "What happened?", "რა მოხდა?")
a1("fill", "შევსება", "ფილ", "Fill the glass.", "ჭიქა შეავსე.")
a1("imagine", "წარმოდგენა", "იმეჯინ", "Imagine peace.", "წარმოიდგინე მშვიდობა.")
a1("miss", "ენატრება/გამოტოვება", "მის", "I miss you.", "მენატრები.")
# 651-750
a1("wear", "ტარება (ტანსაცმელი)", "ვეარ", "I wear a hat.", "ქუდს ვიხურავ.")
a1("burn", "წვა", "ბერნ", "Don't burn yourself.", "არ დაიწვა.")
a1("fall", "ვარდნა", "ფოლ", "Don't fall!", "არ დაეცე!")
a1("climb", "ასვლა", "ქლაიმ", "Climb the mountain.", "მთაზე ადი.")
a1("jump", "ხტომა", "ჯამფ", "Jump high!", "მაღლა ახტი!")
a1("push", "მიწოლა", "ფუშ", "Push the door.", "კარი მიაწიე.")
a1("pull", "მოწევა", "ფულ", "Pull the door.", "კარი მოაწიე.")
a1("throw", "სროლა", "სროუ", "Throw the ball.", "ბურთი ისროლე.")
a1("catch", "დაჭერა", "ქეჩ", "Catch the ball.", "ბურთი დაიჭირე.")
a1("fix", "შეკეთება", "ფიქს", "Fix the car.", "მანქანა შეაკეთე.")
a1("decide", "გადაწყვეტა", "დისაიდ", "I decided.", "გადავწყვიტე.")
a1("promise", "დაპირება", "ფრომის", "I promise.", "გპირდები.")
a1("trust", "ნდობა", "თრასთ", "I trust you.", "გენდობი.")
a1("invite", "მოწვევა", "ინვაიტ", "I invite you.", "მიგიწვევ.")
a1("surprise", "სიურპრიზი", "სერფრაიზ", "What a surprise!", "რა სიურპრიზია!")
a1("gift", "საჩუქარი", "გიფთ", "A nice gift.", "კარგი საჩუქარი.")
a1("respect", "პატივისცემა", "რისფექთ", "Show respect.", "პატივი ეცი.")
a1("simple", "მარტივი", "სიმფლ", "Keep it simple.", "მარტივად.")
a1("clear", "ნათელი/სუფთა", "ქლიარ", "Clear sky.", "ნათელი ცა.")
a1("fresh", "ახალი/სუფთა", "ფრეშ", "Fresh air.", "სუფთა ჰაერი.")
a1("enjoy", "ტკბობა", "ენჯოი", "Enjoy your meal!", "გემრიელად მიირთვი!")
a1("plan", "გეგმა", "ფლენ", "What is your plan?", "რა გეგმა გაქვს?")
a1("cost", "ღირებულება", "ქოსთ", "How much does it cost?", "რა ღირს?")
a1("company", "კომპანია", "ქამფანი", "A big company.", "დიდი კომპანია.")
a1("river", "მდინარე", "რივერ", "The river is deep.", "მდინარე ღრმაა.")
a1("mountain", "მთა", "მაუნთინ", "A high mountain.", "მაღალი მთა.")
a1("market", "ბაზარი", "მარქეთ", "I go to the market.", "ბაზარზე მივდივარ.")
a1("price", "ფასი", "ფრაის", "What is the price?", "რა ფასია?")
a1("business", "ბიზნესი", "ბიზნეს", "My own business.", "საკუთარი ბიზნესი.")
a1("job", "სამუშაო", "ჯობ", "A new job.", "ახალი სამუშაო.")
a1("office", "ოფისი", "ოფის", "I work in an office.", "ოფისში ვმუშაობ.")
a1("meeting", "შეხვედრა", "მიტინგ", "A meeting at 3.", "შეხვედრა 3-ზე.")
a1("science", "მეცნიერება", "საიენს", "Science is great.", "მეცნიერება შესანიშნავია.")
a1("history", "ისტორია", "ჰისთორი", "Georgian history.", "ქართული ისტორია.")
a1("culture", "კულტურა", "ქალჩერ", "Rich culture.", "მდიდარი კულტურა.")
a1("government", "მთავრობა", "გავერნმენთ", "The government.", "მთავრობა.")
a1("freedom", "თავისუფლება", "ფრიდომ", "Freedom is precious.", "თავისუფლება ძვირფასია.")
a1("society", "საზოგადოება", "სოსაიეთი", "Modern society.", "თანამედროვე საზოგადოება.")
a1("law", "კანონი", "ლო", "Follow the law.", "კანონი დაიცავი.")
a1("police", "პოლიცია", "ფოლის", "Call the police.", "პოლიციას დაურეკე.")
a1("church", "ეკლესია", "ჩერჩ", "An old church.", "ძველი ეკლესია.")
a1("god", "ღმერთი", "გოდ", "God is great.", "ღმერთი დიდია.")
a1("death", "სიკვდილი", "დეს", "Death is natural.", "სიკვდილი ბუნებრივია.")
a1("born", "დაბადებული", "ბორნ", "I was born here.", "აქ დავიბადე.")
a1("alive", "ცოცხალი", "ელაივ", "Still alive.", "ჯერ ცოცხალია.")
a1("sad", "სევდიანი", "სედ", "I feel sad.", "სევდიანი ვარ.")
a1("angry", "გაბრაზებული", "ენგრი", "He is angry.", "ის გაბრაზებულია.")
a1("afraid", "შეშინებული", "ეფრეიდ", "I am afraid.", "მეშინია.")
a1("tired", "დაღლილი", "თაიარდ", "I am tired.", "დაღლილი ვარ.")
a1("hungry", "მშიერი", "ჰანგრი", "I am hungry.", "მშია.")
# 751-850
a1("thirsty", "მწყურვალი", "სერსთი", "I am thirsty.", "მწყურია.")
a1("proud", "ამაყი", "ფრაუდ", "I am proud of you.", "შენით ვამაყობ.")
a1("alone", "მარტო", "ელოუნ", "I live alone.", "მარტო ვცხოვრობ.")
a1("tomorrow", "ხვალ", "თუმოროუ", "See you tomorrow.", "ხვალ ნახვამდის.")
a1("yesterday", "გუშინ", "იესთერდეი", "I saw him yesterday.", "გუშინ ვნახე.")
a1("sometimes", "ზოგჯერ", "სამთაიმს", "Sometimes I cook.", "ზოგჯერ ვამზადებ.")
a1("usually", "ჩვეულებრივ", "იუჟუალი", "I usually walk.", "ჩვეულებრივ ფეხით მივდივარ.")
a1("almost", "თითქმის", "ოლმოსთ", "Almost there.", "თითქმის მივედი.")
a1("already", "უკვე", "ოლრედი", "I already ate.", "უკვე ვჭამე.")
a1("again", "კიდევ/ისევ", "ეგეინ", "Try again.", "კიდევ სცადე.")
a1("until", "სანამ/-მდე", "ანთილ", "Wait until tomorrow.", "ხვალამდე.")
a1("behind", "უკან", "ბიჰაინდ", "Behind the house.", "სახლის უკან.")
a1("above", "ზემოთ", "ებავ", "Above the clouds.", "ღრუბლების ზემოთ.")
a1("below", "ქვემოთ", "ბილოუ", "Below the surface.", "ზედაპირის ქვემოთ.")
a1("inside", "შიგნით", "ინსაიდ", "Come inside.", "შიგნით შემოდი.")
a1("outside", "გარეთ", "აუთსაიდ", "Go outside.", "გარეთ გადი.")
a1("against", "წინააღმდეგ", "ეგეინსთ", "Against war.", "ომის წინააღმდეგ.")
a1("without", "გარეშე", "ვიზაუთ", "Without you.", "შენ გარეშე.")
a1("probably", "ალბათ", "ფრობაბლი", "Probably yes.", "ალბათ კი.")
a1("possible", "შესაძლებელი", "ფოსიბლ", "Anything is possible.", "ყველაფერი შესაძლებელია.")
a1("success", "წარმატება", "საქსეს", "I wish you success.", "წარმატებას გისურვებ.")
a1("future", "მომავალი", "ფიუჩერ", "The future is bright.", "მომავალი ნათელია.")
a1("past", "წარსული", "ფასთ", "In the past.", "წარსულში.")
a1("present", "აწმყო/საჩუქარი", "ფრეზენთ", "A present for you.", "საჩუქარი შენთვის.")
a1("attention", "ყურადღება", "ეთენშენ", "Pay attention.", "ყურადღება მიაქციე.")
a1("special", "განსაკუთრებული", "სფეშალ", "You are special.", "განსაკუთრებული ხარ.")
a1("modern", "თანამედროვე", "მოდერნ", "Modern life.", "თანამედროვე ცხოვრება.")
a1("public", "საჯარო", "ფაბლიქ", "Public transport.", "საზოგადოებრივი ტრანსპორტი.")
a1("situation", "სიტუაცია", "სიჩუეიშენ", "The situation is good.", "სიტუაცია კარგია.")
a1("experience", "გამოცდილება", "იქსფირიენს", "Good experience.", "კარგი გამოცდილება.")
a1("practice", "პრაქტიკა", "ფრექთის", "Practice makes perfect.", "ვარჯიშით ყველაფერი მიიღწევა.")
a1("material", "მასალა", "მეთირიალ", "Good material.", "კარგი მასალა.")
a1("purpose", "მიზანი", "ფერფოს", "What is the purpose?", "რა მიზანი აქვს?")
a1("opportunity", "შესაძლებლობა", "ოფორთიუნითი", "A great opportunity.", "კარგი შესაძლებლობა.")
a1("design", "დიზაინი", "დიზაინ", "Good design.", "კარგი დიზაინი.")
a1("include", "მოიცავს", "ინქლუდ", "Price includes tax.", "ფასი გადასახადს მოიცავს.")
a1("provide", "უზრუნველყოფა", "ფროვაიდ", "I provide help.", "დახმარებას ვთავაზობ.")
a1("consider", "განხილვა", "ქონსიდერ", "Consider this.", "ეს განიხილე.")
a1("expect", "მოლოდინი", "იქსფექთ", "I expect results.", "შედეგებს ველოდები.")
a1("increase", "ზრდა", "ინქრის", "Prices increase.", "ფასები იზრდება.")
a1("require", "მოთხოვნა", "რიქვაიარ", "This requires work.", "ეს სამუშაოს მოითხოვს.")
a1("report", "მოხსენება/ანგარიში", "რიფორთ", "Write a report.", "ანგარიში დაწერე.")
a1("produce", "წარმოება", "ფროდიუს", "We produce wine.", "ღვინოს ვაწარმოებთ.")
a1("describe", "აღწერა", "დისქრაიბ", "Describe it.", "აღწერე.")
a1("explain", "ახსნა", "იქსფლეინ", "Please explain.", "ახსენი.")
a1("result", "შედეგი", "რიზალთ", "Good result.", "კარგი შედეგი.")
a1("suggest", "შეთავაზება", "საჯესთ", "I suggest this.", "ამას ვთავაზობ.")
a1("prepare", "მომზადება", "ფრიფეარ", "Prepare for the exam.", "გამოცდისთვის მოემზადე.")
a1("receive", "მიღება", "რისივ", "I received it.", "მივიღე.")
a1("improve", "გაუმჯობესება", "იმფრუვ", "I want to improve.", "გაუმჯობესება მინდა.")
# 851-1000
a1("avoid", "თავის არიდება", "ევოიდ", "Avoid mistakes.", "შეცდომებს მოერიდე.")
a1("notice", "შენიშვნა", "ნოთის", "I noticed it.", "შევამჩნიე.")
a1("exist", "არსებობა", "იგზისთ", "It exists.", "არსებობს.")
a1("express", "გამოხატვა", "იქსფრეს", "Express yourself.", "გამოხატე თავი.")
a1("complete", "სრული/დასრულება", "ქომფლით", "Task complete.", "დავალება შესრულებულია.")
a1("serve", "მომსახურება", "სერვ", "Serve the country.", "ქვეყანას ემსახურე.")
a1("cause", "მიზეზი", "ქოზ", "The cause is clear.", "მიზეზი ნათელია.")
a1("develop", "განვითარება", "დეველოფ", "Develop skills.", "უნარები განავითარე.")
a1("appear", "გამოჩენა", "ეფიარ", "He appeared.", "გამოჩნდა.")
a1("remain", "დარჩენა", "რიმეინ", "Remain calm.", "მშვიდად იყავი.")
a1("contain", "შეიცავს", "ქონთეინ", "It contains water.", "წყალს შეიცავს.")
a1("suppose", "ვარაუდი", "საფოუზ", "I suppose so.", "მგონი ასეა.")
a1("force", "ძალა", "ფორს", "Don't force me.", "ნუ მაიძულებ.")
a1("control", "კონტროლი", "ქონთროლ", "Control yourself.", "თავი დაიჭირე.")
a1("offer", "შეთავაზება", "ოფერ", "I offer help.", "დახმარებას ვთავაზობ.")
a1("refuse", "უარის თქმა", "რეფიუზ", "I refuse.", "უარს ვამბობ.")
a1("raise", "აწევა", "რეიზ", "Raise your hand.", "ხელი აწიე.")
a1("reduce", "შემცირება", "რიდიუს", "Reduce costs.", "ხარჯები შეამცირე.")
a1("discover", "აღმოჩენა", "დისქავერ", "I discovered it.", "აღმოვაჩინე.")
a1("perform", "შესრულება", "ფერფორმ", "Perform well.", "კარგად შეასრულე.")
a1("guess", "გამოცნობა", "გეს", "Guess what!", "გამოიცანი!")
a1("forever", "სამუდამოდ", "ფორევერ", "Friends forever.", "მეგობრები სამუდამოდ.")
a1("deep", "ღრმა", "დიფ", "Deep water.", "ღრმა წყალი.")
a1("wide", "ფართო", "ვაიდ", "A wide road.", "ფართო გზა.")
a1("heavy", "მძიმე", "ჰევი", "Heavy box.", "მძიმე ყუთი.")
a1("bright", "ნათელი", "ბრაით", "Bright light.", "ნათელი შუქი.")
a1("loud", "ხმამაღალი", "ლაუდ", "Loud music.", "ხმამაღალი მუსიკა.")
a1("thin", "თხელი", "სინ", "Thin paper.", "თხელი ქაღალდი.")
a1("thick", "სქელი", "სიქ", "Thick book.", "სქელი წიგნი.")
a1("lucky", "იღბლიანი", "ლაქი", "I am lucky.", "იღბლიანი ვარ.")
a1("dirty", "ბინძური", "დერთი", "Dirty clothes.", "ბინძური ტანსაცმელი.")
a1("across", "გადაღმა", "ექროს", "Across the street.", "ქუჩის გადაღმა.")
a1("among", "შორის", "ემანგ", "Among friends.", "მეგობრებს შორის.")
a1("toward", "-კენ", "თოვარდ", "Walk toward me.", "ჩემკენ მოდი.")
a1("within", "ფარგლებში", "ვიზინ", "Within the city.", "ქალაქში.")
a1("bit", "ცოტა/ნაჭერი", "ბიტ", "A little bit.", "ცოტა.")
a1("less", "ნაკლები", "ლეს", "Less sugar.", "ნაკლები შაქარი.")
a1("more", "მეტი", "მორ", "More water.", "მეტი წყალი.")
a1("quite", "საკმაოდ", "ქვაით", "Quite good.", "საკმაოდ კარგი.")
a1("though", "მიუხედავად", "ზოუ", "Even though.", "მიუხედავად იმისა.")
a1("whether", "თუ არა", "ვეზერ", "Whether or not.", "იქნება თუ არა.")
a1("whose", "ვისი", "ჰუზ", "Whose is this?", "ვისია ეს?")
a1("either", "ორივე/ან", "იზერ", "Either one.", "ნებისმიერი.")
a1("several", "რამდენიმე", "სევერალ", "Several books.", "რამდენიმე წიგნი.")
a1("perhaps", "შესაძლოა", "ფერჰეფს", "Perhaps tomorrow.", "შესაძლოა ხვალ.")
a1("common", "საერთო", "ქომონ", "A common mistake.", "ჩვეულებრივი შეცდომა.")
a1("certain", "გარკვეული", "სერთენ", "I am certain.", "დარწმუნებული ვარ.")
a1("million", "მილიონი", "მილიონ", "A million people.", "მილიონი ადამიანი.")
a1("economy", "ეკონომიკა", "იქონომი", "Strong economy.", "ძლიერი ეკონომიკა.")
a1("national", "ეროვნული", "ნეშენალ", "National team.", "ეროვნული გუნდი.")
a1("international", "საერთაშორისო", "ინთერნეშენალ", "International news.", "საერთაშორისო ამბები.")
a1("political", "პოლიტიკური", "ფოლითიქალ", "Political system.", "პოლიტიკური სისტემა.")
a1("traditional", "ტრადიციული", "თრედიშენალ", "Traditional food.", "ტრადიციული საკვები.")
a1("private", "კერძო/პირადი", "ფრაივეთ", "Private property.", "კერძო საკუთრება.")
a1("recent", "ბოლოდროინდელი", "რისენთ", "Recent news.", "ბოლოდროინდელი ამბები.")
a1("beauty", "სილამაზე", "ბიუთი", "Natural beauty.", "ბუნებრივი სილამაზე.")
a1("prefer", "უპირატესობის მინიჭება", "ფრიფერ", "I prefer tea.", "ჩაის ვამჯობინებ.")
a1("teach", "სწავლება", "თიჩ", "I teach math.", "მათემატიკას ვასწავლი.")
a1("lie", "სიცრუე/წოლა", "ლაი", "Don't lie.", "ნუ ტყუი.")
a1("steal", "ქურდობა", "სთილ", "Don't steal.", "ნუ იპარავ.")
a1("hide", "დამალვა", "ჰაიდ", "Don't hide.", "ნუ იმალები.")
a1("warn", "გაფრთხილება", "ვორნ", "I warned you.", "გაგაფრთხილე.")
a1("celebrate", "აღნიშვნა", "სელებრეიტ", "Let's celebrate!", "აღვნიშნოთ!")
a1("recognize", "ამოცნობა", "რექოგნაიზ", "I recognize you.", "გიცნობ.")
a1("ride", "ტარება (ტრანსპ.)", "რაიდ", "Ride a bike.", "ველოსიპედით იარე.")
a1("paint", "ხატვა/საღებავი", "ფეინთ", "Paint the wall.", "კედელი შეღებე.")
a1("carry", "ტარება", "ქერი", "Carry this bag.", "ეს ჩანთა წაიღე.")
a1("lift", "აწევა", "ლიფთ", "Lift the box.", "ყუთი აწიე.")
a1("drop", "ჩამოვარდნა", "დროფ", "Don't drop it.", "არ დაგივარდეს.")
a1("shake", "რხევა", "შეიქ", "Shake hands.", "ხელი ჩამორთვი.")
a1("shut", "დახურვა", "შათ", "Shut the door.", "კარი დახურე.")
a1("hang", "ჩამოკიდება", "ჰენგ", "Hang your coat.", "პალტო ჩამოკიდე.")
a1("rush", "აჩქარება", "რაშ", "Don't rush.", "ნუ ჩქარობ.")
a1("map", "რუკა", "მეფ", "Read the map.", "რუკას შეხედე.")
a1("clock", "საათი", "ქლოქ", "Wall clock.", "კედლის საათი.")
a1("hat", "ქუდი", "ჰეთ", "A nice hat.", "ლამაზი ქუდი.")
a1("plate", "თეფში", "ფლეიტ", "A clean plate.", "სუფთა თეფში.")
a1("fork", "ჩანგალი", "ფორქ", "Use a fork.", "ჩანგალი გამოიყენე.")
a1("rose", "ვარდი", "როუზ", "A red rose.", "წითელი ვარდი.")
a1("grass", "ბალახი", "გრას", "Green grass.", "მწვანე ბალახი.")
a1("rabbit", "კურდღელი", "რებით", "A white rabbit.", "თეთრი კურდღელი.")
a1("snake", "გველი", "სნეიქ", "A dangerous snake.", "საშიში გველი.")
a1("monkey", "მაიმუნი", "მანქი", "A funny monkey.", "სასაცილო მაიმუნი.")
a1("mouse", "თაგვი", "მაუს", "A small mouse.", "პატარა თაგვი.")
a1("sheep", "ცხვარი", "შიფ", "White sheep.", "თეთრი ცხვარი.")
a1("pig", "ღორი", "ფიგ", "A fat pig.", "მსუქანი ღორი.")
a1("bear", "დათვი", "ბეარ", "A big bear.", "დიდი დათვი.")
a1("wolf", "მგელი", "ვულფ", "A gray wolf.", "ნაცრისფერი მგელი.")
a1("fox", "მელა", "ფოქს", "A clever fox.", "ჭკვიანი მელა.")
a1("elephant", "სპილო", "ელეფენთ", "A big elephant.", "დიდი სპილო.")
a1("king", "მეფე", "ქინგ", "The king is wise.", "მეფე ბრძენია.")
a1("queen", "დედოფალი", "ქვინ", "The queen rules.", "დედოფალი მართავს.")
a1("soldier", "ჯარისკაცი", "სოლჯერ", "A brave soldier.", "მამაცი ჯარისკაცი.")
a1("army", "ჯარი", "არმი", "A strong army.", "ძლიერი ჯარი.")
a1("prison", "ციხე", "ფრიზონ", "In prison.", "ციხეში.")
a1("judge", "მოსამართლე", "ჯაჯ", "A fair judge.", "სამართლიანი მოსამართლე.")
a1("danger", "საფრთხე", "დეინჯერ", "Danger ahead.", "წინ საფრთხეა.")
a1("banana", "ბანანი", "ბენანა", "A yellow banana.", "ყვითელი ბანანი.")
a1("orange", "ფორთოხალი", "ორინჯ", "Orange juice.", "ფორთოხლის წვენი.")
a1("wine", "ღვინო", "ვაინ", "Georgian wine.", "ქართული ღვინო.")
a1("beer", "ლუდი", "ბიარ", "Cold beer.", "ცივი ლუდი.")
a1("butter", "კარაქი", "ბათერ", "Fresh butter.", "ახალი კარაქი.")
a1("rice", "ბრინჯი", "რაის", "I cook rice.", "ბრინჯს ვამზადებ.")
a1("vegetable", "ბოსტნეული", "ვეჯთებლ", "Fresh vegetables.", "ახალი ბოსტნეული.")
a1("iron", "რკინა", "აიერნ", "Iron is strong.", "რკინა მტკიცეა.")
a1("silver", "ვერცხლი", "სილვერ", "Silver ring.", "ვერცხლის ბეჭედი.")
a1("cotton", "ბამბა", "ქოთონ", "Cotton shirt.", "ბამბის პერანგი.")
a1("gas", "გაზი/ბენზინი", "გეს", "I need gas.", "ბენზინი მჭირდება.")
a1("seed", "თესლი", "სიდ", "Plant the seed.", "თესლი დარგე.")
a1("bone", "ძვალი", "ბოუნ", "A broken bone.", "მოტეხილი ძვალი.")
a1("blood", "სისხლი", "ბლად", "Blood is red.", "სისხლი წითელია.")
a1("skin", "კანი", "სქინ", "Soft skin.", "რბილი კანი.")
a1("brain", "ტვინი", "ბრეინ", "The human brain.", "ადამიანის ტვინი.")
a1("neck", "კისერი", "ნექ", "My neck hurts.", "კისერი მტკივა.")
a1("knee", "მუხლი", "ნი", "My knee hurts.", "მუხლი მტკივა.")
a1("stomach", "კუჭი/მუცელი", "სთამაქ", "My stomach hurts.", "მუცელი მტკივა.")
a1("shoulder", "მხარი", "შოულდერ", "My shoulder hurts.", "მხარი მტკივა.")
a1("tooth", "კბილი", "თუს", "I lost a tooth.", "კბილი დავკარგე.")
a1("flag", "დროშა", "ფლეგ", "The national flag.", "ეროვნული დროშა.")
a1("border", "საზღვარი", "ბორდერ", "Cross the border.", "საზღვარი გადაკვეთე.")
a1("island", "კუნძული", "აილენდ", "A beautiful island.", "ლამაზი კუნძული.")
a1("space", "სივრცე/კოსმოსი", "სფეის", "Outer space.", "კოსმოსი.")
a1("cross", "გადაკვეთა/ჯვარი", "ქროს", "Cross the street.", "ქუჩა გადაიარე.")
a1("reach", "მიღწევა", "რიჩ", "I reached the top.", "მწვერვალს მივაღწიე.")
a1("page", "გვერდი", "ფეიჯ", "Turn the page.", "გვერდი გადაშალე.")
a1("math", "მათემატიკა", "მეს", "I like math.", "მათემატიკა მომწონს.")
a1("station", "სადგური", "სთეიშენ", "Train station.", "მატარებლის სადგური.")
a1("trip", "მოგზაურობა", "თრიფ", "A nice trip.", "კარგი მოგზაურობა.")
a1("tourist", "ტურისტი", "თურისთ", "Many tourists.", "ბევრი ტურისტი.")
a1("exit", "გასასვლელი", "ეგზით", "Where is the exit?", "სად არის გასასვლელი?")
a1("score", "ანგარიში/ქულა", "სქორ", "The final score.", "საბოლოო ანგარიში.")
a1("match", "მატჩი", "მეჩ", "A football match.", "ფეხბურთის მატჩი.")
a1("newspaper", "გაზეთი", "ნიუსფეიფერ", "Read the newspaper.", "გაზეთი წაიკითხე.")
a1("program", "პროგრამა", "ფროგრემ", "A new program.", "ახალი პროგრამა.")
a1("disease", "დაავადება", "დიზიზ", "A serious disease.", "სერიოზული დაავადება.")
a1("election", "არჩევნები", "ილექშენ", "The election.", "არჩევნები.")
a1("president", "პრეზიდენტი", "ფრეზიდენთ", "The president.", "პრეზიდენტი.")
a1("prince", "პრინცი", "ფრინს", "A young prince.", "ახალგაზრდა პრინცი.")
a1("princess", "პრინცესა", "ფრინსეს", "A beautiful princess.", "ლამაზი პრინცესა.")
a1("dead", "მკვდარი", "დედ", "The tree is dead.", "ხე მკვდარია.")
a1("ago", "წინ", "ეგო", "Two years ago.", "ორი წლის წინ.")

print(f"A1 words: {len(data)}")

# ============ A2: Words 1001-2000 ============
a2_words = [
("ability", "უნარი", "ებილითი", "Natural ability.", "ბუნებრივი უნარი."),
("accept", "მიღება", "ექსეფთ", "Accept the offer.", "შეთავაზება მიიღე."),
("accident", "ავარია/უბედურება", "ექსიდენთ", "A car accident.", "მანქანის ავარია."),
("account", "ანგარიში", "ექაუნთ", "Bank account.", "საბანკო ანგარიში."),
("achieve", "მიღწევა", "ეჩივ", "Achieve your goals.", "მიზნებს მიაღწიე."),
("actual", "ფაქტობრივი", "ექჩუალ", "The actual cost.", "ფაქტობრივი ღირებულება."),
("add", "დამატება", "ედ", "Add more sugar.", "კიდევ შაქარი დაამატე."),
("address", "მისამართი", "ედრეს", "What is your address?", "რა მისამართი გაქვს?"),
("admit", "აღიარება", "ედმით", "I admit my mistake.", "შეცდომას ვაღიარებ."),
("adult", "ზრდასრული", "ედალთ", "An adult person.", "ზრდასრული ადამიანი."),
("advance", "წინსვლა", "ედვანს", "Technology advances.", "ტექნოლოგია წინ მიიწევს."),
("advantage", "უპირატესობა", "ედვანთიჯ", "A big advantage.", "დიდი უპირატესობა."),
("advice", "რჩევა", "ედვაის", "Good advice.", "კარგი რჩევა."),
("affair", "საქმე/აფერა", "ეფეარ", "A private affair.", "პირადი საქმე."),
("affect", "გავლენა", "ეფექთ", "It affects everyone.", "ყველაზე მოქმედებს."),
("afford", "ხელი მიუწვდება", "ეფორდ", "I can't afford it.", "ეს ხელი არ მიწვდება."),
("agency", "სააგენტო", "ეიჯენსი", "Travel agency.", "ტურისტული სააგენტო."),
("agent", "აგენტი", "ეიჯენთ", "A real estate agent.", "უძრავი ქონების აგენტი."),
("ahead", "წინ", "ეჰედ", "Go ahead.", "გააგრძელე."),
("aim", "მიზანი", "ეიმ", "Aim high.", "მაღალ მიზანს დაისახე."),
("alive", "ცოცხალი", "ელაივ", "He is alive.", "ცოცხალია."),
("ancient", "უძველესი", "ეინშენთ", "Ancient history.", "უძველესი ისტორია."),
("announce", "გამოცხადება", "ენაუნს", "I announce the winner.", "გამარჯვებულს ვაცხადებ."),
("annual", "ყოველწლიური", "ენუალ", "Annual report.", "წლიური ანგარიში."),
("apart", "განცალკევებით", "ეფართ", "Far apart.", "შორს ერთმანეთისგან."),
("apparent", "აშკარა", "ეფერენთ", "It is apparent.", "ეს აშკარაა."),
("appeal", "მიმართვა/მოწონება", "ეფილ", "The idea appeals to me.", "იდეა მომწონს."),
("apply", "მიმართვა/გამოყენება", "ეფლაი", "Apply for a job.", "სამუშაოზე მიმართე."),
("approach", "მიდგომა", "ეფროუჩ", "A new approach.", "ახალი მიდგომა."),
("appropriate", "შესაფერისი", "ეფროფრიეთ", "An appropriate time.", "შესაფერისი დრო."),
("approve", "დამტკიცება", "ეფრუვ", "The plan was approved.", "გეგმა დამტკიცდა."),
("argue", "კამათი", "არგიუ", "Don't argue.", "ნუ კამათობ."),
("arrange", "მოწყობა", "ერეინჯ", "Arrange a meeting.", "შეხვედრა მოაწყვე."),
("arrest", "დაკავება", "ერესთ", "The police arrested him.", "პოლიციამ დააკავა."),
("article", "სტატია/ნაწარმი", "ართიქლ", "An interesting article.", "საინტერესო სტატია."),
("aside", "გვერდით/განზე", "ესაიდ", "Step aside.", "გადადექი."),
("assume", "ვარაუდი", "ესიუმ", "I assume so.", "ვფიქრობ ასეა."),
("atmosphere", "ატმოსფერო", "ეთმოსფიარ", "A friendly atmosphere.", "მეგობრული ატმოსფერო."),
("attach", "მიმაგრება", "ეთეჩ", "Attach the file.", "ფაილი მიამაგრე."),
("attack", "თავდასხმა", "ეთექ", "A sudden attack.", "მოულოდნელი თავდასხმა."),
("attempt", "მცდელობა", "ეთემფთ", "A brave attempt.", "გამბედავი მცდელობა."),
("attract", "მიზიდვა", "ეთრექთ", "It attracts attention.", "ყურადღებას იზიდავს."),
("audience", "აუდიტორია", "ოდიენს", "A large audience.", "დიდი აუდიტორია."),
("author", "ავტორი", "ოსორ", "A famous author.", "ცნობილი ავტორი."),
("available", "ხელმისაწვდომი", "ევეილებლ", "Is it available?", "ხელმისაწვდომია?"),
("average", "საშუალო", "ევერიჯ", "An average score.", "საშუალო ქულა."),
("aware", "ცნობიერი/იცის", "ევეარ", "I am aware.", "ვიცი."),
("background", "ფონი/გამოცდილება", "ბექგრაუნდ", "Professional background.", "პროფესიული გამოცდილება."),
("balance", "ბალანსი/წონასწორობა", "ბელენს", "Keep your balance.", "წონასწორობა შეინარჩუნე."),
("band", "ჯგუფი/ზოლი", "ბენდ", "A music band.", "მუსიკალური ჯგუფი."),
("bank", "ბანკი", "ბენქ", "I go to the bank.", "ბანკში მივდივარ."),
("bar", "ბარი/ზოლი", "ბარ", "A coffee bar.", "ყავის ბარი."),
("base", "ბაზა/საფუძველი", "ბეის", "The military base.", "სამხედრო ბაზა."),
("basic", "საბაზისო", "ბეისიქ", "Basic knowledge.", "საბაზისო ცოდნა."),
("basis", "საფუძველი", "ბეისის", "On a daily basis.", "ყოველდღიურ საფუძველზე."),
("battle", "ბრძოლა", "ბეთლ", "A fierce battle.", "სასტიკი ბრძოლა."),
("beach", "სანაპირო", "ბიჩ", "A beautiful beach.", "ლამაზი სანაპირო."),
("beat", "ცემა/დამარცხება", "ბიტ", "We beat them.", "მათ დავამარცხეთ.